import type { CatalogEntityKind } from '../domain/types'
import wikiData from './wiki-data.json' with { type: 'json' }
import switchData from './switch-data.json' with { type: 'json' }

export const STARTER_SOURCE_URLS = {
  "apworld-classes": "https://github.com/Emerassi/CrystalProjectAPWorld/blob/main/worlds/crystal_project/constants/jobs.py",
  "apworld-items": "https://github.com/Emerassi/CrystalProjectAPWorld/blob/main/worlds/crystal_project/items.py",
  "apworld-monster-magic": "https://github.com/Emerassi/CrystalProjectAPWorld/blob/main/worlds/crystal_project/constants/scholar_abilities.py",
  "equipment-expansion-sheet": "https://docs.google.com/spreadsheets/d/1s3kWj2DONAln5hRx7p4JyEfr71wkLIM-KC3LTA3gNks/edit#gid=0",
  "nintendo-mod-pack-2": "https://www.nintendo.com/en-gb/DLC/Mod-Pack-2-New-Challenges-2646897.html",
  "nintendo-mod-pack-1": "https://www.nintendo.com/us/store/products/mod-pack-1-quality-fun-70050000048696-switch/",
  "wiki-aegis": "https://crystal-project.fandom.com/wiki/Aegis",
  "wiki-assassin": "https://crystal-project.fandom.com/wiki/Assassin",
  "wiki-battle-skill": "https://crystal-project.fandom.com/wiki/Battle_Skill",
  "wiki-beastmaster": "https://crystal-project.fandom.com/wiki/Beastmaster",
  "wiki-beatsmith": "https://crystal-project.fandom.com/wiki/Beatsmith",
  "wiki-black-magic": "https://crystal-project.fandom.com/wiki/Black_Magic",
  "wiki-chemist": "https://crystal-project.fandom.com/wiki/Chemist",
  "wiki-chivalry": "https://crystal-project.fandom.com/wiki/Chivalry",
  "wiki-cleric": "https://crystal-project.fandom.com/wiki/Cleric",
  "wiki-dervish": "https://crystal-project.fandom.com/wiki/Dervish",
  "wiki-execute": "https://crystal-project.fandom.com/wiki/Execute",
  "wiki-fencer": "https://crystal-project.fandom.com/wiki/Fencer",
  "wiki-hex-magic": "https://crystal-project.fandom.com/wiki/Hex_Magic",
  "wiki-hunter": "https://crystal-project.fandom.com/wiki/Hunter",
  "wiki-martial-arts": "https://crystal-project.fandom.com/wiki/Martial_Arts",
  "wiki-mimic": "https://crystal-project.fandom.com/wiki/Mimic",
  "wiki-mixed-magic": "https://crystal-project.fandom.com/wiki/Mixed_Magic",
  "wiki-monk": "https://crystal-project.fandom.com/wiki/Monk",
  "wiki-ninja": "https://crystal-project.fandom.com/wiki/Ninja",
  "wiki-nomad": "https://crystal-project.fandom.com/wiki/Nomad",
  "wiki-prayer-magic": "https://crystal-project.fandom.com/wiki/Prayer_Magic",
  "wiki-reaper": "https://crystal-project.fandom.com/wiki/Reaper",
  "wiki-rogue": "https://crystal-project.fandom.com/wiki/Rogue",
  "wiki-samurai": "https://crystal-project.fandom.com/wiki/Samurai",
  "wiki-scholar": "https://crystal-project.fandom.com/wiki/Scholar",
  "wiki-shaman": "https://crystal-project.fandom.com/wiki/Shaman",
  "wiki-summoner": "https://crystal-project.fandom.com/wiki/Summoner",
  "wiki-swordplay": "https://crystal-project.fandom.com/wiki/Swordplay",
  "wiki-time-magic": "https://crystal-project.fandom.com/wiki/Time_Magic",
  "wiki-trickery": "https://crystal-project.fandom.com/wiki/Trickery",
  "wiki-valkyrie": "https://crystal-project.fandom.com/wiki/Valkyrie",
  "wiki-warlock": "https://crystal-project.fandom.com/wiki/Warlock",
  "wiki-warrior": "https://crystal-project.fandom.com/wiki/Warrior",
  "wiki-waterbend": "https://crystal-project.fandom.com/wiki/Waterbend",
  "wiki-weaver": "https://crystal-project.fandom.com/wiki/Weaver",
  "wiki-white-magic": "https://crystal-project.fandom.com/wiki/White_Magic",
  "wiki-wild-arts": "https://crystal-project.fandom.com/wiki/Wild_Arts",
  "wiki-wizard": "https://crystal-project.fandom.com/wiki/Wizard",
} as const

export type StarterSourceKey = keyof typeof STARTER_SOURCE_URLS
export type StarterNameRecord = readonly [id: string, kind: CatalogEntityKind, name: string, source: StarterSourceKey]

export const STARTER_NAME_RECORDS = [
  ["base:item:tonic", "item", "Tonic", "apworld-items"],
  ["base:item:potion", "item", "Potion", "apworld-items"],
  ["base:item:z-potion", "item", "Z-Potion", "apworld-items"],
  ["base:item:tincture", "item", "Tincture", "apworld-items"],
  ["base:item:ether", "item", "Ether", "apworld-items"],
  ["base:item:zether", "item", "Zether", "apworld-items"],
  ["base:item:fenix-juice", "item", "Fenix Juice", "apworld-items"],
  ["base:item:fenix-syrup", "item", "Fenix Syrup", "apworld-items"],
  ["base:item:nans-stew", "item", "Nans Stew", "apworld-items"],
  ["base:item:nans-cocoa", "item", "Nans Cocoa", "apworld-items"],
  ["base:item:nans-secret-recipe", "item", "Nans Secret Recipe", "apworld-items"],
  ["base:item:nuts", "item", "Nuts", "apworld-items"],
  ["base:item:milk", "item", "Milk", "apworld-items"],
  ["base:item:shoudu-stew", "item", "Shoudu Stew", "apworld-items"],
  ["base:item:sweet-pop-candy", "item", "Sweet Pop Candy", "apworld-items"],
  ["base:item:sour-pop-candy", "item", "Sour Pop Candy", "apworld-items"],
  ["base:item:bitter-pop-candy", "item", "Bitter Pop Candy", "apworld-items"],
  ["base:item:rotten-salmon", "item", "Rotten Salmon", "apworld-items"],
  ["base:item:decent-cod", "item", "Decent Cod", "apworld-items"],
  ["base:item:fresh-salmon", "item", "Fresh Salmon", "apworld-items"],
  ["base:item:scroll", "item", "Scroll", "apworld-items"],
  ["base:item:tonic-pouch", "item", "Tonic Pouch", "apworld-items"],
  ["base:item:potion-pouch", "item", "Potion Pouch", "apworld-items"],
  ["base:item:z-potion-pouch", "item", "Z-Potion Pouch", "apworld-items"],
  ["base:item:tincture-pouch", "item", "Tincture Pouch", "apworld-items"],
  ["base:item:ether-pouch", "item", "Ether Pouch", "apworld-items"],
  ["base:item:zether-pouch", "item", "Zether Pouch", "apworld-items"],
  ["base:item:fenix-juice-pouch", "item", "Fenix Juice Pouch", "apworld-items"],
  ["base:item:fenix-syrup-pouch", "item", "Fenix Syrup Pouch", "apworld-items"],
  ["base:item:nuts-sack", "item", "Nuts Sack", "apworld-items"],
  ["base:item:milk-bag", "item", "Milk Bag", "apworld-items"],
  ["base:item:decent-cod-bag", "item", "Decent Cod Bag", "apworld-items"],
  ["base:item:flimsy-rod", "item", "Flimsy Rod", "apworld-items"],
  ["base:item:tough-rod", "item", "Tough Rod", "apworld-items"],
  ["base:item:super-rod", "item", "Super Rod", "apworld-items"],
  ["base:item:plug-lure", "item", "Plug Lure", "apworld-items"],
  ["base:item:fly-lure", "item", "Fly Lure", "apworld-items"],
  ["base:item:jigging-lure", "item", "Jigging Lure", "apworld-items"],
  ["base:item:silver-ore", "item", "Silver Ore", "apworld-items"],
  ["base:item:silver-ingot", "item", "Silver Ingot", "apworld-items"],
  ["base:item:silver-dust", "item", "Silver Dust", "apworld-items"],
  ["base:item:gold-ore", "item", "Gold Ore", "apworld-items"],
  ["base:item:gold-ingot", "item", "Gold Ingot", "apworld-items"],
  ["base:item:gold-dust", "item", "Gold Dust", "apworld-items"],
  ["base:item:diamond-ore", "item", "Diamond Ore", "apworld-items"],
  ["base:item:diamond-ingot", "item", "Diamond Ingot", "apworld-items"],
  ["base:item:diamond-dust", "item", "Diamond Dust", "apworld-items"],
  ["base:item:quintar-pass", "item", "Quintar Pass", "apworld-items"],
  ["base:item:luxury-pass-v2", "item", "Luxury Pass V2", "apworld-items"],
  ["base:item:quintar-shedding", "item", "Quintar Shedding", "apworld-items"],
  ["base:item:short-sword", "item", "Short Sword", "apworld-items"],
  ["base:item:iron-sword", "item", "Iron Sword", "apworld-items"],
  ["base:item:contract", "item", "Contract", "apworld-items"],
  ["base:item:help-the-prince", "item", "Help the Prince", "apworld-items"],
  ["base:item:craftwork-sword", "item", "Craftwork Sword", "apworld-items"],
  ["base:item:broadsword", "item", "Broadsword", "apworld-items"],
  ["base:item:sharp-sword", "item", "Sharp Sword", "apworld-items"],
  ["base:item:razor-edge", "item", "Razor Edge", "apworld-items"],
  ["base:item:silver-sword", "item", "Silver Sword", "apworld-items"],
  ["base:item:artisan-sword", "item", "Artisan Sword", "apworld-items"],
  ["base:item:longsword", "item", "Longsword", "apworld-items"],
  ["base:item:boomer-sword", "item", "Boomer Sword", "apworld-items"],
  ["base:item:digested-sword", "item", "Digested Sword", "apworld-items"],
  ["base:item:scimitar", "item", "Scimitar", "apworld-items"],
  ["base:item:cutlass", "item", "Cutlass", "apworld-items"],
  ["base:item:cold-touch", "item", "Cold Touch", "apworld-items"],
  ["base:item:burning-blade", "item", "Burning Blade", "apworld-items"],
  ["base:item:gold-sword", "item", "Gold Sword", "apworld-items"],
  ["base:item:war-sword", "item", "War Sword", "apworld-items"],
  ["base:item:bloodbind", "item", "Bloodbind", "apworld-items"],
  ["base:item:temporal-blade", "item", "Temporal Blade", "apworld-items"],
  ["base:item:highland-blade", "item", "Highland Blade", "apworld-items"],
  ["base:item:hydra-edge", "item", "Hydra Edge", "apworld-items"],
  ["base:item:defender", "item", "Defender", "apworld-items"],
  ["base:item:crystal-sword", "item", "Crystal Sword", "apworld-items"],
  ["base:item:conquest", "item", "Conquest", "apworld-items"],
  ["base:item:flame-sword", "item", "Flame Sword", "apworld-items"],
  ["base:item:master-sword", "item", "Master Sword", "apworld-items"],
  ["base:item:rune-sword", "item", "Rune Sword", "apworld-items"],
  ["base:item:auduril", "item", "Auduril", "apworld-items"],
  ["base:item:master-bigsword", "item", "Master Bigsword", "apworld-items"],
  ["base:item:training-sword", "item", "Training Sword", "apworld-items"],
  ["base:item:life-line", "item", "Life Line", "apworld-items"],
  ["base:item:soul-keeper", "item", "Soul Keeper", "apworld-items"],
  ["base:item:crabs-claw", "item", "Crabs Claw", "apworld-items"],
  ["base:item:kings-guard", "item", "Kings Guard", "apworld-items"],
  ["base:item:diamond-sword", "item", "Diamond Sword", "apworld-items"],
  ["base:item:balrog", "item", "Balrog", "apworld-items"],
  ["base:item:oily-sword", "item", "Oily Sword", "apworld-items"],
  ["base:item:hand-axe", "item", "Hand Axe", "apworld-items"],
  ["base:item:craftwork-axe", "item", "Craftwork Axe", "apworld-items"],
  ["base:item:cleaver", "item", "Cleaver", "apworld-items"],
  ["base:item:chopper", "item", "Chopper", "apworld-items"],
  ["base:item:hunting-axe", "item", "Hunting Axe", "apworld-items"],
  ["base:item:silver-axe", "item", "Silver Axe", "apworld-items"],
  ["base:item:stone-splitter", "item", "Stone Splitter", "apworld-items"],
  ["base:item:broadaxe", "item", "Broadaxe", "apworld-items"],
  ["base:item:artisan-axe", "item", "Artisan Axe", "apworld-items"],
  ["base:item:hatchet", "item", "Hatchet", "apworld-items"],
  ["base:item:axe-of-light", "item", "Axe of Light", "apworld-items"],
  ["base:item:gold-axe", "item", "Gold Axe", "apworld-items"],
  ["base:item:war-axe", "item", "War Axe", "apworld-items"],
  ["base:item:berserker-axe", "item", "Berserker Axe", "apworld-items"],
  ["base:item:gaia-axe", "item", "Gaia Axe", "apworld-items"],
  ["base:item:master-axe", "item", "Master Axe", "apworld-items"],
  ["base:item:ancient-axe", "item", "Ancient Axe", "apworld-items"],
  ["base:item:master-bigaxe", "item", "Master Bigaxe", "apworld-items"],
  ["base:item:aphotic-edge", "item", "Aphotic Edge", "apworld-items"],
  ["base:item:diamond-axe", "item", "Diamond Axe", "apworld-items"],
  ["base:item:decapitator", "item", "Decapitator", "apworld-items"],
  ["base:item:ragebringer", "item", "Ragebringer", "apworld-items"],
  ["base:item:dirk", "item", "Dirk", "apworld-items"],
  ["base:item:stabbers", "item", "Stabbers", "apworld-items"],
  ["base:item:fishgutter", "item", "Fishgutter", "apworld-items"],
  ["base:item:poisonkiss", "item", "Poisonkiss", "apworld-items"],
  ["base:item:shank", "item", "Shank", "apworld-items"],
  ["base:item:craftwork-dagger", "item", "Craftwork Dagger", "apworld-items"],
  ["base:item:tanto", "item", "Tanto", "apworld-items"],
  ["base:item:butterfly", "item", "Butterfly", "apworld-items"],
  ["base:item:kris", "item", "Kris", "apworld-items"],
  ["base:item:ambush-knife", "item", "Ambush Knife", "apworld-items"],
  ["base:item:rondel", "item", "Rondel", "apworld-items"],
  ["base:item:silver-dagger", "item", "Silver Dagger", "apworld-items"],
  ["base:item:artisan-dagger", "item", "Artisan Dagger", "apworld-items"],
  ["base:item:parry-knife", "item", "Parry Knife", "apworld-items"],
  ["base:item:janbiya", "item", "Janbiya", "apworld-items"],
  ["base:item:sai", "item", "Sai", "apworld-items"],
  ["base:item:kodachi", "item", "Kodachi", "apworld-items"],
  ["base:item:butter-cutter", "item", "Butter Cutter", "apworld-items"],
  ["base:item:soul-kris", "item", "Soul Kris", "apworld-items"],
  ["base:item:gouger", "item", "Gouger", "apworld-items"],
  ["base:item:fanged-knife", "item", "Fanged Knife", "apworld-items"],
  ["base:item:cinquedea", "item", "Cinquedea", "apworld-items"],
  ["base:item:gold-dagger", "item", "Gold Dagger", "apworld-items"],
  ["base:item:kowakizashi", "item", "Kowakizashi", "apworld-items"],
  ["base:item:bone-knife", "item", "Bone Knife", "apworld-items"],
  ["base:item:poignard", "item", "Poignard", "apworld-items"],
  ["base:item:flamespike", "item", "Flamespike", "apworld-items"],
  ["base:item:master-dagger", "item", "Master Dagger", "apworld-items"],
  ["base:item:sange", "item", "Sange", "apworld-items"],
  ["base:item:yasha", "item", "Yasha", "apworld-items"],
  ["base:item:legend-spike", "item", "Legend Spike", "apworld-items"],
  ["base:item:eclipse", "item", "Eclipse", "apworld-items"],
  ["base:item:mage-masher", "item", "Mage Masher", "apworld-items"],
  ["base:item:mages-pike", "item", "Mages Pike", "apworld-items"],
  ["base:item:diamond-dagger", "item", "Diamond Dagger", "apworld-items"],
  ["base:item:rapier", "item", "Rapier", "apworld-items"],
  ["base:item:stinger", "item", "Stinger", "apworld-items"],
  ["base:item:toothpick", "item", "Toothpick", "apworld-items"],
  ["base:item:craftwork-rapier", "item", "Craftwork Rapier", "apworld-items"],
  ["base:item:estoc", "item", "Estoc", "apworld-items"],
  ["base:item:scarlette", "item", "Scarlette", "apworld-items"],
  ["base:item:fish-skewer", "item", "Fish Skewer", "apworld-items"],
  ["base:item:silver-rapier", "item", "Silver Rapier", "apworld-items"],
  ["base:item:artisan-rapier", "item", "Artisan Rapier", "apworld-items"],
  ["base:item:dueller", "item", "Dueller", "apworld-items"],
  ["base:item:vulture", "item", "Vulture", "apworld-items"],
  ["base:item:falcon-dance", "item", "Falcon Dance", "apworld-items"],
  ["base:item:fleuret", "item", "Fleuret", "apworld-items"],
  ["base:item:gold-rapier", "item", "Gold Rapier", "apworld-items"],
  ["base:item:epee", "item", "Epee", "apworld-items"],
  ["base:item:windsong", "item", "Windsong", "apworld-items"],
  ["base:item:master-rapier", "item", "Master Rapier", "apworld-items"],
  ["base:item:nightingale", "item", "Nightingale", "apworld-items"],
  ["base:item:chartreuse", "item", "Chartreuse", "apworld-items"],
  ["base:item:murgleys", "item", "Murgleys", "apworld-items"],
  ["base:item:diamond-rapier", "item", "Diamond Rapier", "apworld-items"],
  ["base:item:craftwork-katana", "item", "Craftwork Katana", "apworld-items"],
  ["base:item:tachi", "item", "Tachi", "apworld-items"],
  ["base:item:silver-katana", "item", "Silver Katana", "apworld-items"],
  ["base:item:artisan-katana", "item", "Artisan Katana", "apworld-items"],
  ["base:item:nansen", "item", "Nansen", "apworld-items"],
  ["base:item:mitsutada", "item", "Mitsutada", "apworld-items"],
  ["base:item:hitofuri", "item", "Hitofuri", "apworld-items"],
  ["base:item:kokaiji", "item", "Kokaiji", "apworld-items"],
  ["base:item:gold-katana", "item", "Gold Katana", "apworld-items"],
  ["base:item:hokuken", "item", "Hokuken", "apworld-items"],
  ["base:item:tomokirimaru", "item", "Tomokirimaru", "apworld-items"],
  ["base:item:ichimonji", "item", "Ichimonji", "apworld-items"],
  ["base:item:master-katana", "item", "Master Katana", "apworld-items"],
  ["base:item:muramasa", "item", "Muramasa", "apworld-items"],
  ["base:item:diamond-katana", "item", "Diamond Katana", "apworld-items"],
  ["base:item:short-spear", "item", "Short Spear", "apworld-items"],
  ["base:item:craftwork-spear", "item", "Craftwork Spear", "apworld-items"],
  ["base:item:javelin", "item", "Javelin", "apworld-items"],
  ["base:item:skewer", "item", "Skewer", "apworld-items"],
  ["base:item:prodder", "item", "Prodder", "apworld-items"],
  ["base:item:silver-spear", "item", "Silver Spear", "apworld-items"],
  ["base:item:artisan-spear", "item", "Artisan Spear", "apworld-items"],
  ["base:item:trident", "item", "Trident", "apworld-items"],
  ["base:item:wind-lance", "item", "Wind Lance", "apworld-items"],
  ["base:item:halberd", "item", "Halberd", "apworld-items"],
  ["base:item:gold-spear", "item", "Gold Spear", "apworld-items"],
  ["base:item:voulge", "item", "Voulge", "apworld-items"],
  ["base:item:radiance", "item", "Radiance", "apworld-items"],
  ["base:item:partizan", "item", "Partizan", "apworld-items"],
  ["base:item:master-spear", "item", "Master Spear", "apworld-items"],
  ["base:item:incursier", "item", "Incursier", "apworld-items"],
  ["base:item:royal-guard", "item", "Royal Guard", "apworld-items"],
  ["base:item:gungnir", "item", "Gungnir", "apworld-items"],
  ["base:item:diamond-spear", "item", "Diamond Spear", "apworld-items"],
  ["base:item:battle-scythe", "item", "Battle Scythe", "apworld-items"],
  ["base:item:craftwork-scythe", "item", "Craftwork Scythe", "apworld-items"],
  ["base:item:war-scythe", "item", "War Scythe", "apworld-items"],
  ["base:item:wind-sickle", "item", "Wind Sickle", "apworld-items"],
  ["base:item:silver-scythe", "item", "Silver Scythe", "apworld-items"],
  ["base:item:artisan-scythe", "item", "Artisan Scythe", "apworld-items"],
  ["base:item:thresher", "item", "Thresher", "apworld-items"],
  ["base:item:grim-scythe", "item", "Grim Scythe", "apworld-items"],
  ["base:item:great-thresher", "item", "Great Thresher", "apworld-items"],
  ["base:item:frost-reaper", "item", "Frost Reaper", "apworld-items"],
  ["base:item:gold-scythe", "item", "Gold Scythe", "apworld-items"],
  ["base:item:ember-scythe", "item", "Ember Scythe", "apworld-items"],
  ["base:item:gravedigger", "item", "Gravedigger", "apworld-items"],
  ["base:item:wind-thresher", "item", "Wind Thresher", "apworld-items"],
  ["base:item:master-scythe", "item", "Master Scythe", "apworld-items"],
  ["base:item:twilight", "item", "Twilight", "apworld-items"],
  ["base:item:adjudicator", "item", "Adjudicator", "apworld-items"],
  ["base:item:arctic-chill", "item", "Arctic Chill", "apworld-items"],
  ["base:item:diamond-scythe", "item", "Diamond Scythe", "apworld-items"],
  ["base:item:craftwork-bow", "item", "Craftwork Bow", "apworld-items"],
  ["base:item:short-bow", "item", "Short Bow", "apworld-items"],
  ["base:item:hunting-bow", "item", "Hunting Bow", "apworld-items"],
  ["base:item:long-bow", "item", "Long Bow", "apworld-items"],
  ["base:item:silver-bow", "item", "Silver Bow", "apworld-items"],
  ["base:item:artisan-bow", "item", "Artisan Bow", "apworld-items"],
  ["base:item:battle-bow", "item", "Battle Bow", "apworld-items"],
  ["base:item:composite-bow", "item", "Composite Bow", "apworld-items"],
  ["base:item:habins-bow", "item", "Habins Bow", "apworld-items"],
  ["base:item:razor-bow", "item", "Razor Bow", "apworld-items"],
  ["base:item:elven-bow", "item", "Elven Bow", "apworld-items"],
  ["base:item:gold-bow", "item", "Gold Bow", "apworld-items"],
  ["base:item:spore-shooter", "item", "Spore Shooter", "apworld-items"],
  ["base:item:war-bow", "item", "War Bow", "apworld-items"],
  ["base:item:siege-bow", "item", "Siege Bow", "apworld-items"],
  ["base:item:rune-bow", "item", "Rune Bow", "apworld-items"],
  ["base:item:master-bow", "item", "Master Bow", "apworld-items"],
  ["base:item:panakeia", "item", "Panakeia", "apworld-items"],
  ["base:item:artemis", "item", "Artemis", "apworld-items"],
  ["base:item:dream-hunter", "item", "Dream Hunter", "apworld-items"],
  ["base:item:diamond-bow", "item", "Diamond Bow", "apworld-items"],
  ["base:item:short-staff", "item", "Short Staff", "apworld-items"],
  ["base:item:cedar-staff", "item", "Cedar Staff", "apworld-items"],
  ["base:item:gnarled-root", "item", "Gnarled Root", "apworld-items"],
  ["base:item:craftwork-staff", "item", "Craftwork Staff", "apworld-items"],
  ["base:item:bone-smasher", "item", "Bone Smasher", "apworld-items"],
  ["base:item:iron-rod", "item", "Iron Rod", "apworld-items"],
  ["base:item:quarterstaff", "item", "Quarterstaff", "apworld-items"],
  ["base:item:walking-stick", "item", "Walking Stick", "apworld-items"],
  ["base:item:maplewood", "item", "Maplewood", "apworld-items"],
  ["base:item:silver-staff", "item", "Silver Staff", "apworld-items"],
  ["base:item:artisan-staff", "item", "Artisan Staff", "apworld-items"],
  ["base:item:knockout-stick", "item", "Knockout Stick", "apworld-items"],
  ["base:item:skullbasher", "item", "Skullbasher", "apworld-items"],
  ["base:item:future-sight", "item", "Future Sight", "apworld-items"],
  ["base:item:battle-staff", "item", "Battle Staff", "apworld-items"],
  ["base:item:digested-staff", "item", "Digested Staff", "apworld-items"],
  ["base:item:natures-gift", "item", "Natures Gift", "apworld-items"],
  ["base:item:life-jewel", "item", "Life Jewel", "apworld-items"],
  ["base:item:gold-staff", "item", "Gold Staff", "apworld-items"],
  ["base:item:war-staff", "item", "War Staff", "apworld-items"],
  ["base:item:apprentice", "item", "Apprentice", "apworld-items"],
  ["base:item:sages-walker", "item", "Sages Walker", "apworld-items"],
  ["base:item:master-staff", "item", "Master Staff", "apworld-items"],
  ["base:item:beats-stick", "item", "Beats Stick", "apworld-items"],
  ["base:item:staff-of-balance", "item", "Staff of Balance", "apworld-items"],
  ["base:item:judgement", "item", "Judgement", "apworld-items"],
  ["base:item:diamond-staff", "item", "Diamond Staff", "apworld-items"],
  ["base:item:ash-wand", "item", "Ash Wand", "apworld-items"],
  ["base:item:cedar-wand", "item", "Cedar Wand", "apworld-items"],
  ["base:item:oak-wand", "item", "Oak Wand", "apworld-items"],
  ["base:item:torch", "item", "Torch", "apworld-items"],
  ["base:item:ink-stick", "item", "Ink Stick", "apworld-items"],
  ["base:item:craftwork-wand", "item", "Craftwork Wand", "apworld-items"],
  ["base:item:soul-wand", "item", "Soul Wand", "apworld-items"],
  ["base:item:static-rod", "item", "Static Rod", "apworld-items"],
  ["base:item:maple-wand", "item", "Maple Wand", "apworld-items"],
  ["base:item:silver-wand", "item", "Silver Wand", "apworld-items"],
  ["base:item:artisan-wand", "item", "Artisan Wand", "apworld-items"],
  ["base:item:storm-rod", "item", "Storm Rod", "apworld-items"],
  ["base:item:baton", "item", "Baton", "apworld-items"],
  ["base:item:cursegiver", "item", "Cursegiver", "apworld-items"],
  ["base:item:effigy", "item", "Effigy", "apworld-items"],
  ["base:item:gold-wand", "item", "Gold Wand", "apworld-items"],
  ["base:item:rune-wand", "item", "Rune Wand", "apworld-items"],
  ["base:item:sentinel-rod", "item", "Sentinel Rod", "apworld-items"],
  ["base:item:stardust-wand", "item", "Stardust Wand", "apworld-items"],
  ["base:item:master-wand", "item", "Master Wand", "apworld-items"],
  ["base:item:aura-focus", "item", "Aura Focus", "apworld-items"],
  ["base:item:paladin-wand", "item", "Paladin Wand", "apworld-items"],
  ["base:item:obelisk", "item", "Obelisk", "apworld-items"],
  ["base:item:flameseeker", "item", "Flameseeker", "apworld-items"],
  ["base:item:diamond-wand", "item", "Diamond Wand", "apworld-items"],
  ["base:item:moby-dick", "item", "Moby Dick", "apworld-items"],
  ["base:item:orylei", "item", "Orylei", "apworld-items"],
  ["base:item:craftwork-pages", "item", "Craftwork Pages", "apworld-items"],
  ["base:item:encyclopedia", "item", "Encyclopedia", "apworld-items"],
  ["base:item:gospel", "item", "Gospel", "apworld-items"],
  ["base:item:paypirbak", "item", "Paypirbak", "apworld-items"],
  ["base:item:art-of-war", "item", "Art of War", "apworld-items"],
  ["base:item:silver-pages", "item", "Silver Pages", "apworld-items"],
  ["base:item:artisan-pages", "item", "Artisan Pages", "apworld-items"],
  ["base:item:grimoire", "item", "Grimoire", "apworld-items"],
  ["base:item:blank-pages", "item", "Blank Pages", "apworld-items"],
  ["base:item:tome-of-light", "item", "Tome of Light", "apworld-items"],
  ["base:item:hydrology", "item", "Hydrology", "apworld-items"],
  ["base:item:gold-pages", "item", "Gold Pages", "apworld-items"],
  ["base:item:dark-gospel", "item", "Dark Gospel", "apworld-items"],
  ["base:item:divination", "item", "Divination", "apworld-items"],
  ["base:item:malifice", "item", "Malifice", "apworld-items"],
  ["base:item:master-pages", "item", "Master Pages", "apworld-items"],
  ["base:item:codex", "item", "Codex", "apworld-items"],
  ["base:item:diamond-pages", "item", "Diamond Pages", "apworld-items"],
  ["base:item:buckler", "item", "Buckler", "apworld-items"],
  ["base:item:stout-shield", "item", "Stout Shield", "apworld-items"],
  ["base:item:iron-guard", "item", "Iron Guard", "apworld-items"],
  ["base:item:stalwart-shield", "item", "Stalwart Shield", "apworld-items"],
  ["base:item:craftwork-shield", "item", "Craftwork Shield", "apworld-items"],
  ["base:item:vanguard", "item", "Vanguard", "apworld-items"],
  ["base:item:duelling-shield", "item", "Duelling Shield", "apworld-items"],
  ["base:item:lucky-platter", "item", "Lucky Platter", "apworld-items"],
  ["base:item:boomer-shield", "item", "Boomer Shield", "apworld-items"],
  ["base:item:silver-shield", "item", "Silver Shield", "apworld-items"],
  ["base:item:artisan-shield", "item", "Artisan Shield", "apworld-items"],
  ["base:item:cross-shield", "item", "Cross Shield", "apworld-items"],
  ["base:item:brass-cross", "item", "Brass Cross", "apworld-items"],
  ["base:item:blood-shield", "item", "Blood Shield", "apworld-items"],
  ["base:item:the-immovable", "item", "The Immovable", "apworld-items"],
  ["base:item:cross-guard", "item", "Cross Guard", "apworld-items"],
  ["base:item:mages-platter", "item", "Mages Platter", "apworld-items"],
  ["base:item:gold-shield", "item", "Gold Shield", "apworld-items"],
  ["base:item:bulkwark", "item", "Bulkwark", "apworld-items"],
  ["base:item:flame-guard", "item", "Flame Guard", "apworld-items"],
  ["base:item:wizards-wall", "item", "Wizards Wall", "apworld-items"],
  ["base:item:master-shield", "item", "Master Shield", "apworld-items"],
  ["base:item:turtle-shell", "item", "Turtle Shell", "apworld-items"],
  ["base:item:tower-shield", "item", "Tower Shield", "apworld-items"],
  ["base:item:nomads-guard", "item", "Nomads Guard", "apworld-items"],
  ["base:item:ether-shield", "item", "Ether Shield", "apworld-items"],
  ["base:item:mirror-shield", "item", "Mirror Shield", "apworld-items"],
  ["base:item:diamond-shield", "item", "Diamond Shield", "apworld-items"],
  ["base:item:chain-helm", "item", "Chain Helm", "apworld-items"],
  ["base:item:sturdy-helm", "item", "Sturdy Helm", "apworld-items"],
  ["base:item:storm-helm", "item", "Storm Helm", "apworld-items"],
  ["base:item:copper-helm", "item", "Copper Helm", "apworld-items"],
  ["base:item:craftwork-helm", "item", "Craftwork Helm", "apworld-items"],
  ["base:item:bronze-helm", "item", "Bronze Helm", "apworld-items"],
  ["base:item:scale-helm", "item", "Scale Helm", "apworld-items"],
  ["base:item:iron-helm", "item", "Iron Helm", "apworld-items"],
  ["base:item:battle-helm", "item", "Battle Helm", "apworld-items"],
  ["base:item:silver-helm", "item", "Silver Helm", "apworld-items"],
  ["base:item:artisan-helm", "item", "Artisan Helm", "apworld-items"],
  ["base:item:orion-barbut", "item", "Orion Barbut", "apworld-items"],
  ["base:item:iron-barbut", "item", "Iron Barbut", "apworld-items"],
  ["base:item:horned-helm", "item", "Horned Helm", "apworld-items"],
  ["base:item:gold-helm", "item", "Gold Helm", "apworld-items"],
  ["base:item:cross-helm", "item", "Cross Helm", "apworld-items"],
  ["base:item:insignia-helm", "item", "Insignia Helm", "apworld-items"],
  ["base:item:demon-helm", "item", "Demon Helm", "apworld-items"],
  ["base:item:master-helm", "item", "Master Helm", "apworld-items"],
  ["base:item:guts-busby", "item", "Guts Busby", "apworld-items"],
  ["base:item:raid-helm", "item", "Raid Helm", "apworld-items"],
  ["base:item:spellsword-helm", "item", "Spellsword Helm", "apworld-items"],
  ["base:item:diamond-helm", "item", "Diamond Helm", "apworld-items"],
  ["base:item:breastplate", "item", "Breastplate", "apworld-items"],
  ["base:item:ring-mail", "item", "Ring Mail", "apworld-items"],
  ["base:item:copper-suit", "item", "Copper Suit", "apworld-items"],
  ["base:item:plate-of-wolf", "item", "Plate of Wolf", "apworld-items"],
  ["base:item:craftwork-mail", "item", "Craftwork Mail", "apworld-items"],
  ["base:item:bronze-suit", "item", "Bronze Suit", "apworld-items"],
  ["base:item:scale-mail", "item", "Scale Mail", "apworld-items"],
  ["base:item:iron-armor", "item", "Iron Armor", "apworld-items"],
  ["base:item:battleplate", "item", "Battleplate", "apworld-items"],
  ["base:item:silver-mail", "item", "Silver Mail", "apworld-items"],
  ["base:item:artisan-mail", "item", "Artisan Mail", "apworld-items"],
  ["base:item:orion-armor", "item", "Orion Armor", "apworld-items"],
  ["base:item:plate-of-tiger", "item", "Plate of Tiger", "apworld-items"],
  ["base:item:plate-mail", "item", "Plate Mail", "apworld-items"],
  ["base:item:knights-plate", "item", "Knights Plate", "apworld-items"],
  ["base:item:bone-mail", "item", "Bone Mail", "apworld-items"],
  ["base:item:gold-mail", "item", "Gold Mail", "apworld-items"],
  ["base:item:sky-armor", "item", "Sky Armor", "apworld-items"],
  ["base:item:plate-of-lion", "item", "Plate of Lion", "apworld-items"],
  ["base:item:dragon-mail", "item", "Dragon Mail", "apworld-items"],
  ["base:item:demon-plate", "item", "Demon Plate", "apworld-items"],
  ["base:item:master-mail", "item", "Master Mail", "apworld-items"],
  ["base:item:construct-mail", "item", "Construct Mail", "apworld-items"],
  ["base:item:guardian-angel", "item", "Guardian Angel", "apworld-items"],
  ["base:item:plate-of-whale", "item", "Plate of Whale", "apworld-items"],
  ["base:item:lunar-mail", "item", "Lunar Mail", "apworld-items"],
  ["base:item:diamond-mail", "item", "Diamond Mail", "apworld-items"],
  ["base:item:warrior-mail", "item", "Warrior Mail", "apworld-items"],
  ["base:item:warlock-mail", "item", "Warlock Mail", "apworld-items"],
  ["base:item:aegis-mail", "item", "Aegis Mail", "apworld-items"],
  ["base:item:reaper-mail", "item", "Reaper Mail", "apworld-items"],
  ["base:item:samurai-mail", "item", "Samurai Mail", "apworld-items"],
  ["base:item:valkyrie-mail", "item", "Valkyrie Mail", "apworld-items"],
  ["base:item:beastmaster-mail", "item", "Beastmaster Mail", "apworld-items"],
  ["base:item:mimic-mail", "item", "Mimic Mail", "apworld-items"],
  ["base:item:leather-cap", "item", "Leather Cap", "apworld-items"],
  ["base:item:beret", "item", "Beret", "apworld-items"],
  ["base:item:storm-cap", "item", "Storm Cap", "apworld-items"],
  ["base:item:headgear", "item", "Headgear", "apworld-items"],
  ["base:item:craftwork-cap", "item", "Craftwork Cap", "apworld-items"],
  ["base:item:rugged-hat", "item", "Rugged Hat", "apworld-items"],
  ["base:item:spore-blocker", "item", "Spore Blocker", "apworld-items"],
  ["base:item:vikings-hat", "item", "Vikings Hat", "apworld-items"],
  ["base:item:silver-cap", "item", "Silver Cap", "apworld-items"],
  ["base:item:artisan-cap", "item", "Artisan Cap", "apworld-items"],
  ["base:item:combat-band", "item", "Combat Band", "apworld-items"],
  ["base:item:red-cap", "item", "Red Cap", "apworld-items"],
  ["base:item:bandana", "item", "Bandana", "apworld-items"],
  ["base:item:suitor-hat", "item", "Suitor Hat", "apworld-items"],
  ["base:item:gold-cap", "item", "Gold Cap", "apworld-items"],
  ["base:item:red-hat", "item", "Red Hat", "apworld-items"],
  ["base:item:pirate-hat", "item", "Pirate Hat", "apworld-items"],
  ["base:item:tall-tall-hat", "item", "Tall Tall Hat", "apworld-items"],
  ["base:item:master-cap", "item", "Master Cap", "apworld-items"],
  ["base:item:battle-band", "item", "Battle Band", "apworld-items"],
  ["base:item:captains-hat", "item", "Captains Hat", "apworld-items"],
  ["base:item:red-headgear", "item", "Red Headgear", "apworld-items"],
  ["base:item:diamond-cap", "item", "Diamond Cap", "apworld-items"],
  ["base:item:leather-outfit", "item", "Leather Outfit", "apworld-items"],
  ["base:item:studded-armor", "item", "Studded Armor", "apworld-items"],
  ["base:item:leather-mail", "item", "Leather Mail", "apworld-items"],
  ["base:item:craftwork-vest", "item", "Craftwork Vest", "apworld-items"],
  ["base:item:chain-vest", "item", "Chain Vest", "apworld-items"],
  ["base:item:combat-vest", "item", "Combat Vest", "apworld-items"],
  ["base:item:smelly-gi", "item", "Smelly Gi", "apworld-items"],
  ["base:item:training-gi", "item", "Training Gi", "apworld-items"],
  ["base:item:tuxedo", "item", "Tuxedo", "apworld-items"],
  ["base:item:silver-vest", "item", "Silver Vest", "apworld-items"],
  ["base:item:artisan-vest", "item", "Artisan Vest", "apworld-items"],
  ["base:item:power-vest", "item", "Power Vest", "apworld-items"],
  ["base:item:red-coat", "item", "Red Coat", "apworld-items"],
  ["base:item:drifters-vest", "item", "Drifters Vest", "apworld-items"],
  ["base:item:bandage-wrap", "item", "Bandage Wrap", "apworld-items"],
  ["base:item:gaia-vest", "item", "Gaia Vest", "apworld-items"],
  ["base:item:brigandine", "item", "Brigandine", "apworld-items"],
  ["base:item:gold-vest", "item", "Gold Vest", "apworld-items"],
  ["base:item:onion-gi", "item", "Onion Gi", "apworld-items"],
  ["base:item:martial-vest", "item", "Martial Vest", "apworld-items"],
  ["base:item:judo-gi", "item", "Judo Gi", "apworld-items"],
  ["base:item:master-vest", "item", "Master Vest", "apworld-items"],
  ["base:item:quintar-pelt", "item", "Quintar Pelt", "apworld-items"],
  ["base:item:shadow-gi", "item", "Shadow Gi", "apworld-items"],
  ["base:item:rex-vest", "item", "Rex Vest", "apworld-items"],
  ["base:item:slime-coat", "item", "Slime Coat", "apworld-items"],
  ["base:item:diamond-vest", "item", "Diamond Vest", "apworld-items"],
  ["base:item:monk-vest", "item", "Monk Vest", "apworld-items"],
  ["base:item:rogue-vest", "item", "Rogue Vest", "apworld-items"],
  ["base:item:fencer-vest", "item", "Fencer Vest", "apworld-items"],
  ["base:item:hunter-vest", "item", "Hunter Vest", "apworld-items"],
  ["base:item:ninja-vest", "item", "Ninja Vest", "apworld-items"],
  ["base:item:nomad-vest", "item", "Nomad Vest", "apworld-items"],
  ["base:item:beatsmith-vest", "item", "Beatsmith Vest", "apworld-items"],
  ["base:item:assassin-vest", "item", "Assassin Vest", "apworld-items"],
  ["base:item:hemp-hood", "item", "Hemp Hood", "apworld-items"],
  ["base:item:cotton-hood", "item", "Cotton Hood", "apworld-items"],
  ["base:item:storm-hood", "item", "Storm Hood", "apworld-items"],
  ["base:item:holy-hat", "item", "Holy Hat", "apworld-items"],
  ["base:item:craftwork-crown", "item", "Craftwork Crown", "apworld-items"],
  ["base:item:silk-hat", "item", "Silk Hat", "apworld-items"],
  ["base:item:circlet", "item", "Circlet", "apworld-items"],
  ["base:item:holy-miter", "item", "Holy Miter", "apworld-items"],
  ["base:item:woven-hood", "item", "Woven Hood", "apworld-items"],
  ["base:item:silver-crown", "item", "Silver Crown", "apworld-items"],
  ["base:item:artisan-crown", "item", "Artisan Crown", "apworld-items"],
  ["base:item:clerics-hood", "item", "Clerics Hood", "apworld-items"],
  ["base:item:wizards-hat", "item", "Wizards Hat", "apworld-items"],
  ["base:item:fairys-crown", "item", "Fairys Crown", "apworld-items"],
  ["base:item:quilted-hat", "item", "Quilted Hat", "apworld-items"],
  ["base:item:blood-hat", "item", "Blood Hat", "apworld-items"],
  ["base:item:plague-mask", "item", "Plague Mask", "apworld-items"],
  ["base:item:guard-crown", "item", "Guard Crown", "apworld-items"],
  ["base:item:gold-crown", "item", "Gold Crown", "apworld-items"],
  ["base:item:bronze-hairpin", "item", "Bronze Hairpin", "apworld-items"],
  ["base:item:regen-crown", "item", "Regen Crown", "apworld-items"],
  ["base:item:ravens-hood", "item", "Ravens Hood", "apworld-items"],
  ["base:item:celestial-crown", "item", "Celestial Crown", "apworld-items"],
  ["base:item:master-crown", "item", "Master Crown", "apworld-items"],
  ["base:item:pointy-hat", "item", "Pointy Hat", "apworld-items"],
  ["base:item:vita-crown", "item", "Vita Crown", "apworld-items"],
  ["base:item:pact-crown", "item", "Pact Crown", "apworld-items"],
  ["base:item:protector", "item", "Protector", "apworld-items"],
  ["base:item:diamond-crown", "item", "Diamond Crown", "apworld-items"],
  ["base:item:hemp-robe", "item", "Hemp Robe", "apworld-items"],
  ["base:item:cotton-robe", "item", "Cotton Robe", "apworld-items"],
  ["base:item:mages-robe", "item", "Mages Robe", "apworld-items"],
  ["base:item:swimmers-top", "item", "Swimmers Top", "apworld-items"],
  ["base:item:craftwork-robe", "item", "Craftwork Robe", "apworld-items"],
  ["base:item:priest-garb", "item", "Priest Garb", "apworld-items"],
  ["base:item:dress", "item", "Dress", "apworld-items"],
  ["base:item:silk-shirt", "item", "Silk Shirt", "apworld-items"],
  ["base:item:woven-shirt", "item", "Woven Shirt", "apworld-items"],
  ["base:item:silver-cape", "item", "Silver Cape", "apworld-items"],
  ["base:item:artisan-shirt", "item", "Artisan Shirt", "apworld-items"],
  ["base:item:wizards-robe", "item", "Wizards Robe", "apworld-items"],
  ["base:item:clerics-robe", "item", "Clerics Robe", "apworld-items"],
  ["base:item:cosplay-garb", "item", "Cosplay Garb", "apworld-items"],
  ["base:item:sturdy-cape", "item", "Sturdy Cape", "apworld-items"],
  ["base:item:shelter-dress", "item", "Shelter Dress", "apworld-items"],
  ["base:item:gold-robe", "item", "Gold Robe", "apworld-items"],
  ["base:item:winter-cape", "item", "Winter Cape", "apworld-items"],
  ["base:item:blue-cape", "item", "Blue Cape", "apworld-items"],
  ["base:item:seekers-garb", "item", "Seekers Garb", "apworld-items"],
  ["base:item:ravens-cloak", "item", "Ravens Cloak", "apworld-items"],
  ["base:item:master-cape", "item", "Master Cape", "apworld-items"],
  ["base:item:archmage-vest", "item", "Archmage Vest", "apworld-items"],
  ["base:item:saviors-cape", "item", "Saviors Cape", "apworld-items"],
  ["base:item:assassins-cloak", "item", "Assassins Cloak", "apworld-items"],
  ["base:item:stealth-cape", "item", "Stealth Cape", "apworld-items"],
  ["base:item:shell-gown", "item", "Shell Gown", "apworld-items"],
  ["base:item:diamond-robe", "item", "Diamond Robe", "apworld-items"],
  ["base:item:cleric-robe", "item", "Cleric Robe", "apworld-items"],
  ["base:item:wizard-robe", "item", "Wizard Robe", "apworld-items"],
  ["base:item:shaman-robe", "item", "Shaman Robe", "apworld-items"],
  ["base:item:scholar-robe", "item", "Scholar Robe", "apworld-items"],
  ["base:item:chemist-robe", "item", "Chemist Robe", "apworld-items"],
  ["base:item:dervish-robe", "item", "Dervish Robe", "apworld-items"],
  ["base:item:weaver-robe", "item", "Weaver Robe", "apworld-items"],
  ["base:item:summoner-robe", "item", "Summoner Robe", "apworld-items"],
  ["base:item:fervor-charm", "item", "Fervor Charm", "apworld-items"],
  ["base:item:dodge-charm", "item", "Dodge Charm", "apworld-items"],
  ["base:item:earring", "item", "Earring", "apworld-items"],
  ["base:item:bracer", "item", "Bracer", "apworld-items"],
  ["base:item:jewel-of-defense", "item", "Jewel of Defense", "apworld-items"],
  ["base:item:scope-bit", "item", "Scope Bit", "apworld-items"],
  ["base:item:protect-amulet", "item", "Protect Amulet", "apworld-items"],
  ["base:item:wasps-stinger", "item", "Wasps Stinger", "apworld-items"],
  ["base:item:gem-ring", "item", "Gem Ring", "apworld-items"],
  ["base:item:earth-bangle", "item", "Earth Bangle", "apworld-items"],
  ["base:item:water-bangle", "item", "Water Bangle", "apworld-items"],
  ["base:item:looters-ring", "item", "Looters Ring", "apworld-items"],
  ["base:item:burglars-glove", "item", "Burglars Glove", "apworld-items"],
  ["base:item:torpid-cuffs", "item", "Torpid Cuffs", "apworld-items"],
  ["base:item:squirrel-dung", "item", "Squirrel Dung", "apworld-items"],
  ["base:item:fang-pendant", "item", "Fang Pendant", "apworld-items"],
  ["base:item:mana-ring", "item", "Mana Ring", "apworld-items"],
  ["base:item:awake-ring", "item", "Awake Ring", "apworld-items"],
  ["base:item:prayer-beads", "item", "Prayer Beads", "apworld-items"],
  ["base:item:shell-amulet", "item", "Shell Amulet", "apworld-items"],
  ["base:item:samurais-glove", "item", "Samurais Glove", "apworld-items"],
  ["base:item:magic-finder", "item", "Magic Finder", "apworld-items"],
  ["base:item:learners-pin", "item", "Learners Pin", "apworld-items"],
  ["base:item:givers-ring", "item", "Givers Ring", "apworld-items"],
  ["base:item:aggro-band", "item", "Aggro Band", "apworld-items"],
  ["base:item:hemoring", "item", "Hemoring", "apworld-items"],
  ["base:item:float-shoes", "item", "Float Shoes", "apworld-items"],
  ["base:item:hope-cross", "item", "Hope Cross", "apworld-items"],
  ["base:item:defense-shifter", "item", "Defense Shifter", "apworld-items"],
  ["base:item:resist-shifter", "item", "Resist Shifter", "apworld-items"],
  ["base:item:casters-ring", "item", "Casters Ring", "apworld-items"],
  ["base:item:fearsome-ring", "item", "Fearsome Ring", "apworld-items"],
  ["base:item:crit-fang", "item", "Crit Fang", "apworld-items"],
  ["base:item:dancing-shoes", "item", "Dancing Shoes", "apworld-items"],
  ["base:item:bulk-belt", "item", "Bulk Belt", "apworld-items"],
  ["base:item:poison-talon", "item", "Poison Talon", "apworld-items"],
  ["base:item:first-strike-mitt", "item", "First Strike Mitt", "apworld-items"],
  ["base:item:menders-ring", "item", "Menders Ring", "apworld-items"],
  ["base:item:kitsune-mask", "item", "Kitsune Mask", "apworld-items"],
  ["base:item:pact-ring", "item", "Pact Ring", "apworld-items"],
  ["base:item:scope-specs", "item", "Scope Specs", "apworld-items"],
  ["base:item:loot-finder", "item", "Loot Finder", "apworld-items"],
  ["base:item:quiet-shoes", "item", "Quiet Shoes", "apworld-items"],
  ["base:item:knicked-knackers", "item", "Knicked Knackers", "apworld-items"],
  ["base:item:looters-pin", "item", "Looters Pin", "apworld-items"],
  ["base:item:acrobat-shoes", "item", "Acrobat Shoes", "apworld-items"],
  ["base:item:bone-trophy", "item", "Bone Trophy", "apworld-items"],
  ["base:item:gusto-fang", "item", "Gusto Fang", "apworld-items"],
  ["base:item:beads-of-defense", "item", "Beads of Defense", "apworld-items"],
  ["base:item:winter-mitten", "item", "Winter Mitten", "apworld-items"],
  ["base:item:glasses", "item", "Glasses", "apworld-items"],
  ["base:item:gusto-charm", "item", "Gusto Charm", "apworld-items"],
  ["base:item:muggers-glove", "item", "Muggers Glove", "apworld-items"],
  ["base:item:fursuit", "item", "Fursuit", "apworld-items"],
  ["base:item:snow-pendant", "item", "Snow Pendant", "apworld-items"],
  ["base:item:ogre-ball", "item", "Ogre Ball", "apworld-items"],
  ["base:item:sanity-ring", "item", "Sanity Ring", "apworld-items"],
  ["base:item:undead-ring", "item", "Undead Ring", "apworld-items"],
  ["base:item:fairys-ring", "item", "Fairys Ring", "apworld-items"],
  ["base:item:oven-mitt", "item", "Oven Mitt", "apworld-items"],
  ["base:item:autumns-oath", "item", "Autumns Oath", "apworld-items"],
  ["base:item:springs-oath", "item", "Springs Oath", "apworld-items"],
  ["base:item:lucky-socks", "item", "Lucky Socks", "apworld-items"],
  ["base:item:lucky-briefs", "item", "Lucky Briefs", "apworld-items"],
  ["base:item:tall-stand-ring", "item", "Tall Stand Ring", "apworld-items"],
  ["base:item:nomads-emblem", "item", "Nomads Emblem", "apworld-items"],
  ["base:item:lockon-lense", "item", "Lockon Lense", "apworld-items"],
  ["base:item:red-hairpin", "item", "Red Hairpin", "apworld-items"],
  ["base:item:stone-of-jodan", "item", "Stone of Jodan", "apworld-items"],
  ["base:item:ribbon", "item", "Ribbon", "apworld-items"],
  ["base:item:hand-of-midas", "item", "Hand of Midas", "apworld-items"],
  ["base:item:ghendolfs-ring", "item", "Ghendolfs Ring", "apworld-items"],
  ["base:item:master-material", "item", "Master Material", "apworld-items"],
  ["base:item:gaea-shard", "item", "Gaea Shard", "apworld-items"],
  ["base:item:mercury-shard", "item", "Mercury Shard", "apworld-items"],
  ["base:item:poseidon-shard", "item", "Poseidon Shard", "apworld-items"],
  ["base:item:mars-shard", "item", "Mars Shard", "apworld-items"],
  ["base:item:ganymede-shard", "item", "Ganymede Shard", "apworld-items"],
  ["base:item:triton-shard", "item", "Triton Shard", "apworld-items"],
  ["base:item:callisto-shard", "item", "Callisto Shard", "apworld-items"],
  ["base:item:europa-shard", "item", "Europa Shard", "apworld-items"],
  ["base:item:dione-shard", "item", "Dione Shard", "apworld-items"],
  ["base:item:neptune-shard", "item", "Neptune Shard", "apworld-items"],
  ["base:item:new-world-shard", "item", "New World Shard", "apworld-items"],
  ["base:item:old-world-shard", "item", "Old World Shard", "apworld-items"],
  ["base:item:sketchy-seed", "item", "Sketchy Seed", "apworld-items"],
  ["base:item:tuber-seed", "item", "Tuber Seed", "apworld-items"],
  ["base:item:spore-seed", "item", "Spore Seed", "apworld-items"],
  ["base:item:gourmet-seed", "item", "Gourmet Seed", "apworld-items"],
  ["base:item:fetish-seed", "item", "Fetish Seed", "apworld-items"],
  ["base:item:tear-seed", "item", "Tear Seed", "apworld-items"],
  ["base:item:colony-seed", "item", "Colony Seed", "apworld-items"],
  ["base:item:watery-seed", "item", "Watery Seed", "apworld-items"],
  ["base:item:bloody-seed", "item", "Bloody Seed", "apworld-items"],
  ["base:item:dark-seed", "item", "Dark Seed", "apworld-items"],
  ["base:item:warrior-seal", "item", "Warrior Seal", "apworld-items"],
  ["base:item:monk-seal", "item", "Monk Seal", "apworld-items"],
  ["base:item:rogue-seal", "item", "Rogue Seal", "apworld-items"],
  ["base:item:cleric-seal", "item", "Cleric Seal", "apworld-items"],
  ["base:item:wizard-seal", "item", "Wizard Seal", "apworld-items"],
  ["base:item:warlock-seal", "item", "Warlock Seal", "apworld-items"],
  ["base:item:fencer-seal", "item", "Fencer Seal", "apworld-items"],
  ["base:item:shaman-seal", "item", "Shaman Seal", "apworld-items"],
  ["base:item:scholar-seal", "item", "Scholar Seal", "apworld-items"],
  ["base:item:aegis-seal", "item", "Aegis Seal", "apworld-items"],
  ["base:item:hunter-seal", "item", "Hunter Seal", "apworld-items"],
  ["base:item:chemist-seal", "item", "Chemist Seal", "apworld-items"],
  ["base:item:reaper-seal", "item", "Reaper Seal", "apworld-items"],
  ["base:item:ninja-seal", "item", "Ninja Seal", "apworld-items"],
  ["base:item:nomad-seal", "item", "Nomad Seal", "apworld-items"],
  ["base:item:dervish-seal", "item", "Dervish Seal", "apworld-items"],
  ["base:item:beatsmith-seal", "item", "Beatsmith Seal", "apworld-items"],
  ["base:item:samurai-seal", "item", "Samurai Seal", "apworld-items"],
  ["base:item:assassin-seal", "item", "Assassin Seal", "apworld-items"],
  ["base:item:valkyrie-seal", "item", "Valkyrie Seal", "apworld-items"],
  ["base:item:weaver-seal", "item", "Weaver Seal", "apworld-items"],
  ["base:item:summoner-seal", "item", "Summoner Seal", "apworld-items"],
  ["base:item:beastmaster-seal", "item", "Beastmaster Seal", "apworld-items"],
  ["base:item:mimic-seal", "item", "Mimic Seal", "apworld-items"],
  ["base:item:quintar-grass", "item", "Quintar Grass", "apworld-items"],
  ["base:item:quintar-wheat", "item", "Quintar Wheat", "apworld-items"],
  ["base:item:quintar-berries", "item", "Quintar Berries", "apworld-items"],
  ["base:item:quintar-cheese", "item", "Quintar Cheese", "apworld-items"],
  ["base:item:quintar-cookie", "item", "Quintar Cookie", "apworld-items"],
  ["base:item:name-tag", "item", "Name Tag", "apworld-items"],
  ["base:item:incubator", "item", "Incubator", "apworld-items"],
  ["equipment-expansion:item:heavy-edge", "item", "Heavy Edge", "equipment-expansion-sheet"],
  ["equipment-expansion:item:woodchopper", "item", "Woodchopper", "equipment-expansion-sheet"],
  ["equipment-expansion:item:primitive-axe", "item", "Primitive Axe", "equipment-expansion-sheet"],
  ["equipment-expansion:item:bokken", "item", "Bokken", "equipment-expansion-sheet"],
  ["equipment-expansion:item:thin-spear", "item", "Thin Spear", "equipment-expansion-sheet"],
  ["equipment-expansion:item:dull-scythe", "item", "Dull Scythe", "equipment-expansion-sheet"],
  ["equipment-expansion:item:tiny-bow", "item", "Tiny Bow", "equipment-expansion-sheet"],
  ["equipment-expansion:item:book-of-salads", "item", "Book of Salads", "equipment-expansion-sheet"],
  ["equipment-expansion:item:loyalty", "item", "Loyalty", "equipment-expansion-sheet"],
  ["equipment-expansion:item:kaiser-blade", "item", "Kaiser Blade", "equipment-expansion-sheet"],
  ["equipment-expansion:item:squire-of-avalon", "item", "Squire of Avalon", "equipment-expansion-sheet"],
  ["equipment-expansion:item:spear-of-io", "item", "Spear of Io", "equipment-expansion-sheet"],
  ["equipment-expansion:item:unbound-s-scythe", "item", "Unbound's Scythe", "equipment-expansion-sheet"],
  ["equipment-expansion:item:codex-consiliarii", "item", "Codex Consiliarii", "equipment-expansion-sheet"],
  ["equipment-expansion:item:twilight-s-edge", "item", "Twilight's Edge", "equipment-expansion-sheet"],
  ["equipment-expansion:item:facetsplitter", "item", "Facetsplitter", "equipment-expansion-sheet"],
  ["equipment-expansion:item:guardian-of-tharsis", "item", "Guardian of Tharsis", "equipment-expansion-sheet"],
  ["equipment-expansion:item:bookbeater", "item", "Bookbeater", "equipment-expansion-sheet"],
  ["equipment-expansion:item:depth-seer-s-tome", "item", "Depth-seer's Tome", "equipment-expansion-sheet"],
  ["equipment-expansion:item:the-mage-in-yellow", "item", "The Mage in Yellow", "equipment-expansion-sheet"],
  ["equipment-expansion:item:sequoian-barrier", "item", "Sequoian Barrier", "equipment-expansion-sheet"],
  ["equipment-expansion:item:titanfeller", "item", "Titanfeller", "equipment-expansion-sheet"],
  ["equipment-expansion:item:triton-s-cloak", "item", "Triton's Cloak", "equipment-expansion-sheet"],
  ["equipment-expansion:item:blood-of-heroes", "item", "Blood of Heroes", "equipment-expansion-sheet"],
  ["equipment-expansion:item:frostwing-feather", "item", "Frostwing Feather", "equipment-expansion-sheet"],
  ["equipment-expansion:item:moonchill", "item", "Moonchill", "equipment-expansion-sheet"],
  ["equipment-expansion:item:equalizer-hammer", "item", "Equalizer Hammer", "equipment-expansion-sheet"],
  ["equipment-expansion:item:sledgehammer", "item", "Sledgehammer", "equipment-expansion-sheet"],
  ["equipment-expansion:item:woodsmacker", "item", "Woodsmacker", "equipment-expansion-sheet"],
  ["equipment-expansion:item:desert-ringblade", "item", "Desert Ringblade", "equipment-expansion-sheet"],
  ["equipment-expansion:item:darkwood-spear", "item", "Darkwood Spear", "equipment-expansion-sheet"],
  ["equipment-expansion:item:warding-glory", "item", "Warding Glory", "equipment-expansion-sheet"],
  ["equipment-expansion:item:royal-dominance", "item", "Royal Dominance", "equipment-expansion-sheet"],
  ["equipment-expansion:item:hooked-sickle", "item", "Hooked Sickle", "equipment-expansion-sheet"],
  ["equipment-expansion:item:dragonslayer", "item", "Dragonslayer", "equipment-expansion-sheet"],
  ["equipment-expansion:item:executioner", "item", "Executioner", "equipment-expansion-sheet"],
  ["equipment-expansion:item:grand-emerald", "item", "Grand Emerald", "equipment-expansion-sheet"],
  ["equipment-expansion:item:runehammer", "item", "Runehammer", "equipment-expansion-sheet"],
  ["equipment-expansion:item:backbreaker", "item", "Backbreaker", "equipment-expansion-sheet"],
  ["equipment-expansion:item:butterfly-shortspear", "item", "Butterfly Shortspear", "equipment-expansion-sheet"],
  ["equipment-expansion:item:acolyte-s-cookbook", "item", "Acolyte's Cookbook", "equipment-expansion-sheet"],
  ["equipment-expansion:item:sacrificial-ring", "item", "Sacrificial Ring", "equipment-expansion-sheet"],
  ["equipment-expansion:item:bloodthirsty-vest", "item", "Bloodthirsty Vest", "equipment-expansion-sheet"],
  ["equipment-expansion:item:the-impregnable", "item", "The Impregnable", "equipment-expansion-sheet"],
  ["equipment-expansion:item:gilded-crescent", "item", "Gilded Crescent", "equipment-expansion-sheet"],
  ["equipment-expansion:item:hihiirokane", "item", "Hihiirokane", "equipment-expansion-sheet"],
  ["equipment-expansion:item:thunderstruck-knife", "item", "Thunderstruck Knife", "equipment-expansion-sheet"],
  ["equipment-expansion:item:bone-katars", "item", "Bone Katars", "equipment-expansion-sheet"],
  ["equipment-expansion:item:old-reliable", "item", "Old Reliable", "equipment-expansion-sheet"],
  ["equipment-expansion:item:hoplite-s-shield", "item", "Hoplite's Shield", "equipment-expansion-sheet"],
  ["equipment-expansion:item:piercing-bone", "item", "Piercing Bone", "equipment-expansion-sheet"],
  ["equipment-expansion:item:mercury-s-cloak", "item", "Mercury's Cloak", "equipment-expansion-sheet"],
  ["equipment-expansion:item:trailblazer-s-coat", "item", "Trailblazer's Coat", "equipment-expansion-sheet"],
  ["equipment-expansion:item:soaring-falcon", "item", "Soaring Falcon", "equipment-expansion-sheet"],
  ["equipment-expansion:item:shinigami-no-yokan", "item", "Shinigami-no-yokan", "equipment-expansion-sheet"],
  ["equipment-expansion:item:lightforged-katars", "item", "Lightforged Katars", "equipment-expansion-sheet"],
  ["equipment-expansion:item:concealable-knife", "item", "Concealable Knife", "equipment-expansion-sheet"],
  ["equipment-expansion:item:blue-moon-katars", "item", "Blue Moon Katars", "equipment-expansion-sheet"],
  ["equipment-expansion:item:greywood-nunchaku", "item", "Greywood Nunchaku", "equipment-expansion-sheet"],
  ["equipment-expansion:item:serrated-sickle", "item", "Serrated Sickle", "equipment-expansion-sheet"],
  ["equipment-expansion:item:ancient-monster-bone", "item", "Ancient Monster Bone", "equipment-expansion-sheet"],
  ["equipment-expansion:item:gaea-s-cloak", "item", "Gaea's Cloak", "equipment-expansion-sheet"],
  ["equipment-expansion:item:fanged-nunchaku", "item", "Fanged Nunchaku", "equipment-expansion-sheet"],
  ["equipment-expansion:item:desert-sickle", "item", "Desert Sickle", "equipment-expansion-sheet"],
  ["equipment-expansion:item:mars-cloak", "item", "Mars' Cloak", "equipment-expansion-sheet"],
  ["equipment-expansion:item:ganymede-s-cloak", "item", "Ganymede's Cloak", "equipment-expansion-sheet"],
  ["equipment-expansion:item:eaglesclaw", "item", "Eaglesclaw", "equipment-expansion-sheet"],
  ["equipment-expansion:item:twin-blade-staff", "item", "Twin Blade Staff", "equipment-expansion-sheet"],
  ["equipment-expansion:item:enchanted-nunchaku", "item", "Enchanted Nunchaku", "equipment-expansion-sheet"],
  ["equipment-expansion:item:steel-nunchaku", "item", "Steel Nunchaku", "equipment-expansion-sheet"],
  ["equipment-expansion:item:soulfrost-gauntlet", "item", "Soulfrost Gauntlet", "equipment-expansion-sheet"],
  ["equipment-expansion:item:moonfrost-wand", "item", "Moonfrost Wand", "equipment-expansion-sheet"],
  ["equipment-expansion:item:traveler-s-plate", "item", "Traveler's Plate", "equipment-expansion-sheet"],
  ["equipment-expansion:item:hoarfrost-buckler", "item", "Hoarfrost Buckler", "equipment-expansion-sheet"],
  ["equipment-expansion:item:black-cat-s-ring", "item", "Black Cat's Ring", "equipment-expansion-sheet"],
  ["equipment-expansion:item:les-condamnes", "item", "Les Condamnes", "equipment-expansion-sheet"],
  ["equipment-expansion:item:light-crossbow", "item", "Light Crossbow", "equipment-expansion-sheet"],
  ["equipment-expansion:item:regenerating-flask", "item", "Regenerating Flask", "equipment-expansion-sheet"],
  ["equipment-expansion:item:sawn-off-rifle", "item", "Sawn-off Rifle", "equipment-expansion-sheet"],
  ["equipment-expansion:item:longneck-rifle", "item", "Longneck Rifle", "equipment-expansion-sheet"],
  ["equipment-expansion:item:synthesized-angel", "item", "Synthesized Angel", "equipment-expansion-sheet"],
  ["equipment-expansion:item:sunray", "item", "Sunray", "equipment-expansion-sheet"],
  ["equipment-expansion:item:dew-staff", "item", "Dew Staff", "equipment-expansion-sheet"],
  ["equipment-expansion:item:ace-of-diamonds", "item", "Ace of Diamonds", "equipment-expansion-sheet"],
  ["equipment-expansion:item:flask-of-heroism", "item", "Flask of Heroism", "equipment-expansion-sheet"],
  ["equipment-expansion:item:soul-mirror", "item", "Soul Mirror", "equipment-expansion-sheet"],
  ["equipment-expansion:item:congealed-orb", "item", "Congealed Orb", "equipment-expansion-sheet"],
  ["equipment-expansion:item:barrier-of-blood", "item", "Barrier of Blood", "equipment-expansion-sheet"],
  ["equipment-expansion:item:vampiric-wand", "item", "Vampiric Wand", "equipment-expansion-sheet"],
  ["equipment-expansion:item:liquidator", "item", "Liquidator", "equipment-expansion-sheet"],
  ["equipment-expansion:item:kingshammer", "item", "Kingshammer", "equipment-expansion-sheet"],
  ["equipment-expansion:item:wardstaff", "item", "Wardstaff", "equipment-expansion-sheet"],
  ["equipment-expansion:item:broadestsword", "item", "Broadestsword", "equipment-expansion-sheet"],
  ["equipment-expansion:item:plate-of-the-phoenix", "item", "Plate of the Phoenix", "equipment-expansion-sheet"],
  ["equipment-expansion:item:helm-of-the-phoenix", "item", "Helm of the Phoenix", "equipment-expansion-sheet"],
  ["equipment-expansion:item:padded-vest", "item", "Padded Vest", "equipment-expansion-sheet"],
  ["equipment-expansion:item:reinforced-crossbow", "item", "Reinforced Crossbow", "equipment-expansion-sheet"],
  ["equipment-expansion:item:huntsman", "item", "Huntsman", "equipment-expansion-sheet"],
  ["equipment-expansion:item:twinshot-crossbow", "item", "Twinshot Crossbow", "equipment-expansion-sheet"],
  ["equipment-expansion:item:potion-of-aetherbody", "item", "Potion of Aetherbody", "equipment-expansion-sheet"],
  ["equipment-expansion:item:jade-hourglass", "item", "Jade Hourglass", "equipment-expansion-sheet"],
  ["equipment-expansion:item:titanium-shell", "item", "Titanium Shell", "equipment-expansion-sheet"],
  ["equipment-expansion:item:throwing-knives", "item", "Throwing Knives", "equipment-expansion-sheet"],
  ["equipment-expansion:item:divine-ruler-s-helmet", "item", "Divine Ruler's Helmet", "equipment-expansion-sheet"],
  ["equipment-expansion:item:woodcarved-goose", "item", "Woodcarved Goose", "equipment-expansion-sheet"],
  ["equipment-expansion:item:snail-s-ring", "item", "Snail's Ring", "equipment-expansion-sheet"],
  ["equipment-expansion:item:divine-ruler-s-plate", "item", "Divine Ruler's Plate", "equipment-expansion-sheet"],
  ["equipment-expansion:item:alloy-helm", "item", "Alloy Helm", "equipment-expansion-sheet"],
  ["equipment-expansion:item:wavelord-s-regalia", "item", "Wavelord's Regalia", "equipment-expansion-sheet"],
  ["equipment-expansion:item:nomad-s-bandana", "item", "Nomad's Bandana", "equipment-expansion-sheet"],
  ["equipment-expansion:item:bruiser-s-cleaver", "item", "Bruiser's Cleaver", "equipment-expansion-sheet"],
  ["equipment-expansion:item:galebound-tome", "item", "Galebound Tome", "equipment-expansion-sheet"],
  ["equipment-expansion:item:kamihime", "item", "Kamihime", "equipment-expansion-sheet"],
  ["equipment-expansion:item:silent-judge", "item", "Silent Judge", "equipment-expansion-sheet"],
  ["equipment-expansion:item:faded-colour", "item", "Faded Colour", "equipment-expansion-sheet"],
  ["equipment-expansion:item:the-second-warning", "item", "The Second Warning", "equipment-expansion-sheet"],
  ["equipment-expansion:item:the-wolf", "item", "The Wolf", "equipment-expansion-sheet"],
  ["equipment-expansion:item:stonechill", "item", "Stonechill", "equipment-expansion-sheet"],
  ["equipment-expansion:item:demon-mail", "item", "Demon Mail", "equipment-expansion-sheet"],
  ["equipment-expansion:item:reaper-s-cuffs", "item", "Reaper's Cuffs", "equipment-expansion-sheet"],
  ["equipment-expansion:item:old-monk-s-cloak", "item", "Old Monk's Cloak", "equipment-expansion-sheet"],
  ["equipment-expansion:item:stalactite", "item", "Stalactite", "equipment-expansion-sheet"],
  ["equipment-expansion:item:quintar-pheromones", "item", "Quintar Pheromones", "equipment-expansion-sheet"],
  ["equipment-expansion:item:faceless-hood", "item", "Faceless Hood", "equipment-expansion-sheet"],
  ["equipment-expansion:item:silenced-screams", "item", "Silenced Screams", "equipment-expansion-sheet"],
  ["equipment-expansion:item:shellter-gown", "item", "Shellter Gown", "equipment-expansion-sheet"],
  ["equipment-expansion:item:blue-dress", "item", "Blue Dress", "equipment-expansion-sheet"],
  ["equipment-expansion:item:feyblessed-tiara", "item", "Feyblessed Tiara", "equipment-expansion-sheet"],
  ["equipment-expansion:item:bloodied-hood", "item", "Bloodied Hood", "equipment-expansion-sheet"],
  ["equipment-expansion:item:leviathan-plate", "item", "Leviathan Plate", "equipment-expansion-sheet"],
  ["equipment-expansion:item:warstorm-helm", "item", "Warstorm Helm", "equipment-expansion-sheet"],
  ["equipment-expansion:item:boomer-duelist", "item", "Boomer Duelist", "equipment-expansion-sheet"],
  ["equipment-expansion:item:squirrel-champion", "item", "Squirrel Champion", "equipment-expansion-sheet"],
  ["equipment-expansion:item:jadeforged-ring", "item", "Jadeforged Ring", "equipment-expansion-sheet"],
  ["equipment-expansion:item:ring-of-the-accursed", "item", "Ring of the Accursed", "equipment-expansion-sheet"],
  ["equipment-expansion:item:flood-pendant", "item", "Flood Pendant", "equipment-expansion-sheet"],
  ["equipment-expansion:item:circle-of-ruin", "item", "Circle of Ruin", "equipment-expansion-sheet"],
  ["equipment-expansion:item:ring-of-wizardry", "item", "Ring of Wizardry", "equipment-expansion-sheet"],
  ["equipment-expansion:item:warding-beads", "item", "Warding Beads", "equipment-expansion-sheet"],
  ["equipment-expansion:item:stonecore-beads", "item", "Stonecore Beads", "equipment-expansion-sheet"],
  ["equipment-expansion:item:mistcore-beads", "item", "Mistcore Beads", "equipment-expansion-sheet"],
  ["equipment-expansion:item:darkspike", "item", "Darkspike", "equipment-expansion-sheet"],
  ["equipment-expansion:item:giant-boomer", "item", "Giant Boomer", "equipment-expansion-sheet"],
  ["equipment-expansion:item:tarot-accessories", "item", "Tarot Accessories", "equipment-expansion-sheet"],
  ["base:class:warrior", "class", "Warrior", "apworld-classes"],
  ["base:class:monk", "class", "Monk", "apworld-classes"],
  ["base:class:rogue", "class", "Rogue", "apworld-classes"],
  ["base:class:cleric", "class", "Cleric", "apworld-classes"],
  ["base:class:wizard", "class", "Wizard", "apworld-classes"],
  ["base:class:warlock", "class", "Warlock", "apworld-classes"],
  ["base:class:fencer", "class", "Fencer", "apworld-classes"],
  ["base:class:shaman", "class", "Shaman", "apworld-classes"],
  ["base:class:scholar", "class", "Scholar", "apworld-classes"],
  ["base:class:aegis", "class", "Aegis", "apworld-classes"],
  ["base:class:hunter", "class", "Hunter", "apworld-classes"],
  ["base:class:chemist", "class", "Chemist", "apworld-classes"],
  ["base:class:reaper", "class", "Reaper", "apworld-classes"],
  ["base:class:ninja", "class", "Ninja", "apworld-classes"],
  ["base:class:nomad", "class", "Nomad", "apworld-classes"],
  ["base:class:dervish", "class", "Dervish", "apworld-classes"],
  ["base:class:beatsmith", "class", "Beatsmith", "apworld-classes"],
  ["base:class:samurai", "class", "Samurai", "apworld-classes"],
  ["base:class:assassin", "class", "Assassin", "apworld-classes"],
  ["base:class:valkyrie", "class", "Valkyrie", "apworld-classes"],
  ["base:class:summoner", "class", "Summoner", "apworld-classes"],
  ["base:class:beastmaster", "class", "Beastmaster", "apworld-classes"],
  ["base:class:weaver", "class", "Weaver", "apworld-classes"],
  ["base:class:mimic", "class", "Mimic", "apworld-classes"],
  ["mod-pack-2:class:bloodmage", "class", "Bloodmage", "nintendo-mod-pack-2"],
  ["mod-pack-2:class:tempest", "class", "Tempest", "nintendo-mod-pack-2"],
  ["mod-pack-2:class:forcemage", "class", "Forcemage", "nintendo-mod-pack-2"],
  ["mod-pack-2:class:barbarian", "class", "Barbarian", "nintendo-mod-pack-2"],
  ["base:warrior:innate:fighter", "innate", "Fighter", "wiki-warrior"],
  ["base:monk:innate:aversive", "innate", "Aversive", "wiki-monk"],
  ["base:monk:innate:brawler", "innate", "Brawler", "wiki-monk"],
  ["base:rogue:innate:pinpoint", "innate", "Pinpoint", "wiki-rogue"],
  ["base:cleric:innate:pinch-healer", "innate", "Pinch Healer", "wiki-cleric"],
  ["base:wizard:innate:element-specialist", "innate", "Element Specialist", "wiki-wizard"],
  ["base:warlock:innate:chaincaster", "innate", "Chaincaster", "wiki-warlock"],
  ["base:fencer:innate:eagle-talon", "innate", "Eagle Talon", "wiki-fencer"],
  ["base:shaman:innate:spell-steal", "innate", "Spell Steal", "wiki-shaman"],
  ["base:scholar:innate:studious", "innate", "Studious", "wiki-scholar"],
  ["base:scholar:innate:learning", "innate", "Learning", "wiki-scholar"],
  ["base:aegis:innate:white-knight", "innate", "White Knight", "wiki-aegis"],
  ["base:hunter:innate:camouflage", "innate", "Camouflage", "wiki-hunter"],
  ["base:chemist:innate:efficience", "innate", "Efficience", "wiki-chemist"],
  ["base:reaper:innate:reaping", "innate", "Reaping", "wiki-reaper"],
  ["base:ninja:innate:dual-wield", "innate", "Dual Wield", "wiki-ninja"],
  ["base:nomad:innate:ap-focus", "innate", "AP Focus", "wiki-nomad"],
  ["base:dervish:innate:aura", "innate", "Aura", "wiki-dervish"],
  ["base:beatsmith:innate:rhythm", "innate", "Rhythm", "wiki-beatsmith"],
  ["base:samurai:innate:endless-fury", "innate", "Endless Fury", "wiki-samurai"],
  ["base:samurai:innate:two-handed", "innate", "Two-handed", "wiki-samurai"],
  ["base:assassin:innate:assassination", "innate", "Assassination", "wiki-assassin"],
  ["base:valkyrie:innate:immortal", "innate", "Immortal", "wiki-valkyrie"],
  ["base:summoner:innate:mp-boost", "innate", "MP Boost", "wiki-summoner"],
  ["base:beastmaster:innate:savage", "innate", "Savage", "wiki-beastmaster"],
  ["base:beastmaster:innate:morphology", "innate", "Morphology", "wiki-beastmaster"],
  ["base:weaver:innate:chrono-loop", "innate", "Chrono Loop", "wiki-weaver"],
  ["base:mimic:innate:shapeshift", "innate", "Shapeshift", "wiki-mimic"],
  ["base:warrior:passive:grudge", "passive", "Grudge", "wiki-warrior"],
  ["base:warrior:passive:adrenaline", "passive", "Adrenaline", "wiki-warrior"],
  ["base:warrior:passive:equip-axe", "passive", "Equip Axe", "wiki-warrior"],
  ["base:warrior:passive:equip-sword", "passive", "Equip Sword", "wiki-warrior"],
  ["base:monk:passive:hp-boost", "passive", "HP Boost", "wiki-monk"],
  ["base:monk:passive:counter", "passive", "Counter", "wiki-monk"],
  ["base:monk:passive:brawler", "passive", "Brawler", "wiki-monk"],
  ["base:rogue:passive:backstabber", "passive", "Backstabber", "wiki-rogue"],
  ["base:rogue:passive:equip-dagger", "passive", "Equip Dagger", "wiki-rogue"],
  ["base:rogue:passive:pocket-sand", "passive", "Pocket Sand", "wiki-rogue"],
  ["base:cleric:passive:equip-staff", "passive", "Equip Staff", "wiki-cleric"],
  ["base:cleric:passive:inner-warmth", "passive", "Inner Warmth", "wiki-cleric"],
  ["base:wizard:passive:initial-focus", "passive", "Initial Focus", "wiki-wizard"],
  ["base:wizard:passive:equip-wand", "passive", "Equip Wand", "wiki-wizard"],
  ["base:warlock:passive:regenerator", "passive", "Regenerator", "wiki-warlock"],
  ["base:warlock:passive:refresher", "passive", "Refresher", "wiki-warlock"],
  ["base:fencer:passive:eagle-eye", "passive", "Eagle Eye", "wiki-fencer"],
  ["base:fencer:passive:equip-rapier", "passive", "Equip Rapier", "wiki-fencer"],
  ["base:shaman:passive:safeguard", "passive", "Safeguard", "wiki-shaman"],
  ["base:scholar:passive:learning", "passive", "Learning", "wiki-scholar"],
  ["base:scholar:passive:equip-book", "passive", "Equip Book", "wiki-scholar"],
  ["base:aegis:passive:natural-tank", "passive", "Natural Tank", "wiki-aegis"],
  ["base:aegis:passive:stalwart", "passive", "Stalwart", "wiki-aegis"],
  ["base:aegis:passive:stance-tank", "passive", "Stance Tank", "wiki-aegis"],
  ["base:aegis:passive:equip-shield", "passive", "Equip Shield", "wiki-aegis"],
  ["base:hunter:passive:equip-bow", "passive", "Equip Bow", "wiki-hunter"],
  ["base:hunter:passive:perfect-vision", "passive", "Perfect Vision", "wiki-hunter"],
  ["base:hunter:passive:covert", "passive", "Covert", "wiki-hunter"],
  ["base:reaper:passive:blood-spiller", "passive", "Blood Spiller", "wiki-reaper"],
  ["base:reaper:passive:initial-oomph", "passive", "Initial Oomph", "wiki-reaper"],
  ["base:reaper:passive:equip-scythe", "passive", "Equip Scythe", "wiki-reaper"],
  ["base:nomad:passive:attack-focus", "passive", "Attack Focus", "wiki-nomad"],
  ["base:nomad:passive:frenzy-stance", "passive", "Frenzy Stance", "wiki-nomad"],
  ["base:dervish:passive:critical-power", "passive", "Critical Power", "wiki-dervish"],
  ["base:dervish:passive:focus-shield", "passive", "Focus Shield", "wiki-dervish"],
  ["base:beatsmith:passive:auto-speed", "passive", "Auto Speed", "wiki-beatsmith"],
  ["base:beatsmith:passive:critical-turn", "passive", "Critical Turn", "wiki-beatsmith"],
  ["base:samurai:passive:equip-katana", "passive", "Equip Katana", "wiki-samurai"],
  ["base:samurai:passive:unreactable", "passive", "Unreactable", "wiki-samurai"],
  ["base:samurai:passive:fury", "passive", "Fury", "wiki-samurai"],
  ["base:assassin:passive:crippling-coat", "passive", "Crippling Coat", "wiki-assassin"],
  ["base:assassin:passive:venom-coat", "passive", "Venom Coat", "wiki-assassin"],
  ["base:summoner:passive:mp-boost", "passive", "MP Boost", "wiki-summoner"],
  ["base:summoner:passive:initial-resist", "passive", "Initial Resist", "wiki-summoner"],
  ["base:beastmaster:passive:duel-ready", "passive", "Duel Ready", "wiki-beastmaster"],
  ["base:beastmaster:passive:threatening", "passive", "Threatening", "wiki-beastmaster"],
  ["base:weaver:passive:fast-cast", "passive", "Fast Cast", "wiki-weaver"],
  ["base:weaver:passive:preemptive", "passive", "Preemptive", "wiki-weaver"],
  ["base:weaver:passive:delay-20", "passive", "Delay 20", "wiki-weaver"],
  ["base:weaver:passive:delay-40", "passive", "Delay 40", "wiki-weaver"],
  ["base:mimic:passive:equip-all", "passive", "Equip All", "wiki-mimic"],
  ["base:warrior:ability:taunt", "ability", "Taunt", "wiki-battle-skill"],
  ["base:warrior:ability:bruiser-crush", "ability", "Bruiser Crush", "wiki-battle-skill"],
  ["base:warrior:ability:paragon-crush", "ability", "Paragon Crush", "wiki-battle-skill"],
  ["base:warrior:ability:blitz-crush", "ability", "Blitz Crush", "wiki-battle-skill"],
  ["base:warrior:ability:battle-crush", "ability", "Battle Crush", "wiki-battle-skill"],
  ["base:warrior:ability:power-break", "ability", "Power Break", "wiki-battle-skill"],
  ["base:warrior:ability:armor-break", "ability", "Armor Break", "wiki-battle-skill"],
  ["base:warrior:ability:defender", "ability", "Defender", "wiki-battle-skill"],
  ["base:warrior:ability:berserker", "ability", "Berserker", "wiki-battle-skill"],
  ["base:warlock:ability:heal", "ability", "Heal", "wiki-mixed-magic"],
  ["base:warlock:ability:remedy", "ability", "Remedy", "wiki-mixed-magic"],
  ["base:warlock:ability:life", "ability", "Life", "wiki-mixed-magic"],
  ["base:warlock:ability:protect", "ability", "Protect", "wiki-mixed-magic"],
  ["base:warlock:ability:shell", "ability", "Shell", "wiki-mixed-magic"],
  ["base:warlock:ability:regen", "ability", "Regen", "wiki-mixed-magic"],
  ["base:warlock:ability:refresh", "ability", "Refresh", "wiki-mixed-magic"],
  ["base:warlock:ability:dispel", "ability", "Dispel", "wiki-mixed-magic"],
  ["base:warlock:ability:blaze", "ability", "Blaze", "wiki-mixed-magic"],
  ["base:warlock:ability:douse", "ability", "Douse", "wiki-mixed-magic"],
  ["base:warlock:ability:frost", "ability", "Frost", "wiki-mixed-magic"],
  ["base:warlock:ability:scan", "ability", "Scan", "wiki-mixed-magic"],
  ["base:warlock:ability:doublecast", "ability", "Doublecast", "wiki-mixed-magic"],
  ["base:cleric:ability:cure", "ability", "Cure", "wiki-white-magic"],
  ["base:cleric:ability:curen", "ability", "Curen", "wiki-white-magic"],
  ["base:cleric:ability:curena", "ability", "Curena", "wiki-white-magic"],
  ["base:cleric:ability:raise", "ability", "Raise", "wiki-white-magic"],
  ["base:cleric:ability:return", "ability", "Return", "wiki-white-magic"],
  ["base:cleric:ability:spark-shine", "ability", "Spark Shine", "wiki-white-magic"],
  ["base:cleric:ability:star-flare", "ability", "Star Flare", "wiki-white-magic"],
  ["base:cleric:ability:mend", "ability", "Mend", "wiki-white-magic"],
  ["base:cleric:ability:spotlight", "ability", "Spotlight", "wiki-white-magic"],
  ["base:cleric:ability:blackout", "ability", "Blackout", "wiki-white-magic"],
  ["base:wizard:ability:fire", "ability", "Fire", "wiki-black-magic"],
  ["base:wizard:ability:firen", "ability", "Firen", "wiki-black-magic"],
  ["base:wizard:ability:firena", "ability", "Firena", "wiki-black-magic"],
  ["base:wizard:ability:bolt", "ability", "Bolt", "wiki-black-magic"],
  ["base:wizard:ability:bolten", "ability", "Bolten", "wiki-black-magic"],
  ["base:wizard:ability:boltena", "ability", "Boltena", "wiki-black-magic"],
  ["base:wizard:ability:flare", "ability", "Flare", "wiki-black-magic"],
  ["base:wizard:ability:thunder", "ability", "Thunder", "wiki-black-magic"],
  ["base:wizard:ability:mind-stance", "ability", "Mind Stance", "wiki-black-magic"],
  ["base:wizard:ability:storm-stance", "ability", "Storm Stance", "wiki-black-magic"],
  ["base:monk:ability:beat-down", "ability", "Beat Down", "wiki-martial-arts"],
  ["base:monk:ability:earth-split", "ability", "Earth Split", "wiki-martial-arts"],
  ["base:monk:ability:thunder-chop", "ability", "Thunder Chop", "wiki-martial-arts"],
  ["base:monk:ability:wind-punch", "ability", "Wind Punch", "wiki-martial-arts"],
  ["base:monk:ability:chi-burst", "ability", "Chi Burst", "wiki-martial-arts"],
  ["base:monk:ability:chakra", "ability", "Chakra", "wiki-martial-arts"],
  ["base:monk:ability:meditate", "ability", "Meditate", "wiki-martial-arts"],
  ["base:monk:ability:focus-energy", "ability", "Focus Energy", "wiki-martial-arts"],
  ["base:monk:ability:first-aid", "ability", "First-Aid", "wiki-martial-arts"],
  ["base:monk:ability:revive", "ability", "Revive", "wiki-martial-arts"],
  ["base:fencer:ability:poison-tip", "ability", "Poison Tip", "wiki-swordplay"],
  ["base:fencer:ability:barbed-cap", "ability", "Barbed Cap", "wiki-swordplay"],
  ["base:fencer:ability:swallowtail", "ability", "Swallowtail", "wiki-swordplay"],
  ["base:fencer:ability:piercethrough", "ability", "Piercethrough", "wiki-swordplay"],
  ["base:fencer:ability:feathercut", "ability", "Feathercut", "wiki-swordplay"],
  ["base:fencer:ability:snowfang", "ability", "Snowfang", "wiki-swordplay"],
  ["base:fencer:ability:nighthawk", "ability", "Nighthawk", "wiki-swordplay"],
  ["base:fencer:ability:checkmate", "ability", "Checkmate", "wiki-swordplay"],
  ["base:fencer:ability:hawk-stance", "ability", "Hawk Stance", "wiki-swordplay"],
  ["base:fencer:ability:eagle-stance", "ability", "Eagle Stance", "wiki-swordplay"],
  ["base:aegis:ability:cover", "ability", "Cover", "wiki-chivalry"],
  ["base:aegis:ability:resist-break", "ability", "Resist Break", "wiki-chivalry"],
  ["base:aegis:ability:magic-break", "ability", "Magic Break", "wiki-chivalry"],
  ["base:aegis:ability:armor-boost", "ability", "Armor Boost", "wiki-chivalry"],
  ["base:aegis:ability:resist-boost", "ability", "Resist Boost", "wiki-chivalry"],
  ["base:aegis:ability:power-wall", "ability", "Power Wall", "wiki-chivalry"],
  ["base:aegis:ability:magic-wall", "ability", "Magic Wall", "wiki-chivalry"],
  ["base:aegis:ability:reprisal-aura", "ability", "Reprisal Aura", "wiki-chivalry"],
  ["base:aegis:ability:entrench", "ability", "Entrench", "wiki-chivalry"],
  ["base:aegis:ability:crystal-form", "ability", "Crystal Form", "wiki-chivalry"],
  ["base:hunter:ability:quickshot", "ability", "Quickshot", "wiki-hunter"],
  ["base:hunter:ability:take-aim", "ability", "Take Aim", "wiki-hunter"],
  ["base:hunter:ability:barrage", "ability", "Barrage", "wiki-hunter"],
  ["base:hunter:ability:thorned-shot", "ability", "Thorned Shot", "wiki-hunter"],
  ["base:hunter:ability:pickoff", "ability", "Pickoff", "wiki-hunter"],
  ["base:hunter:ability:snipe", "ability", "Snipe", "wiki-hunter"],
  ["base:hunter:ability:track", "ability", "Track", "wiki-hunter"],
  ["base:hunter:ability:unguent", "ability", "Unguent", "wiki-hunter"],
  ["base:hunter:ability:hide", "ability", "Hide", "wiki-hunter"],
  ["base:hunter:ability:hunter-s-mark", "ability", "Hunter's Mark", "wiki-hunter"],
  ["base:beatsmith:ability:bass-kick", "ability", "Bass Kick", "wiki-beatsmith"],
  ["base:beatsmith:ability:beat-roll", "ability", "Beat Roll", "wiki-beatsmith"],
  ["base:beatsmith:ability:rhythm-break", "ability", "Rhythm Break", "wiki-beatsmith"],
  ["base:beatsmith:ability:third-act", "ability", "Third Act", "wiki-beatsmith"],
  ["base:beatsmith:ability:crescendo", "ability", "Crescendo", "wiki-beatsmith"],
  ["base:beatsmith:ability:requiem", "ability", "Requiem", "wiki-beatsmith"],
  ["base:beatsmith:ability:rhapsody", "ability", "Rhapsody", "wiki-beatsmith"],
  ["base:beatsmith:ability:mana-song", "ability", "Mana Song", "wiki-beatsmith"],
  ["base:beatsmith:ability:resistance-style", "ability", "Resistance Style", "wiki-beatsmith"],
  ["base:beatsmith:ability:defense-style", "ability", "Defense Style", "wiki-beatsmith"],
  ["base:reaper:ability:reaping-cut", "ability", "Reaping Cut", "wiki-reaper"],
  ["base:reaper:ability:rending-cut", "ability", "Rending Cut", "wiki-reaper"],
  ["base:reaper:ability:nightfall", "ability", "Nightfall", "wiki-reaper"],
  ["base:reaper:ability:guillotine", "ability", "Guillotine", "wiki-reaper"],
  ["base:reaper:ability:lifedrink", "ability", "Lifedrink", "wiki-reaper"],
  ["base:reaper:ability:bloodwell", "ability", "Bloodwell", "wiki-reaper"],
  ["base:reaper:ability:satanic", "ability", "Satanic", "wiki-reaper"],
  ["base:reaper:ability:moon-slash", "ability", "Moon Slash", "wiki-reaper"],
  ["base:reaper:ability:expertise", "ability", "Expertise", "wiki-reaper"],
  ["base:reaper:ability:frenzy", "ability", "Frenzy", "wiki-reaper"],
  ["base:chemist:ability:tonic", "ability", "Tonic", "wiki-chemist"],
  ["base:chemist:ability:potion", "ability", "Potion", "wiki-chemist"],
  ["base:chemist:ability:z-potion", "ability", "Z-Potion", "wiki-chemist"],
  ["base:chemist:ability:tincture", "ability", "Tincture", "wiki-chemist"],
  ["base:chemist:ability:ether", "ability", "Ether", "wiki-chemist"],
  ["base:chemist:ability:zether", "ability", "Zether", "wiki-chemist"],
  ["base:chemist:ability:fenix-juice", "ability", "Fenix Juice", "wiki-chemist"],
  ["base:chemist:ability:fenix-syrup", "ability", "Fenix Syrup", "wiki-chemist"],
  ["base:chemist:ability:heal-oil", "ability", "Heal Oil", "wiki-chemist"],
  ["base:chemist:ability:mp-juice", "ability", "MP Juice", "wiki-chemist"],
  ["base:chemist:ability:ap-juice", "ability", "AP Juice", "wiki-chemist"],
  ["base:chemist:ability:levigel", "ability", "Levigel", "wiki-chemist"],
  ["base:chemist:ability:invisigel", "ability", "Invisigel", "wiki-chemist"],
  ["base:chemist:ability:fig-mixture", "ability", "Fig Mixture", "wiki-chemist"],
  ["base:chemist:ability:sap-mixture", "ability", "Sap Mixture", "wiki-chemist"],
  ["base:chemist:ability:smoke-bomb", "ability", "Smoke Bomb", "wiki-chemist"],
  ["base:weaver:ability:slow", "ability", "Slow", "wiki-time-magic"],
  ["base:weaver:ability:haste", "ability", "Haste", "wiki-time-magic"],
  ["base:weaver:ability:daze", "ability", "Daze", "wiki-time-magic"],
  ["base:weaver:ability:dust", "ability", "Dust", "wiki-time-magic"],
  ["base:weaver:ability:status-drop", "ability", "Status Drop", "wiki-time-magic"],
  ["base:weaver:ability:status-amp", "ability", "Status Amp", "wiki-time-magic"],
  ["base:weaver:ability:stability", "ability", "Stability", "wiki-time-magic"],
  ["base:weaver:ability:statis", "ability", "Statis", "wiki-time-magic"],
  ["base:weaver:ability:rewind", "ability", "Rewind", "wiki-time-magic"],
  ["base:weaver:ability:quick", "ability", "Quick", "wiki-time-magic"],
  ["base:summoner:ability:shaku", "ability", "Shaku", "wiki-summoner"],
  ["base:summoner:ability:pamoa", "ability", "Pamoa", "wiki-summoner"],
  ["base:summoner:ability:niltsi", "ability", "Niltsi", "wiki-summoner"],
  ["base:summoner:ability:ioske", "ability", "Ioske", "wiki-summoner"],
  ["base:summoner:ability:guaba", "ability", "Guaba", "wiki-summoner"],
  ["base:summoner:ability:coyote", "ability", "Coyote", "wiki-summoner"],
  ["base:summoner:ability:pinga", "ability", "Pinga", "wiki-summoner"],
  ["base:summoner:ability:pah", "ability", "Pah", "wiki-summoner"],
  ["base:summoner:ability:tira", "ability", "Tira", "wiki-summoner"],
  ["base:summoner:ability:juses", "ability", "Juses", "wiki-summoner"],
  ["base:mimic:ability:imitate", "ability", "Imitate", "wiki-mimic"],
  ["base:mimic:ability:repeat", "ability", "Repeat", "wiki-mimic"],
  ["base:mimic:ability:copy", "ability", "Copy", "wiki-mimic"],
  ["base:mimic:ability:observe", "ability", "Observe", "wiki-mimic"],
  ["base:mimic:ability:mirror", "ability", "Mirror", "wiki-mimic"],
  ["base:shaman:ability:acid", "ability", "Acid", "wiki-hex-magic"],
  ["base:shaman:ability:bio", "ability", "Bio", "wiki-hex-magic"],
  ["base:shaman:ability:drain", "ability", "Drain", "wiki-shaman"],
  ["base:shaman:ability:instability", "ability", "Instability", "wiki-shaman"],
  ["base:shaman:ability:sleep-echo", "ability", "Sleep Echo", "wiki-shaman"],
  ["base:shaman:ability:stone-core", "ability", "Stone Core", "wiki-shaman"],
  ["base:shaman:ability:mist-core", "ability", "Mist Core", "wiki-shaman"],
  ["base:nomad:ability:healing-spring", "ability", "Healing Spring", "wiki-waterbend"],
  ["base:nomad:ability:shimmertide", "ability", "Shimmertide", "wiki-waterbend"],
  ["base:dervish:ability:quakesand", "ability", "Quakesand", "wiki-prayer-magic"],
  ["base:dervish:ability:fissure", "ability", "Fissure", "wiki-prayer-magic"],
  ["base:valkyrie:ability:warcry", "ability", "Warcry", "wiki-valkyrie"],
  ["base:valkyrie:ability:bracing-strike", "ability", "Bracing Strike", "wiki-valkyrie"],
  ["base:beastmaster:ability:feast", "ability", "Feast", "wiki-wild-arts"],
  ["base:beastmaster:ability:famine", "ability", "Famine", "wiki-wild-arts"],
  ["base:beastmaster:ability:gouge", "ability", "Gouge", "wiki-wild-arts"],
  ["base:assassin:ability:bloody-slice", "ability", "Bloody Slice", "wiki-execute"],
  ["base:assassin:ability:maim-focus", "ability", "Maim Focus", "wiki-assassin"],
  ["base:assassin:ability:maim-sustain", "ability", "Maim Sustain", "wiki-assassin"],
  ["base:assassin:ability:harm-power", "ability", "Harm Power", "wiki-assassin"],
  ["base:assassin:ability:coup-de-grace", "ability", "Coup de Grace", "wiki-assassin"],
  ["base:rogue:ability:steal", "ability", "Steal", "wiki-trickery"],
  ["base:rogue:ability:shadow-cut", "ability", "Shadow Cut", "wiki-trickery"],
  ["base:samurai:ability:ken-asura", "ability", "Ken: Asura", "wiki-samurai"],
  ["base:samurai:ability:ken-heavenslash", "ability", "Ken: Heavenslash", "wiki-samurai"],
  ["base:samurai:ability:ken-omnislice", "ability", "Ken: Omnislice", "wiki-samurai"],
  ["base:scholar:monster-magic:roost", "monsterMagic", "Roost", "apworld-monster-magic"],
  ["base:scholar:monster-magic:lucky-dice", "monsterMagic", "Lucky Dice", "apworld-monster-magic"],
  ["base:scholar:monster-magic:sun-bath", "monsterMagic", "Sun Bath", "apworld-monster-magic"],
  ["base:scholar:monster-magic:sleep-aura", "monsterMagic", "Sleep Aura", "apworld-monster-magic"],
  ["base:scholar:monster-magic:regenerate", "monsterMagic", "Regenerate", "apworld-monster-magic"],
  ["base:scholar:monster-magic:reverse-polarity", "monsterMagic", "Reverse Polarity", "apworld-monster-magic"],
  ["base:scholar:monster-magic:barrier", "monsterMagic", "Barrier", "apworld-monster-magic"],
  ["base:scholar:monster-magic:mp-sickle", "monsterMagic", "MP Sickle", "apworld-monster-magic"],
  ["base:scholar:monster-magic:adrenaline", "monsterMagic", "Adrenaline", "apworld-monster-magic"],
  ["base:scholar:monster-magic:fire-breath", "monsterMagic", "Fire Breath", "apworld-monster-magic"],
  ["base:scholar:monster-magic:explode", "monsterMagic", "Explode", "apworld-monster-magic"],
  ["base:scholar:monster-magic:whirlwind", "monsterMagic", "Whirlwind", "apworld-monster-magic"],
  ["base:scholar:monster-magic:atmoshear", "monsterMagic", "Atmoshear", "apworld-monster-magic"],
  ["base:scholar:monster-magic:build-life", "monsterMagic", "Build Life", "apworld-monster-magic"],
  ["base:scholar:monster-magic:aero", "monsterMagic", "Aero", "apworld-monster-magic"],
  ["base:scholar:monster-magic:insult", "monsterMagic", "Insult", "apworld-monster-magic"],
  ["base:scholar:monster-magic:infusion", "monsterMagic", "Infusion", "apworld-monster-magic"],
  ["base:scholar:monster-magic:overload", "monsterMagic", "Overload", "apworld-monster-magic"],
  ["base:scholar:monster-magic:reflection", "monsterMagic", "Reflection", "apworld-monster-magic"],
  ["base:scholar:monster-magic:lifegiver", "monsterMagic", "Lifegiver", "apworld-monster-magic"],
] as const satisfies readonly StarterNameRecord[]

export function starterCatalogChecksumInput(): string {
  return JSON.stringify({ sources: STARTER_SOURCE_URLS, records: STARTER_NAME_RECORDS, wikiContentDigest: wikiData.contentDigest, switchData })
}

export const STARTER_CATALOG_CONTENT_DIGEST = "18f4b659efb3091482f2300cee31257c9ec14a41eee59cd4e49ec97bb79a82fa"
