import type { LearnedNodeKind } from '../domain/types'

export const ADDITIONAL_CLASS_MAP_FIXTURES: readonly { readonly className: string; readonly squares: readonly (readonly [number, number, string | null, LearnedNodeKind | null])[] }[] = [
  {
    className: 'Rogue',
    squares: [
      [0, 0, 'Steal', 'ability'],
      [0, 2, 'Eye Gouge', 'ability'],
      [0, 3, 'Pinpoint', 'innate'],
      [1, 0, 'Backstab', 'ability'],
      [1, 2, 'Sleep Bomb', 'ability'],
      [2, 0, 'Equip Dagger', 'passive'],
      [2, 1, 'Shadow Cut', 'ability'],
      [2, 2, 'Pocket Sand', 'passive'],
      [2, 3, 'Run Away', 'ability'],
      [3, 1, 'Sneak Attack', 'ability'],
      [3, 3, 'Reflex Stance', 'ability'],
      [4, 1, 'Backstabber', 'passive'],
      [4, 2, 'Trick Slash', 'ability'],
      [5, 2, 'Rupture', 'ability'],
    ],
  },
  {
    className: 'Cleric',
    squares: [
      [0, 1, 'Cure', 'ability'],
      [0, 2, 'Spark Shine', 'ability'],
      [0, 3, 'Pinch Healer', 'innate'],
      [1, 0, 'Mend', 'ability'],
      [1, 3, 'Equip Staff', 'passive'],
      [2, 1, 'Curen', 'ability'],
      [2, 2, 'Spotlight', 'ability'],
      [3, 0, 'Raise', 'ability'],
      [3, 3, 'Inner Warmth', 'passive'],
      [4, 0, 'Return', 'ability'],
      [4, 3, 'Blackout', 'ability'],
      [5, 1, 'Curena', 'ability'],
      [5, 2, 'Star Flare', 'ability'],
    ],
  },
  {
    className: 'Wizard',
    squares: [
      [0, 1, 'Fire', 'ability'],
      [0, 2, 'Bolt', 'ability'],
      [0, 3, 'Element Specialist', 'innate'],
      [1, 0, 'Equip Wand', 'passive'],
      [1, 3, 'Initial Focus', 'passive'],
      [2, 1, 'Firen', 'ability'],
      [2, 2, 'Bolten', 'ability'],
      [3, 1, 'Firena', 'ability'],
      [3, 2, 'Boltena', 'ability'],
      [4, 0, 'Mind Stance', 'ability'],
      [4, 3, 'Storm Stance', 'ability'],
      [5, 1, 'Flare', 'ability'],
      [5, 2, 'Thunder', 'ability'],
    ],
  },
  {
    className: 'Warlock',
    squares: [
      [0, 1, 'Scan', 'ability'],
      [0, 3, 'Chaincaster', 'innate'],
      [1, 0, 'Heal', 'ability'],
      [1, 2, 'Protect', 'ability'],
      [1, 3, 'Blaze', 'ability'],
      [2, 0, 'Remedy', 'ability'],
      [2, 1, 'Regen', 'ability'],
      [2, 2, 'Shell', 'ability'],
      [2, 3, 'Douse', 'ability'],
      [3, 0, 'Life', 'ability'],
      [3, 1, 'Refresh', 'ability'],
      [3, 2, 'Dispel', 'ability'],
      [3, 3, 'Frost', 'ability'],
      [4, 0, 'Regenerator', 'passive'],
      [4, 1, 'Refresher', 'passive'],
      [5, 2, 'Doublecast', 'ability'],
    ],
  },
  {
    className: 'Fencer',
    squares: [
      [0, 1, 'Poison Tip', 'ability'],
      [0, 2, 'Barbed Cap', 'ability'],
      [0, 3, 'Eagle Talon', 'innate'],
      [1, 0, 'Swallowtail', 'ability'],
      [1, 1, 'Hawk Stance', 'ability'],
      [1, 2, 'Eagle Stance', 'ability'],
      [1, 3, 'Piercethrough', 'ability'],
      [4, 0, 'Feathercut', 'ability'],
      [4, 1, 'Eagle Eye', 'passive'],
      [4, 2, 'Equip Rapier', 'passive'],
      [4, 3, 'Snowfang', 'ability'],
      [5, 1, 'Nighthawk', 'ability'],
      [5, 2, 'Checkmate', 'ability'],
    ],
  },
  {
    className: 'Shaman',
    squares: [
      [0, 0, 'Acid', 'ability'],
      [0, 1, 'Bio', 'ability'],
      [0, 2, 'Drain', 'ability'],
      [0, 3, 'Instability', 'ability'],
      [2, 0, 'Acid II', 'ability'],
      [2, 1, 'Bio II', 'ability'],
      [2, 2, 'Safeguard', 'passive'],
      [2, 3, 'Sleep Echo', 'ability'],
      [5, 0, 'Spell Steal', 'innate'],
      [5, 1, 'Epidemic', 'ability'],
      [5, 2, 'Stone Core', 'ability'],
      [5, 3, 'Mist Core', 'ability'],
    ],
  },
  {
    className: 'Scholar',
    squares: [
      [0, 1, 'Learning', 'innate'],
      [0, 2, 'Equip Book', 'passive'],
      [0, 3, 'Studious', 'innate'],
      [1, 0, 'Infusion', 'monsterMagic'],
      [1, 1, 'Regenerate', 'monsterMagic'],
      [1, 2, 'Sun Bath', 'monsterMagic'],
      [1, 3, 'Roost', 'monsterMagic'],
      [2, 0, 'Build Life', 'monsterMagic'],
      [2, 1, 'Lifegiver', 'monsterMagic'],
      [2, 2, 'Reverse Polarity', 'monsterMagic'],
      [2, 3, 'Barrier', 'monsterMagic'],
      [3, 0, null, null],
      [3, 1, 'Adrenaline', 'monsterMagic'],
      [3, 2, 'Aero', 'monsterMagic'],
      [3, 3, 'Whirlwind', 'monsterMagic'],
      [4, 0, 'Fire Breath', 'monsterMagic'],
      [4, 1, 'Lucky Dice', 'monsterMagic'],
      [4, 2, 'Explode', 'monsterMagic'],
      [4, 3, 'MP Sickle', 'monsterMagic'],
      [5, 0, 'Atmoshear', 'monsterMagic'],
      [5, 1, 'Sleep Aura', 'monsterMagic'],
      [5, 2, 'Overload', 'monsterMagic'],
      [5, 3, 'Insult', 'monsterMagic'],
    ],
  },
  {
    className: 'Aegis',
    squares: [
      [0, 0, 'Cover', 'ability'],
      [0, 3, 'Entrench', 'ability'],
      [1, 0, 'Armor Boost', 'ability'],
      [1, 1, 'Natural Tank', 'passive'],
      [1, 2, 'Equip Shield', 'passive'],
      [1, 3, 'Resist Boost', 'ability'],
      [2, 1, 'Stalwart', 'passive'],
      [2, 2, 'Stance Tank', 'passive'],
      [3, 0, 'Magic Break', 'ability'],
      [3, 3, 'Resist Break', 'ability'],
      [4, 1, 'Power Wall', 'ability'],
      [4, 2, 'Magic Wall', 'ability'],
      [5, 1, 'Crystal Form', 'ability'],
      [5, 2, 'Reprisal Aura', 'ability'],
      [5, 3, 'White Knight', 'innate'],
    ],
  },
  {
    className: 'Hunter',
    squares: [
      [0, 0, 'Camouflage', 'innate'],
      [0, 3, 'Quickshot', 'ability'],
      [1, 2, 'Take Aim', 'ability'],
      [1, 3, 'Track', 'ability'],
      [2, 1, 'Barrage', 'ability'],
      [2, 2, 'Equip Bow', 'passive'],
      [2, 3, 'Unguent', 'ability'],
      [3, 0, 'Thorned Shot', 'ability'],
      [3, 1, 'Perfect Vision', 'passive'],
      [3, 3, 'Hide', 'ability'],
      [4, 3, 'Hunter\'s Mark', 'ability'],
      [5, 1, 'Pickoff', 'ability'],
      [5, 2, 'Covert', 'passive'],
      [5, 3, 'Snipe', 'ability'],
    ],
  },
  {
    className: 'Chemist',
    squares: [
      [0, 1, 'Tonic', 'ability'],
      [0, 2, 'Tincture', 'ability'],
      [0, 3, 'Efficience', 'innate'],
      [1, 0, 'Fenix Juice', 'ability'],
      [1, 1, 'Potion', 'ability'],
      [1, 2, 'Ether', 'ability'],
      [1, 3, 'Selfless Cure', 'passive'],
      [2, 0, 'Fenix Syrup', 'ability'],
      [2, 1, 'Z-Potion', 'ability'],
      [2, 2, 'Zether', 'ability'],
      [2, 3, 'Item Finder', 'passive'],
      [3, 0, 'Levigel', 'ability'],
      [3, 1, 'Smoke Bomb', 'ability'],
      [3, 2, 'MP Juice', 'ability'],
      [3, 3, 'Fig Mixture', 'ability'],
      [5, 0, 'Invisigel', 'ability'],
      [5, 1, 'Heal Oil', 'ability'],
      [5, 2, 'AP Juice', 'ability'],
      [5, 3, 'Sap Mixture', 'ability'],
    ],
  },
  {
    className: 'Reaper',
    squares: [
      [0, 0, 'Reaping Cut', 'ability'],
      [0, 1, 'Lifedrink', 'ability'],
      [0, 3, 'Reaping', 'innate'],
      [1, 0, 'Rending Cut', 'ability'],
      [1, 1, 'Bloodwell', 'ability'],
      [2, 0, 'Frenzy', 'ability'],
      [2, 1, 'Expertise', 'ability'],
      [3, 0, 'Blood Spiller', 'passive'],
      [3, 1, 'Satanic', 'ability'],
      [4, 0, 'Nightfall', 'ability'],
      [4, 2, 'Equip Scythe', 'passive'],
      [5, 1, 'Guillotine', 'ability'],
      [5, 2, 'Initial Oomph', 'passive'],
      [5, 3, 'Moon Slash', 'ability'],
    ],
  },
  {
    className: 'Ninja',
    squares: [
      [0, 1, 'Utsusemi', 'ability'],
      [0, 2, 'Fuzake', 'ability'],
      [0, 3, 'Dual Wield', 'innate'],
      [1, 0, 'Smokescreen', 'passive'],
      [1, 3, 'Perfect Dodge', 'passive'],
      [2, 0, 'Fire Seal', 'ability'],
      [2, 3, 'Ice Seal', 'ability'],
      [3, 1, 'Wind Seal', 'ability'],
      [3, 2, 'Earth Seal', 'ability'],
      [4, 0, 'Kawakage', 'ability'],
      [4, 3, 'Vanish', 'ability'],
      [5, 1, 'Thunder Seal', 'ability'],
      [5, 2, 'Water Seal', 'ability'],
    ],
  },
  {
    className: 'Dervish',
    squares: [
      [0, 1, 'Quakesand', 'ability'],
      [0, 2, 'Tornado', 'ability'],
      [0, 3, 'Aura', 'innate'],
      [1, 0, 'Fissure', 'ability'],
      [1, 3, 'Cyclone', 'ability'],
      [2, 1, 'Magic Prayer', 'ability'],
      [2, 2, 'Focus Shield', 'passive'],
      [3, 0, 'Rockslide', 'ability'],
      [3, 3, 'Soul Prayer', 'ability'],
      [4, 1, 'Vigor Drain', 'ability'],
      [4, 2, 'Critical Power', 'passive'],
      [4, 3, 'Typhoon', 'ability'],
      [5, 2, 'Meteor', 'ability'],
    ],
  },
  {
    className: 'Beatsmith',
    squares: [
      [0, 0, 'Bass Kick', 'ability'],
      [0, 3, 'Rhythm', 'innate'],
      [1, 1, 'Beat Roll', 'ability'],
      [2, 0, 'Defense Style', 'ability'],
      [2, 1, 'Auto Speed', 'passive'],
      [2, 2, 'Resistance Style', 'ability'],
      [3, 0, 'Critical Turn', 'passive'],
      [3, 1, 'Rhythm Break', 'ability'],
      [3, 2, 'Third Act', 'ability'],
      [3, 3, 'Mana Song', 'ability'],
      [4, 0, 'Rhapsody', 'ability'],
      [4, 3, 'Requiem', 'ability'],
      [5, 2, 'Crescendo', 'ability'],
    ],
  },
  {
    className: 'Samurai',
    squares: [
      [0, 0, 'Swift Wind', 'ability'],
      [0, 1, 'Swift Ember', 'ability'],
      [0, 2, 'Two-handed', 'innate'],
      [0, 3, 'Endless Fury', 'innate'],
      [1, 1, 'Ken: Asura', 'ability'],
      [1, 2, 'Equip Katana', 'passive'],
      [2, 0, 'Fierce Wind', 'ability'],
      [2, 2, 'Fury', 'passive'],
      [3, 1, 'Blade Song', 'ability'],
      [3, 3, 'Fierce Ember', 'ability'],
      [4, 2, 'Unreactable', 'passive'],
      [4, 3, 'Ken: Heavenslash', 'ability'],
      [5, 3, 'Ken: Omnislice', 'ability'],
    ],
  },
  {
    className: 'Assassin',
    squares: [
      [0, 0, 'Bloody Slice', 'ability'],
      [0, 1, 'Assassination', 'innate'],
      [0, 2, 'Harm Power', 'ability'],
      [0, 3, 'Avid Assault', 'ability'],
      [1, 0, 'Maim Focus', 'ability'],
      [1, 2, 'Harm Magic', 'ability'],
      [2, 0, 'Maim Sustain', 'ability'],
      [2, 3, 'Voracity', 'ability'],
      [3, 2, 'Harm Memory', 'ability'],
      [3, 3, 'Executioner', 'ability'],
      [4, 0, 'Venom Coat', 'passive'],
      [5, 1, 'Coup de Grace', 'ability'],
      [5, 3, 'Crippling Coat', 'passive'],
    ],
  },
]
