import { expect, test, type Page } from '@playwright/test'
import { createBlankPlaythrough, openBuildGameSetup, skipInitialModSetup } from './local-data-helpers'
import { expectOfflineReady } from './offline-helpers'
import { MOBILE_TEST_TAG } from './test-tags'

async function chooseNative(page: Page, label: string, name: string) {
  await page.getByRole('combobox', { name: label, exact: true }).fill(name)
  await page.getByRole('listbox', { name: `Choose ${label}`, exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: new RegExp(`^${name}$`) }) }).filter({ hasText: 'PC 1.6.9.0' }).click()
}

async function openCombat(page: Page) {
  await page.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  const disclosure = page.getByText('Ability and hit-chance preview', { exact: true })
  if (!(await page.getByRole('region', { name: 'Combat preview', exact: true }).isVisible())) await disclosure.click()
}

async function openAdvanced(page: Page) {
  const advanced = page.locator('details.battle-advanced')
  if (!(await advanced.evaluate(element => (element as HTMLDetailsElement).open))) await advanced.locator('summary').first().click()
}

async function openResources(page: Page, actor: 'Actor' | 'Target') {
  const resources = page.getByLabel(`${actor} resources`, { exact: true })
  if (!(await resources.evaluate(element => (element as HTMLDetailsElement).open))) await resources.locator('summary').click()
}

test('native damage stays prominent with inherited stats and optional details collapsed', { tag: MOBILE_TEST_TAG }, async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  // Finish first-run selection before opening another Sheet; the mod selector is lazy loaded
  await skipInitialModSetup(page)
  await createBlankPlaythrough(page)
  await page.goto('/#/builds/library/new')
  await openBuildGameSetup(page)
  await page.getByRole('combobox', { name: 'Difficulty', exact: true }).selectOption({ label: 'Normal' })
  await chooseNative(page, 'Class', 'Wizard')
  const calculationContext = page.getByRole('group', { name: 'Calculation context', exact: true })
  await expect(calculationContext.getByText("Resting stats, without active statuses or turn effects.", { exact: true })).toBeVisible()
  await expect(page.locator('.calculation-coverage')).toHaveJSProperty('open', false)
  await openCombat(page)
  await chooseNative(page, 'Preview ability', 'Fire')
  await page.getByRole('button', { name: 'Add battle scenario', exact: true }).click()
  await page.getByRole('button', { name: 'Loadout', exact: true }).click()
  await expect(calculationContext.getByText("Includes active statuses and elapsed turns from Checks & notes.", { exact: true })).toBeVisible()
  await expect(calculationContext.getByText("Resting stats, without active statuses or turn effects.", { exact: true })).toHaveCount(0)
  await expect(page.locator('.calculation-coverage')).toHaveJSProperty('open', false)
  await openCombat(page)
  await page.getByRole('combobox', { name: 'Battle target', exact: true }).selectOption('monster')
  await chooseNative(page, 'Target monster', 'Slime')
  const actor = page.getByRole('region', { name: 'Your character', exact: true })
  const target = page.getByRole('region', { name: 'Target combatant', exact: true })
  const outcome = page.getByLabel('Battle ability outcome', { exact: true })
  const advanced = page.locator('details.battle-advanced')
  await expect(actor.getByLabel('Actor maximum resources', { exact: true })).not.toContainText('Unknown')
  await expect(target.getByLabel('Target maximum resources', { exact: true })).toContainText('50')
  await expect(outcome.locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^Damage before variance$/ }) }).locator('strong')).toHaveText(/^[1-9][\d,]*$/)
  await expect(advanced).toHaveJSProperty('open', false)
  for (const recipient of ['Actor', 'Target'] as const) {
    await expect(page.getByLabel(`${recipient} resources`, { exact: true })).toHaveJSProperty('open', false)
    for (const resource of ['HP', 'MP', 'AP']) await expect(page.getByLabel(`${recipient} current ${resource}`, { exact: true })).toHaveValue('')
  }
  const abilityBounds = await page.getByRole('combobox', { name: 'Preview ability', exact: true }).boundingBox()
  const targetBounds = await target.boundingBox()
  const actorBounds = await actor.boundingBox()
  const targetPickerBounds = await page.getByRole('combobox', { name: 'Battle target', exact: true }).boundingBox()
  const outcomeBounds = await outcome.boundingBox()
  const advancedBounds = await advanced.locator('summary').first().boundingBox()
  expect(abilityBounds!.y).toBeLessThan(outcomeBounds!.y)
  expect(targetPickerBounds!.y).toBeLessThan(outcomeBounds!.y)
  expect(actorBounds!.y).toBeLessThan(advancedBounds!.y)
  expect(targetBounds!.y).toBeLessThan(advancedBounds!.y)
  expect(outcomeBounds!.y).toBeLessThan(advancedBounds!.y)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('simple-battle-preview.png'), fullPage: true })
  await chooseNative(page, 'Preview ability', '1000 Cuts')
  const selectedAbility = page.getByLabel('Selected ability', { exact: true })
  await expect(selectedAbility.getByRole('heading', { name: '1000 Cuts', exact: true })).toBeVisible()
  await expect(selectedAbility.locator('[data-artwork-placeholder="ability"]')).toBeVisible()
  await expect(selectedAbility.getByText('Magic', { exact: true })).toBeVisible()
  await expect(selectedAbility.getByText('Single target', { exact: true })).toBeVisible()
  await expect(selectedAbility.getByText('None', { exact: true })).toBeVisible()
  const damage = outcome.locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^Damage before variance$/ }) }).locator('strong')
  const hit = outcome.locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^Hit chance before luck$/ }) }).locator('strong')
  await expect(damage).toHaveText('1,000')
  await expect(hit).toHaveText('100%')
  await expect(outcome.getByRole('meter', { name: 'Hit chance before luck', exact: true })).toHaveAttribute('value', '100')
  await expect(outcome.getByRole('meter', { name: 'Critical chance before luck', exact: true })).toHaveAttribute('value', '0')
  expect(await damage.evaluate(element => Number.parseFloat(getComputedStyle(element).fontSize))).toBeGreaterThan(await hit.evaluate(element => Number.parseFloat(getComputedStyle(element).fontSize)))
  const costs = page.getByLabel('Effective ability costs', { exact: true })
  for (const label of ['HP cost', 'MP cost', 'AP cost', 'CT delay', 'Cooldown']) {
    const value = costs.locator('.definition-row').filter({ has: page.locator('dt', { hasText: new RegExp(`^${label}$`) }) }).locator('strong')
    await expect(value).toBeVisible()
    await expect(value).toHaveText('0')
  }
  const baseCosts = page.getByLabel('Base ability costs', { exact: true })
  const damageBreakdown = outcome.locator('details').filter({ has: page.locator('summary', { hasText: /^Damage breakdown$/ }) })
  await expect(baseCosts).not.toBeVisible()
  await expect(damageBreakdown).toHaveJSProperty('open', false)
  await expect(advanced).toHaveJSProperty('open', false)
  await damageBreakdown.locator('summary').click()
  await expect(damageBreakdown).toContainText('Critical amount before variance')
  await expect(damageBreakdown.locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^Critical amount before variance$/ }) }).locator('strong')).toHaveText('1,000')
  await damageBreakdown.locator('summary').click()
  await page.locator('summary').filter({ hasText: /^Base ability costs$/ }).click()
  await expect(baseCosts).toBeVisible()
  await page.locator('summary').filter({ hasText: /^Base ability costs$/ }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await outcome.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('thousand-cuts-result.png') })
  await selectedAbility.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('thousand-cuts-identity.png') })
  await page.locator('summary').filter({ hasText: /^Formula reference$/ }).click()
  const formula = page.getByLabel('Ability estimate', { exact: true })
  await expect(formula.locator('dt').filter({ hasText: /^Power coefficient$/ }).locator('..').locator('dd')).toHaveText('1,000')
  for (const label of ['JP', 'Displayed LP', 'Whole LP needed']) await expect(formula.locator('dt').filter({ hasText: new RegExp(`^${label}$`) }).locator('..').locator('dd')).toHaveText('0')
  await expect(formula.locator('input, select, textarea')).toHaveCount(0)
  const sourceFormula = formula.locator('details').filter({ has: page.locator('summary', { hasText: /^Source formula inputs$/ }) })
  await expect(sourceFormula).toHaveJSProperty('open', false)
  await expect(page.getByLabel('Target evasion', { exact: true })).not.toBeVisible()
  await formula.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('thousand-cuts-formula.png') })
  expect(errors).toEqual([])
})

test('Power Up impact shows Snipe damage changes without current resource assumptions', { tag: MOBILE_TEST_TAG }, async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await skipInitialModSetup(page)
  await createBlankPlaythrough(page)
  await page.goto('/#/builds/library/new')
  await openBuildGameSetup(page)
  await page.getByRole('combobox', { name: 'Difficulty', exact: true }).selectOption({ label: 'Normal' })
  await chooseNative(page, 'Class', 'Hunter')
  await expect(page.getByLabel('Calculation level', { exact: true })).toHaveValue('60')
  await chooseNative(page, 'Main hand', 'War Bow')
  await openCombat(page)
  await chooseNative(page, 'Preview ability', 'Snipe')
  await page.getByRole('button', { name: 'Add battle scenario', exact: true }).click()
  await page.getByRole('combobox', { name: 'Battle target', exact: true }).selectOption('monster')
  await chooseNative(page, 'Target monster', 'Coyote')
  const outcome = page.getByLabel('Battle ability outcome', { exact: true })
  const damage = outcome.locator('.combat-outcome-primary strong')
  await expect(damage).toHaveText('947')
  await expect(page.getByRole('region', { name: 'Status impact', exact: true })).toHaveCount(0)
  await page.getByText('Actor statuses · 0', { exact: true }).click()
  await chooseNative(page, 'Add actor statuses', 'Power Up')
  await expect(damage).toHaveText('1,278')
  const comparison = page.getByRole('region', { name: 'Status impact', exact: true })
  await expect(comparison).toBeVisible()
  await expect(comparison.getByText('Without Power Up', { exact: true }).first()).toBeVisible()
  await expect(comparison.getByText('With Power Up', { exact: true }).first()).toBeVisible()
  await expect(comparison.locator('[data-metric="damage"] strong')).toHaveText(['947', '1,278'])
  await expect(comparison.locator('[data-metric="damage"] .combat-impact__delta')).toHaveText('+331')
  await expect(comparison.locator('[data-metric="criticalDamage"] strong')).toHaveText(['1,429', '1,929'])
  await expect(comparison.locator('[data-metric="criticalDamage"] .combat-impact__delta')).toHaveText('+500')
  expect(await comparison.evaluate(element => element.closest('details:not([open])') === null)).toBe(true)
  expect((await comparison.boundingBox())!.y).toBeGreaterThan((await damage.boundingBox())!.y)
  await expect(page.locator('details.battle-advanced')).toHaveJSProperty('open', false)
  for (const recipient of ['Actor', 'Target'] as const) {
    await expect(page.getByLabel(`${recipient} resources`, { exact: true })).toHaveJSProperty('open', false)
    for (const resource of ['HP', 'MP', 'AP']) await expect(page.getByLabel(`${recipient} current ${resource}`, { exact: true })).toHaveValue('')
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await comparison.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('power-up-status-impact.png') })
  await page.getByText('Target statuses · 0', { exact: true }).click()
  await chooseNative(page, 'Add target statuses', 'Armor Down')
  const selectedStatus = comparison.getByRole('combobox', { name: 'Compare active status', exact: true })
  await selectedStatus.selectOption({ label: 'Armor Down (target)' })
  await expect(comparison.getByText('Target', { exact: true })).toBeVisible()
  await expect(comparison.getByText('Without Armor Down', { exact: true }).first()).toBeVisible()
  await expect(comparison.getByText('With Armor Down', { exact: true }).first()).toBeVisible()
  await expect(comparison.getByText('Without Power Up', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Remove Armor Down from target statuses', exact: true }).click()
  await expect(selectedStatus).toHaveCount(0)
  await expect(comparison.getByText('Power Up', { exact: true })).toBeVisible()
  await expect(comparison.locator('[data-metric="damage"] strong')).toHaveText(['947', '1,278'])
  await page.getByRole('button', { name: 'Remove Power Up from actor statuses', exact: true }).click()
  await expect(comparison).toHaveCount(0)
  await expect(damage).toHaveText('947')
  expect(errors).toEqual([])
})

test('battle assumptions survive editing, sharing, saved copies and offline reload', { tag: MOBILE_TEST_TAG }, async ({ page, context }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await skipInitialModSetup(page)
  await createBlankPlaythrough(page)
  await page.goto('/#/builds/library/new')
  await openBuildGameSetup(page)
  await page.getByRole('combobox', { name: 'Difficulty', exact: true }).selectOption({ label: 'Normal' })
  await chooseNative(page, 'Class', 'Cleric')
  await openCombat(page)
  await chooseNative(page, 'Preview ability', 'Cure')
  const costs = page.getByLabel('Effective ability costs', { exact: true })
  const mp = costs.locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^MP cost$/ }) })
  await expect(mp.locator('strong')).toHaveText('6')
  await page.getByRole('button', { name: 'Add battle scenario', exact: true }).click()
  await expect(page.locator('details.battle-advanced')).toHaveJSProperty('open', false)
  await expect(page.getByLabel('Elapsed actor turns', { exact: true })).toHaveValue('0')
  await expect(page.getByLabel('Elapsed target turns', { exact: true })).toHaveValue('0')
  await page.getByRole('combobox', { name: 'Battle target', exact: true }).selectOption('self')
  const outcome = page.getByLabel('Battle ability outcome', { exact: true })
  await expect(outcome).toContainText('current HP is unknown')
  await expect(mp.locator('strong')).toHaveText('6')
  await outcome.getByRole('button', { name: 'Set actor HP', exact: true }).first().click()
  await expect(page.getByLabel('Actor current HP', { exact: true })).toBeFocused()
  await expect(page.getByLabel('Actor current HP', { exact: true })).toHaveValue('')
  await page.getByRole('button', { name: 'Use full actor resources', exact: true }).click()
  await expect(outcome).toContainText('Healing before variance')
  await expect(outcome).not.toContainText('Unknown')
  await expect(page.getByRole('combobox', { name: 'Target monster', exact: true })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Battle target', exact: true }).selectOption('monster')
  await chooseNative(page, 'Target monster', 'Slime')
  await expect(page.getByRole('combobox', { name: 'Battle target', exact: true })).toHaveValue('monster')
  await expect(outcome).toContainText('current HP is unknown')
  await outcome.getByRole('button', { name: 'Set target HP', exact: true }).first().click()
  await expect(page.getByLabel('Target current HP', { exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Use full target resources', exact: true }).click()
  await openAdvanced(page)
  await page.getByLabel('Elapsed target turns', { exact: true }).fill('3')
  await expect(outcome).not.toContainText('Unknown')
  await page.getByRole('combobox', { name: 'Battle target', exact: true }).selectOption('self')
  await expect(page.getByLabel('Elapsed target turns', { exact: true })).toHaveCount(0)
  await page.getByLabel('Actor current HP', { exact: true }).fill('100')
  await page.getByLabel('Elapsed actor turns', { exact: true }).fill('2')
  await page.getByText('Actor statuses · 0', { exact: true }).click()
  await chooseNative(page, 'Add actor statuses', 'Poison')
  await page.getByLabel('Actor statuses: Poison duration', { exact: true }).fill('3')
  await page.locator('summary').filter({ hasText: /^Periodic and status effects$/ }).click()
  const periodic = page.getByLabel('Periodic battle effects', { exact: true })
  const poisonTick = periodic.locator('.definition-row').filter({ hasText: 'HP per tick' }).locator('strong')
  await expect(poisonTick).toHaveText(/^[1-9][\d,]*$/)
  await page.getByRole('combobox', { name: 'Add actor statuses', exact: true }).fill('Poison')
  await expect(page.getByRole('listbox', { name: 'Choose Add actor statuses', exact: true }).getByRole('option').filter({ hasText: 'PC 1.6.9.0' }).filter({ has: page.locator('strong', { hasText: /^Poison$/ }) })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeEnabled()
  await page.reload()
  await openCombat(page)
  await openAdvanced(page)
  await openResources(page, 'Actor')
  await expect(page.getByLabel('Elapsed actor turns', { exact: true })).toHaveValue('2')
  await expect(page.getByLabel('Actor current HP', { exact: true })).toHaveValue('100')
  await page.getByText('Actor statuses · 1', { exact: true }).click()
  await expect(page.getByLabel('Actor statuses: Poison duration', { exact: true })).toHaveValue('3')
  const results = await outcome.locator('dt, dd').allTextContents()
  await page.getByRole('button', { name: 'Share build', exact: true }).click()
  const share = page.getByRole('dialog', { name: 'Share build', exact: true })
  const url = await share.getByLabel('Share URL', { exact: true }).inputValue()
  await page.goto(url)
  await openCombat(page)
  const preview = page.getByRole('region', { name: 'Combat preview', exact: true })
  await expect(outcome.locator('dt, dd')).toHaveText(results)
  await expect(preview.locator('input, select, textarea')).toHaveCount(0)
  await expect(preview.getByRole('button', { name: 'Use resting stats', exact: true })).toHaveCount(0)
  await page.locator('summary').filter({ hasText: /^Calculation inputs$/ }).click()
  await expect(page.getByLabel('Calculation inputs', { exact: true }).locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^Elapsed target turns \(retained for other targets\)$/ }) }).locator('dd')).toHaveText('3')
  await page.getByRole('button', { name: 'Save a copy', exact: true }).click()
  await openCombat(page)
  await openAdvanced(page)
  await expect(page.getByLabel('Elapsed actor turns', { exact: true })).toHaveValue('2')
  await page.getByRole('combobox', { name: 'Battle target', exact: true }).selectOption('')
  await expect(page.getByLabel('Elapsed target turns', { exact: true })).toHaveValue('3')
  await page.getByRole('combobox', { name: 'Battle target', exact: true }).selectOption('self')
  await expect(outcome.locator('dt, dd')).toHaveText(results)
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  await expect(page.getByText('Unsaved edits are still open', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save and continue', exact: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  await settings.getByRole('button', { name: 'Prepare for offline use', exact: true }).click()
  await expectOfflineReady(settings)
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.reload()
  await openCombat(page)
  await expect(outcome.locator('dt, dd')).toHaveText(results)
  await expect(page.getByLabel('Actor current HP', { exact: true })).toHaveValue('100')
  await openAdvanced(page)
  await openResources(page, 'Actor')
  await page.getByRole('combobox', { name: 'Battle target', exact: true }).selectOption('')
  await expect(page.getByLabel('Elapsed target turns', { exact: true })).toHaveValue('3')
  await page.getByRole('combobox', { name: 'Battle target', exact: true }).selectOption('self')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByLabel('Actor current HP', { exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('battle-scenario.png'), fullPage: true })
  expect(errors).toEqual([])
})
