import { expect, test, type Page } from '@playwright/test'
import { createBlankPlaythrough } from './profile-helpers'

async function choose(page: Page, label: string, name: string) {
  const field = page.getByRole('combobox', { name: label, exact: true })
  await field.fill(name)
  await page.getByRole('listbox', { name: `Choose ${label}`, exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: new RegExp(`^${name}$`) }) }).click()
  if (label !== 'Add planned status') await expect(field).toHaveValue(name)
}

test('build mechanics survive checkpoints and offline reload without observed character data', async ({ page, context }, testInfo) => {
  await page.goto('/')
  await createBlankPlaythrough(page)
  await page.goto('/#/builds/library/new')
  await choose(page, 'Class', 'Cleric')
  await choose(page, 'Main hand', 'Short Sword')
  const mechanics = page.getByRole('region', { name: 'Build mechanics', exact: true })
  await expect(mechanics.getByText('Cleric cannot equip Sword;', { exact: false })).toBeVisible()
  await choose(page, 'Passive 1', 'Equip Sword')
  await expect(mechanics.getByText('No conflict found in the supported equipment checks.')).toBeVisible()
  await mechanics.getByText('Stats & combat estimates', { exact: true }).click()
  await page.getByLabel('Planned level', { exact: true }).fill('20')
  await page.getByRole('button', { name: 'Use primary class for all growth', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Planned growth class 1', exact: true })).toHaveValue('Cleric')
  const table = page.getByRole('table', { name: 'Build stat estimates', exact: true })
  const spirit = table.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Spirit', exact: true }) })
  await expect(spirit).not.toContainText('Unknown')
  await mechanics.getByText('Planned active statuses', { exact: true }).click()
  await choose(page, 'Add planned status', 'Power Up')
  await expect(mechanics.getByText(/Power Up: Deal 35% more physical damage/)).toBeVisible()
  await mechanics.getByText('Ability and hit-chance preview', { exact: true }).click()
  await choose(page, 'Preview ability', 'Cure')
  await expect(mechanics.getByLabel('Ability estimate')).toContainText('50 + 1.5 Spi')
  await page.getByLabel('Target evasion', { exact: true }).fill('50')
  await page.screenshot({ path: testInfo.outputPath('build-mechanics.png'), fullPage: true })
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeVisible()
  await page.getByText('Stats & combat estimates · level 20', { exact: true }).click()
  await expect(page.getByLabel('Planned level', { exact: true })).toHaveValue('20')
  await expect(page.getByLabel('Planned growth levels 1', { exact: true })).toHaveValue('20')
  await page.getByLabel('Planned growth levels 1', { exact: true }).fill('19')
  await expect(spirit).toContainText('Unknown')
  await page.getByRole('button', { name: 'Save new revision', exact: true }).click()
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  await settings.getByRole('button', { name: 'Prepare for offline use', exact: true }).click()
  await expect(settings.getByText('Offline ready', { exact: true })).toBeVisible()
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.reload()
  await page.getByText('Stats & combat estimates · level 20', { exact: true }).click()
  await expect(page.getByLabel('Planned growth levels 1', { exact: true })).toHaveValue('19')
  await expect(spirit).toContainText('Unknown')
  await page.getByText('Ability and hit-chance preview', { exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Preview ability', exact: true })).toHaveValue('Cure')
  await expect(page.getByLabel('Target evasion', { exact: true })).toHaveValue('50')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
