import { expect, test, type Page } from '@playwright/test'
import { createBlankPlaythrough } from './profile-helpers'
import { readFile } from 'node:fs/promises'
import { strFromU8, unzipSync } from 'fflate'
import type { Profile } from '../src/domain/types'

async function choose(page: Page, label: string, name: string) {
  await page.getByRole('combobox', { name: label, exact: true }).fill(name)
  await page.getByRole('listbox', { name: `Choose ${label}`, exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: new RegExp(`^${name}$`) }) }).click()
  await expect(page.getByRole('combobox', { name: label, exact: true })).toHaveValue(name)
}

async function navigate(page: Page, name: string | RegExp) {
  await page.getByRole('button', { name, exact: typeof name === 'string' }).filter({ visible: true }).click()
}

test('build choices expose source facts, uncertain identities, and explicit innate costs', async ({ page, isMobile }, testInfo) => {
  await page.goto('/#/builds/library/new')
  const hand = page.getByRole('combobox', { name: 'Main hand', exact: true })
  await hand.fill('katana')
  await expect(page.getByRole('listbox').getByRole('option').filter({ has: page.locator('strong', { hasText: /^Katanas$/ }) })).toHaveCount(0)
  await choose(page, 'Main hand', 'Muramasa')
  const handField = page.locator('.build-field').filter({ has: hand })
  await expect(handField.locator('.build-field__evidence')).toContainText('Attack: 372')
  await hand.fill('Diamond Katana')
  await expect(page.getByRole('listbox')).toContainText('Attack: 350')
  await hand.press('ArrowDown')
  if (!isMobile) {
    const comparison = page.locator('.build-sheet__preview').getByRole('table')
    await expect(comparison).toContainText('372')
    await expect(comparison).toContainText('350')
  }
  await hand.press('Escape')
  await page.getByRole('combobox', { name: 'Head', exact: true }).fill('viking')
  const hats = page.getByRole('listbox')
  await expect(hats).toContainText("Viking's Hat")
  await expect(hats).toContainText('Vikings Hat')
  await expect(hats).toContainText('Name only')
  await expect(hats).toContainText('shared identity unconfirmed')
  await page.getByRole('combobox', { name: 'Head', exact: true }).press('Escape')
  await choose(page, 'Accessory 1', 'Crit Fang')
  const fang = page.locator('.build-field').filter({ has: page.getByRole('combobox', { name: 'Accessory 1', exact: true }) })
  await expect(fang.locator('.build-field__evidence')).toContainText('Crit. Chance: +10%')
  await expect(fang.locator('.build-field__evidence')).toContainText('Accuracy: +20')
  if (isMobile) {
    const inputBox = (await fang.getByRole('combobox').boundingBox())!
    const factsBox = (await fang.locator('.build-field__evidence').boundingBox())!
    expect(factsBox.y - inputBox.y - inputBox.height).toBeLessThan(30)
  }
  await choose(page, 'Passive 1', 'Attack Focus')
  await choose(page, 'Passive 2', 'Backstabber')
  await choose(page, 'Passive 3', 'Duel Ready')
  await expect(page.getByRole('status', { name: 'Passive PP summary' })).toContainText('9 source PP total')
  await expect(page.getByRole('status', { name: 'Passive PP summary' })).toContainText('PP capacity unknown')
  const passive = page.getByRole('combobox', { name: 'Passive 4', exact: true })
  await passive.fill('Two-handed')
  await expect(page.getByRole('listbox')).toContainText('No matching definitions')
  await passive.press('Escape')
  await page.getByRole('checkbox', { name: 'Include innate effects in Passive 4 (rules unverified)', exact: true }).check()
  await passive.fill('Two-handed')
  await expect(page.getByRole('listbox')).toContainText('Innate')
  await expect(page.getByRole('listbox')).toContainText('PP: unknown')
  await page.getByRole('listbox').getByRole('option').filter({ has: page.locator('strong', { hasText: /^Two-handed$/ }) }).click()
  await expect(page.getByRole('status', { name: 'Passive PP summary' })).toContainText('9 source PP + 1 unresolved cost')
  await page.screenshot({ path: testInfo.outputPath('build-source-evidence.png'), fullPage: true })
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeVisible()
  if (isMobile) await expect(page.locator('.build-library')).not.toHaveAttribute('open')
  await page.reload()
  await expect(page.getByRole('combobox', { name: 'Passive 4', exact: true })).toHaveValue('Two-handed')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('new and existing build drafts survive Reference research, history, and return navigation', async ({ page, isMobile }) => {
  await page.goto('/')
  await createBlankPlaythrough(page)
  await page.goto('/#/builds/library/new')
  await choose(page, 'Main hand', 'Muramasa')
  await page.getByText('Build details & notes', { exact: true }).click()
  await page.getByLabel('Build title').fill('Synthetic research draft')
  await page.getByLabel('Rotation or use notes').fill('Keep this draft while checking evidence')
  await page.getByLabel('Context assumptions').fill('First assumption\nSecond assumption')
  await page.getByLabel('Checkpoint name').fill('Initial idea')
  await navigate(page, 'Reference')
  await expect(page.getByText('Your build draft is kept in this tab', { exact: true })).toBeVisible()
  if (isMobile) await page.getByRole('button', { name: /^Filters/ }).click()
  await page.getByRole('searchbox', { name: 'Search reference', exact: true }).fill('Crit Fang')
  await page.locator('.reference-card').filter({ has: page.getByRole('heading', { name: 'Crit Fang', exact: true }) }).click()
  await expect(page).toHaveURL(/#\/reference\//)
  await page.goBack()
  await expect(page.getByText('Your build draft is kept in this tab', { exact: true })).toBeVisible()
  await navigate(page, /^(Builds|Builds & teams)$/)
  await expect(page.getByLabel('Build title')).toHaveValue('Synthetic research draft')
  await expect(page.getByLabel('Rotation or use notes')).toHaveValue('Keep this draft while checking evidence')
  await expect(page.getByLabel('Context assumptions')).toHaveValue('First assumption\nSecond assumption')
  await expect(page.getByLabel('Checkpoint name')).toHaveValue('Initial idea')
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue('Muramasa')
  await navigate(page, 'Inventory')
  await expect(page).toHaveURL(/#\/builds\/library\/new$/)
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeVisible()
  await choose(page, 'Main hand', 'Diamond Katana')
  await navigate(page, 'Reference')
  await navigate(page, 'Return to build draft')
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue('Diamond Katana')
  await page.getByRole('button', { name: 'Discard edits', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue('Muramasa')
  await navigate(page, 'Reference')
  await expect(page.getByText('Your build draft is kept in this tab', { exact: true })).not.toBeVisible()
})

test('readiness assigns the saved revision, groups shared causes, and opens affected stock', async ({ page }, testInfo) => {
  await page.goto('/#/builds/library/new')
  await choose(page, 'Main hand', 'Muramasa')
  await choose(page, 'Accessory 1', 'Crit Fang')
  await choose(page, 'Passive 1', 'Attack Focus')
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await page.getByText('Check in-game readiness', { exact: true }).click()
  await expect(page.getByText('Validation awaits a scenario', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Assign revision to team', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Revision assigned', exact: true })).toBeDisabled()
  await expect(page.getByText('Validation awaits a scenario', { exact: true })).not.toBeVisible()
  const suggested = page.locator('.validation-group').filter({ has: page.locator('summary', { hasText: /suggested slot definition/ }) })
  await expect(suggested).toHaveCount(1)
  await suggested.locator('summary').click()
  await expect(suggested.getByText('Main hand', { exact: true })).toBeVisible()
  await expect(suggested.getByText('Passive 1', { exact: true })).toBeVisible()
  await expect(suggested.getByRole('button', { name: 'Review ruleset settings', exact: true })).toBeVisible()
  const stock = page.locator('.validation-group').filter({ has: page.getByRole('button', { name: 'Review stock for Muramasa', exact: true, includeHidden: true }) })
  await stock.locator('summary').click()
  await page.screenshot({ path: testInfo.outputPath('grouped-readiness.png'), fullPage: true })
  await stock.getByRole('button', { name: 'Review stock for Muramasa', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Inventory', exact: true })).toBeVisible()
  await expect(page.getByRole('searchbox', { name: /Search/ }).first()).toHaveValue('Muramasa')
})

test('readiness creates a team pinned to the saved build when the active ruleset changes', async ({ page }) => {
  await page.goto('/')
  await createBlankPlaythrough(page)
  await page.goto('/#/builds/library/new')
  await choose(page, 'Main hand', 'Muramasa')
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeVisible()
  const buildUrl = page.url()
  await navigate(page, /^(Data & settings|Open data and settings)$/)
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Ruleset', exact: true }).click()
  await settings.getByLabel('Ruleset label').fill('Synthetic later ruleset')
  await settings.getByRole('button', { name: 'Save new ruleset revision', exact: true }).click()
  await expect(page.getByText('Saved locally', { exact: true })).toBeAttached()
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await page.goto(buildUrl)
  await page.getByText('Check in-game readiness', { exact: true }).click()
  await page.getByRole('button', { name: 'Create a team scenario', exact: true }).click()
  const scenario = page.getByRole('dialog', { name: 'Create team scenario', exact: true })
  await expect(scenario).toContainText('Uses saved r1:')
  await scenario.getByLabel('Scenario label').fill('Synthetic pinned readiness')
  await scenario.getByRole('button', { name: 'Create scenario', exact: true }).click()
  await expect(scenario).not.toBeVisible()
  await expect(page).toHaveURL(buildUrl)
  await navigate(page, /^(Data & settings|Open data and settings)$/)
  await settings.getByRole('button', { name: 'Import & backup', exact: true }).click()
  const download = page.waitForEvent('download')
  await settings.getByRole('button', { name: 'Export backup', exact: true }).click()
  const archive = unzipSync(await readFile((await (await download).path())!))
  const profile = (JSON.parse(strFromU8(archive['bundle.json']!)) as { profile: Profile }).profile
  const revision = Object.values(profile.buildRevisions)[0]!
  const team = Object.values(profile.scenarios)[0]!
  expect(team.rulesetRevisionId).toBe(revision.rulesetRevisionId)
  expect(team.catalogLock).toEqual(revision.catalogLock)
  expect(profile.activeRulesetRevisionId).not.toBe(revision.rulesetRevisionId)
  expect(team.assignments).toEqual({})
  expect(profile.inventory).toEqual({})
})

test('readiness and recording actions follow the displayed editor checkpoint', async ({ page }) => {
  const openReadiness = async () => {
    const panel = page.locator('.build-readiness')
    if (await panel.getAttribute('open') === null) await panel.locator(':scope > summary').click()
  }
  await page.goto('/#/builds/library/new')
  await choose(page, 'Main hand', 'Muramasa')
  await page.getByText('Build details & notes', { exact: true }).click()
  await page.getByLabel('Build title').fill('Synthetic checkpoint readiness')
  await page.getByRole('combobox', { name: 'Character', exact: true }).selectOption({ label: 'Rowan' })
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  const checkpoint = page.getByRole('combobox', { name: /^Editor checkpoint/ })
  await expect(checkpoint).toBeVisible()
  const firstRevision = await checkpoint.inputValue()
  await choose(page, 'Main hand', 'Diamond Katana')
  await page.getByRole('button', { name: 'Save new revision', exact: true }).click()
  await expect(checkpoint).not.toHaveValue(firstRevision)
  const secondRevision = await checkpoint.inputValue()
  const secondUrl = page.url()
  await openReadiness()
  const assignment = page.getByRole('region', { name: 'Assign revision for readiness', exact: true })
  await expect(assignment).toContainText('Assign saved r2')

  for (const [revision, name, number] of [[firstRevision, 'Muramasa', 1], [secondRevision, 'Diamond Katana', 2]] as const) {
    await checkpoint.selectOption(revision)
    await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue(name)
    await expect(assignment).toContainText(`Assign saved r${number}`)
    await assignment.getByRole('button', { name: 'Assign revision to team', exact: true }).click()
    await expect(assignment.getByRole('button', { name: 'Revision assigned', exact: true })).toBeDisabled()
    await assignment.getByRole('button', { name: 'Open team scenario', exact: true }).click()
    await expect(page.getByRole('combobox', { name: 'Rowan', exact: true })).toHaveValue(revision)
    await page.goBack()
    await expect(checkpoint).toHaveValue(revision)
    await openReadiness()
  }

  await page.goto(`${secondUrl}/from/${firstRevision}`)
  await expect(checkpoint).toHaveValue(firstRevision)
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue('Muramasa')
  await openReadiness()
  await expect(assignment).toContainText('Assign saved r1')
  await expect(assignment.getByRole('button', { name: 'Assign revision to team', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Record as current', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Record build as current', exact: true })).toContainText('Rowan · revision 1')
})
