import { MOBILE_TEST_TAG } from './test-tags'
import { expectOfflineReady } from './offline-helpers'
import { readFile } from 'node:fs/promises'
import { expect, test, type Page } from '@playwright/test'
import { createBlankPlaythrough } from './local-data-helpers'

async function choose(page: Page, label: string, name: string, options: { includeConflicts?: boolean } = {}) {
  const field = page.getByRole('combobox', { name: label, exact: true })
  await field.fill(name)
  if (options.includeConflicts) await page.getByRole('checkbox', { name: 'Hide known equipment conflicts', exact: true }).uncheck()
  await page.getByRole('listbox', { name: `Choose ${label}`, exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: new RegExp(`^${name}$`) }) }).click()
  if (label !== 'Add planned status') await expect(field).toHaveValue(name)
}

async function expectIncompleteGrowth(page: Page, allocated: number, level: number) {
  await expect(page.getByRole('table', { name: 'Calculated character stats', exact: true })).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Calculated stats', exact: true })).toContainText(`Growth allocates ${allocated} of ${level} levels.`)
  const overview = page.getByRole('table', { name: 'Planned build stats', exact: true })
  await expect(overview.getByRole('columnheader')).toHaveText(['Stat', 'Base'])
  await expect(overview).not.toContainText('Unknown')
}

test('build mechanics survive checkpoints and offline reload without observed character data', { tag: MOBILE_TEST_TAG }, async ({ page, context }, testInfo) => {
  await page.goto('/')
  await createBlankPlaythrough(page)
  await page.goto('/#/builds/library/new')
  await choose(page, 'Class', 'Cleric')
  await choose(page, 'Main hand', 'Short Sword', { includeConflicts: true })
  await page.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  const mechanics = page.getByRole('region', { name: 'Build mechanics', exact: true })
  await expect(mechanics.getByText('Cleric cannot equip Sword;', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Loadout', exact: true }).click()
  await choose(page, 'Equipped passive 1', 'Equip Sword')
  await page.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  await expect(mechanics.getByText('No conflict found in the supported equipment checks.')).toBeVisible()
  await page.getByRole('button', { name: 'Loadout', exact: true }).click()
  await page.getByLabel('Calculation level', { exact: true }).fill('20')
  await page.getByText(/^Level-up growth/).click()
  await expect(page.getByRole('combobox', { name: 'Growth class 1', exact: true })).toHaveValue('Cleric')
  const table = page.getByRole('table', { name: 'Calculated character stats', exact: true })
  const spirit = table.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Spirit', exact: true }) })
  await expect(spirit).not.toContainText('Unknown')
  await page.getByRole('button', { name: 'Decrease growth 1 by 10', exact: true }).click()
  await expect(page.getByLabel('Growth levels 1', { exact: true })).toHaveValue('10')
  await expectIncompleteGrowth(page, 10, 20)
  await page.getByRole('button', { name: 'Increase growth 1 by 10', exact: true }).click()
  await expect(page.getByLabel('Growth levels 1', { exact: true })).toHaveValue('20')
  await page.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  await page.getByText('Ability and hit-chance preview', { exact: true }).click()
  await choose(page, 'Preview ability', 'Cure')
  const ability = page.getByLabel('Ability estimate', { exact: true })
  await expect(ability).toContainText('Native coefficient power before battle effects: -192')
  await expect(ability).toContainText('display 0 LP')
  await page.getByLabel('Target evasion', { exact: true }).fill('0')
  await expect(page.getByLabel('Base physical hit chance', { exact: true })).toHaveText('Base physical hit chance: 100%')
  await page.getByLabel('Target evasion', { exact: true }).fill('100')
  await expect(page.getByLabel('Base physical hit chance', { exact: true })).toHaveText('Base physical hit chance: 50%')
  await page.getByLabel('Target evasion', { exact: true }).fill('')
  await expect(page.getByLabel('Base physical hit chance', { exact: true })).toHaveText('Base physical hit chance: Unknown')
  await page.getByRole('button', { name: 'Loadout', exact: true }).click()
  await page.getByText(/^Level-up growth/).click()
  await choose(page, 'Class', 'Wizard')
  await expect(page.getByRole('combobox', { name: 'Growth class 1', exact: true })).toHaveValue('Cleric')
  await page.getByText('Sample damage calculations', { exact: true }).click()
  await expect(page.getByRole('table', { name: 'Damage benchmarks', exact: true })).not.toContainText('Unknown')
  await page.getByRole('button', { name: 'Add growth class', exact: true }).click()
  await choose(page, 'Growth class 2', 'Warrior')
  await page.getByRole('button', { name: 'Decrease growth 1 by 5', exact: true }).click()
  const slider = page.getByLabel('Growth slider 2', { exact: true })
  await slider.focus()
  await slider.press('End')
  await expect(slider).toHaveValue('5')
  await expect(slider).toHaveAttribute('max', '20')
  await expect(page.getByLabel('Growth levels 1', { exact: true })).toHaveValue('15')
  await page.getByLabel('Calculation level', { exact: true }).fill('10')
  await expect(page.getByLabel('Growth levels 1', { exact: true })).toHaveValue('15')
  await expectIncompleteGrowth(page, 20, 10)
  await page.getByRole('button', { name: 'Decrease growth 1 by 1', exact: true }).click()
  await expect(page.getByLabel('Growth levels 1', { exact: true })).toHaveValue('14')
  await page.getByLabel('Calculation level', { exact: true }).fill('20')
  await page.getByRole('button', { name: 'Follow primary class for all growth', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Growth class 1', exact: true })).toHaveValue('Wizard')
  await expect(page.getByRole('combobox', { name: 'Growth class 2', exact: true })).toHaveCount(0)
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export calculation package', exact: true }).click()
  const file = await download
  expect(file.suggestedFilename()).toBe('crystal-project-calculations-pc-1.6.9-package-v2.json')
  const path = await file.path()
  if (!path) throw new Error('Calculation download failed')
  const exported = JSON.parse(await readFile(path, 'utf8'))
  expect(exported.schemaVersion).toBe(2)
  expect(exported.rules.id).toBe(exported.data.engine)
  expect(exported.rules.formulas.memberHP.evidence).toContain('CalculateMemberHP')
  expect(exported.combat.formulas.periodicHP.evidence).toContain('Sang.Battle.AbilityProcessor.ResolveDamagePerTurn')
  await page.screenshot({ path: testInfo.outputPath('build-mechanics.png'), fullPage: true })
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeVisible()
  await page.getByText(/^Level-up growth/).click()
  await expect(page.getByLabel('Calculation level', { exact: true })).toHaveValue('20')
  await expect(page.getByLabel('Growth levels 1', { exact: true })).toHaveValue('20')
  await page.getByLabel('Growth levels 1', { exact: true }).fill('19')
  await expectIncompleteGrowth(page, 19, 20)
  await page.getByRole('button', { name: 'Save new revision', exact: true }).click()
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  await settings.getByRole('button', { name: 'Prepare for offline use', exact: true }).click()
  await expectOfflineReady(settings)
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.reload()
  await page.getByText(/^Level-up growth/).click()
  await expect(page.getByLabel('Growth levels 1', { exact: true })).toHaveValue('19')
  await expect(page.getByRole('combobox', { name: 'Growth class 1', exact: true })).toHaveValue('Wizard')
  await expectIncompleteGrowth(page, 19, 20)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const offlineDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export calculation package', exact: true }).click()
  const offlinePath = await (await offlineDownload).path()
  if (!offlinePath) throw new Error('Offline calculation download failed')
  expect(JSON.parse(await readFile(offlinePath, 'utf8'))).toEqual(exported)
})
