import { openBuildPickerFilters } from './build-picker-helpers'
import { MOBILE_TEST_TAG } from './test-tags'
import { skipInitialModSetup, openBuildGameSetup, saveAndApplyGameSetup, openCurrentGameSetup, selectedPlaythrough, chooseFourTeamMembers, createBlankPlaythrough, openGameSetupSection } from './local-data-helpers'
import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { strFromU8, unzipSync } from 'fflate'
import type { LocalData } from '../src/domain/types'

const MAX_MOBILE_EVIDENCE_GAP_PX = 30
const MAX_INLINE_BADGE_CENTER_OFFSET_PX = 6

async function choose(page: Page, label: string, name: string, options: { includeConflicts?: boolean } = {}) {
  await page.getByRole('combobox', { name: label, exact: true }).fill(name)
  if (options.includeConflicts) {
    await openBuildPickerFilters(page)
    await page.getByRole('checkbox', { name: 'Hide known equipment conflicts', exact: true }).uncheck()
  }
  await page.getByRole('listbox', { name: `Choose ${label}`, exact: true }).getByRole('option').filter({ hasText: 'PC 1.6.9.0' }).filter({ has: page.locator('strong', { hasText: new RegExp(`^${name}$`) }) }).click()
  await expect(page.getByRole('combobox', { name: label, exact: true })).toHaveValue(name)
}

async function navigate(page: Page, name: string | RegExp) {
  await page.getByRole('button', { name, exact: typeof name === 'string' }).filter({ visible: true }).click()
}

async function addCharacter(page: Page, name: string) {
  await navigate(page, 'Characters')
  await page.getByRole('button', { name: 'Add character', exact: true }).first().click()
  const form = page.getByRole('dialog', { name: 'Add character', exact: true })
  await form.getByLabel('Character name').fill(name)
  await form.getByRole('button', { name: 'Add character', exact: true }).click()
  await expect(form).not.toBeVisible()
}

test('build choices expose native facts, mod scope, and duplicate passive filtering', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }) => {
  await page.goto('/#/builds/library/new')
  await expect(page.getByLabel('Game mode', { exact: true })).toHaveValue('Standard')
  await expect(page.getByLabel('Difficulty', { exact: true })).toHaveValue('0')
  await expect(page.getByLabel('Difficulty', { exact: true }).locator('option:checked')).toHaveText('Normal')
  const classPicker = page.getByRole('combobox', { name: 'Class', exact: true })
  await classPicker.click()
  await expect(page.getByRole('listbox', { name: 'Choose Class', exact: true })).toBeVisible()
  await page.mouse.click(20, 20)
  await expect(page.getByRole('listbox', { name: 'Choose Class', exact: true })).not.toBeVisible()
  await expect(classPicker).toHaveAttribute('aria-expanded', 'false')
  await classPicker.fill('Barbarian')
  await openBuildPickerFilters(page)
  await page.getByText('Broader planning options', { exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Include disabled or unconfirmed mods', exact: true })).toBeChecked()
  const barbarianResult = page.getByRole('listbox').getByRole('option').filter({ has: page.locator('strong', { hasText: /^Barbarian$/ }) })
  await expect(barbarianResult.locator('.picker-result__heading').getByText('Mod: Barbarian', { exact: true })).toBeVisible()
  await expect(barbarianResult.locator('.picker-result__content > [data-mod-badge="Barbarian"]')).toHaveCount(0)
  await expect.poll(() => barbarianResult.locator('.picker-result__heading').evaluate(heading => {
    const name = heading.querySelector('strong')!.getBoundingClientRect()
    const badge = heading.querySelector('[data-mod-badge="Barbarian"] > .badge')!.getBoundingClientRect()
    return Math.abs((name.top + name.bottom - badge.top - badge.bottom) / 2)
  })).toBeLessThanOrEqual(MAX_INLINE_BADGE_CENTER_OFFSET_PX)
  await page.getByRole('checkbox', { name: 'Include disabled or unconfirmed mods', exact: true }).press('Escape')
  await expect(classPicker).toHaveAttribute('aria-expanded', 'false')
  await expect(classPicker).toBeFocused()
  const hand = page.getByRole('combobox', { name: 'Main hand', exact: true })
  await hand.fill('katana')
  await expect(page.getByRole('listbox').getByRole('option').filter({ has: page.locator('strong', { hasText: /^Katanas$/ }) })).toHaveCount(0)
  await openBuildPickerFilters(page)
  await page.getByRole('combobox', { name: 'Sort results', exact: true }).press('Escape')
  await expect(hand).toHaveAttribute('aria-expanded', 'false')
  await expect(hand).toBeFocused()
  await choose(page, 'Main hand', 'Muramasa')
  const handField = page.locator('.build-field').filter({ has: hand })
  await expect(handField.locator('.build-field__evidence')).toContainText('Attack: +372')
  await hand.fill('Diamond Katana')
  await expect(page.getByRole('listbox')).toContainText('Attack: +350')
  await hand.press('ArrowDown')
  if (!isMobile) {
    const nativeKatana = page.getByRole('listbox').getByRole('option').filter({ hasText: 'Attack: +350' }).filter({ has: page.locator('strong', { hasText: /^Diamond Katana$/ }) })
    await hand.press('Home')
    await expect(nativeKatana).toHaveClass(/picker-result--active/)
    const comparison = page.locator('.build-sheet__preview').getByRole('table')
    await expect(comparison).toContainText('372')
    await expect(comparison).toContainText('350')
  }
  await hand.press('Escape')
  await page.getByRole('combobox', { name: 'Head', exact: true }).fill('viking')
  const hats = page.getByRole('listbox')
  await expect(hats).toContainText("Viking's Hat")
  await expect(hats.getByRole('option').filter({ has: page.locator('strong', { hasText: /^Viking's Hat$/ }) })).toHaveCount(1)
  await expect(hats).toContainText('PC 1.6.9.0')
  await expect(hats).not.toContainText('Name only')
  await page.getByRole('combobox', { name: 'Head', exact: true }).press('Escape')
  const offHand = page.getByRole('combobox', { name: 'Off hand', exact: true })
  await offHand.fill('Doge Shield')
  await expect(page.getByRole('listbox').getByText('Mod: Doge Shield', { exact: true })).toBeVisible()
  await expect(page.getByRole('listbox')).toContainText("Mod status unknown in this Build's Game Setup")
  await offHand.press('Escape')
  await choose(page, 'Accessory 1', 'Crit Fang')
  const fang = page.locator('.build-field').filter({ has: page.getByRole('combobox', { name: 'Accessory 1', exact: true }) })
  await expect(fang.locator('.build-field__evidence')).toContainText('Crit. Chance: +10%')
  await expect(fang.locator('.build-field__evidence')).toContainText('Accuracy: +20')
  if (isMobile) {
    await expect.poll(() => fang.evaluate(field => {
      const inputBox = field.querySelector('[role="combobox"]')!.getBoundingClientRect()
      const factsBox = field.querySelector('.build-field__evidence')!.getBoundingClientRect()
      return factsBox.top - inputBox.bottom
    })).toBeLessThan(MAX_MOBILE_EVIDENCE_GAP_PX)
  }
  await choose(page, 'Equipped passive 1', 'Attack Focus')
  const secondPassive = page.getByRole('combobox', { name: 'Equipped passive 2', exact: true })
  await secondPassive.fill('Attack Focus')
  await expect(page.getByRole('listbox').getByRole('option').filter({ hasText: 'PC 1.6.9.0' }).filter({ has: page.locator('strong', { hasText: /^Attack Focus$/ }) })).toHaveCount(0)
  await secondPassive.press('Escape')
  await choose(page, 'Equipped passive 2', 'Backstabber')
  await choose(page, 'Equipped passive 3', 'Duel Ready')
  await expect(page.getByRole('status', { name: 'Build PP summary' })).toContainText('9 / 10 PP')
  await expect(page.getByLabel('PP reference character')).toHaveCount(0)
})

test('learnable mod innates retain source costs, badges and saved selections', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }, testInfo) => {
  await page.goto('/#/builds/library/new')
  await choose(page, 'Main hand', 'Muramasa')
  await choose(page, 'Accessory 1', 'Crit Fang')
  await choose(page, 'Equipped passive 1', 'Attack Focus')
  await choose(page, 'Equipped passive 2', 'Backstabber')
  await choose(page, 'Equipped passive 3', 'Duel Ready')
  await expect(page.getByRole('status', { name: 'Build PP summary' })).toContainText('9 / 10 PP')
  const innateToggle = page.getByRole('checkbox', { name: /^Include learnable innates/ })
  if (!await innateToggle.isVisible()) await page.getByText('Mod passive options', { exact: true }).click()
  await expect(innateToggle).toHaveCount(1)
  await expect(innateToggle).not.toBeChecked()
  await innateToggle.check()
  const passive = page.getByRole('combobox', { name: 'Equipped passive 4', exact: true })
  await passive.fill('Toughness')
  await expect(page.getByRole('listbox').getByRole('option').filter({ hasText: 'PC 1.6.9.0' })).toHaveCount(0)
  await passive.fill('Squall')
  await expect(page.getByRole('listbox').getByRole('option').filter({ hasText: 'PC 1.6.9.0' })).toHaveCount(0)
  await passive.fill('Two-Handed')
  let innateResult = page.getByRole('listbox').getByRole('option').filter({ hasText: 'Learnable Innate Skills' }).filter({ has: page.locator('strong', { hasText: /^Two-Handed$/ }) })
  await expect(innateResult).toContainText('Innate')
  await expect(innateResult).toContainText('6 PP')
  await expect(innateResult.locator('.picker-result__heading').getByText('Mod: Learnable Innate Skills', { exact: true })).toBeVisible()
  await expect(innateResult.locator('.picker-result__content > [data-mod-badge="Learnable Innate Skills"]')).toHaveCount(0)
  await expect.poll(() => innateResult.locator('.picker-result__heading').evaluate(heading => {
    const badge = heading.querySelector('[data-mod-badge="Learnable Innate Skills"]')!.getBoundingClientRect()
    const ppCost = [...heading.querySelectorAll('small')].find(node => node.textContent === '6 PP')!.getBoundingClientRect()
    return badge.right <= ppCost.left || badge.bottom <= ppCost.top
  })).toBe(true)
  await expect(innateResult.locator('[data-game-icon="skill:passive"]')).toBeVisible()
  await expect(innateResult.locator('[data-artwork-placeholder]')).toHaveCount(0)
  await expect.poll(() => innateResult.evaluate(row => {
    const artwork = row.querySelector(':scope > .wiki-sprite, :scope > .game-icon')!.getBoundingClientRect()
    return artwork.width
  })).toBeLessThanOrEqual(32)
  await passive.press('Escape')
  await innateToggle.uncheck()
  await passive.fill('Two-Handed')
  await expect(page.getByRole('listbox')).toContainText('No matching definitions')
  await passive.press('Escape')
  if (!await innateToggle.isVisible()) await page.getByText('Mod passive options', { exact: true }).click()
  await innateToggle.check()
  await passive.fill('Two-Handed')
  innateResult = page.getByRole('listbox').getByRole('option').filter({ hasText: 'Learnable Innate Skills' }).filter({ has: page.locator('strong', { hasText: /^Two-Handed$/ }) })
  await innateResult.click()
  const enableInnates = page.getByRole('dialog', { name: /^Enable Learnable Innate Skills?\?$/ })
  await enableInnates.getByRole('button', { name: 'Enable and select Two-Handed', exact: true }).click()
  await expect(enableInnates).not.toBeVisible()
  await expect(page.getByRole('status', { name: 'Build PP summary' })).toContainText('15 / 10 PP')
  await expect(page.getByRole('region', { name: 'Build validity' })).toContainText('Build needs changes')
  await expect(page.getByRole('region', { name: 'Build validity' })).toContainText('Selected passives cost 15 PP, above the 10 PP limit')
  await innateToggle.uncheck()
  await expect(passive).toHaveValue('Two-Handed')
  await expect(page.getByText('1 equipped innate remains selected. Innates are hidden from search results.', { exact: true })).toBeVisible()
  const nextPassive = page.getByRole('combobox', { name: 'Equipped passive 5', exact: true })
  await nextPassive.fill('Two-Handed')
  await expect(page.getByRole('listbox')).toContainText('No matching definitions')
  await nextPassive.press('Escape')
  if (!await innateToggle.isVisible()) await page.getByText('Mod passive options', { exact: true }).click()
  await innateToggle.check()
  await page.screenshot({ path: testInfo.outputPath('build-catalog-evidence.png'), fullPage: true })
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeVisible()
  if (isMobile) await expect(page.locator('.build-library')).not.toHaveAttribute('open')
  await page.reload()
  await expect(page.getByRole('combobox', { name: 'Equipped passive 4', exact: true })).toHaveValue('Two-Handed')
  await page.getByRole('button', { name: 'Back to Build library', exact: true }).click()
  const card = page.getByRole('region', { name: 'Build library', exact: true }).locator('.build-card').filter({ hasText: 'Untitled build' })
  await expect(card.locator('.build-card__summary-group').filter({ hasText: 'Equipment' })).toContainText('Muramasa')
  await expect(card.locator('.build-card__summary-group').filter({ hasText: 'Equipment' })).toContainText('Crit Fang')
  const passives = card.locator('.build-card__summary-group').filter({ hasText: 'Passives' })
  await expect(passives).toContainText('Attack Focus')
  await expect(passives).toContainText('Backstabber')
  await expect(passives).toContainText('Duel Ready')
  await expect(passives).toContainText('Two-Handed')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('build edit warnings save or discard before continuing to another section', async ({ page }) => {
  await page.goto('/')
  await skipInitialModSetup(page)
  await createBlankPlaythrough(page)
  await page.goto('/#/builds/library/new')
  await choose(page, 'Class', 'Warrior')
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await choose(page, 'Main hand', 'Muramasa', { includeConflicts: true })
  await page.locator('.build-library > summary').click()
  await page.getByRole('button', { name: 'Compare revisions', exact: true }).click()

  let warning = page.locator('.external-update').filter({ hasText: 'Build edits are still open' })
  await expect(warning.getByRole('button', { name: 'Discard and continue', exact: true })).toBeVisible()
  await expect(warning.getByRole('button', { name: 'Save and continue', exact: true })).toBeVisible()
  await warning.getByRole('button', { name: 'Save and continue', exact: true }).click()
  await expect(page).toHaveURL(/#\/builds\/compare(?:\/.*)?$/)

  await page.getByRole('button', { name: 'Build library', exact: true }).click()
  await page.locator('.build-card').filter({ hasText: 'Warrior build' }).click()
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue('Muramasa')
  await choose(page, 'Main hand', 'Diamond Katana', { includeConflicts: true })
  await page.locator('.build-library > summary').click()
  await page.getByRole('button', { name: 'Compare revisions', exact: true }).click()

  warning = page.locator('.external-update').filter({ hasText: 'Build edits are still open' })
  await warning.getByRole('button', { name: 'Discard and continue', exact: true }).click()
  await expect(page).toHaveURL(/#\/builds\/compare(?:\/.*)?$/)
  await page.getByRole('button', { name: 'Build library', exact: true }).click()
  await page.locator('.build-card').filter({ hasText: 'Warrior build' }).click()
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue('Muramasa')
})

test('new and existing build drafts survive Reference research, history, and return navigation', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }) => {
  await page.goto('/')
  await skipInitialModSetup(page)
  await createBlankPlaythrough(page)
  await page.goto('/#/builds/library/new')
  await openBuildGameSetup(page)
  await page.getByRole('combobox', { name: 'Copy Game Setup', exact: true }).selectOption('playthrough')
  await choose(page, 'Main hand', 'Muramasa')
  await page.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  await page.getByText('Build details & notes', { exact: true }).click()
  await page.getByLabel('Build title').fill('Synthetic research draft')
  await page.getByLabel('Rotation or use notes').fill('Keep this draft while checking evidence')
  await page.getByLabel('Context assumptions').fill('First assumption\nSecond assumption')
  await page.getByLabel('Checkpoint name').fill('Initial idea')
  await navigate(page, 'Reference')
  await expect(page.getByText('Your build draft is kept in this tab', { exact: true })).toBeVisible()
  if (isMobile) await page.getByRole('button', { name: /^Filters/ }).click()
  await page.getByRole('searchbox', { name: 'Search reference', exact: true }).fill('Crit Fang')
  await page.locator('.reference-card').filter({ has: page.getByRole('heading', { name: 'Crit Fang', exact: true }) }).click()
  await expect(page).toHaveURL(/#\/reference\//)
  await page.goBack()
  await expect(page.getByText('Your build draft is kept in this tab', { exact: true })).toBeVisible()
  await navigate(page, /^(Builds|Builds & teams)$/)
  await expect(page.getByLabel('Build title')).toHaveValue('Synthetic research draft')
  await expect(page.getByLabel('Rotation or use notes')).toHaveValue('Keep this draft while checking evidence')
  await expect(page.getByLabel('Context assumptions')).toHaveValue('First assumption\nSecond assumption')
  await expect(page.getByLabel('Checkpoint name')).toHaveValue('Initial idea')
  await page.getByRole('button', { name: 'Loadout', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue('Muramasa')
  await navigate(page, 'Inventory')
  await expect(page).toHaveURL(/#\/builds\/library\/new$/)
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Loadout', exact: true }).click()
  await choose(page, 'Main hand', 'Diamond Katana')
  await navigate(page, 'Reference')
  await navigate(page, 'Return to build draft')
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue('Diamond Katana')
  await page.getByRole('button', { name: 'Discard edits', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue('Muramasa')
  await navigate(page, 'Reference')
  await expect(page.getByText('Your build draft is kept in this tab', { exact: true })).not.toBeVisible()
})

test('readiness assigns the saved revision, groups shared causes, and opens affected stock', async ({ page }, testInfo) => {
  await page.goto('/#/builds/library/new')
  await openBuildGameSetup(page)
  await page.getByRole('combobox', { name: 'Copy Game Setup', exact: true }).selectOption('vanilla')
  await choose(page, 'Main hand', 'Muramasa')
  await choose(page, 'Accessory 1', 'Crit Fang')
  await choose(page, 'Equipped passive 1', 'Attack Focus')
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeVisible()
  const checkpointUrl = page.url()
  await page.getByText('Use with Tracking', { exact: true }).click()
  await expect(page.getByText('Choose a party plan', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Create a party plan', exact: true }).click()
  const partyForm = page.getByRole('dialog', { name: 'Create party plan', exact: true })
  await partyForm.getByLabel('Party plan name').fill('Synthetic readiness party')
  await chooseFourTeamMembers(partyForm)
  await partyForm.getByRole('button', { name: 'Create party plan', exact: true }).click()
  await expect(partyForm).not.toBeVisible()
  await page.goto(checkpointUrl)
  await page.getByText('Use with Tracking', { exact: true }).click()
  await expect(page.getByRole('button', { name: 'Revision assigned', exact: true })).toBeDisabled()
  await expect(page.getByText('Choose a party plan', { exact: true })).not.toBeVisible()
  const suggested = page.locator('.validation-group').filter({ has: page.locator('summary', { hasText: /Standard equipment slots in use/ }) })
  await expect(suggested).toHaveCount(1)
  await suggested.locator('summary').click()
  await expect(suggested.getByText('Main hand', { exact: true })).toBeVisible()
  await expect(suggested.getByRole('button', { name: 'Review equipment slots', exact: true })).toBeVisible()
  const stock = page.locator('.validation-group').filter({ has: page.getByRole('button', { name: 'Review stock for Muramasa', exact: true, includeHidden: true }) })
  if (await stock.getAttribute('open') === null) await stock.locator('summary').click()
  await page.screenshot({ path: testInfo.outputPath('grouped-readiness.png'), fullPage: true })
  await stock.getByRole('button', { name: 'Review stock for Muramasa', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Inventory', exact: true })).toBeVisible()
  await expect(page.getByRole('searchbox', { name: /Search/ }).first()).toHaveValue('Muramasa')
})

test('readiness creates a team pinned to the saved build when the current Game Setup changes', async ({ page }) => {
  await page.goto('/')
  await skipInitialModSetup(page)
  await createBlankPlaythrough(page)
  for (const name of ['Synthetic Rowan', 'Synthetic Mira', 'Synthetic Tavi', 'Synthetic Sol']) await addCharacter(page, name)
  await page.goto('/#/builds/library/new')
  await choose(page, 'Main hand', 'Muramasa')
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeVisible()
  const buildUrl = page.url()
  await page.reload()
  await expect(page.getByRole('button', { name: /^Playthrough:/ })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeVisible()
  await navigate(page, /^(Data & settings|Open data and settings)$/)
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await openCurrentGameSetup(settings)
  await settings.getByRole('combobox', { name: 'Difficulty', exact: true }).selectOption('2')
  const gameSetupLabel = settings.getByLabel('Game Setup label')
  await gameSetupLabel.fill('Synthetic later Game Setup')
  await saveAndApplyGameSetup(settings)
  await expect(settings.getByRole('button', { name: 'Save Game Setup', exact: true })).toBeDisabled()
  await expect(gameSetupLabel).toHaveValue('Synthetic later Game Setup')
  await expect(page.getByText('Saved locally', { exact: true })).toBeAttached()
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await page.goto(buildUrl)
  await page.getByText('Use with Tracking', { exact: true }).click()
  await page.getByRole('button', { name: 'Create a party plan', exact: true }).click()
  const scenario = page.getByRole('dialog', { name: 'Create party plan', exact: true })
  await expect(scenario).toContainText('Uses saved r1:')
  await scenario.getByLabel('Party plan name').fill('Synthetic pinned readiness')
  await chooseFourTeamMembers(scenario)
  await scenario.getByRole('button', { name: 'Create party plan', exact: true }).click()
  await expect(scenario).not.toBeVisible()
  await expect(page).toHaveURL(buildUrl)
  await navigate(page, /^(Data & settings|Open data and settings)$/)
  await settings.getByRole('button', { name: 'Import & backup', exact: true }).click()
  const download = page.waitForEvent('download')
  await settings.getByRole('button', { name: 'Export backup', exact: true }).click()
  const archive = unzipSync(await readFile((await (await download).path())!))
  const localData = (JSON.parse(strFromU8(archive['bundle.json']!)) as { localData: LocalData }).localData
  const buildId = decodeURIComponent(/#\/builds\/library\/([^/]+)/.exec(buildUrl)?.[1] ?? '')
  const revision = Object.values(localData.buildRevisions).find(candidate => candidate.buildId === buildId)!
  const team = Object.values(selectedPlaythrough(localData).scenarios).find(candidate => candidate.label === 'Synthetic pinned readiness')!
  expect(team.gameSetupRevisionId).toBe(revision.gameSetupRevisionId)
  expect(team.catalogLock).toEqual(revision.catalogLock)
  expect(localData.planningGameSetupRevisionId).not.toBe(revision.gameSetupRevisionId)
  expect(Object.values(team.assignments)).toEqual([revision.id])
  expect(selectedPlaythrough(localData).inventory).toEqual({})
})

test('readiness and recording actions follow the displayed editor checkpoint', async ({ page }) => {
  const openReadiness = async () => {
    const panel = page.locator('.build-readiness')
    if (await panel.getAttribute('open') === null) await panel.locator(':scope > summary').click()
  }
  await page.goto('/#/builds/library/new')
  await openBuildGameSetup(page)
  await page.getByRole('combobox', { name: 'Copy Game Setup', exact: true }).selectOption('playthrough')
  await choose(page, 'Main hand', 'Muramasa')
  await page.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  await page.getByText('Build details & notes', { exact: true }).click()
  await page.getByLabel('Build title').fill('Synthetic checkpoint readiness')
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  const checkpoint = page.getByRole('combobox', { name: /^Editor checkpoint/ })
  await expect(checkpoint).toBeVisible()
  const firstRevision = await checkpoint.inputValue()
  await choose(page, 'Main hand', 'Diamond Katana')
  await page.getByRole('button', { name: 'Save new revision', exact: true }).click()
  await expect(checkpoint).not.toHaveValue(firstRevision)
  const secondRevision = await checkpoint.inputValue()
  const secondUrl = page.url()
  await openReadiness()
  const assignment = page.getByRole('region', { name: 'Assign revision for readiness', exact: true })
  await expect(assignment).toContainText('Assign saved r2')

  for (const [revision, name, number] of [[firstRevision, 'Muramasa', 1], [secondRevision, 'Diamond Katana', 2]] as const) {
    await checkpoint.selectOption(revision)
    await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue(name)
    await expect(assignment).toContainText(`Assign saved r${number}`)
    await assignment.getByRole('button', { name: 'Assign revision to party', exact: true }).click()
    await expect(assignment.getByRole('button', { name: 'Revision assigned', exact: true })).toBeDisabled()
    await assignment.getByRole('button', { name: 'Open party plan', exact: true }).click()
    await expect(page.getByRole('combobox', { name: 'Rowan', exact: true })).toHaveValue(revision)
    await page.goBack()
    await expect(checkpoint).toHaveValue(revision)
    await openReadiness()
  }

  await page.goto(`${secondUrl}/from/${firstRevision}`)
  await expect(checkpoint).toHaveValue(firstRevision)
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue('Muramasa')
  await openReadiness()
  await expect(assignment).toContainText('Assign saved r1')
  await expect(assignment.getByRole('button', { name: 'Assign revision to party', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Compare / record on a character', exact: true }).click()
  await expect(page.locator('dialog').filter({ has: page.getByRole('heading', { name: 'Compare and record Build', exact: true }) })).toContainText('Synthetic checkpoint readiness r1')
})
