import { createBlankPlaythrough } from './profile-helpers'
import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { strFromU8, unzipSync } from 'fflate'
import type { Profile } from '../src/domain/types'

async function choose(page: Page, label: string, name: string) {
  await page.getByRole('combobox', { name: label, exact: true }).fill(name)
  await page.getByRole('listbox', { name: `Choose ${label}`, exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: new RegExp(`^${name}$`) }) }).click()
  await expect(page.getByRole('combobox', { name: label, exact: true })).toHaveValue(name)
}

async function exportProfile(page: Page): Promise<Profile> {
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Import & backup', exact: true }).click()
  const download = page.waitForEvent('download')
  await settings.getByRole('button', { name: 'Export backup', exact: true }).click()
  const archive = unzipSync(await readFile((await (await download).path())!))
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  return (JSON.parse(strFromU8(archive['bundle.json']!)) as { profile: Profile }).profile
}

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await createBlankPlaythrough(page)
})

test('a blank playthrough can plan unowned gear directly and reopen it offline', async ({ page, context }, testInfo) => {
  await expect(page).toHaveURL(/#\/builds\/library$/)
  await expect(page.getByRole('button', { name: /^Scenario:/ })).toHaveCount(0)
  await page.getByRole('button', { name: 'New build', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toBeVisible()
  await expect(page.locator('dialog:modal')).toHaveCount(0)
  await expect(page.getByLabel('Build title')).not.toBeVisible()
  await choose(page, 'Class', 'Warrior')
  await choose(page, 'Sub-command', 'White Magic')
  await choose(page, 'Main hand', 'Muramasa')
  await choose(page, 'Off hand', "Wizard's Wall")
  await choose(page, 'Head', 'Red Hat')
  await choose(page, 'Body', 'Shadow Gi')
  await choose(page, 'Accessory 1', 'Acrobat Shoes')
  await choose(page, 'Accessory 2', 'Ring of Wizardry')
  await choose(page, 'Equipped passive 1', 'Counter')
  await expect(page.getByRole('combobox', { name: 'Equipped passive 2', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('planned-sheet.png'), fullPage: true })
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeVisible()
  await expect(page.locator('.build-readiness')).not.toHaveAttribute('open')
  const before = await exportProfile(page)
  expect(Object.values(before.builds)).toHaveLength(1)
  expect(Object.values(before.buildRevisions)).toHaveLength(1)
  expect(Object.values(before.builds)[0]).toMatchObject({ title: 'Warrior build', kind: 'template' })
  for (const key of ['inventory', 'inventoryEvents', 'characters', 'personalDefinitions', 'scenarios', 'progress'] as const) expect(before[key]).toEqual({})
  expect(before.rulesets[before.activeRulesetRevisionId!]!.mods.state).toBe('unknown')
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  await settings.getByRole('button', { name: 'Prepare for offline use', exact: true }).click()
  await expect(settings.getByText('Offline ready', { exact: true })).toBeVisible()
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue('Muramasa')
  await expect(page.getByRole('combobox', { name: 'Sub-command', exact: true })).toHaveValue('White Magic')
  await choose(page, 'Accessory 2', 'Acrobat Shoes')
  await page.getByRole('button', { name: 'Save new revision', exact: true }).click()
  await expect(page.getByText('Saved locally', { exact: true })).toBeVisible()
  const after = await exportProfile(page)
  const originalRevision = Object.values(before.buildRevisions)[0]!
  expect(after.buildRevisions[originalRevision.id]).toEqual(originalRevision)
  expect(Object.values(after.buildRevisions)).toHaveLength(2)
  expect(after.inventory).toEqual({})
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('inline search accepts only exact choices and supports keyboard, touch, and history', async ({ page, isMobile }, testInfo) => {
  await page.goto('/#/builds/library/new')
  const hand = page.getByRole('combobox', { name: 'Main hand', exact: true })
  await hand.click()
  const results = page.getByRole('listbox', { name: 'Choose Main hand', exact: true })
  await expect(results).toBeVisible()
  const firstPageCount = await results.getByRole('option').count()
  await hand.press('End')
  await hand.press('Enter')
  await expect.poll(() => results.getByRole('option').count()).toBeGreaterThan(firstPageCount)
  await hand.press('Escape')
  await hand.click()
  await expect.poll(() => results.getByRole('option').count()).toBeGreaterThan(firstPageCount)
  await hand.fill('Muramasa')
  await expect(results).toBeVisible()
  const popup = (await results.boundingBox())!
  const viewport = page.viewportSize()!
  expect(popup.x).toBeGreaterThanOrEqual(0)
  expect(popup.x + popup.width).toBeLessThanOrEqual(viewport.width)
  expect(popup.y).toBeGreaterThanOrEqual(0)
  expect(popup.y + popup.height).toBeLessThanOrEqual(viewport.height)
  await page.screenshot({ path: testInfo.outputPath('inline-search.png'), fullPage: true })
  await hand.press('ArrowDown')
  await hand.press('Enter')
  await expect(hand).toHaveValue('Muramasa')
  await expect(results).not.toBeVisible()
  await hand.fill('made up equipment')
  await expect(results.getByText(/No matching definitions/)).toBeVisible()
  await hand.press('Enter')
  await expect(page.getByRole('button', { name: 'Save build', exact: true })).toBeVisible()
  await hand.press('Escape')
  await expect(hand).toHaveValue('Muramasa')
  await hand.fill('Potion')
  await expect(results.getByRole('option').filter({ has: page.locator('strong', { hasText: /^Potion$/ }) })).toHaveCount(0)
  const head = page.getByRole('combobox', { name: 'Head', exact: true })
  if (isMobile) await head.tap()
  else await head.click()
  await head.fill('Red Hat')
  await expect(page.getByRole('listbox')).toHaveCount(1)
  await page.goBack()
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await page.goForward()
  await expect(head).toHaveValue('Red Hat')
  if (isMobile) {
    await page.getByRole('listbox').getByRole('option').filter({ has: page.locator('strong', { hasText: /^Red Hat$/ }) }).tap()
    await expect(page.locator('.build-sheet__preview')).not.toBeVisible()
    const details = page.getByLabel('Details for Red Hat', { exact: true })
    await expect(details).toHaveText('Details')
    await expect(details).toHaveAccessibleName('Details for Red Hat')
    await page.getByRole('button', { name: 'Clear Head', exact: true }).tap()
  } else await head.press('Escape')
  await expect(head).toHaveValue('')
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeVisible()
  const saved = await exportProfile(page)
  expect(saved.personalDefinitions).toEqual({})
  const equipment = Object.values(saved.buildRevisions)[0]!.content.equipment
  expect(Object.values(equipment).filter(Boolean)).toHaveLength(1)
})

test('build details ignore pointer transit while keyboard inspection stays available', async ({ page, isMobile }) => {
  test.skip(isMobile, 'The shared build inspector is a desktop layout')
  await page.goto('/#/builds/library/new')
  await choose(page, 'Class', 'Warrior')
  const details = page.getByRole('complementary', { name: 'Selection details', exact: true })
  await expect(details.getByRole('heading', { name: 'Warrior', exact: true })).toBeVisible()

  const classField = page.getByRole('combobox', { name: 'Class', exact: true })
  await classField.fill('Wizard')
  const candidate = page.getByRole('listbox', { name: 'Choose Class', exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: /^Wizard$/ }) })
  await candidate.hover()
  await expect(details.getByRole('heading', { name: 'Warrior', exact: true })).toBeVisible()
  await classField.press('ArrowDown')
  await expect(details.getByRole('heading', { name: 'Wizard', exact: true })).toBeVisible()
})

test('failed creation retains the sheet and retry saves one build and checkpoint', async ({ page }) => {
  await page.goto('/#/builds/library/new')
  await choose(page, 'Main hand', 'Muramasa')
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.put
    IDBObjectStore.prototype.put = function (...args: Parameters<typeof original>) {
      if (this.name === 'profiles') { IDBObjectStore.prototype.put = original; throw new DOMException('Synthetic failed build save', 'QuotaExceededError') }
      return original.apply(this, args)
    }
  })
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByText('Revision not saved', { exact: true })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue('Muramasa')
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Retry save', exact: true }).click()
  await expect(page.getByText('Local save failed', { exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeVisible()
  const saved = await exportProfile(page)
  expect(Object.values(saved.builds)).toHaveLength(1)
  expect(Object.values(saved.buildRevisions)).toHaveLength(1)
  expect(saved.inventory).toEqual({})
  await page.reload()
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue('Muramasa')
})

test('direct links reveal the next passive position and restore its inline search', async ({ page }) => {
  await page.goto('/#/builds/library/new/pick/slot/passive-1?q=Counter')
  const passive = page.getByRole('combobox', { name: 'Equipped passive 1', exact: true })
  await expect(passive).toBeFocused()
  await expect(passive).toHaveValue('Counter')
  await expect(page.getByRole('listbox', { name: 'Choose Equipped passive 1', exact: true })).toBeVisible()
  await page.reload()
  await expect(passive).toBeFocused()
  await expect(passive).toHaveValue('Counter')
})
