import { openBuildPickerFilters } from './build-picker-helpers'
import { openBuildActions } from './planning-header-helpers'
import { MOBILE_TEST_TAG } from './test-tags'
import { expect, test, type Page } from '@playwright/test'
import { selectWithSeparateEvents } from './select-helpers'

async function planNativeSample(page: Page) {
  await page.goto('/#/builds/library')
  await page.getByRole('button', { name: 'Rowan: sample Warrior', exact: true }).click()
  await expect(page.getByLabel('Calculation level', { exact: true })).toHaveValue('60')
  await page.locator('.build-behavior > summary').click()
  await page.getByRole('combobox', { name: 'Copy Game Setup', exact: true }).selectOption({ label: 'Unmodified game' })
  await page.getByRole('combobox', { name: 'Game version', exact: true }).selectOption('1.6.9')
  await page.locator('.game-setup-base-details > summary').click()
  await page.getByRole('combobox', { name: 'Platform', exact: true }).selectOption('Windows')
  await page.getByRole('combobox', { name: 'Game mode', exact: true }).selectOption('Standard')
  await page.getByRole('button', { name: 'Save new revision', exact: true }).click()
  await expect(page.getByRole('combobox', { name: /^Editor checkpoint/ }).locator('option:checked')).toContainText('r2')
}

test('build details separate fixed class ratings from level stats and keep editing usable across viewport sizes', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }) => {
  await page.goto('/#/builds/library')
  await page.getByRole('button', { name: 'Rowan: sample Warrior', exact: true }).click()
  const stats = page.getByRole('region', { name: 'Class stats', exact: true })
  await expect(stats.getByRole('heading', { name: 'Warrior stats', exact: true })).toBeVisible()
  const classRatings = stats.getByRole('region', { name: 'Class growth ratings', exact: true })
  await expect(classRatings).toBeVisible()
  await expect(classRatings.locator('.stat-rating')).toHaveCount(10)
  await expect(classRatings.locator('.stat-rating').filter({ has: page.locator('abbr', { hasText: /^HP$/ }) }).getByRole('img', { name: '4 of 5 stars', exact: true })).toBeVisible()
  await expect(classRatings.locator('.stat-rating').filter({ has: page.locator('abbr', { hasText: /^MND$/ }) }).getByRole('img', { name: '0.5 of 5 stars', exact: true })).toBeVisible()
  await expect(stats.getByRole('heading', { name: 'Level 60 stats', exact: true })).toBeVisible()
  await expect(stats).not.toContainText('assumed for preview')
  await expect(stats.getByRole('table', { name: 'Planned build stats', exact: true })).not.toContainText('Unknown')
  await expect(page.getByRole('table', { name: 'Calculated character stats', exact: true })).not.toContainText('Unknown')
  await expect(page.getByRole('region', { name: 'Calculated stats', exact: true })).toContainText('Game version 1.6.6 is treated as equivalent to PC 1.6.9 for calculations.')
  await expect(stats).not.toContainText('Crystal Edit')
  await expect(stats.getByText('Rating sources', { exact: true })).toHaveCount(0)
  await expect(stats.getByRole('table', { name: 'Planned build stats' })).toBeVisible()
  await expect(page.getByLabel('Calculation level', { exact: true })).toHaveValue('60')
  const classPicker = page.getByRole('combobox', { name: 'Class', exact: true })
  const classField = page.locator('.build-field').filter({ has: classPicker })
  await expect(classField.locator('.build-field__artwork .wiki-sprite')).toBeVisible()
  const classFacts = classField.locator('.build-class-facts')
  await expect(classFacts.locator(':scope > span').first()).toHaveText('Command: Battle Skill')
  await expect(classFacts.getByRole('img', { name: 'Weapons: Swords', exact: true })).toHaveAttribute('title', 'Swords')
  await expect(classFacts.getByRole('img', { name: 'Armor: Shields', exact: true })).toHaveAttribute('tabindex', '0')
  const body = page.locator('.build-field').filter({ has: page.getByRole('combobox', { name: 'Body', exact: true }) })
  await expect(body.locator('.build-selection-facts')).toContainText('Defense')
  await expect(body.locator('.build-selection-facts')).not.toContainText('Cost')
  await body.getByText('Details', { exact: true }).click()
  const factLines = body.locator('.build-selection-details__summary > li')
  await expect(factLines.last()).toContainText('Cost:')
  if (isMobile) {
    await openBuildActions(page)
    for (const button of ['New Build', 'Clone Build']) {
      await page.getByRole('button', { name: button, exact: true }).scrollIntoViewIfNeeded()
      const bounds = await page.getByRole('button', { name: button, exact: true }).boundingBox()
      expect(bounds!.x).toBeGreaterThanOrEqual(0)
      expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
    }
    await page.keyboard.press('Escape')
  } else {
    const library = (await page.locator('.build-layout > .build-library').boundingBox())!
    const editor = (await page.locator('.build-layout > section.build-column').boundingBox())!
    expect(library.width).toBeGreaterThanOrEqual(310)
    expect(editor.y).toBeGreaterThanOrEqual(library.y + library.height)
    expect(editor.width).toBeGreaterThanOrEqual(library.width)
  }
  await classPicker.fill('Wizard')
  await classPicker.press('ArrowDown')
  const inspector = page.getByRole('complementary', { name: 'Selection details', exact: true })
  await expect(inspector.locator('.build-selection-details__ratings .stat-rating').filter({ has: page.locator('abbr', { hasText: /^MND$/ }) }).getByRole('img', { name: '4.5 of 5 stars', exact: true })).toBeVisible()
  await expect(stats.getByRole('heading', { name: 'Warrior stats', exact: true })).toBeVisible()
  await page.getByRole('listbox', { name: 'Choose Class', exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: /^Wizard$/ }) }).click()
  await expect(stats.getByRole('heading', { name: 'Wizard stats', exact: true })).toBeVisible()
  await expect(classRatings.locator('.stat-rating').filter({ has: page.locator('abbr', { hasText: /^MND$/ }) }).getByRole('img', { name: '4.5 of 5 stars', exact: true })).toBeVisible()
  await expect(inspector).toBeVisible()
  await expect(inspector.locator('.build-selection-details__ratings')).toHaveCount(0)
  await page.getByRole('button', { name: 'Save new revision', exact: true }).click()
  await expect(page.getByRole('combobox', { name: /^Editor checkpoint/ }).locator('option:checked')).toContainText('r2')
  await page.reload()
  await expect(stats.getByRole('heading', { name: 'Wizard stats', exact: true })).toBeVisible()
})

test('level and allocated growth change numeric stats while class ratings remain fixed', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await page.goto('/#/builds/library/new')
  await page.getByRole('combobox', { name: 'Class', exact: true }).fill('Warrior')
  await page.getByRole('listbox', { name: 'Choose Class', exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: /^Warrior$/ }) }).click()
  const stats = page.getByRole('region', { name: 'Class stats', exact: true })
  const classRatings = stats.getByRole('region', { name: 'Class growth ratings', exact: true }).locator('.rating-stars')
  await expect(classRatings.first()).toBeVisible()
  const ratings = await classRatings.evaluateAll(elements => elements.map(element => element.getAttribute('aria-label')))
  const overview = stats.getByRole('table', { name: 'Planned build stats', exact: true })
  const hp = overview.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Max HP', exact: true }) })
  await expect(hp).not.toContainText('Unknown')
  const originalBase = await hp.getByRole('cell').first().innerText()
  const originalLevel = await hp.getByRole('cell').nth(2).innerText()
  await page.getByLabel('Calculation level', { exact: true }).fill('24')
  await expect(stats).toContainText('Level 24')
  await expect(hp.getByRole('cell').first()).toHaveText(originalBase)
  await expect(hp.getByRole('cell').nth(2)).not.toHaveText(originalLevel)
  const selectedLevel = await hp.getByRole('cell').nth(2).innerText()
  const selectedTotal = await hp.getByRole('cell').nth(4).innerText()
  const detailedHP = page.getByRole('table', { name: 'Calculated character stats', exact: true }).getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Max HP', exact: true }) })
  await expect(detailedHP.getByRole('cell').first()).toHaveText(selectedTotal)
  await page.getByText(/^Level-up growth/).click()
  await page.getByRole('button', { name: 'Decrease growth 1 by 5', exact: true }).click()
  await expect(stats).toContainText('Growth allocates 19 of 24 levels.')
  await expect(overview.getByRole('columnheader')).toHaveText(['Stat', 'Base'])
  await expect(page.getByRole('table', { name: 'Calculated character stats', exact: true })).toHaveCount(0)
  await page.getByLabel('Calculation level', { exact: true }).fill('19')
  await expect(hp).not.toContainText('Unknown')
  await expect(hp.getByRole('cell').first()).toHaveText(originalBase)
  await expect(hp.getByRole('cell').nth(2)).not.toHaveText(selectedLevel)
  expect(await classRatings.evaluateAll(elements => elements.map(element => element.getAttribute('aria-label')))).toEqual(ratings)
  expect(await overview.locator('..').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('gender contributions reconcile colored columns and persist alongside the selected total', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await planNativeSample(page)
  const table = page.getByRole('table', { name: 'Planned build stats', exact: true })
  await expect(table.getByRole('columnheader')).toHaveText(['Stat', 'Base', 'Equipment', 'Level', 'Gender', 'Total'])
  const hp = table.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Max HP', exact: true }) })
  const base = await hp.getByRole('cell').first().innerText()
  const neutral = Number((await hp.getByRole('cell').nth(4).innerText()).replaceAll(',', ''))
  await selectWithSeparateEvents(page.getByLabel('Calculation gender', { exact: true }), 'male')
  const cells = await hp.getByRole('cell').allTextContents()
  const values = cells.map(value => Number(value.replaceAll(',', '')))
  expect(values.slice(0, 4).reduce((sum, value) => sum + value, 0)).toBe(values[4])
  expect(values[4]).toBeGreaterThan(neutral)
  expect(values[3]).toBe(values[4]! - neutral)
  await expect(hp.getByRole('cell').first()).toHaveText(base)
  await expect(hp.getByRole('cell').nth(4).locator('strong')).toHaveText(cells[4]!)
  expect(await table.locator('..').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  const colors = await table.getByRole('columnheader').evaluateAll(elements => elements.slice(1).map(element => getComputedStyle(element).color))
  expect(new Set(colors).size).toBe(colors.length)
  await expect(page.getByRole('table', { name: 'Calculated character stats', exact: true }).getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Max HP', exact: true }) }).getByRole('cell').first()).toHaveText(cells[4]!)
  await page.getByRole('button', { name: 'Save new revision', exact: true }).click()
  await expect(page.getByRole('combobox', { name: /^Editor checkpoint/ }).locator('option:checked')).toContainText('r3')
  await page.reload()
  await expect(page.getByLabel('Calculation gender', { exact: true })).toHaveValue('male')
  await expect(hp.getByRole('cell')).toHaveText(cells)
  await page.getByText('Growth and loadout breakdown', { exact: true }).click()
  const growthHP = page.getByRole('table', { name: 'Growth stat differences', exact: true }).getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'HP', exact: true }) })
  await expect(growthHP.getByRole('cell').nth(1)).toHaveText(cells[4]!)
  await expect(growthHP.getByRole('cell').nth(2)).toHaveText('+0')
  await page.getByLabel('Calculation gender', { exact: true }).selectOption('female')
  await expect(hp.getByRole('cell').nth(3)).toHaveText('0')
  await expect(hp.getByRole('cell').nth(4)).toHaveText(neutral.toLocaleString())
  const agility = table.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Agility', exact: true }) })
  await expect(agility.getByRole('cell').nth(3)).not.toHaveText('0')
})

test('the first female selection and balance mode change survive separate native events', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await planNativeSample(page)
  const checkpoint = page.getByRole('combobox', { name: /^Editor checkpoint/ })
  const gender = page.getByLabel('Calculation gender', { exact: true })
  const mode = page.getByLabel('Game mode', { exact: true })
  const mp = page.getByRole('table', { name: 'Planned build stats', exact: true }).getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Max MP', exact: true }) })
  await expect(checkpoint).toBeEnabled()
  const neutral = Number(await mp.getByRole('cell').nth(4).innerText())
  await selectWithSeparateEvents(gender, 'female')
  await expect(mp.getByRole('cell').nth(3)).toHaveText('+20')
  await expect(mp.getByRole('cell').nth(4)).toHaveText(String(neutral + 20))
  await expect(checkpoint).toBeDisabled()
  await page.getByRole('button', { name: 'Discard edits', exact: true }).click()
  await expect(gender).toHaveValue('')
  await expect(checkpoint).toBeEnabled()
  await page.locator('.build-behavior > summary').click()
  await page.locator('.game-setup-base-details > summary').click()
  await selectWithSeparateEvents(mode, 'Vanilla')
  await expect(checkpoint).toBeDisabled()
  await page.getByRole('button', { name: 'Save new revision', exact: true }).click()
  await expect(checkpoint.locator('option:checked')).toContainText('r3')
  await page.reload()
  await page.locator('.build-behavior > summary').click()
  await page.locator('.game-setup-base-details > summary').click()
  await expect(mode).toHaveValue('Vanilla')
  await expect(gender).toHaveValue('')
})

test('equipment searches explicitly reveal incompatible choices below allowed equipment and respond to class and passive changes', async ({ page }) => {
  await page.goto('/#/builds/library/new')
  const choose = async (label: string, name: string) => {
    await page.getByRole('combobox', { name: label, exact: true }).fill(name)
    await page.getByRole('listbox', { name: `Choose ${label}`, exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: new RegExp(`^${name}$`) }) }).click()
  }
  await choose('Class', 'Cleric')
  const hand = page.getByRole('combobox', { name: 'Main hand', exact: true })
  const results = page.getByRole('listbox', { name: 'Choose Main hand', exact: true })
  await hand.fill('Short')
  const sword = results.getByRole('option').filter({ has: page.locator('strong', { hasText: /^Short Sword$/ }) })
  const staff = results.getByRole('option').filter({ has: page.locator('strong', { hasText: /^Short Staff$/ }) })
  await expect(staff).toHaveAttribute('data-permission-state', 'valid')
  await expect(sword).toHaveCount(0)
  await openBuildPickerFilters(page)
  await results.getByRole('checkbox', { name: 'Hide known equipment conflicts', exact: true }).uncheck()
  await expect(sword).toHaveAttribute('data-permission-state', 'invalid')
  await expect(sword).toContainText('Cleric cannot equip Sword')
  expect(await results.locator('[data-permission-state]').evaluateAll(options => options.every((option, index) => option.getAttribute('data-permission-state') !== 'invalid' || options.slice(index).every(later => later.getAttribute('data-permission-state') === 'invalid')))).toBe(true)
  expect(await sword.evaluate(element => getComputedStyle(element).color)).not.toEqual(await staff.evaluate(element => getComputedStyle(element).color))
  await sword.click()
  await expect(hand).toHaveValue('Short Sword')
  await choose('Equipped passive 1', 'Equip Sword')
  await hand.fill('Short')
  await expect(sword).toHaveAttribute('data-permission-state', 'valid')
  await hand.press('Escape')
  await page.getByRole('button', { name: 'Clear Equipped passive 1', exact: true }).click()
  await choose('Class', 'Warrior')
  await hand.fill('Short')
  await expect(sword).toHaveAttribute('data-permission-state', 'valid')
  await expect(staff).toHaveAttribute('data-permission-state', 'invalid')
  await hand.press('Escape')
  await page.getByRole('button', { name: 'Clear Class', exact: true }).click()
  await hand.fill('Short')
  await expect(sword).toHaveAttribute('data-permission-state', 'undetermined')
  await expect(sword).toContainText('Sword permission is unresolved for the primary class and selected passives')
  await expect(results.locator('[data-permission-state="invalid"]')).toHaveCount(0)
  await hand.press('Escape')
  await page.getByRole('combobox', { name: 'Head', exact: true }).fill('Short Sword')
  await expect(page.getByRole('listbox', { name: 'Choose Head', exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: /^Short Sword$/ }) })).toHaveCount(0)
})

test('class choices show medium armor icons and identify Brawler as Moonlight Project content', async ({ page }) => {
  await page.goto('/#/builds/library/new')
  const classPicker = page.getByRole('combobox', { name: 'Class', exact: true })
  const classField = page.locator('.build-field').filter({ has: classPicker })
  const results = page.getByRole('listbox', { name: 'Choose Class', exact: true })
  await classPicker.fill('Assassin')
  const assassin = results.getByRole('option').filter({ has: page.locator('strong', { hasText: /^Assassin$/ }) })
  for (const type of ['Medium headgear', 'Medium armor']) {
    const icon = assassin.getByRole('img', { name: `Armor: ${type}`, exact: true })
    await expect(icon).toHaveAttribute('title', type)
    await expect.poll(() => icon.locator('img').evaluate(image => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  }
  await expect(assassin.locator('.build-class-facts')).not.toContainText('Medium')
  await classPicker.fill('Brawler')
  const brawler = results.getByRole('option').filter({ has: page.locator('strong', { hasText: /^Brawler$/ }) })
  const modBadge = '[data-mod-badge="Moonlight Project"]'
  await expect(brawler).toBeVisible()
  await expect(brawler.locator(`${modBadge} .badge`)).toHaveText('Mod: Moonlight Project')
  await expect(brawler).toHaveAttribute('data-mod-state', 'unknown')
  await expect(brawler).toContainText("Mod status unknown in this Build's Game Setup. You can still select it.")
  await expect(brawler).not.toContainText('Enabled status not recorded')
  await brawler.click()
  const confirmation = page.getByRole('dialog', { name: 'Enable Moonlight Project?', exact: true })
  await expect(confirmation).toContainText('Brawler requires Moonlight Project')
  await confirmation.getByRole('button', { name: 'Enable and select Brawler', exact: true }).click()
  await expect(classPicker).toHaveValue('Brawler')
  await classField.getByText('Details', { exact: true }).click()
  const sourceBadge = classField.locator('.build-selection-details [data-mod-badge="Moonlight Project - Classes"]')
  await expect(sourceBadge.locator('.badge')).toHaveText('Mod: Moonlight Project - Classes')
  await expect(sourceBadge).toHaveAttribute('data-mod-state', 'enabled')
  await page.goto('/#/reference')
  const referenceSearch = page.getByRole('searchbox', { name: 'Search reference', exact: true })
  if (!await referenceSearch.isVisible()) await page.getByRole('button', { name: /Refine|Filters/ }).click()
  await referenceSearch.fill('Brawler')
  const brawlerClass = page.getByRole('link').filter({ has: page.getByRole('heading', { name: 'Brawler', exact: true }) }).filter({ has: page.locator(modBadge) })
  await expect(brawlerClass.locator(`${modBadge} .badge`)).toHaveText('Mod: Moonlight Project')
  await brawlerClass.click()
  await expect(page.locator(`.reference-detail ${modBadge}`)).toBeVisible()
})
