import { expect, test } from '@playwright/test'

test('build details keep class ratings, artwork, and editing usable across viewport sizes', async ({ page, isMobile }) => {
  await page.goto('/#/builds/library')
  await page.getByRole('button', { name: 'Rowan: sample Warrior', exact: true }).click()
  const stats = page.getByRole('region', { name: 'Class stats', exact: true })
  await expect(stats.getByRole('heading', { name: 'Warrior stat ratings', exact: true })).toBeVisible()
  await expect(stats.locator('.stat-rating')).toHaveCount(10)
  await expect(stats.locator('.stat-rating').filter({ has: page.locator('abbr', { hasText: /^HP$/ }) }).getByRole('img', { name: '4 of 5 stars', exact: true })).toBeVisible()
  await expect(stats.locator('.stat-rating').filter({ has: page.locator('abbr', { hasText: /^MND$/ }) }).getByRole('img', { name: '0.5 of 5 stars', exact: true })).toBeVisible()
  await expect(stats).toContainText('level and growth history')
  await expect(stats).not.toContainText('Crystal Edit')
  await expect(stats.getByText('Rating sources', { exact: true })).toHaveCount(0)
  await expect(stats.getByRole('table', { name: 'Planned build stats' })).toHaveCount(0)
  const classPicker = page.getByRole('combobox', { name: 'Class', exact: true })
  const classField = page.locator('.build-field').filter({ has: classPicker })
  await expect(classField.locator('.build-field__artwork .wiki-sprite')).toBeVisible()
  const classFacts = classField.locator('.build-class-facts')
  await expect(classFacts.locator(':scope > span').first()).toHaveText('Command: Battle Skill')
  await expect(classFacts.getByRole('img', { name: 'Weapons: Swords', exact: true })).toHaveAttribute('title', 'Swords')
  await expect(classFacts.getByRole('img', { name: 'Armor: Shields', exact: true })).toHaveAttribute('tabindex', '0')
  const body = page.locator('.build-field').filter({ has: page.getByRole('combobox', { name: 'Body', exact: true }) })
  await expect(body.locator('.build-selection-facts')).toContainText('Defense')
  await expect(body.locator('.build-selection-facts')).not.toContainText('Cost')
  await body.getByText('Details', { exact: true }).click()
  const factLabels = body.locator('.build-selection-details > .definition-list > .definition-row > dt')
  await expect(factLabels.last()).toHaveText('Cost')
  if (isMobile) {
    for (const button of ['New Build', 'Clone Build']) {
      await page.getByRole('button', { name: button, exact: true }).scrollIntoViewIfNeeded()
      const bounds = await page.getByRole('button', { name: button, exact: true }).boundingBox()
      expect(bounds!.x).toBeGreaterThanOrEqual(0)
      expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
    }
  } else {
    const library = await page.locator('.build-layout > .build-library').boundingBox()
    expect(library!.width).toBeGreaterThanOrEqual(310)
  }
  await classPicker.fill('Wizard')
  await page.getByRole('listbox', { name: 'Choose Class', exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: /^Wizard$/ }) }).click()
  await expect(stats.getByRole('heading', { name: 'Wizard stat ratings', exact: true })).toBeVisible()
  await expect(stats.locator('.stat-rating').filter({ has: page.locator('abbr', { hasText: /^MND$/ }) }).getByRole('img', { name: '4.5 of 5 stars', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save new revision', exact: true }).click()
  await expect(page.getByRole('combobox', { name: /^Editor checkpoint/ })).toContainText('r2')
  await page.reload()
  await expect(stats.getByRole('heading', { name: 'Wizard stat ratings', exact: true })).toBeVisible()
})

test('equipment searches retain incompatible choices below allowed equipment and respond to class and passive changes', async ({ page }) => {
  await page.goto('/#/builds/library/new')
  const choose = async (label: string, name: string) => {
    await page.getByRole('combobox', { name: label, exact: true }).fill(name)
    await page.getByRole('listbox', { name: `Choose ${label}`, exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: new RegExp(`^${name}$`) }) }).click()
  }
  await choose('Class', 'Cleric')
  const hand = page.getByRole('combobox', { name: 'Main hand', exact: true })
  const results = page.getByRole('listbox', { name: 'Choose Main hand', exact: true })
  await hand.fill('Short')
  const sword = results.getByRole('option').filter({ has: page.locator('strong', { hasText: /^Short Sword$/ }) })
  const staff = results.getByRole('option').filter({ has: page.locator('strong', { hasText: /^Short Staff$/ }) })
  await expect(staff).toHaveAttribute('data-permission-state', 'valid')
  await expect(sword).toHaveAttribute('data-permission-state', 'invalid')
  await expect(sword).toContainText('Cleric cannot equip Sword')
  expect(await results.locator('[data-permission-state]').evaluateAll(options => options.every((option, index) => option.getAttribute('data-permission-state') !== 'invalid' || options.slice(index).every(later => later.getAttribute('data-permission-state') === 'invalid')))).toBe(true)
  expect(await sword.evaluate(element => getComputedStyle(element).color)).not.toEqual(await staff.evaluate(element => getComputedStyle(element).color))
  await sword.click()
  await expect(hand).toHaveValue('Short Sword')
  await choose('Equipped passive 1', 'Equip Sword')
  await hand.fill('Short')
  await expect(sword).toHaveAttribute('data-permission-state', 'valid')
  await hand.press('Escape')
  await page.getByRole('button', { name: 'Clear Equipped passive 1', exact: true }).click()
  await choose('Class', 'Warrior')
  await hand.fill('Short')
  await expect(sword).toHaveAttribute('data-permission-state', 'valid')
  await expect(staff).toHaveAttribute('data-permission-state', 'invalid')
  await hand.press('Escape')
  await page.getByRole('button', { name: 'Clear Class', exact: true }).click()
  await hand.fill('Short')
  await expect(sword).toHaveAttribute('data-permission-state', 'undetermined')
  await expect(sword).toContainText('Equip permission unknown')
  await expect(results.locator('[data-permission-state="invalid"]')).toHaveCount(0)
  await hand.press('Escape')
  await page.getByRole('combobox', { name: 'Head', exact: true }).fill('Short Sword')
  await expect(page.getByRole('listbox', { name: 'Choose Head', exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: /^Short Sword$/ }) })).toHaveCount(0)
})

test('class choices show medium armor icons and identify Brawler as Moonlight Project content', async ({ page }) => {
  await page.goto('/#/builds/library/new')
  const classPicker = page.getByRole('combobox', { name: 'Class', exact: true })
  const classField = page.locator('.build-field').filter({ has: classPicker })
  const results = page.getByRole('listbox', { name: 'Choose Class', exact: true })
  await classPicker.fill('Assassin')
  const assassin = results.getByRole('option').filter({ has: page.locator('strong', { hasText: /^Assassin$/ }) })
  for (const type of ['Medium headgear', 'Medium armor']) {
    const icon = assassin.getByRole('img', { name: `Armor: ${type}`, exact: true })
    await expect(icon).toHaveAttribute('title', type)
    await expect.poll(() => icon.locator('img').evaluate(image => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  }
  await expect(assassin.locator('.build-class-facts')).not.toContainText('Medium')
  await classPicker.fill('Brawler')
  const brawler = results.getByRole('option').filter({ has: page.locator('strong', { hasText: /^Brawler$/ }) })
  const modBadge = '[data-mod-badge="Moonlight Project Custom Bosses"]'
  await expect(brawler.locator(`${modBadge} .badge`)).toHaveText('Mod: Moonlight Project')
  await expect(brawler).toHaveAttribute('data-mod-state', 'unknown')
  await expect(brawler).toContainText("Mod status unknown in this Build's Game Setup. You can still select it.")
  await expect(brawler).not.toContainText('Enabled status not recorded')
  await brawler.click()
  await classField.getByText('Details', { exact: true }).click()
  await expect(classField.locator(`.build-selection-details ${modBadge}`)).toBeVisible()
  await page.goto('/#/reference')
  const referenceSearch = page.getByRole('searchbox', { name: 'Search reference', exact: true })
  if (!await referenceSearch.isVisible()) await page.getByRole('button', { name: /Refine|Filters/ }).click()
  await referenceSearch.fill('Brawler')
  const brawlerClass = page.getByRole('link').filter({ has: page.getByRole('heading', { name: 'Brawler', exact: true }) }).filter({ has: page.locator(modBadge) })
  await expect(brawlerClass.locator(`${modBadge} .badge`)).toHaveText('Mod: Moonlight Project')
  await brawlerClass.click()
  await expect(page.locator(`.reference-detail ${modBadge}`)).toBeVisible()
})
