import { MOBILE_TEST_TAG } from './test-tags'
import { expectOfflineReady } from './offline-helpers'
import { selectedPlaythrough, replacePlannerData } from './local-data-helpers'
import { selectWithSeparateEvents } from './select-helpers'
import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { strFromU8, unzipSync, zipSync } from 'fflate'
import { addGameSetupRevision, asId, captureCharacter, createCharacter, createPersonalDefinition, createScenario, upsertCharacterClassProgress } from '../src/domain'
import { addTestBuild, addTestDefinition, createTestLocalData, HAND_SLOT, PASSIVE_SLOT, known, personalRef, TEST_NOW, TEST_GAME_SETUP_REVISION_ID } from '../src/domain/test-helpers'
import type { BuildRevisionId, CharacterId, CharacterSnapshotId, LocalData, GameSetupRevisionId } from '../src/domain/types'
import { SUGGESTED_BUILD_SLOTS } from '../src/domain/build-planning'

const CHARACTER_ID = asId<CharacterId>('synthetic-rowan')
const BEFORE_ID = asId<CharacterSnapshotId>('before')
const AFTER_ID = asId<CharacterSnapshotId>('after')
const BEFORE_DATE = '2026-01-01T10:00:00.000Z'

function syntheticLocalData(changedContext = false, nativeCalculations = false): LocalData {
  let localData = createTestLocalData()
  localData = addTestDefinition(localData, 'Synthetic blade')
  localData = createPersonalDefinition(localData, { id: personalRef('Synthetic warrior').definitionId, name: 'Synthetic warrior', kind: 'class', ...(nativeCalculations ? { fields: { 'Crystal Edit source record': known({ ID: 9000, Name: 'Synthetic warrior', HPRating: 50, MPRating: 50, StrRating: 50, VitRating: 50, DexRating: 50, AgiRating: 50, MndRating: 50, SpiRating: 50, SpdRating: 50, LckRating: 50, PassiveIDs: [] }) } } : {}), now: TEST_NOW })
  localData = createCharacter(localData, { id: CHARACTER_ID, name: 'Synthetic Rowan', now: TEST_NOW })
  localData = createCharacter(localData, { id: asId<CharacterId>('synthetic-mira'), name: 'Synthetic Mira', now: TEST_NOW })
  localData = createCharacter(localData, { id: asId<CharacterId>('synthetic-tavi'), name: 'Synthetic Tavi', now: TEST_NOW })
  localData = createCharacter(localData, { id: asId<CharacterId>('synthetic-sol'), name: 'Synthetic Sol', now: TEST_NOW })
  localData = upsertCharacterClassProgress(localData, { characterId: CHARACTER_ID, classRef: personalRef('Synthetic warrior'), observedLp: known(12), now: TEST_NOW })
  localData = captureCharacter(localData, { characterId: CHARACTER_ID, snapshotId: BEFORE_ID, primaryClass: known(personalRef('Synthetic warrior')), level: known(24), displayedStats: { 'Max HP': { value: known(540), unit: 'points' }, Luck: { value: { state: 'unknown' }, unit: 'displayed' } }, equipment: { [HAND_SLOT]: personalRef('Synthetic blade'), 'second-hand': null }, passives: known([]), observedAt: BEFORE_DATE, note: 'Synthetic earlier observation', now: BEFORE_DATE })
  localData = captureCharacter(localData, { characterId: CHARACTER_ID, snapshotId: AFTER_ID, primaryClass: known(personalRef('Synthetic warrior')), level: known(26), displayedStats: { 'Max HP': { value: known(620), unit: 'points' }, Luck: { value: { state: 'unknown' }, unit: 'displayed' } }, equipment: { [HAND_SLOT]: personalRef('Synthetic blade') }, passives: known([]), observedAt: TEST_NOW, note: 'Synthetic later observation', now: TEST_NOW })
  localData = addTestBuild(localData, 'Synthetic Rowan proposal', CHARACTER_ID, {})
  localData = addTestBuild(localData, 'Synthetic Mira proposal', 'synthetic-mira', {})
  localData = createScenario(localData, { label: 'Synthetic complete team', memberIds: [CHARACTER_ID, asId<CharacterId>('synthetic-mira'), asId<CharacterId>('synthetic-tavi'), asId<CharacterId>('synthetic-sol')], assignments: { [CHARACTER_ID]: asId<BuildRevisionId>('Synthetic Rowan proposal-revision') }, gameSetupRevisionId: TEST_GAME_SETUP_REVISION_ID, activate: true, now: TEST_NOW })
  if (changedContext) {
    const character = selectedPlaythrough(localData).characters[CHARACTER_ID]!
    const { gameSetupRevisionId: _context, ...legacy } = character.snapshots[BEFORE_ID]!
    const playthrough = selectedPlaythrough(localData)
    localData = { ...localData, playthroughs: { ...localData.playthroughs, [playthrough.id]: { ...playthrough, characters: { ...playthrough.characters, [CHARACTER_ID]: { ...character, snapshots: { ...character.snapshots, [BEFORE_ID]: legacy } } } } } }
    localData = addGameSetupRevision(localData, { ...localData.gameSetups[TEST_GAME_SETUP_REVISION_ID]!, id: asId<GameSetupRevisionId>('revised-gameSetup'), activate: true, slots: localData.gameSetups[TEST_GAME_SETUP_REVISION_ID]!.slots.map((slot) => ({ ...slot, label: `Revised ${slot.label}` })), now: TEST_NOW })
  }
  if (nativeCalculations) {
    const setupId = asId<GameSetupRevisionId>('synthetic-native-stats-setup')
    localData = addGameSetupRevision(localData, { ...localData.gameSetups[TEST_GAME_SETUP_REVISION_ID]!, id: setupId, platform: known('Windows'), gameVersion: known('1.6.9.0'), mode: known('Standard'), slots: SUGGESTED_BUILD_SLOTS, activate: true, now: TEST_NOW })
    localData = captureCharacter(localData, { characterId: CHARACTER_ID, gameSetupRevisionId: setupId, primaryClass: known(personalRef('Synthetic warrior')), secondaryClass: { state: 'notApplicable' }, level: known(24), displayedStats: { 'Max HP': { value: known(777), unit: 'points' } }, equipment: Object.fromEntries(SUGGESTED_BUILD_SLOTS.map(slot => [slot.id, null])), passives: known([]), now: TEST_NOW })
  }
  return { ...localData, changes: [] }
}

async function dataPanel(page: Page) {
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  return page.getByRole('dialog', { name: 'Data & settings', exact: true })
}

async function loadFixture(page: Page, changedContext = false, nativeCalculations = false) {
  await page.goto('/')
  const localData = syntheticLocalData(changedContext, nativeCalculations)
  const encode = (value: unknown) => new TextEncoder().encode(JSON.stringify(value))
  const archive = zipSync({
    'manifest.json': encode({ format: 'crykit-backup', formatVersion: '2.0.0', exportedAt: TEST_NOW, payload: 'bundle.json', sources: [] }),
    'bundle.json': encode({ localData, lineage: { rootLocalDataId: localData.id }, catalogs: [], evidence: [], history: [] }),
  })
  const panel = await dataPanel(page)
  await panel.locator('input[type="file"]').setInputFiles({ name: 'synthetic-sheet.zip', mimeType: 'application/zip', buffer: Buffer.from(archive) })
  await expect(panel.getByText('native-backup-2.0.0', { exact: true })).toBeVisible()
  await replacePlannerData(panel)
  await expect(panel).not.toBeVisible()
  await page.goto(`/#/characters/${CHARACTER_ID}/current`)
  await expect(page.getByRole('heading', { name: 'Synthetic Rowan', exact: true })).toBeVisible()
  return localData
}

async function exportLocalData(page: Page): Promise<LocalData> {
  const panel = await dataPanel(page)
  const download = page.waitForEvent('download')
  await panel.getByRole('button', { name: 'Export backup', exact: true }).click()
  const path = await (await download).path()
  if (!path) throw new Error('Backup download failed')
  const archive = unzipSync(await readFile(path))
  const payload = JSON.parse(strFromU8(archive['bundle.json']!)) as { localData: LocalData }
  await panel.getByRole('button', { name: 'Close dialog', exact: true }).click()
  return payload.localData
}

test('character growth calculations save separately from observed level and displayed totals', { tag: MOBILE_TEST_TAG }, async ({ page }, testInfo) => {
  const original = await loadFixture(page, false, true)
  await expect(page.getByRole('region', { name: 'Calculated stats', exact: true })).toContainText('No calculation inputs saved.')
  await page.getByRole('button', { name: 'Plan level-60 native calculations', exact: true }).click()
  await page.getByLabel('Calculation level', { exact: true }).fill('24')
  const table = page.getByRole('table', { name: 'Calculated character stats', exact: true })
  const hp = table.getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Max HP', exact: true }) })
  await expect(hp).not.toContainText('Unknown')
  await expect(hp.getByRole('cell', { name: '777', exact: true })).toBeVisible()
  const overviewHP = page.getByRole('table', { name: 'Planned build stats', exact: true }).getByRole('row').filter({ has: page.getByRole('rowheader', { name: 'Max HP', exact: true }) })
  await expect(overviewHP.getByRole('cell').nth(4)).toHaveText(await hp.getByRole('cell').first().innerText())
  await selectWithSeparateEvents(page.getByLabel('Calculation gender', { exact: true }), 'female')
  await expect(table.getByRole('columnheader').nth(1)).toContainText('Female')
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toBeVisible()
  const originalLevel = await overviewHP.getByRole('cell').nth(2).innerText()
  await page.getByText(/^Level-up growth/).click()
  await page.getByRole('button', { name: 'Decrease growth 1 by 5', exact: true }).click()
  await expect(page.getByLabel('Growth levels 1', { exact: true })).toHaveValue('19')
  await expect(table).toHaveCount(0)
  await expect(page.getByRole('table', { name: 'Recorded character stats', exact: true })).toContainText('777')
  await expect(page.getByRole('region', { name: 'Calculated stats', exact: true })).toContainText('Growth allocates 19 of 24 levels.')
  await expect(overviewHP).not.toContainText('Unknown')
  await expect(page.getByRole('table', { name: 'Planned build stats', exact: true }).getByRole('columnheader')).toHaveText(['Stat', 'Base'])
  await page.getByLabel('Calculation level', { exact: true }).fill('19')
  await expect(hp).not.toContainText('Unknown')
  await expect(overviewHP.getByRole('cell').nth(2)).not.toHaveText(originalLevel)
  await expect(page.getByLabel('Calculation gender', { exact: true })).toHaveValue('female')
  await expect(overviewHP.getByRole('cell').nth(4)).toHaveText(await hp.getByRole('cell').first().innerText())
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.getByLabel('Calculation level', { exact: true })).toHaveValue('19')
  await expect(page.getByLabel('Calculation gender', { exact: true })).toHaveValue('female')
  await expect(hp.getByRole('cell', { name: '777', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('character-calculated-stats.png'), fullPage: true })
  const saved = await exportLocalData(page)
  const character = selectedPlaythrough(saved).characters[CHARACTER_ID]!
  const snapshot = character.snapshots[character.currentSnapshotId!]!
  expect(snapshot.level).toEqual(known(24))
  expect(snapshot.displayedStats['Max HP']?.value).toEqual(known(777))
  expect(snapshot.calculation).toMatchObject({ model: 'pc-1.6.9-v1', growthMode: 'manual', level: 19, gender: 'female' })
  for (const [id, earlier] of Object.entries(selectedPlaythrough(original).characters[CHARACTER_ID]!.snapshots)) expect(character.snapshots[id]).toEqual(earlier)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('recorded sheets inspect and compare exact snapshots without changing observations or proposals', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  const original = await loadFixture(page)
  const lp = page.locator('.member-vital').filter({ has: page.locator('dt', { hasText: /^LP$/ }) })
  await expect(lp).toContainText('12')
  const stats = page.getByRole('region', { name: 'Displayed final stats', exact: true })
  const equipment = page.getByRole('region', { name: 'Equipment and equipped passives', exact: true })
  await page.getByRole('button', { name: 'Status Recorded stats', exact: true }).click()
  await page.locator('.member-record > summary').filter({ hasText: 'Observation details' }).click()
  await expect(stats.getByText('620', { exact: false })).toBeVisible()
  await expect(page.getByText('Synthetic later observation', { exact: true })).toBeVisible()
  await page.getByText('Compare or apply a Build', { exact: true }).click()
  await expect(page.getByRole('button', { name: 'Synthetic Rowan proposal', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Synthetic Mira proposal', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: /^Passives/ }).click()
  await expect(equipment).toContainText('10 PP limit for this Game Setup')
  const statBounds = await stats.boundingBox()
  const equipmentBounds = await equipment.boundingBox()
  expect(statBounds).not.toBeNull()
  expect(equipmentBounds).not.toBeNull()
  expect(equipmentBounds!.y).toBeLessThan(statBounds!.y)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.goto('/#/builds/library')
  const library = page.getByRole('region', { name: 'Build library', exact: true })
  await expect(library.getByRole('button', { name: 'Synthetic Rowan proposal', exact: true })).toBeVisible()
  await expect(library.getByRole('button', { name: 'Synthetic Mira proposal', exact: true })).toBeVisible()
  await page.goto(`/#/characters/${CHARACTER_ID}/current`)
  await page.getByRole('button', { name: 'History', exact: true }).click()
  await page.getByRole('button', { name: 'Inspect snapshot', exact: true }).last().click()
  await expect(page).toHaveURL(new RegExp(`/history/snapshots/${BEFORE_ID}$`))
  await expect(page.getByText('Synthetic earlier observation', { exact: true })).toBeVisible()
  await expect(lp).toContainText('Unknown')
  await expect(page.locator('.member-state')).toHaveText('Historical')
  await expect(page.getByRole('button', { name: 'Edit Hand', exact: true })).toHaveCount(0)
  await page.reload()
  await expect(stats.getByText('540 points', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Back to snapshot history', exact: true }).click()
  await page.getByRole('button', { name: 'Compare snapshots', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/history/compare/${BEFORE_ID}/${AFTER_ID}$`))
  const hp = page.getByRole('region', { name: 'Max HP', exact: true })
  await expect(hp).toContainText('Observed difference (B minus A): +80')
  await expect(page.getByRole('region', { name: 'PP capacity', exact: true })).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Second hand', exact: true })).toContainText('Empty')
  await expect(page.getByRole('region', { name: 'Second hand', exact: true })).toContainText('Unknown')
  await expect(page.getByRole('region', { name: 'Luck', exact: true })).toHaveCount(0)
  await page.getByLabel('Show unchanged fields', { exact: true }).check()
  await expect(page.getByRole('region', { name: 'Luck', exact: true })).toContainText('Unchanged')
  const values = hp.locator('.snapshot-difference__values > div')
  expect(Math.abs((await values.nth(0).boundingBox())!.y - (await values.nth(1).boundingBox())!.y)).toBeLessThan(2)
  await page.reload()
  await expect(hp).toContainText('+80')
  await page.getByRole('combobox', { name: 'Snapshot A', exact: true }).selectOption(AFTER_ID)
  await expect(page.getByText('Same snapshot selected', { exact: true })).toBeVisible()
  const exported = await exportLocalData(page)
  expect(selectedPlaythrough(exported).characters).toEqual(selectedPlaythrough(original).characters)
  expect(exported.buildRevisions).toEqual(original.buildRevisions)
  expect(selectedPlaythrough(exported).inventory).toEqual({})
})

test('member details stay pinned during pointer transit and follow deliberate focus', async ({ page, isMobile }) => {
  test.skip(isMobile, 'The shared member inspector is a desktop layout')
  await page.goto('/')
  await page.getByRole('button', { name: 'Characters', exact: true }).filter({ visible: true }).click()
  await page.getByRole('article', { name: 'Rowan', exact: true }).getByRole('link', { name: 'Rowan', exact: true }).click()
  const details = page.getByRole('complementary', { name: 'Selection details', exact: true })
  await expect(details.getByRole('heading', { name: 'Warrior', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Choose Main hand', exact: true }).hover()
  await expect(details.getByRole('heading', { name: 'Warrior', exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Choose Off hand', exact: true }).click()
  await expect(details.getByRole('heading', { name: 'Buckler', exact: true })).toBeVisible()
  const picker = page.getByRole('dialog', { name: 'Choose Off hand', exact: true })
  await picker.getByRole('searchbox').fill('Ace of Diamonds')
  const candidate = picker.locator('[data-definition-result="true"]').filter({ has: page.getByText('Ace of Diamonds', { exact: true }) })
  await candidate.hover()
  await expect(details.getByRole('heading', { name: 'Buckler', exact: true })).toBeVisible()
  await candidate.focus()
  await expect(details.getByRole('heading', { name: 'Ace of Diamonds', exact: true })).toBeVisible()
})

test('direct slot editing protects a draft and saves a new observation offline', { tag: MOBILE_TEST_TAG }, async ({ page, context }) => {
  const original = await loadFixture(page)
  const storage = await dataPanel(page)
  await storage.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  await storage.getByRole('button', { name: 'Prepare for offline use', exact: true }).click()
  await expectOfflineReady(storage)
  await storage.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.reload()
  expect(await page.evaluate(() => navigator.onLine)).toBe(false)
  expect(await page.evaluate(() => fetch('/synthetic-uncached-offline-probe').then(() => false, () => true))).toBe(true)
  await page.getByRole('button', { name: 'Choose Hand', exact: true }).click()
  const picker = page.getByRole('dialog', { name: 'Choose Hand', exact: true })
  await expect(page.getByRole('dialog', { name: 'Capture character snapshot', exact: true })).toHaveCount(0)
  await expect(picker.getByRole('searchbox')).toBeFocused()
  await picker.getByRole('button', { name: /^Empty/ }).click()
  await expect(page.getByRole('button', { name: 'Choose Hand', exact: true })).toBeFocused()
  await expect(page.getByRole('button', { name: 'Choose Hand', exact: true })).toContainText('Empty')
  await page.getByRole('button', { name: 'Next member', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Synthetic Rowan', exact: true })).toBeVisible()
  const warning = page.locator('.external-update').filter({ hasText: 'Unsaved edits are still open' })
  await expect(warning.getByRole('button', { name: 'Discard and continue', exact: true })).toBeVisible()
  await expect(warning.getByRole('button', { name: 'Save and continue', exact: true })).toBeVisible()
  await page.getByLabel('Snapshot note', { exact: true }).fill('Synthetic changed hand')
  await warning.getByRole('button', { name: 'Save and continue', exact: true }).click()
  await expect(page.getByLabel('Snapshot note', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Synthetic Mira', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Previous member', exact: true }).click()
  await page.reload()
  await page.locator('.member-record > summary').filter({ hasText: 'Observation details' }).click()
  await expect(page.getByText('Synthetic changed hand', { exact: true })).toBeVisible()
  const saved = await exportLocalData(page)
  const character = selectedPlaythrough(saved).characters[CHARACTER_ID]!
  expect(character.snapshots[BEFORE_ID]).toEqual(selectedPlaythrough(original).characters[CHARACTER_ID]!.snapshots[BEFORE_ID])
  expect(character.snapshots[AFTER_ID]).toEqual(selectedPlaythrough(original).characters[CHARACTER_ID]!.snapshots[AFTER_ID])
  expect(character.snapshots[character.currentSnapshotId!]!.equipment[HAND_SLOT]).toBeNull()
  expect(character.snapshots[character.currentSnapshotId!]!.calculation).toBeUndefined()
  expect(character.snapshots[character.currentSnapshotId!]!.gameSetupRevisionId).toBe(TEST_GAME_SETUP_REVISION_ID)
  expect(character.learnedNodes).toEqual({})
  expect(selectedPlaythrough(saved).inventory).toEqual({})
  await page.getByRole('button', { name: 'History', exact: true }).click()
  await page.getByRole('button', { name: 'Compare snapshots', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Hand', exact: true })).toContainText('Empty')
  await page.reload()
  await expect(page.getByRole('region', { name: 'Hand', exact: true })).toContainText('Empty')
  await context.setOffline(false)
})

test('legacy and missing snapshots keep explicit context and never fall back to current', async ({ page }) => {
  await loadFixture(page, true)
  await expect(page.getByText('Slot context has changed', { exact: true })).toBeVisible()
  await page.goto(`/#/characters/${CHARACTER_ID}/history/snapshots/${BEFORE_ID}`)
  await expect(page.getByText('Slot hand', { exact: true })).toBeVisible()
  await expect(page.getByText('Slot context was not recorded', { exact: true })).toBeVisible()
  await expect(page.getByText('Revised Hand', { exact: true })).toHaveCount(0)
  await page.goto(`/#/characters/${CHARACTER_ID}/history/compare/${BEFORE_ID}/${BEFORE_ID}`)
  await expect(page.getByText('Slot context is unrecorded', { exact: true })).toBeVisible()
  await page.goto(`/#/characters/${CHARACTER_ID}/history/snapshots/missing`)
  await expect(page.getByText('Snapshot unavailable', { exact: true })).toBeVisible()
  await expect(page.locator('.recorded-sheet')).toHaveCount(0)
  await page.goto(`/#/characters/synthetic-mira/history/snapshots/${AFTER_ID}`)
  await expect(page.getByText('Snapshot unavailable', { exact: true })).toBeVisible()
  await page.goto(`/#/characters/${CHARACTER_ID}/history/compare/missing/${AFTER_ID}`)
  await expect(page.getByText('Snapshot unavailable', { exact: true }).filter({ visible: true })).toBeVisible()
  await expect(page.locator('.snapshot-difference')).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Snapshot A', exact: true }).selectOption(BEFORE_ID)
  await expect(page.getByText('Different slot contexts', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Capture snapshot', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Capture character snapshot', exact: true })
  await expect(form.getByText('Record equipment again', { exact: true })).toBeVisible()
  await expect(form.getByRole('button', { name: 'Choose Revised Hand', exact: true })).toContainText('Unknown')
  await form.getByRole('button', { name: 'Save snapshot', exact: true }).click()
  const saved = await exportLocalData(page)
  const character = selectedPlaythrough(saved).characters[CHARACTER_ID]!
  expect(character.snapshots[character.currentSnapshotId!]!.gameSetupRevisionId).toBe('revised-gameSetup')
  expect(character.snapshots[character.currentSnapshotId!]!.equipment).toEqual({})
  expect(character.snapshots[character.currentSnapshotId!]!.passives).toEqual(known([]))
  expect(character.snapshots[AFTER_ID]!.equipment[HAND_SLOT]).toEqual(personalRef('Synthetic blade'))
})

test('snapshot save failure retains entered fields and retries a single observation', async ({ page }) => {
  await loadFixture(page)
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.put
    let failOnce = true
    IDBObjectStore.prototype.put = function (...args: Parameters<typeof original>) {
      if (this.name === 'localDatas' && failOnce) { failOnce = false; throw new DOMException('Synthetic storage limit', 'QuotaExceededError') }
      return original.apply(this, args)
    }
  })
  await page.getByRole('button', { name: 'Capture snapshot', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Capture character snapshot', exact: true })
  await form.getByLabel('Snapshot note', { exact: true }).fill('Synthetic retained observation')
  await form.getByLabel('Level', { exact: true }).fill('30')
  await form.getByRole('button', { name: 'Save snapshot', exact: true }).click()
  await expect(form.getByText('Snapshot not saved', { exact: true })).toBeVisible()
  await expect(form.getByLabel('Snapshot note', { exact: true })).toHaveValue('Synthetic retained observation')
  await expect(form.getByLabel('Level', { exact: true })).toHaveValue('30')
  await form.getByRole('button', { name: 'Close form', exact: true }).click()
  await page.getByRole('button', { name: 'Retry save', exact: true }).click()
  await expect(page.getByText('Saved locally', { exact: true })).toBeVisible()
  await page.reload()
  const localData = await exportLocalData(page)
  const snapshots = Object.values(selectedPlaythrough(localData).characters[CHARACTER_ID]!.snapshots)
  expect(snapshots.filter((snapshot) => snapshot.note === 'Synthetic retained observation')).toHaveLength(1)
  expect(snapshots).toHaveLength(3)
})

test('recording a proposal retains its Game Setup and requires in-game confirmation', async ({ page }) => {
  const original = await loadFixture(page, true)
  await page.goto('/#/builds/library')
  await page.getByRole('button', { name: 'Synthetic Rowan proposal', exact: true }).click()
  await page.locator('.build-readiness > summary').click()
  await page.getByRole('button', { name: 'Compare / record on a character', exact: true }).click()
  const recording = page.locator('dialog').filter({ has: page.getByRole('heading', { name: 'Compare and record Build', exact: true }) })
  await recording.getByRole('combobox', { name: /^Character/ }).selectOption(CHARACTER_ID)
  await expect(recording.getByRole('button', { name: 'Record as current', exact: true })).toBeDisabled()
  await recording.getByRole('checkbox', { name: /I made these changes in game/ }).check()
  await recording.getByRole('button', { name: 'Record as current', exact: true }).click()
  await expect(recording).not.toBeVisible()
  const saved = await exportLocalData(page)
  const character = selectedPlaythrough(saved).characters[CHARACTER_ID]!
  const snapshot = character.snapshots[character.currentSnapshotId!]!
  expect(saved.planningGameSetupRevisionId).toBe('revised-gameSetup')
  expect(snapshot.gameSetupRevisionId).toBe(TEST_GAME_SETUP_REVISION_ID)
  expect(snapshot.displayedStats).toEqual({})
  expect(snapshot).not.toHaveProperty('ppCapacity')
  expect(character.snapshots[AFTER_ID]).toEqual(selectedPlaythrough(original).characters[CHARACTER_ID]!.snapshots[AFTER_ID])
  expect(character.learnedNodes).toEqual({})
  expect(selectedPlaythrough(saved).inventory).toEqual({})
})

test('member picker links preserve unknown and empty selections and guard the inline draft', async ({ page }) => {
  const original = await loadFixture(page)
  await page.goto(`/#/characters/${CHARACTER_ID}/current/pick/slot/${PASSIVE_SLOT}`)
  const passivePicker = page.getByRole('dialog', { name: 'Choose Equipped passive 1', exact: true })
  await expect(passivePicker.getByRole('searchbox')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Choose Equipped passive 1', exact: true })).toBeFocused()
  await page.goto(`/#/characters/${CHARACTER_ID}/current/pick/slot/${HAND_SLOT}`)
  const picker = page.getByRole('dialog', { name: 'Choose Hand', exact: true })
  await expect(picker.getByRole('searchbox')).toBeFocused()
  await page.reload()
  await expect(picker.getByRole('searchbox')).toBeFocused()
  await picker.getByRole('button', { name: /^Unknown/ }).click()
  await expect(page.getByRole('button', { name: 'Choose Hand', exact: true })).toContainText('Unknown')
  await page.getByRole('button', { name: 'Choose Second hand', exact: true }).click()
  await page.getByRole('dialog', { name: 'Choose Second hand', exact: true }).getByRole('button', { name: /^Empty/ }).click()
  await page.getByRole('button', { name: 'History', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/characters/${CHARACTER_ID}/current$`))
  await expect(page.getByRole('button', { name: 'Capture snapshot', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByLabel('Snapshot note', { exact: true })).toHaveCount(0)
  const saved = await exportLocalData(page)
  const member = selectedPlaythrough(saved).characters[CHARACTER_ID]!
  const recorded = member.snapshots[member.currentSnapshotId!]!
  expect(recorded.equipment).not.toHaveProperty(HAND_SLOT)
  expect(recorded.equipment['second-hand']).toBeNull()
  expect(recorded.displayedStats).toEqual(selectedPlaythrough(original).characters[CHARACTER_ID]!.snapshots[AFTER_ID]!.displayedStats)
  expect(selectedPlaythrough(saved).inventory).toEqual(selectedPlaythrough(original).inventory)
  expect(saved.buildRevisions).toEqual(original.buildRevisions)
  await page.getByRole('button', { name: 'Next member', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Synthetic Mira', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Previous member', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Choose Hand', exact: true })).toContainText('Unknown')
})

for (const retryAction of ['Retry member save', 'Retry save']) {
  test(`inline save failure retains the member draft and ${retryAction} persists the same snapshot`, async ({ page }) => {
    const original = await loadFixture(page)
    await page.getByRole('button', { name: 'Choose Hand', exact: true }).click()
    await page.getByRole('dialog', { name: 'Choose Hand', exact: true }).getByRole('button', { name: /^Empty/ }).click()
    await page.getByLabel('Snapshot note', { exact: true }).fill('Synthetic inline recovery')
    await page.evaluate(() => {
      const put = IDBObjectStore.prototype.put
      let failOnce = true
      IDBObjectStore.prototype.put = function (...args: Parameters<typeof put>) {
        if (this.name === 'localDatas' && failOnce) { failOnce = false; throw new DOMException('Synthetic storage limit', 'QuotaExceededError') }
        return put.apply(this, args)
      }
    })
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await expect(page.getByText('Snapshot not saved', { exact: true })).toBeVisible()
    await expect(page.getByLabel('Snapshot note', { exact: true })).toHaveValue('Synthetic inline recovery')
    await expect(page.getByLabel('Snapshot note', { exact: true })).toBeDisabled()
    await page.getByRole('button', { name: retryAction, exact: true }).click()
    await expect(page.getByText('Saved locally', { exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Retry member save', exact: true })).toHaveCount(0)
    await expect(page.getByText('Snapshot not saved', { exact: true })).toHaveCount(0)
    await page.reload()
    await expect(page.getByRole('button', { name: 'Choose Hand', exact: true })).toContainText('Empty')
    const saved = await exportLocalData(page)
    const member = selectedPlaythrough(saved).characters[CHARACTER_ID]!
    expect(Object.values(member.snapshots)).toHaveLength(Object.keys(selectedPlaythrough(original).characters[CHARACTER_ID]!.snapshots).length + 1)
    expect(Object.values(member.snapshots).filter(snapshot => snapshot.note === 'Synthetic inline recovery')).toHaveLength(1)
    expect(member.snapshots[BEFORE_ID]).toEqual(selectedPlaythrough(original).characters[CHARACTER_ID]!.snapshots[BEFORE_ID])
    expect(member.snapshots[AFTER_ID]).toEqual(selectedPlaythrough(original).characters[CHARACTER_ID]!.snapshots[AFTER_ID])
  })
}

test('the grouped member sheet aligns loadout sections and learning shares a single view', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await page.goto('/#/characters')
  await page.getByRole('article', { name: 'Rowan', exact: true }).getByRole('link', { name: 'Rowan', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Rowan', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Class growth ratings', exact: true }).locator('.stat-rating').first()).toBeVisible()
  await expect(page.getByRole('region', { name: 'Stats at selected level', exact: true })).toBeVisible()
  await expect(page.getByRole('tab')).toHaveCount(0)
  const mainHand = page.getByRole('button', { name: 'Choose Main hand', exact: true })
  const classes = await page.getByRole('region', { name: 'Class and command', exact: true }).boundingBox()
  const equipment = await page.getByRole('region', { name: 'Equipment', exact: true }).boundingBox()
  expect(classes).not.toBeNull()
  expect(equipment).not.toBeNull()
  expect(equipment!.y).toBeGreaterThan(classes!.y)
  await page.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Build mechanics', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Loadout', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Choose Equipped passive 1', exact: true })).toHaveCount(0)
  await mainHand.click()
  const picker = page.getByRole('dialog', { name: 'Choose Main hand', exact: true })
  await picker.getByRole('searchbox').fill('Ancient Labyrinth Map')
  await expect(picker.locator('[data-definition-result="true"]').filter({ hasText: 'Ancient Labyrinth Map' })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(mainHand).toBeFocused()
  await page.locator('button.member-row').filter({ has: page.locator('.member-row__label', { hasText: /^Passives$/ }) }).click()
  const passiveChoice = page.getByRole('button', { name: 'Choose Equipped passive 1', exact: true })
  const passiveLabelBounds = await passiveChoice.locator('.member-row__label').boundingBox()
  const passiveValueBounds = await passiveChoice.locator('.member-row__value').boundingBox()
  expect(passiveLabelBounds).not.toBeNull()
  expect(passiveValueBounds).not.toBeNull()
  expect(passiveLabelBounds!.x + passiveLabelBounds!.width).toBeLessThanOrEqual(passiveValueBounds!.x + 1)
  expect(await passiveChoice.locator('.member-row__label').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await expect(page.getByRole('button', { name: 'Skills', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await expect(page.getByRole('region', { name: 'Class progress', exact: true })).toContainText('Warrior')
  await expect(page.getByRole('region', { name: 'Learned skills', exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: 'Skill type', exact: true }).selectOption('monsterMagic')
  await expect(page.getByRole('button', { name: 'Add spell', exact: true })).toBeVisible()
  await expect(page).toHaveURL(/\/current$/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('member edits block context switches until saved or discarded', async ({ page }) => {
  await page.goto('/#/characters')
  await page.getByRole('article', { name: 'Rowan', exact: true }).getByRole('link', { name: 'Rowan', exact: true }).click()
  const hand = page.getByRole('button', { name: 'Choose Main hand', exact: true })
  await hand.click()
  await page.getByRole('dialog', { name: 'Choose Main hand', exact: true }).getByRole('button', { name: /^Empty/ }).click()
  const scenario = page.getByRole('button', { name: /^Party plan:/ })
  await scenario.click()
  const picker = page.getByRole('dialog', { name: 'Choose party plan', exact: true })
  await picker.getByRole('button', { name: /^None selected/ }).click()
  await expect(picker.getByText('Party plan switch failed', { exact: true })).toBeVisible()
  await expect(picker).toContainText('Save or discard open form edits')
  await page.keyboard.press('Escape')
  await expect(hand).toContainText('Empty')
  await page.getByRole('button', { name: 'Discard changes', exact: true }).click()
  await expect(hand).toContainText('Short Sword')
  await scenario.click()
  await picker.getByRole('button', { name: /^None selected/ }).click()
  await expect(picker).not.toBeVisible()
  await expect(scenario).toHaveAccessibleName('Party plan: None selected')
})
