import { formatAppRoute, parseAppRoute } from '../src/ui/navigation'
import { openSavedCatalogVersion } from './definition-fixtures'
import { MOBILE_TEST_TAG } from './test-tags'
import { expect, test } from '@playwright/test'
import { referencePath, referenceUrlPattern } from './reference-helpers'
import { waitForPlannerReady } from './local-data-helpers'

const DESERT_QUINTAR = referencePath('base:monster:316')
const BOSS = referencePath('base:monster:201')
const CHAOS_BOSS = referencePath('base:monster:201:mode:Chaos')

test('enemy difficulty scales source inputs, survives reloads, and retains raw technical integers', async ({ page }) => {
  await page.goto(DESERT_QUINTAR)
  const difficulty = page.getByRole('combobox', { name: 'Difficulty', exact: true })
  const hp = page.locator('.enemy-metric--hp dd')
  const attack = page.getByRole('region', { name: 'Combat inputs', exact: true }).locator('.enemy-stat-grid > div').filter({ has: page.locator('dt', { hasText: /^Attack$/ }) }).locator('dd')
  const mind = page.getByRole('region', { name: 'Attributes', exact: true }).locator('.enemy-stat-grid > div').filter({ has: page.locator('dt', { hasText: /^Mind$/ }) }).locator('dd')
  await expect(difficulty).toHaveValue('0')
  await expect(hp).toHaveText('4900')
  await difficulty.selectOption({ label: 'Easy' })
  await expect(hp).toHaveText('3920')
  await expect(attack).toHaveText('224')
  await expect(mind).toHaveText('144')
  await difficulty.selectOption({ label: 'Hard' })
  await expect(hp).toHaveText('6370')
  await expect(attack).toHaveText('336')
  await expect(mind).toHaveText('216')
  await expect(page).toHaveURL(/difficulty=2/)
  await page.reload()
  await expect(difficulty).toHaveValue('2')
  await expect(hp).toHaveText('6370')
  await expect(page.locator('.enemy-rewards').getByRole('img', { name: '1 gold', exact: true })).toBeVisible()
  await page.getByText('Technical details', { exact: false }).click()
  const facts = page.getByRole('region', { name: 'Definition facts', exact: true })
  await expect(facts.locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^HP$/ }) }).locator('dd')).toHaveText('4900')
  await expect(facts.locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^Money \(copper\)$/ }) }).locator('dd')).toHaveText('10000')
  await expect(facts.locator('.money-amount')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('boss entries use their exact mode difficulty rates', async ({ page }) => {
  await page.goto(BOSS)
  const mode = page.getByRole('combobox', { name: 'Game mode', exact: true })
  const difficulty = page.getByRole('combobox', { name: 'Difficulty', exact: true })
  await difficulty.selectOption({ label: 'Hard' })
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('35100')
  await mode.selectOption({ label: 'Chaos' })
  await expect(difficulty).toHaveValue('2')
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('56000')
  await expect(page.locator('.enemy-metric--mp dd')).toHaveText('740')
  await page.goto(CHAOS_BOSS)
  await expect(mode).toHaveValue('chaos')
  await expect(difficulty).toHaveValue('0')
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('42000')
  await difficulty.selectOption({ label: 'Hard' })
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('56000')
  await expect(page.locator('.enemy-metric--mp dd')).toHaveText('740')
})

test('game mode switches enemy records, rewards, and actions while preserving difficulty and reloads', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await page.goto(`${DESERT_QUINTAR}?difficulty=2`)
  const mode = page.getByRole('combobox', { name: 'Game mode', exact: true })
  const difficulty = page.getByRole('combobox', { name: 'Difficulty', exact: true })
  const hp = page.locator('.enemy-metric--hp dd')
  await expect(mode).toHaveValue('standard')
  await mode.selectOption({ label: 'Chaos' })
  await expect(page).toHaveURL(referenceUrlPattern('base:monster:316:mode:Chaos'))
  await expect(page).toHaveURL(/[?&]mode=chaos(?:&|$)/)
  await expect(difficulty).toHaveValue('2')
  await expect(hp).toHaveText('8250')
  await expect(page.locator('.enemy-rewards')).toContainText('1960')
  await expect(page.getByRole('region', { name: 'Actions', exact: true }).locator('.enemy-action')).toHaveCount(5)
  await page.reload()
  await expect(mode).toHaveValue('chaos')
  await expect(difficulty).toHaveValue('2')
  await expect(hp).toHaveText('8250')
  await page.getByText('Technical details', { exact: false }).click()
  const facts = page.getByRole('region', { name: 'Definition facts', exact: true })
  await expect(facts.locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^HP$/ }) }).locator('dd')).toHaveText('5500')
  await expect(facts.locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^Money \(copper\)$/ }) }).locator('dd')).toHaveText('15000')
  await mode.selectOption({ label: 'Vanilla' })
  await expect(page).toHaveURL(referenceUrlPattern('base:monster:316:mode:Vanilla'))
  await expect(difficulty).toHaveValue('2')
  await expect(hp).toHaveText('6370')
  await expect(page.getByRole('region', { name: 'Actions', exact: true }).locator('.enemy-action')).toHaveCount(4)
  await mode.selectOption({ label: 'Standard' })
  await expect(page).toHaveURL(referenceUrlPattern('base:monster:316'))
  await expect(hp).toHaveText('6370')
  await page.setViewportSize({ width: 320, height: 780 })
  await expect(mode).toBeVisible()
  await expect(difficulty).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('a mode query resolves its matching record and unchanged enemies retain the base record', async ({ page }) => {
  await page.goto(`${BOSS}?mode=chaos&difficulty=2`)
  const mode = page.getByRole('combobox', { name: 'Game mode', exact: true })
  await expect(mode).toHaveValue('chaos')
  await expect(page).toHaveURL(referenceUrlPattern('base:monster:201:mode:Chaos'))
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('56000')
  await page.goto(`${referencePath('base:monster:0')}?difficulty=2`)
  await mode.selectOption({ label: 'Chaos' })
  await expect(mode).toHaveValue('chaos')
  await expect(page).toHaveURL(referenceUrlPattern('base:monster:0'))
  await expect(page).toHaveURL(/[?&]mode=chaos(?:&|$)/)
  await expect(page.getByRole('combobox', { name: 'Difficulty', exact: true })).toHaveValue('2')
  await page.reload()
  await expect(mode).toHaveValue('chaos')
})

test('saved personal versions scale their recorded inputs without changing the source catalog', async ({ page }) => {
  await page.goto(`${DESERT_QUINTAR}?difficulty=2`)
  const baselineHp = await page.locator('.enemy-metric--hp dd').textContent()
  const facts = page.getByRole('region', { name: 'Definition facts', exact: true })
  const mode = page.getByRole('combobox', { name: 'Game mode', exact: true })
  await openSavedCatalogVersion(page, 'base:monster:316', 'Synthetic difficulty quintar', { fields: { HP: { state: 'known', value: 17 } } })
  await expect(page.getByRole('heading', { name: 'Synthetic difficulty quintar', exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: 'Difficulty', exact: true }).selectOption({ label: 'Hard' })
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('20')
  const savedPersonalUrl = page.url()
  await page.getByText('Technical details', { exact: false }).click()
  await expect(facts.locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^HP$/ }) }).locator('dd')).toHaveText('17')
  await expect(facts.locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^Money \(copper\)$/ }) }).locator('dd')).toHaveText('10000')
  await mode.selectOption({ label: 'Chaos' })
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('8250')
  await expect(page).toHaveURL(referenceUrlPattern('base:monster:316:mode:Chaos'))
  await mode.selectOption({ label: 'Standard' })
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText(baselineHp!)
  await page.goto(savedPersonalUrl)
  await expect(page.getByRole('heading', { name: 'Synthetic difficulty quintar', exact: true })).toBeVisible()
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('20')
  const personalUrl = page.url()
  const personalRoute = parseAppRoute(new URL(personalUrl).hash)
  await page.goto(`/${formatAppRoute({ ...personalRoute, query: { ...personalRoute.query, mode: ['chaos'] } })}`)
  await expect(mode).toHaveValue('')
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('17')
  await mode.selectOption({ label: 'Standard' })
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('20')
})

test('an unknown difficulty stays unselected until a known definition is chosen', async ({ page }) => {
  await page.goto(`${DESERT_QUINTAR}?difficulty=999`)
  await waitForPlannerReady(page)
  const difficulty = page.getByRole('combobox', { name: 'Difficulty', exact: true })
  await expect(difficulty).toHaveValue('')
  await expect(page.getByRole('region', { name: 'Combat inputs', exact: true })).toContainText('Raw database values')
  await difficulty.selectOption({ label: 'Easy' })
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('3920')
})

test('an unknown mode stays unselected until a known mode is chosen', async ({ page }) => {
  await page.goto(`${DESERT_QUINTAR}?mode=unknown&difficulty=2`)
  const mode = page.getByRole('combobox', { name: 'Game mode', exact: true })
  await expect(mode).toHaveValue('')
  await expect(page.getByRole('region', { name: 'Combat inputs', exact: true })).toContainText('Raw database values')
  await mode.selectOption({ label: 'Chaos' })
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('8250')
})
