import { expect, test } from '@playwright/test'
import { referencePath, referenceUrlPattern } from './reference-helpers'
import { MOBILE_TEST_TAG } from './test-tags'
import { expectOfflineReady } from './offline-helpers'

test('an item leads to its shop and required item, with usable mobile layout', { tag: MOBILE_TEST_TAG }, async ({ page, context }) => {
  await page.goto(referencePath('base:item:quintar-berries'))
  const section = page.getByRole('region', { name: 'How to obtain', exact: true })
  await expect(section.getByRole('heading', { name: 'Buy', exact: true })).toBeVisible()
  await expect(section).toContainText('Dione Shrine')
  await expect(section.getByRole('img', { name: '60 silver', exact: true })).toBeVisible()
  await expect(section).toContainText('Understand Quintars')
  await section.getByRole('combobox', { name: 'Game mode', exact: true }).selectOption({ label: 'Vanilla' })
  await page.reload()
  await expect(section.getByRole('combobox', { name: 'Game mode', exact: true })).toHaveValue('vanilla')
  const prerequisite = section.getByRole('link', { name: 'Babel Quintar', exact: true })
  await expect(prerequisite).toBeVisible()
  const tab = await context.newPage()
  await tab.goto(await prerequisite.evaluate((link: HTMLAnchorElement) => link.href))
  await expect(tab.getByRole('region', { name: 'How to obtain', exact: true }).getByRole('combobox', { name: 'Game mode', exact: true })).toHaveValue('vanilla')
  await tab.close()
  await prerequisite.click()
  await expect(page).toHaveURL(referenceUrlPattern('base:item:167'))
  await expect(page.getByRole('region', { name: 'How to obtain', exact: true }).getByRole('combobox', { name: 'Game mode', exact: true })).toHaveValue('vanilla')
  await expect(page.getByRole('region', { name: 'How to obtain', exact: true }).getByRole('heading', { name: 'Find in a chest', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('an item leads to its monster source and preserves separate steal rates', async ({ page }) => {
  await page.goto(referencePath('base:item:tonic'))
  const section = page.getByRole('region', { name: 'How to obtain', exact: true })
  const slime = section.locator('.acquisition-route').filter({ has: page.getByRole('link', { name: 'Slime (level 3)', exact: true }) })
  await expect(slime.filter({ hasText: 'Base drop chance' })).toContainText('50%')
  await expect(slime.filter({ hasText: 'Steal success per attempt' })).toContainText('Availability: 75%')
  await expect(slime.filter({ hasText: 'Steal success per attempt' })).toContainText('60%')
  await slime.filter({ hasText: 'Base drop chance' }).getByRole('link', { name: 'Slime (level 3)', exact: true }).click()
  await expect(page).toHaveURL(referenceUrlPattern('base:monster:2'))
  await expect(page.getByRole('region', { name: 'Drops', exact: true }).getByRole('link', { name: 'Tonic', exact: true })).toBeVisible()
})

test('crafting ingredients link to their own acquisition routes and missing routes stay explicit', async ({ page }) => {
  await page.goto(referencePath('base:item:nans-secret-recipe'))
  const section = page.getByRole('region', { name: 'How to obtain', exact: true })
  await expect(section.getByRole('heading', { name: 'Craft', exact: true })).toBeVisible()
  await section.getByRole('link', { name: 'Secret Veggie', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Secret Veggie', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'How to obtain', exact: true })).toContainText('Gourmet')
  await page.goto(referencePath('base:item:46'))
  await expect(page.getByRole('region', { name: 'How to obtain', exact: true })).toContainText('No acquisition route found')
  await page.goto(referencePath('base:item:ibek-bell'))
  await expect(page.getByRole('region', { name: 'How to obtain', exact: true })).toContainText('Additional acquisition guidance is recorded in Definition facts below')
  await expect(page.getByText('Reward for clearing the Ancient Reservoir in Poko Poko Desert.', { exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Community wiki · Mounts', exact: true })).toHaveAttribute('href', /Mounts\?oldid=5937/)
})

test('item sources and prerequisite navigation work offline', async ({ page, context }) => {
  await page.goto(referencePath('base:item:quintar-berries'))
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  await settings.getByRole('button', { name: 'Prepare for offline use', exact: true }).click()
  await expectOfflineReady(settings)
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.reload()
  const section = page.getByRole('region', { name: 'How to obtain', exact: true })
  await expect(section).toContainText('Dione Shrine')
  await section.getByRole('link', { name: 'Babel Quintar', exact: true }).click()
  await expect(page.getByRole('region', { name: 'How to obtain', exact: true }).getByRole('heading', { name: 'Find in a chest', exact: true })).toBeVisible()
})
