import { expect, test } from '@playwright/test'
import { referencePath, referenceUrlPattern } from './reference-helpers'
import { MOBILE_TEST_TAG } from './test-tags'
import { expectOfflineReady } from './offline-helpers'

test('an item leads to its shop and required item, with usable mobile layout', { tag: MOBILE_TEST_TAG }, async ({ page, context }) => {
  await page.goto(referencePath('base:item:203'))
  const section = page.getByRole('region', { name: 'How to obtain', exact: true })
  await expect(section.getByRole('heading', { name: 'Buy', exact: true })).toBeVisible()
  await expect(section).toContainText('Dione Shrine')
  await expect(section.getByRole('img', { name: '60 silver', exact: true })).toBeVisible()
  await expect(section).toContainText('Understand Quintars')
  await section.getByRole('combobox', { name: 'Game mode', exact: true }).selectOption({ label: 'Vanilla' })
  await page.reload()
  await expect(section.getByRole('combobox', { name: 'Game mode', exact: true })).toHaveValue('vanilla')
  const prerequisite = section.getByRole('link', { name: 'Babel Quintar', exact: true })
  await expect(prerequisite).toBeVisible()
  const tab = await context.newPage()
  await tab.goto(await prerequisite.evaluate((link: HTMLAnchorElement) => link.href))
  await expect(tab.getByRole('region', { name: 'How to obtain', exact: true }).getByRole('combobox', { name: 'Game mode', exact: true })).toHaveValue('vanilla')
  await tab.close()
  await prerequisite.click()
  await expect(page).toHaveURL(referenceUrlPattern('base:item:167'))
  await expect(page.getByRole('region', { name: 'How to obtain', exact: true }).getByRole('combobox', { name: 'Game mode', exact: true })).toHaveValue('vanilla')
  await expect(page.getByRole('region', { name: 'How to obtain', exact: true }).getByRole('heading', { name: 'Find in a chest', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('an item leads to its monster source and preserves separate steal rates', async ({ page }) => {
  await page.goto(referencePath('base:item:18'))
  const section = page.getByRole('region', { name: 'How to obtain', exact: true })
  const slime = section.locator('.acquisition-route').filter({ has: page.getByRole('link', { name: 'Slime (level 3)', exact: true }) })
  await expect(slime.filter({ hasText: 'Base drop chance' })).toContainText('50%')
  await expect(slime.filter({ hasText: 'Steal success per attempt' })).toContainText('Availability: 75%')
  await expect(slime.filter({ hasText: 'Steal success per attempt' })).toContainText('60%')
  await slime.filter({ hasText: 'Base drop chance' }).getByRole('link', { name: 'Slime (level 3)', exact: true }).click()
  await expect(page).toHaveURL(referenceUrlPattern('base:monster:2'))
  await expect(page.getByRole('region', { name: 'Drops', exact: true }).getByRole('link', { name: 'Tonic', exact: true })).toBeVisible()
})

test('crafting ingredients link to their own acquisition routes and missing routes stay explicit', async ({ page }) => {
  await page.goto(referencePath('base:item:54'))
  const section = page.getByRole('region', { name: 'How to obtain', exact: true })
  await expect(section.getByRole('heading', { name: 'Craft', exact: true })).toBeVisible()
  await section.getByRole('link', { name: 'Secret Veggie', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Secret Veggie', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'How to obtain', exact: true })).toContainText('Gourmet')
  await page.goto(referencePath('base:item:46'))
  await expect(page.getByRole('region', { name: 'How to obtain', exact: true })).toContainText("No source here says how to obtain this item.")
  await page.goto(referencePath('base:item:50'))
  await expect(page.getByRole('region', { name: 'How to obtain', exact: true })).not.toContainText('Additional acquisition guidance is recorded')
  await expect(page.getByText('Reward for clearing the Ancient Reservoir in Poko Poko Desert.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Sources for Ibek Bell', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Sources for Ibek Bell', exact: true }).getByRole('link', { name: 'Community wiki · Mounts', exact: true })).toHaveAttribute('href', /Mounts\?oldid=5937/)
})

test('item sources and prerequisite navigation work offline', async ({ page, context }) => {
  await page.goto(referencePath('base:item:203'))
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  await settings.getByRole('button', { name: 'Prepare for offline use', exact: true }).click()
  await expectOfflineReady(settings)
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.reload()
  const section = page.getByRole('region', { name: 'How to obtain', exact: true })
  await expect(section).toContainText('Dione Shrine')
  await section.getByRole('link', { name: 'Babel Quintar', exact: true }).click()
  await expect(page.getByRole('region', { name: 'How to obtain', exact: true }).getByRole('heading', { name: 'Find in a chest', exact: true })).toBeVisible()
})

test('native rewards explain their requirements and seed facts link to the harvested encounter', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await page.goto(referencePath('base:equipment:183'))
  const section = page.getByRole('region', { name: 'How to obtain', exact: true })
  await expect(section).toContainText('Return at least 6 lost penguins')
  await expect(section).not.toContainText('Additional acquisition guidance is recorded')
  await page.goto(referencePath('base:equipment:244'))
  await expect(section).toContainText('Win at least 9 Sky Arena battles')
  await page.goto(referencePath('base:item:114'))
  await expect(section).toContainText('Finish first in the Salmon Run')
  await page.goto(referencePath('base:item:178'))
  await expect(section.getByRole('heading', { name: 'Growing this seed', exact: true })).toBeVisible()
  await expect(section).toContainText('Sprouts after 5 minutes of play time')
  await expect(section).toContainText('earlier by 2 minutes')
  await section.getByRole('link', { name: 'Weed', exact: true }).click()
  await expect(page).toHaveURL(referenceUrlPattern('base:monster:270'))
  await page.goto(referencePath('base:item:183'))
  await expect(section).toContainText("Watering does not shorten this seed's growth time")
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('the reviewed Rotten Salmon choice shows its price and retains the original acquisition claims', async ({ page }) => {
  await page.goto(referencePath('base:item:11'))
  const section = page.getByRole('region', { name: 'How to obtain', exact: true })
  const original = page.getByText(/^Can be purchased in Delende from the Shady Merchant for /).filter({ visible: true })
  await expect(section.getByRole('img', { name: '13 copper', exact: true })).toBeVisible()
  await expect(section).toContainText('Choose Buy')
  await expect(original).toHaveCount(1)
  await expect(page.getByRole('region', { name: 'Description', exact: true })).toContainText('Can be purchased in Delende from the Shady Merchant for')
  await page.getByRole('button', { name: 'Sources for Rotten Salmon', exact: true }).click()
  const sources = page.getByRole('dialog', { name: 'Sources for Rotten Salmon', exact: true })
  await sources.getByText('Original acquisition notes', { exact: true }).click()
  await expect(original).toHaveCount(1)
  await expect(sources).toContainText('The matching game routes appear under How to obtain.')
  await expect(sources.locator('a[href*="/wiki/Rotten_Salmon?"]').first()).toBeVisible()
  await page.keyboard.press('Escape')
  await section.getByRole('combobox', { name: 'Game mode', exact: true }).selectOption({ label: 'Chaos' })
  await expect(section.getByRole('img', { name: '13 copper', exact: true })).toHaveCount(0)
  await expect(section).not.toContainText('Additional acquisition guidance is recorded')
})

test('Dress keeps native acquisition quiet and cites its external description', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await page.goto(referencePath('base:equipment:134'))
  const section = page.getByRole('region', { name: 'How to obtain', exact: true })
  await expect(section).toContainText('Fungus')
  await expect(section).toContainText('Quintar Sanctum')
  await expect(section).not.toContainText('Definition facts below')
  await expect(page.getByRole('region', { name: 'Description', exact: true }).getByText(/before reaching the Chemist crystal/)).toBeVisible()
  await expect(page.locator('.reference-description')).toContainText('before reaching the Chemist crystal')
  await expect(page.locator('.reference-description')).toContainText("useful to light armor wearers who don't need Mind or Spirit")
  await expect(section.locator('.sources-trigger')).toHaveCount(0)
  const location = section.getByText('Coordinates', { exact: true }).locator('..')
  await expect(location).not.toHaveAttribute('open')
  await location.getByText('Coordinates', { exact: true }).click()
  await expect(location).toContainText('X 564 · Y 172 · Z -477')
  await page.getByRole('button', { name: 'Sources for Description', exact: true }).click()
  const sources = page.getByRole('dialog', { name: 'Sources for Description', exact: true })
  await expect(sources.locator('a[href*="/wiki/Dress?"]').first()).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(sources).toHaveCount(0)
})
