import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { addVoxelPlatform, newMapProject } from '../src/mod-inspector/map-editor'
import { isoProject, type IsoCamera } from '../src/mod-inspector/isometric'
import worldMap from '../src/catalog/world-map.json' with { type: 'json' }
import { expectOfflineReady } from './offline-helpers'
import { MOBILE_TEST_TAG } from './test-tags'
import { skipInitialModSetup } from './local-data-helpers'
import { modWorkspaceRoute } from '../src/ui/mod-workspace'
import { formatAppRoute } from '../src/ui/navigation'

const FILENAME = 'synthetic-map-editor.json'
const ID = 'a1943ce8-2a42-486a-9549-d497685b671e'
const TREASURE = '{"ID":1,"Coord":{"X":-12,"Y":99,"Z":4,"FutureCoordinate":9007199254740993},"BiomeID":1,"EntityType":5,"TreasureData":{"LootType":2,"LootValue":18,"Condition":{"ConditionType":0,"Data":null,"IsNegation":false}},"FutureRecord":0.12345678901234567890123456789}'
const SOURCE = newMapProject(ID, '2026-01-01T00:00:00.000Z').replace('"Entities": []', '"Entities": [' + TREASURE + ']').replace('"SteamWorkshopFileID": 0', '"SteamWorkshopFileID": 9007199254740993')

async function openEditor(page: Page, source = SOURCE) {
  await page.goto('/#/mods/editor')
  await page.getByLabel('Open mod JSON file', { exact: true }).setInputFiles({ name: FILENAME, mimeType: 'application/json', buffer: Buffer.from(source) })
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Map Editor', exact: true }).click()
  await expectMap(page)
}
async function expectMap(page: Page) {
  await expect(page.getByRole('heading', { name: 'Map Placement Editor', exact: true })).toBeVisible()
  await expect(page.getByRole('img', { name: 'Isometric terrain and authored placements', exact: true })).toBeVisible()
  await expect(page.getByText('Opening native surface heights...', { exact: true })).toHaveCount(0)
  await expect.poll(() => page.locator('.iso-scene-bitmap').getAttribute('data-geometry-runs').then(Number)).toBeGreaterThan(0)
  await expect(page.getByText('Loading nearby native voxel geometry...', { exact: true })).toHaveCount(0)
  await expect.poll(() => page.locator('.map-editor .world-map-terrain img').evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBe(true)
}

test('opens Map Editor directly from Mods menus and preserves view history and pending moves', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }, testInfo) => {
  await page.goto('/')
  await skipInitialModSetup(page)
  const menu = page.getByRole('navigation', { name: 'Primary navigation', exact: true }).filter({ visible: true })
  await menu.getByRole('button', { name: 'Mods', exact: true }).click()
  const workspace = page.getByRole('tablist', { name: 'Mods workspace', exact: true })
  const workspaceNames = ['Mod Library', 'Map Editor', 'JSON Editor', 'Enum Dictionary']
  await expect(workspace.getByRole('tab')).toHaveText(workspaceNames)
  if (!isMobile) await expect(menu.getByRole('list', { name: 'Mods pages', exact: true }).getByRole('link')).toHaveText(workspaceNames)
  const menuStyle = () => workspace.evaluate(element => {
    const style = getComputedStyle(element)
    return { background: style.backgroundColor, border: style.border, borderRadius: style.borderRadius, padding: style.padding, display: style.display, fontSize: getComputedStyle(element.querySelector('button')!).fontSize }
  })
  const libraryStyle = await menuStyle()
  const mapTab = page.getByRole('tab', { name: 'Map Editor', exact: true })
  const documentTab = page.getByRole('tab', { name: 'JSON Editor', exact: true })
  let mapTabId = await mapTab.getAttribute('id')
  async function expectWorkspace() {
    await expect(workspace).toHaveCount(1)
    await expect(workspace.getByRole('tab')).toHaveText(workspaceNames)
    await expect(mapTab).toHaveAttribute('id', mapTabId!)
    expect(await menuStyle()).toEqual(libraryStyle)
    expect(await workspace.getByRole('tab').evaluateAll(tabs => tabs.every(tab => tab.getBoundingClientRect().height >= 44))).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  const mapLink = menu.getByRole('link', { name: 'Map Editor', exact: true })
  if (isMobile) await mapTab.tap()
  else {
    await expect(mapLink).toHaveAttribute('href', formatAppRoute(modWorkspaceRoute('map')))
    await mapLink.press('Enter')
  }
  await expectWorkspace()
  await expect(mapTab).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('heading', { name: 'Create or Open a Map Mod', exact: true })).toBeVisible()
  await expect(menu.getByRole('button', { name: 'Mods', exact: true })).toHaveAttribute('aria-current', 'page')
  if (!isMobile) await expect(mapLink).toHaveAttribute('aria-current', 'page')
  await page.getByLabel('Open mod JSON file', { exact: true }).setInputFiles({ name: FILENAME, mimeType: 'application/json', buffer: Buffer.from(SOURCE) })
  await expectMap(page)
  await page.locator('.map-editor-placement-list button').filter({ hasText: 'Treasure #1' }).click()
  await page.getByRole('spinbutton', { name: 'Placement height Y', exact: true }).fill('100')
  if (!isMobile) {
    await menu.getByRole('link', { name: 'JSON Editor', exact: true }).click()
    await expect(page.getByText('Unsaved edits are still open', { exact: true })).toBeVisible()
    await expect(mapTab).toHaveAttribute('aria-selected', 'true')
  }
  await page.getByRole('button', { name: 'Move selected placement', exact: true }).click()
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  const undo = page.getByRole('button', { name: 'Undo map edit', exact: true })
  await expect(undo).toBeEnabled()
  await documentTab.click()
  await expect(documentTab).toHaveAttribute('aria-selected', 'true')
  await expectWorkspace()
  await page.goBack()
  await expect(mapTab).toHaveAttribute('aria-selected', 'true')
  await expect(undo).toBeEnabled()
  await page.goForward()
  await expect(documentTab).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('tab', { name: 'Enum Dictionary', exact: true }).click()
  await expectWorkspace()
  if (!isMobile) await expect(menu.getByRole('link', { name: 'Enum Dictionary', exact: true })).toHaveAttribute('aria-current', 'page')
  await page.getByRole('searchbox', { name: 'Search enum names and values', exact: true }).fill('NpcFree')
  await documentTab.click()
  await page.goBack()
  await expect(page.getByRole('searchbox', { name: 'Search enum names and values', exact: true })).toHaveValue('NpcFree')
  await mapTab.click()
  await page.reload()
  await expect(mapTab).toHaveAttribute('aria-selected', 'true')
  // A reload creates new React IDs; in-page view switches keep the same menu
  mapTabId = await mapTab.getAttribute('id')
  const files = page.getByRole('combobox', { name: 'Files opened in this tool', exact: true })
  const draftId = await files.locator('option').filter({ hasText: FILENAME }).getAttribute('value')
  await files.selectOption(draftId!)
  await expectMap(page)
  await expect(page.locator('.map-editor-placement-list')).toContainText('Y 100')
  if (!isMobile) {
    await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).click()
    await expect(mapLink).not.toBeVisible()
    await page.getByRole('button', { name: 'Expand sidebar', exact: true }).click()
    await expect(mapLink).toBeVisible()
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await workspace.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('mods-map-editor-navigation.png'), fullPage: true })
  await page.getByRole('tab', { name: 'Mod Library', exact: true }).click()
  await expect(workspace).toBeVisible()
  await expectWorkspace()
  await documentTab.click()
  await expect(documentTab).toHaveAttribute('aria-selected', 'true')
  await documentTab.press('Home')
  const libraryTab = workspace.getByRole('tab', { name: 'Mod Library', exact: true })
  await expect(libraryTab).toBeFocused()
  await expect(libraryTab).toHaveAttribute('aria-selected', 'true')
  await libraryTab.press('ArrowLeft')
  await expect(page.getByRole('tab', { name: 'Enum Dictionary', exact: true })).toBeFocused()
  await expectWorkspace()
})

test('renders native walls and trunks below map surfaces while loading only nearby geometry', { tag: MOBILE_TEST_TAG }, async ({ page }, testInfo) => {
  const requests = new Set<string>()
  page.on('request', request => { if (/geometry-.*\.bin/.test(request.url())) requests.add(request.url()) })
  await openEditor(page, newMapProject(ID, '2026-01-01T00:00:00.000Z'))
  const canvas = page.locator('.iso-scene-bitmap')
  await expect.poll(() => canvas.getAttribute('data-wall-runs').then(Number)).toBeGreaterThan(0)
  await expect.poll(() => canvas.getAttribute('data-trunk-runs').then(Number)).toBeGreaterThan(0)
  expect(requests.size).toBeGreaterThan(0)
  expect(requests.size).toBeLessThan(worldMap.layers[0]!.geometry.length / 10)
  // Geometry stays bitmap paint data; terrain volume must not recreate a large SVG tree
  expect(await page.locator('.iso-canvas *').count()).toBeLessThan(100)
  for (let rotation = 0; rotation < 7; rotation++) {
    await page.getByRole('button', { name: 'Rotate view right', exact: true }).click()
    await expect(page.getByText('Loading nearby native voxel geometry...', { exact: true })).toHaveCount(0)
    await expect.poll(() => canvas.getAttribute('data-wall-runs').then(Number)).toBeGreaterThan(0)
    await expect.poll(() => canvas.getAttribute('data-trunk-runs').then(Number)).toBeGreaterThan(0)
  }
  await page.locator('.iso-scene').scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('native-walls-and-trunks.png'), fullPage: true })
  await page.getByRole('button', { name: 'Rotate view left', exact: true }).click()
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-rotation', '270')
  await page.getByRole('button', { name: 'Rotate view right', exact: true }).click()
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-rotation', '315')
  for (let step = 0; step < 4; step++) await page.getByRole('button', { name: 'Tilt view up', exact: true }).click()
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-elevation', '65')
  await expect(page.getByRole('button', { name: 'Tilt view up', exact: true })).toBeDisabled()
  await expect.poll(() => canvas.getAttribute('data-wall-runs').then(Number)).toBeGreaterThan(0)
  for (let step = 0; step < 9; step++) await page.getByRole('button', { name: 'Tilt view down', exact: true }).click()
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-elevation', '20')
  await expect(page.getByRole('button', { name: 'Tilt view down', exact: true })).toBeDisabled()
  await expect.poll(() => canvas.getAttribute('data-wall-runs').then(Number)).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'Game-style view', exact: true }).click()
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-rotation', '45')
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-elevation', '56')
  await page.getByRole('button', { name: 'Isometric camera', exact: true }).click()
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-rotation', '0')
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-elevation', '45')
  expect(JSON.parse(await exportDraft(page)).Entities).toEqual([])
})

test('retains map context and the exact draft when native geometry loading fails, then retries', async ({ page }) => {
  await page.route('**/*geometry*.bin*', route => route.fulfill({ status: 503, body: 'Synthetic unavailable tile' }))
  await page.goto('/#/mods/editor')
  await page.getByLabel('Open mod JSON file', { exact: true }).setInputFiles({ name: FILENAME, mimeType: 'application/json', buffer: Buffer.from(SOURCE) })
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Map Editor', exact: true }).click()
  await expect(page.getByText('Native geometry needs attention', { exact: true })).toBeVisible()
  const canvas = page.locator('.iso-scene-bitmap')
  await expect(canvas).toHaveAttribute('data-geometry-runs', '0')
  await expect.poll(() => canvas.getAttribute('data-terrain-cells').then(Number)).toBeGreaterThan(0)
  await page.unroute('**/*geometry*.bin*')
  await page.getByRole('button', { name: 'Retry native geometry', exact: true }).click()
  await expectMap(page)
  await expect(page.getByText('Native geometry needs attention', { exact: true })).toHaveCount(0)
  expect(await exportDraft(page)).toBe(SOURCE)
})

async function download(page: Page, name: string) {
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name, exact: true }).click()
  return readFile((await (await downloaded).path())!, 'utf8')
}
async function exportDraft(page: Page) {
  await page.getByRole('button', { name: 'Review map export', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Export review', exact: true })).toBeVisible()
  return download(page, 'Download mod')
}
async function moveTreasure(page: Page) {
  await page.locator('.map-editor-placement-list button').filter({ hasText: 'Treasure #1' }).click()
  await page.getByRole('spinbutton', { name: 'Placement X', exact: true }).fill('-10')
  await page.getByRole('spinbutton', { name: 'Placement height Y', exact: true }).fill('100')
  await page.getByRole('spinbutton', { name: 'Placement Z', exact: true }).fill('3')
  await expect(page.locator('.iso-draft-destination')).toHaveAttribute('data-coord', '-10,100,3')
  await expect(page.getByRole('tab', { name: 'JSON Editor', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Move selected placement', exact: true }).click()
}

async function pointerGesture(page: Page, mobile: boolean) {
  if (!mobile) return {
    start: async (x: number, y: number) => { await page.mouse.move(x, y); await page.mouse.down() },
    move: async (x: number, y: number) => { await page.mouse.move(x, y, { steps: 4 }) },
    end: async () => { await page.mouse.up() },
    cancel: async () => { await page.locator('.iso-canvas').dispatchEvent('pointercancel', { pointerId: 1 }); await page.mouse.up() },
    dispose: async () => undefined,
  }
  // Use actual Chromium touch input so mobile coverage exercises pointer cancellation and capture
  const client = await page.context().newCDPSession(page)
  return {
    start: async (x: number, y: number) => { await client.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] }) },
    move: async (x: number, y: number) => { await client.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x, y }] }) },
    end: async () => { await client.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }) },
    cancel: async () => { await client.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] }) },
    dispose: async () => { await client.detach() },
  }
}

async function scenePoint(page: Page, coord: { X: number; Y: number; Z: number }) {
  const svg = page.locator('.iso-canvas')
  await svg.scrollIntoViewIfNeeded()
  const camera = await svg.evaluate(element => {
    const [X, Y, Z] = element.getAttribute('data-camera')!.split(',').map(Number)
    return { coord: { X: X!, Y: Y!, Z: Z! }, rotation: Number(element.getAttribute('data-rotation')) / 45, elevation: Number(element.getAttribute('data-elevation')), zoom: Number(element.getAttribute('data-zoom')) }
  }) as IsoCamera
  return svg.evaluate((element, point) => {
    const p = new DOMPoint(point.x, point.y).matrixTransform((element as SVGSVGElement).getScreenCTM()!)
    return { x: p.x, y: p.y }
  }, isoProject(coord, camera))
}
const BRUSH_SOURCE = addVoxelPlatform(newMapProject(ID, '2026-01-01T00:00:00.000Z'), { coord: { X: -12, Y: 140, Z: 4 }, width: 1, depth: 1, biomeId: 1, voxelId: 9, lastNativeEntityId: 3824, knownVoxelIds: [9] })
async function openBrush(page: Page) {
  await openEditor(page, BRUSH_SOURCE)
  await page.locator('.map-editor-placement-list button').click()
  await page.getByRole('button', { name: 'Paint blocks', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Block biome', exact: true })).toHaveValue('1')
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-camera', '-12,140,4')
}

test('paints connected face strokes and erases blocks with atomic undo and touch cancellation', { tag: MOBILE_TEST_TAG }, async ({ page }, testInfo) => {
  await openBrush(page)
  const gesture = await pointerGesture(page, testInfo.project.name === 'mobile')
  const list = page.locator('.map-editor-placement-list button')
  const start = await scenePoint(page, { X: -11.5, Y: 141, Z: 4.5 })
  const end = await scenePoint(page, { X: -7.5, Y: 141, Z: 4.5 })
  // Pending cursor/stroke feedback must not repaint the stationary native terrain
  await page.locator('.iso-scene-bitmap').evaluate((canvas: HTMLCanvasElement) => {
    const context = canvas.getContext('2d')!
    const fill = context.fillRect
    canvas.dataset.transientPaints = '0'
    context.fillRect = function (...args) { canvas.dataset.transientPaints = String(Number(canvas.dataset.transientPaints) + 1); fill.apply(this, args) }
  })
  await gesture.start(start.x, start.y)
  await gesture.move(end.x, end.y)
  await expect(list).toHaveCount(1)
  await expect(page.getByText('5 blocks in this stroke.', { exact: false })).toBeVisible()
  await expect(page.locator('.iso-scene-bitmap')).toHaveAttribute('data-transient-paints', '0')
  await gesture.cancel()
  await expect(list).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Undo map edit', exact: true })).toBeDisabled()
  await gesture.start(start.x, start.y)
  await gesture.move(end.x, end.y)
  await gesture.end()
  await expect(list).toHaveCount(6)
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Undo map edit', exact: true }).click()
  await expect(list).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Undo map edit', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Redo map edit', exact: true }).click()
  await expect(list).toHaveCount(6)
  await page.getByRole('button', { name: 'Erase blocks', exact: true }).click()
  const eraseStart = await scenePoint(page, { X: -11.5, Y: 142, Z: 4.5 })
  const eraseEnd = await scenePoint(page, { X: -7.5, Y: 142, Z: 4.5 })
  await gesture.start(eraseStart.x, eraseStart.y)
  await gesture.move(eraseEnd.x, eraseEnd.y)
  await expect(list).toHaveCount(6)
  await gesture.end()
  await expect(list).toHaveCount(1)
  await page.getByRole('button', { name: 'Undo map edit', exact: true }).click()
  await expect(list).toHaveCount(6)
  await page.getByRole('button', { name: 'Undo map edit', exact: true }).click()
  await expect(list).toHaveCount(1)
  expect(await exportDraft(page)).toBe(BRUSH_SOURCE)
  await gesture.dispose()
})

test('places repeated blocks and brushes top and side faces after horizontal and vertical pivots', { tag: MOBILE_TEST_TAG }, async ({ page }, testInfo) => {
  await openBrush(page)
  const gesture = await pointerGesture(page, testInfo.project.name === 'mobile')
  const list = page.locator('.map-editor-placement-list button')
  for (const Y of [141, 142, 143]) {
    const p = await scenePoint(page, { X: -11.5, Y, Z: 4.5 })
    await gesture.start(p.x, p.y); await gesture.end()
  }
  await expect(list).toHaveCount(4)
  for (let index = 0; index < 3; index++) await page.getByRole('button', { name: 'Undo map edit', exact: true }).click()
  await expect(list).toHaveCount(1)
  await page.getByRole('button', { name: 'Rotate view right', exact: true }).click()
  await page.getByRole('button', { name: 'Tilt view up', exact: true }).click()
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-rotation', '45')
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-elevation', '50')
  let p = await scenePoint(page, { X: -11.5, Y: 141, Z: 4.5 })
  await gesture.start(p.x, p.y); await gesture.end()
  await expect(list).toHaveCount(2)
  await expect(list.nth(1)).toContainText('X -12, Y 141, Z 4')
  await page.getByRole('button', { name: 'Undo map edit', exact: true }).click()
  for (let step = 0; step < 6; step++) await page.getByRole('button', { name: 'Tilt view down', exact: true }).click()
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-elevation', '20')
  p = await scenePoint(page, { X: -11.5, Y: 140.5, Z: 5 })
  await gesture.start(p.x, p.y); await gesture.end()
  await expect(list).toHaveCount(2)
  await expect(list.nth(1)).toContainText('X -12, Y 140, Z 5')
  await page.getByRole('combobox', { name: 'Brush size', exact: true }).selectOption('2')
  p = await scenePoint(page, { X: -11.5, Y: 140.5, Z: 6 })
  await gesture.start(p.x, p.y); await gesture.end()
  await expect(list).toHaveCount(6)
  await page.locator('.iso-scene').scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('brush-shallow-view.png'), fullPage: true })
  const exported = JSON.parse(await exportDraft(page))
  expect(exported.Entities.map((record: { Coord: unknown }) => record.Coord)).toEqual([{ X: -12, Y: 140, Z: 4 }, { X: -12, Y: 140, Z: 5 }, { X: -12, Y: 140, Z: 6 }, { X: -12, Y: 141, Z: 6 }, { X: -11, Y: 140, Z: 6 }, { X: -11, Y: 141, Z: 6 }])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await gesture.dispose()
})

test('paints floating blocks on a construction plane without adding spacers or changing the original', { tag: MOBILE_TEST_TAG }, async ({ page }, testInfo) => {
  const blank = newMapProject(ID, '2026-01-01T00:00:00.000Z')
  await openEditor(page, blank)
  await page.getByRole('button', { name: 'Construction plane', exact: true }).click()
  const height = page.getByRole('spinbutton', { name: 'Construction height Y', exact: true })
  await height.fill('99')
  await expect(page.getByRole('img', { name: 'Construction plane Y 99. At mapped surface Y 99', exact: true })).toBeVisible()
  await height.fill('98')
  await expect(page.getByRole('img', { name: 'Construction plane Y 98. 1 below mapped surface Y 99', exact: true })).toBeVisible()
  await height.fill('140')
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-camera', '0,140,0')
  await expect(page.locator('.iso-plane-bitmap')).toHaveAttribute('data-plane-height', '140')
  const planeLabel = page.getByRole('img', { name: 'Construction plane Y 140. 41 above mapped surface Y 99', exact: true })
  await expect(planeLabel).toBeVisible()
  const navigation = page.getByRole('region', { name: 'Navigate editor camera', exact: true })
  await navigation.focus(); await page.keyboard.press('ArrowRight')
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-camera', '8,140,0')
  await page.getByRole('button', { name: 'Center on placement', exact: true }).click()
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-camera', '0,140,0')
  await page.locator('.iso-scene').scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('construction-plane-height-guide.png'), fullPage: true })
  await expect(page.getByRole('button', { name: 'Undo map edit', exact: true })).toBeDisabled()
  const gesture = await pointerGesture(page, testInfo.project.name === 'mobile')
  const list = page.locator('.map-editor-placement-list button')
  const start = await scenePoint(page, { X: .25, Y: 140, Z: .25 })
  // The visible reference outline must not constrain the construction plane's brush area
  const end = await scenePoint(page, { X: 7.25, Y: 140, Z: .25 })
  await gesture.start(start.x, start.y); await gesture.move(end.x, end.y)
  await expect(page.getByText('8 blocks in this stroke.', { exact: false })).toBeVisible()
  await expect(list).toHaveCount(0)
  await gesture.cancel()
  await expect(list).toHaveCount(0)
  await gesture.start(start.x, start.y); await gesture.move(end.x, end.y); await gesture.end()
  await expect(list).toHaveCount(8)
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  const exported = JSON.parse(await exportDraft(page))
  expect(exported.Entities.map((entity: { Coord: unknown }) => entity.Coord)).toEqual(Array.from({ length: 8 }, (_, X) => ({ X, Y: 140, Z: 0 })))
  expect(exported.Entities.every((entity: { NpcData: { Outfits: { VoxelID: number }[] } }) => entity.NpcData.Outfits[0]!.VoxelID === 9)).toBe(true)
  await page.getByRole('tab', { name: 'Map Editor', exact: true }).click()
  await page.getByRole('button', { name: 'Undo map edit', exact: true }).click()
  await expect(list).toHaveCount(0)
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-camera', '0,140,0')
  await expect(planeLabel).toBeVisible()
  await expect(page.getByRole('button', { name: 'Undo map edit', exact: true })).toBeDisabled()
  // An invalid plane cannot silently fall back to face painting or mutate history
  await height.fill('')
  await expect(page.locator('.iso-plane-label')).toHaveCount(0)
  const point = await scenePoint(page, { X: .25, Y: 140, Z: .25 })
  await gesture.start(point.x, point.y); await gesture.end()
  await expect(list).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Undo map edit', exact: true })).toBeDisabled()
  await height.fill('141')
  await page.getByRole('button', { name: 'Construction plane', exact: true }).click()
  await expect(height).toHaveCount(0)
  await expect(page.locator('.iso-plane-label')).toHaveCount(0)
  await page.getByRole('button', { name: 'Center on placement', exact: true }).click()
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-camera', '0,99,0')
  await page.getByRole('button', { name: 'Construction plane', exact: true }).click()
  await expect(height).toHaveValue('141')
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-camera', '0,141,0')
  await expect(page.getByRole('img', { name: 'Construction plane Y 141. 42 above mapped surface Y 99', exact: true })).toBeVisible()
  expect(await exportDraft(page)).toBe(blank)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await gesture.dispose()
})

test('places one rectangular platform with F and restores it with toolbar icons and scoped history shortcuts', { tag: MOBILE_TEST_TAG }, async ({ page }, testInfo) => {
  await openEditor(page, newMapProject(ID, '2026-01-01T00:00:00.000Z'))
  const svg = page.locator('.iso-canvas')
  const list = page.locator('.map-editor-placement-list button')
  await svg.focus(); await page.keyboard.press('f')
  await expect(page.getByRole('button', { name: 'Voxel platform', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('spinbutton', { name: 'Platform depth Z', exact: true }).fill('3')
  const undo = page.getByRole('button', { name: 'Undo map edit', exact: true })
  const redo = page.getByRole('button', { name: 'Redo map edit', exact: true })
  await expect(page.locator('.iso-toolbar .map-editor-history button')).toHaveCount(2)
  await expect(page.locator('.map-editor-toolbar button')).toHaveCount(0)
  await expect(undo.locator('svg')).toHaveCount(1)
  await expect(redo.locator('svg')).toHaveCount(1)
  const gesture = await pointerGesture(page, testInfo.project.name === 'mobile')
  let start = await scenePoint(page, { X: .25, Y: 99, Z: .25 })
  let end = await scenePoint(page, { X: 2.25, Y: 99, Z: 1.25 })
  await gesture.start(start.x, start.y); await gesture.move(end.x, end.y)
  await expect(page.getByText('6 blocks in this platform.', { exact: false })).toBeVisible()
  await expect(page.locator('.iso-preview-status')).toContainText('X 2 · Y 99 · Z 1')
  await expect(svg).toHaveAttribute('data-camera', '0,99,0')
  await expect(list).toHaveCount(0)
  await expect(undo).toBeDisabled()
  await gesture.cancel()
  await expect(list).toHaveCount(0)
  await gesture.start(start.x, start.y); await gesture.move(end.x, end.y); await gesture.end()
  await expect(list).toHaveCount(6)
  await expect(list.nth(0)).toContainText('X 2, Y 99, Z 1')
  await expect(list.nth(5)).toContainText('X 3, Y 99, Z 3')
  await undo.click(); await expect(list).toHaveCount(0)
  await redo.click(); await expect(list).toHaveCount(6)
  for (const [back, forward] of [['Control+z', 'Control+Shift+z'], ['Meta+z', 'Meta+Shift+z'], ['Control+z', 'Control+y']]) {
    await svg.focus(); await page.keyboard.press(back!); await expect(list).toHaveCount(0)
    await page.keyboard.press(forward!); await expect(list).toHaveCount(6)
  }
  const search = page.getByRole('searchbox', { name: 'Search voxel types', exact: true })
  await search.fill('stone'); await search.press('Control+z')
  await expect(list).toHaveCount(6)
  await svg.focus(); await page.keyboard.press('Control+z')
  await expect(list).toHaveCount(0)
  await expect(undo).toBeDisabled()
  // Changing dimensions invalidates the captured footprint rather than applying a different rectangle
  start = await scenePoint(page, { X: .25, Y: 99, Z: .25 })
  await gesture.start(start.x, start.y)
  await page.getByRole('spinbutton', { name: 'Platform width X', exact: true }).fill('3')
  await gesture.end()
  await expect(list).toHaveCount(0)
  const height = page.getByRole('spinbutton', { name: 'Placement height Y', exact: true })
  await height.fill('140')
  start = await scenePoint(page, { X: .25, Y: 140, Z: .25 })
  await gesture.start(start.x, start.y); await gesture.end()
  await expect(list).toHaveCount(9)
  await expect(list.nth(0)).toContainText('X 0, Y 140, Z 0')
  await expect(list.nth(8)).toContainText('X 2, Y 140, Z 2')
  // A platform rejects the complete rectangle if even one authored block overlaps
  end = await scenePoint(page, { X: 2.25, Y: 140, Z: 2.25 })
  await gesture.start(end.x, end.y); await gesture.end()
  await expect(page.getByText('This platform overlaps an existing voxel placement. Choose another cell or height.', { exact: true })).toBeVisible()
  await expect(list).toHaveCount(9)
  await height.fill('140.5')
  await svg.scrollIntoViewIfNeeded()
  const rect = (await svg.boundingBox())!
  await gesture.start(rect.x + rect.width / 2, rect.y + rect.height / 2); await gesture.end()
  await expect(list).toHaveCount(9)
  await height.fill('140')
  if (testInfo.project.name === 'desktop') {
    const camera = await svg.getAttribute('data-camera')
    await page.keyboard.down('Shift')
    start = await scenePoint(page, { X: .25, Y: 140, Z: .25 })
    await gesture.start(start.x, start.y); await gesture.move(start.x + 40, start.y); await gesture.end()
    await page.keyboard.up('Shift')
    await expect(svg).not.toHaveAttribute('data-camera', camera!)
    await expect(list).toHaveCount(9)
  }
  await svg.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('platform-tool-and-history.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await gesture.dispose()
})

test('switches icon tools with scoped shortcuts while preserving typing and pending stroke cancellation', { tag: MOBILE_TEST_TAG }, async ({ page }, testInfo) => {
  await openBrush(page)
  const svg = page.locator('.iso-canvas')
  await svg.focus()
  for (const [key, name] of [['v', 'Move / pan'], ['e', 'Erase blocks'], ['f', 'Voxel platform'], ['b', 'Paint blocks']]) {
    await page.keyboard.press(key!)
    await expect(page.getByRole('button', { name: name!, exact: true })).toHaveAttribute('aria-pressed', 'true')
  }
  const search = page.getByRole('searchbox', { name: 'Search voxel types', exact: true })
  await search.fill('beef')
  await search.press('v')
  await expect(page.getByRole('button', { name: 'Paint blocks', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await search.fill('')
  await svg.focus()
  await page.keyboard.press('Control+e')
  await expect(page.getByRole('button', { name: 'Paint blocks', exact: true })).toHaveAttribute('aria-pressed', 'true')
  const gesture = await pointerGesture(page, testInfo.project.name === 'mobile')
  const point = await scenePoint(page, { X: -11.5, Y: 141, Z: 4.5 })
  await gesture.start(point.x, point.y)
  await page.keyboard.press('e')
  await gesture.end()
  await expect(page.locator('.map-editor-placement-list button')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Undo map edit', exact: true })).toBeDisabled()
  await svg.focus()
  await page.keyboard.press('p')
  const height = page.getByRole('spinbutton', { name: 'Construction height Y', exact: true })
  await expect(height).toHaveValue('140')
  await expect(page.getByRole('button', { name: 'Paint blocks', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.press(']')
  await expect(height).toHaveValue('141')
  await page.keyboard.press('[')
  await expect(height).toHaveValue('140')
  await height.focus()
  await height.press('b')
  await expect(page.getByRole('button', { name: 'Construction plane', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Undo map edit', exact: true })).toBeDisabled()
  expect(await exportDraft(page)).toBe(BRUSH_SOURCE)
  await gesture.dispose()
})

test('cancels brush gestures on Escape and camera changes, and recovers failed stroke saves', { tag: MOBILE_TEST_TAG }, async ({ page }, testInfo) => {
  await page.addInitScript(() => {
    const put = IDBObjectStore.prototype.put
    IDBObjectStore.prototype.put = function (...args: Parameters<typeof put>) {
      const request = put.apply(this, args)
      if (this.transaction.db.name === 'crykit-mod-inspector-v1' && sessionStorage.getItem('synthetic-reject-brush-write') === 'true') this.transaction.abort()
      return request
    }
  })
  await openBrush(page)
  const gesture = await pointerGesture(page, testInfo.project.name === 'mobile')
  const list = page.locator('.map-editor-placement-list button')
  const start = await scenePoint(page, { X: -11.5, Y: 141, Z: 4.5 })
  const end = await scenePoint(page, { X: -7.5, Y: 141, Z: 4.5 })
  await page.locator('.iso-canvas').focus()
  await gesture.start(start.x, start.y); await gesture.move(end.x, end.y)
  await page.keyboard.press('Escape')
  await gesture.end()
  await expect(list).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Undo map edit', exact: true })).toBeDisabled()
  await gesture.start(start.x, start.y); await gesture.move(end.x, end.y)
  await page.getByRole('button', { name: 'Rotate view right', exact: true }).focus()
  await page.keyboard.press('Enter')
  await gesture.end()
  await expect(list).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Undo map edit', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Rotate view left', exact: true }).click()
  await page.evaluate(() => sessionStorage.setItem('synthetic-reject-brush-write', 'true'))
  const nextStart = await scenePoint(page, { X: -11.5, Y: 141, Z: 4.5 })
  const nextEnd = await scenePoint(page, { X: -7.5, Y: 141, Z: 4.5 })
  await gesture.start(nextStart.x, nextStart.y); await gesture.move(nextEnd.x, nextEnd.y); await gesture.end()
  await expect(page.getByRole('alert')).toContainText('Draft is not saved')
  const recovery = await download(page, 'Download unsaved draft for recovery')
  expect(JSON.parse(recovery).Entities).toHaveLength(6)
  await page.evaluate(() => sessionStorage.removeItem('synthetic-reject-brush-write'))
  await page.getByRole('button', { name: 'Retry save', exact: true }).click()
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  expect(await exportDraft(page)).toBe(recovery)
  await gesture.dispose()
})

test('creates, undoes and exports a voxel platform with blank original and persistent draft', { tag: MOBILE_TEST_TAG }, async ({ page }, testInfo) => {
  await page.goto('/#/mods/editor')
  await page.getByRole('button', { name: 'New map mod', exact: true }).click()
  await expectMap(page)
  await page.getByRole('button', { name: 'Voxel platform', exact: true }).click()
  await page.getByRole('spinbutton', { name: 'Placement height Y', exact: true }).fill('100')
  await page.getByRole('button', { name: 'Choose destination on map', exact: true }).click()
  const viewport = page.locator('.map-editor .world-map-viewport')
  await viewport.scrollIntoViewIfNeeded()
  const rect = (await viewport.boundingBox())!
  await page.mouse.move(rect.x + rect.width / 2, rect.y + rect.height / 2)
  await page.mouse.down()
  await page.mouse.move(rect.x + rect.width / 2 + 30, rect.y + rect.height / 2, { steps: 3 })
  await page.mouse.up()
  await expect(page.getByRole('spinbutton', { name: 'Placement X', exact: true })).toHaveValue('0')
  await expect(page.getByRole('button', { name: 'Cancel destination pick', exact: true })).toBeVisible()
  // Aim at the native cell's center with fractional CSS coordinates, including the viewport border
  const terrain = (await page.locator('.map-editor .world-map-terrain').boundingBox())!
  await page.mouse.click(terrain.x + terrain.width / 2 + terrain.width / worldMap.bounds.width / 2, terrain.y + terrain.height / 2 + terrain.height / worldMap.bounds.height / 2)
  await expect(page.getByRole('spinbutton', { name: 'Placement X', exact: true })).toHaveValue(String(Math.floor(worldMap.bounds.x + worldMap.bounds.width / 2)))
  await expect(page.getByRole('spinbutton', { name: 'Placement Z', exact: true })).toHaveValue(String(Math.floor(worldMap.bounds.z + worldMap.bounds.height / 2)))
  await expect(page.getByRole('spinbutton', { name: 'Placement height Y', exact: true })).toHaveValue('100')
  await expect(page.getByRole('button', { name: 'Choose destination on map', exact: true })).toBeVisible()
  await page.getByRole('spinbutton', { name: 'Placement X', exact: true }).fill('-12')
  await page.getByRole('spinbutton', { name: 'Placement height Y', exact: true }).fill('100')
  await page.getByRole('spinbutton', { name: 'Placement Z', exact: true }).fill('4')
  await page.getByRole('combobox', { name: 'Block biome', exact: true }).selectOption('1')
  await page.getByRole('button', { name: 'Add voxel platform', exact: true }).click()
  const placements = page.locator('.map-editor-placement-list button')
  await expect(placements).toHaveCount(4)
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Undo map edit', exact: true }).click()
  await expect(placements).toHaveCount(0)
  await page.getByRole('button', { name: 'Redo map edit', exact: true }).click()
  await expect(placements).toHaveCount(4)
  expect(JSON.parse(await download(page, 'Download original')).Entities).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('map-editor-platform.png'), fullPage: true })
  const exported = JSON.parse(await exportDraft(page))
  expect(exported.Entities.map((record: { ID: number }) => record.ID)).toEqual([3825, 3826, 3827, 3828])
  expect(exported.Entities[0].NpcData.Outfits[0]).toMatchObject({ VoxelID: 9, MountType: 20, WanderType: 0, PlayerCollision: 3, Condition: { ConditionType: 0, IsNegation: false } })
  await page.reload()
  const files = page.getByRole('combobox', { name: 'Files opened in this tool', exact: true })
  const id = await files.locator('option').filter({ hasText: 'map-placements.json' }).getAttribute('value')
  await files.selectOption(id!)
  await page.getByRole('tab', { name: 'Map Editor', exact: true }).click()
  await expectMap(page)
  await expect(placements).toHaveCount(4)
  await expect(page.getByRole('button', { name: 'Undo map edit', exact: true })).toBeDisabled()
})

test('moves imported treasure without losing unknown fields and restores exact export through undo', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await openEditor(page)
  await moveTreasure(page)
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Undo map edit', exact: true }).click()
  await expect(page.locator('.map-editor-placement-list button')).toContainText('X -12, Y 99, Z 4')
  await page.getByRole('button', { name: 'Redo map edit', exact: true }).click()
  await expect(page.locator('.map-editor-placement-list button')).toContainText('X -10, Y 100, Z 3')
  const exported = await exportDraft(page)
  expect(exported).toBe(SOURCE.replace('"X":-12,"Y":99,"Z":4', '"X":-10,"Y":100,"Z":3'))
  expect(await download(page, 'Download original')).toBe(SOURCE)
  await page.getByRole('tab', { name: 'Map Editor', exact: true }).click()
  await page.getByRole('button', { name: 'Inspect entity JSON', exact: true }).click()
  await expect(page.getByRole('textbox', { name: /^Exact JSON value/ })).toHaveValue(TREASURE.replace('"X":-12,"Y":99,"Z":4', '"X":-10,"Y":100,"Z":3'))
})

test('retains failed map saves for recovery and retries the exact authored draft', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await page.addInitScript(() => {
    const put = IDBObjectStore.prototype.put
    IDBObjectStore.prototype.put = function (...args: Parameters<typeof put>) {
      const request = put.apply(this, args)
      if (this.transaction.db.name === 'crykit-mod-inspector-v1' && sessionStorage.getItem('synthetic-reject-map-write') === 'true') this.transaction.abort()
      return request
    }
  })
  await openEditor(page)
  await page.evaluate(() => sessionStorage.setItem('synthetic-reject-map-write', 'true'))
  await moveTreasure(page)
  await expect(page.getByRole('alert')).toContainText('Draft is not saved')
  expect(await download(page, 'Download unsaved draft for recovery')).toBe(SOURCE.replace('"X":-12,"Y":99,"Z":4', '"X":-10,"Y":100,"Z":3'))
  await expect(page.getByRole('button', { name: 'New map mod', exact: true })).toBeDisabled()
  await page.evaluate(() => sessionStorage.removeItem('synthetic-reject-map-write'))
  await page.getByRole('button', { name: 'Retry save', exact: true }).click()
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  expect(await exportDraft(page)).toBe(SOURCE.replace('"X":-12,"Y":99,"Z":4', '"X":-10,"Y":100,"Z":3'))
})

test('loads the map editor and exports its saved draft after offline preparation', { tag: MOBILE_TEST_TAG }, async ({ page, context }) => {
  await page.goto('/#/mods/editor')
  // Prepare before visiting Map Editor so its deferred chunk must also survive an offline reload
  await page.getByLabel('Open mod JSON file', { exact: true }).setInputFiles({ name: FILENAME, mimeType: 'application/json', buffer: Buffer.from(SOURCE) })
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  await settings.getByRole('button', { name: 'Prepare for offline use', exact: true }).click()
  await expectOfflineReady(settings)
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.reload()
  const files = page.getByRole('combobox', { name: 'Files opened in this tool', exact: true })
  const id = await files.locator('option').filter({ hasText: FILENAME }).getAttribute('value')
  await files.selectOption(id!)
  await page.getByRole('tab', { name: 'Map Editor', exact: true }).click()
  await expectMap(page)
  await moveTreasure(page)
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  expect(await exportDraft(page)).toBe(SOURCE.replace('"X":-12,"Y":99,"Z":4', '"X":-10,"Y":100,"Z":3'))
})


test('expands terrain with zoom and navigates the orientation map without editing the draft', { tag: MOBILE_TEST_TAG }, async ({ page }, testInfo) => {
  await openEditor(page)
  await page.locator('.map-editor-placement-list button').filter({ hasText: 'Treasure #1' }).click()
  const terrain = page.locator('.iso-scene-bitmap')
  const terrainCount = async () => Number(await terrain.getAttribute('data-terrain-cells'))
  await expect.poll(terrainCount).toBeGreaterThan(361)
  const initialCount = await terrainCount()
  await page.getByRole('button', { name: 'Zoom isometric out', exact: true }).click()
  await page.getByRole('button', { name: 'Zoom isometric out', exact: true }).click()
  await expect.poll(terrainCount).toBeGreaterThan(initialCount)
  // Terrain coverage expands without adding a DOM node for every native block
  expect(await page.locator('.iso-canvas *').count()).toBeLessThan(100)
  const map = page.locator('.map-orientation-canvas')
  await map.scrollIntoViewIfNeeded()
  const target = await map.evaluate(svg => {
    const point = new DOMPoint(28, 24).matrixTransform((svg as SVGSVGElement).getScreenCTM()!)
    return { x: point.x, y: point.y }
  })
  if (testInfo.project.name === 'mobile') await page.touchscreen.tap(target.x, target.y)
  else await page.mouse.click(target.x, target.y)
  await expect(map).toHaveAttribute('data-center', '28,24')
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-camera', /^28,\d+,24$/)
  const navigator = page.getByRole('region', { name: 'Navigate editor camera', exact: true })
  await navigator.focus()
  await page.keyboard.press('ArrowRight')
  await expect(map).toHaveAttribute('data-center', '36,24')
  await page.getByRole('button', { name: 'World', exact: true }).click()
  await expect(map).toHaveAttribute('viewBox', /1328 880$/)
  await page.getByRole('button', { name: 'Rotate view right', exact: true }).click()
  await expect(map).toHaveAttribute('data-center', '36,24')
  await expect(page.locator('.map-editor-placement-list button')).toContainText('X -12, Y 99, Z 4')
  await expect(page.getByRole('button', { name: 'Undo map edit', exact: true })).toBeDisabled()
  expect(await exportDraft(page)).toBe(SOURCE)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('drags imported placements on X/Z and height Y with single-step undo and cancellation', { tag: MOBILE_TEST_TAG }, async ({ page }, testInfo) => {
  await openEditor(page)
  const gesture = await pointerGesture(page, testInfo.project.name === 'mobile')
  await page.locator('.map-editor-placement-list button').filter({ hasText: 'Treasure #1' }).click()
  const placement = page.locator('[data-placement-id="1"]')
  const svg = page.locator('.iso-canvas')
  await svg.scrollIntoViewIfNeeded()
  let box = (await placement.boundingBox())!
  let rect = (await svg.boundingBox())!
  const scale = rect.width / 960
  await gesture.start(box.x + box.width / 2, box.y + box.height / 2)
  await gesture.move(box.x + box.width / 2 + 72 * scale, box.y + box.height / 2 + 12 * scale)
  // A gesture is preview-only until release; intermediate pointer updates cannot autosave
  await expect(page.locator('.map-editor-placement-list button')).toContainText('X -12, Y 99, Z 4')
  await expect(page.locator('.iso-preview-status')).toContainText('X -10 · Y 99 · Z 3')
  await gesture.end()
  await expect(page.locator('.map-editor-placement-list button')).toContainText('X -10, Y 99, Z 3')
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Undo map edit', exact: true }).click()
  await expect(page.locator('.map-editor-placement-list button')).toContainText('X -12, Y 99, Z 4')
  await expect(page.getByRole('button', { name: 'Undo map edit', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Rotate view right', exact: true }).click()
  await page.getByRole('button', { name: 'Zoom isometric in', exact: true }).click()
  await svg.scrollIntoViewIfNeeded()
  const handle = page.locator('[data-height-handle="1"] circle')
  box = (await handle.boundingBox())!
  rect = (await svg.boundingBox())!
  const heightStep = 24 * 1.25 * rect.width / 960
  await gesture.start(box.x + box.width / 2, box.y + box.height / 2)
  await gesture.move(box.x + box.width / 2, box.y + box.height / 2 - heightStep * 2)
  await gesture.cancel()
  await expect(page.locator('.map-editor-placement-list button')).toContainText('X -12, Y 99, Z 4')
  await expect(page.getByRole('button', { name: 'Undo map edit', exact: true })).toBeDisabled()
  box = (await handle.boundingBox())!
  await gesture.start(box.x + box.width / 2, box.y + box.height / 2)
  await gesture.move(box.x + box.width / 2, box.y + box.height / 2 - heightStep * 2)
  await gesture.end()
  await expect(page.locator('.map-editor-placement-list button')).toContainText('X -12, Y 101, Z 4')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await svg.scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('isometric-height.png'), fullPage: true })
  expect(await exportDraft(page)).toBe(SOURCE.replace('"X":-12,"Y":99,"Z":4', '"X":-12,"Y":101,"Z":4'))
  expect(await download(page, 'Download original')).toBe(SOURCE)
  await gesture.dispose()
})

test('authors precise platform coordinates and explicitly chooses native surface height', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await page.goto('/#/mods/editor')
  await page.getByRole('button', { name: 'New map mod', exact: true }).click()
  await expectMap(page)
  await page.getByRole('button', { name: 'Voxel platform', exact: true }).click()
  await page.getByRole('spinbutton', { name: 'Placement X', exact: true }).fill('-11')
  await page.getByRole('spinbutton', { name: 'Placement height Y', exact: true }).fill('100')
  await page.getByRole('spinbutton', { name: 'Placement Z', exact: true }).fill('4')
  await page.getByRole('spinbutton', { name: 'Platform width X', exact: true }).fill('1')
  await page.getByRole('spinbutton', { name: 'Platform depth Z', exact: true }).fill('1')
  await expect(page.locator('.iso-canvas')).toHaveAttribute('data-camera', '-11,100,4')
  await expect(page.getByRole('spinbutton', { name: 'Placement X', exact: true })).toHaveValue('-11')
  await expect(page.getByRole('spinbutton', { name: 'Placement height Y', exact: true })).toHaveValue('100')
  await expect(page.locator('.map-editor-placement-list button')).toHaveCount(0)
  await page.getByRole('button', { name: 'Use mapped surface height', exact: true }).click()
  await expect(page.locator('.iso-preview-status')).toContainText('Aligned with mapped surface')
  await page.getByRole('combobox', { name: 'Block biome', exact: true }).selectOption('1')
  await page.getByRole('button', { name: 'Add voxel platform', exact: true }).click()
  await expect(page.locator('.map-editor-placement-list button')).toHaveCount(1)
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
})
