import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { expectOfflineReady } from './offline-helpers'

const ROUTE = '/#/mods/editor'
const FILENAME = 'synthetic-inspector.json'
const SOURCE = '\ufeff{\r\n  "EditorVersion": 34,\r\n  "Title": "Synthetic inspector",\r\n  "SteamWorkshopFileID": 9007199254740993,\r\n  "Passives": [{"ID": 91000, "Name": "Synthetic sight", "StatMods": [{"Tag": 9001, "Value1": 0, "Value2": 0, "Value3": 0}]}],\r\n  "Abilities": [{"ID": 92000, "Name": "Synthetic action"}],\r\n  "Jobs": [{"ID": 93000, "Name": "Synthetic job", "AbilityIDs": [92000]}],\r\n  "FutureData": {"nullValue": null, "text": "<script>throw new Error(1)</script>", "precise": 0.12345678901234567890123456789}\r\n}\r\n'

async function importMod(page: Page, source = SOURCE) {
  await page.goto(ROUTE)
  await page.getByLabel('Open mod JSON file', { exact: true }).setInputFiles({ name: FILENAME, mimeType: 'application/json', buffer: Buffer.from(source) })
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
}

async function reopenFile(page: Page) {
  const files = page.getByRole('combobox', { name: 'Files opened in this tool', exact: true })
  const option = files.locator('option').filter({ hasText: FILENAME })
  await expect(option).toHaveCount(1)
  await files.selectOption((await option.getAttribute('value'))!)
}

async function selectPath(page: Page, path: string, query = path) {
  await page.getByLabel('Search keys, values, and decoded names', { exact: true }).fill(query)
  await page.locator('.inspector-search-result').filter({ has: page.locator('code', { hasText: new RegExp(`^${path.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`) }) }).click()
  await expect(page.getByRole('textbox', { name: /^Exact JSON value/ })).toBeEnabled()
}

async function downloadText(page: Page, buttonName: string) {
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: buttonName, exact: true }).click()
  const result = await download
  return readFile((await result.path())!, 'utf8')
}

test('switches between document and shared dictionary tabs by keyboard without importing', async ({ page }) => {
  await page.goto(ROUTE)
  await expect(page.getByRole('heading', { name: 'Mods', exact: true })).toBeVisible()
  const documentTab = page.getByRole('tab', { name: 'JSON document', exact: true })
  const dictionaryTab = page.getByRole('tab', { name: 'Enum dictionary', exact: true })
  const documentPanel = page.getByRole('tabpanel', { name: 'JSON document', exact: true })
  const dictionaryPanel = page.getByRole('tabpanel', { name: 'Enum dictionary', exact: true })
  await expect(documentTab).toHaveAttribute('aria-selected', 'true')
  await expect(documentPanel).toBeVisible()
  await expect(dictionaryPanel).not.toBeVisible()
  await documentTab.focus()
  await documentTab.press('ArrowLeft')
  await expect(dictionaryTab).toBeFocused()
  await expect(dictionaryTab).toHaveAttribute('aria-selected', 'true')
  await expect(dictionaryPanel).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Files opened in this tool', exact: true })).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Open JSON file', exact: true })).not.toBeVisible()
  await page.getByLabel('Search enum names and values', { exact: true }).fill('RevealStatsAuto')
  const table = page.locator('.inspector-enum-groups details').filter({ hasText: 'SangStatModTag' })
  await expect(table).toContainText('477')
  await expect(table).toContainText('RevealStatsAuto')
  await dictionaryTab.press('Home')
  await expect(documentTab).toBeFocused()
  await expect(documentPanel).toBeVisible()
  await documentTab.press('End')
  await expect(dictionaryTab).toBeFocused()
  await expect(page.getByLabel('Search enum names and values', { exact: true })).toHaveValue('RevealStatsAuto')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width)
  await dictionaryTab.press('ArrowRight')
  await expect(documentTab).toBeFocused()
  await expect(documentTab).toHaveAttribute('aria-selected', 'true')
  await documentTab.press('Tab')
  await expect(documentPanel).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width)
})

test('edits a tag through its picklist, restores a saved draft, and exports only that exact change', async ({ page }) => {
  const pageErrors: string[] = []
  page.on('pageerror', error => pageErrors.push(error.message))
  await importMod(page)
  await selectPath(page, '$.Passives[0].StatMods[0].Tag', '9001')
  await expect(page.locator('.inspector-context')).toContainText('Unknown SangStatModTag (9001)')
  await page.getByLabel('Search known values', { exact: true }).fill('RevealStatsAuto')
  await page.locator('.inspector-option').filter({ hasText: 'RevealStatsAuto' }).click()
  await expect(page.getByRole('textbox', { name: /^Exact JSON value/ })).toHaveValue('477')
  await page.getByRole('button', { name: 'Apply JSON edit', exact: true }).click()
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await expect(page.locator('.inspector-context')).toContainText('RevealStatsAuto')
  await page.reload()
  await reopenFile(page)
  await page.getByRole('button', { name: 'Review export', exact: true }).click()
  const review = page.getByRole('region', { name: 'Export review', exact: true })
  await expect(review.locator('.inspector-change')).toHaveCount(1)
  await expect(review).toContainText('$.Passives[0].StatMods[0].Tag')
  await expect(review).toContainText('RevealStatsAuto')
  expect(await downloadText(page, 'Download mod')).toBe(SOURCE.replace('"Tag": 9001', '"Tag": 477'))
  expect(await downloadText(page, 'Download original')).toBe(SOURCE)
  expect(pageErrors).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width)
})

test('keeps invalid edits open, protects navigation, and links mod-local relationships', async ({ page }) => {
  await importMod(page)
  await selectPath(page, '$.Jobs[0].AbilityIDs[0]')
  await expect(page.locator('.inspector-context')).toContainText('Synthetic action')
  await page.getByRole('button', { name: 'Go to referenced record', exact: true }).click()
  await expect(page.locator('.inspector-path')).toHaveText('$.Abilities[0]')
  await page.getByRole('button', { name: 'Find relationships', exact: true }).click()
  await expect(page.locator('.inspector-relationships')).toContainText('incoming: Synthetic action')
  await selectPath(page, '$.Title')
  await page.getByRole('textbox', { name: /^Exact JSON value/ }).fill('"unfinished')
  await page.getByRole('button', { name: 'Apply JSON edit', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Unterminated JSON string')
  await expect(page.getByRole('button', { name: 'Review export', exact: true })).toBeDisabled()
  await page.getByRole('tab', { name: 'Enum dictionary', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Current file', exact: true })).not.toBeVisible()
  await page.getByLabel('Search enum names and values', { exact: true }).fill('RevealStatsAuto')
  await page.getByRole('tab', { name: 'JSON document', exact: true }).click()
  await expect(page.getByRole('textbox', { name: /^Exact JSON value/ })).toHaveValue('"unfinished')
  await expect(page.getByRole('alert')).toContainText('Unterminated JSON string')
  await expect(page.getByRole('button', { name: 'Review export', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Builds', exact: true }).filter({ visible: true }).click()
  await expect(page.getByText('Unsaved edits are still open', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Mods', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save and continue', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Mods', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Discard and continue', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Mods', exact: true })).not.toBeVisible()
  await page.goto(ROUTE)
  await reopenFile(page)
  await page.getByRole('button', { name: 'Review export', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Export review', exact: true })).toContainText('No semantic changes')
})

test('rejects invalid imports without replacing saved data', async ({ page }) => {
  await importMod(page)
  await page.getByLabel('Open mod JSON file', { exact: true }).setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"ID": 1, "ID": 2}') })
  await expect(page.getByText(/Import failed: Duplicate object property/)).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Files opened in this tool', exact: true })).toHaveValue(/.+/)
  expect(await downloadText(page, 'Download original')).toBe(SOURCE)
})

test('keeps a conflicting tab recoverable without overwriting the winning draft', async ({ page, context }) => {
  await importMod(page)
  const other = await context.newPage()
  await other.goto(ROUTE)
  await reopenFile(other)
  await selectPath(page, '$.Title')
  await selectPath(other, '$.Title')
  await page.getByRole('textbox', { name: /^Exact JSON value/ }).fill('"Winning draft"')
  await page.getByRole('button', { name: 'Apply JSON edit', exact: true }).click()
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await other.getByRole('textbox', { name: /^Exact JSON value/ }).fill('"Conflicting draft"')
  await other.getByRole('button', { name: 'Apply JSON edit', exact: true }).click()
  await expect(other.getByRole('alert')).toContainText('changed in another tab')
  expect(await downloadText(other, 'Download unsaved draft for recovery')).toBe(SOURCE.replace('"Synthetic inspector"', '"Conflicting draft"'))
  await other.getByRole('button', { name: 'Retry save', exact: true }).click()
  await expect(other.getByRole('alert')).toContainText('changed in another tab')
  await other.getByRole('button', { name: 'Reopen saved version', exact: true }).click()
  await expect(other.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await selectPath(other, '$.Title')
  await expect(other.getByRole('textbox', { name: /^Exact JSON value/ })).toHaveValue('"Winning draft"')
  expect(await downloadText(other, 'Download original')).toBe(SOURCE)
})

test('opens saved originals, edits, and exports while offline', async ({ page, context }) => {
  await importMod(page)
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  await settings.getByRole('button', { name: 'Prepare for offline use', exact: true }).click()
  await expectOfflineReady(settings)
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.goto(ROUTE)
  await page.reload()
  await reopenFile(page)
  await selectPath(page, '$.Title')
  await page.getByRole('textbox', { name: /^Exact JSON value/ }).fill('"Offline draft"')
  await page.getByRole('button', { name: 'Apply JSON edit', exact: true }).click()
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Review export', exact: true }).click()
  expect(await downloadText(page, 'Download mod')).toBe(SOURCE.replace('"Synthetic inspector"', '"Offline draft"'))
  expect(await downloadText(page, 'Download original')).toBe(SOURCE)
})

test('retains a failed save for recovery and retries the same exact draft', async ({ page }) => {
  await page.addInitScript(() => {
    const originalPut = IDBObjectStore.prototype.put
    IDBObjectStore.prototype.put = function (...args: Parameters<typeof originalPut>) {
      const request = originalPut.apply(this, args)
      if (this.transaction.db.name === 'crykit-mod-inspector-v1' && sessionStorage.getItem('synthetic-reject-inspector-write') === 'true') this.transaction.abort()
      return request
    }
  })
  await importMod(page)
  await selectPath(page, '$.Title')
  await page.evaluate(() => sessionStorage.setItem('synthetic-reject-inspector-write', 'true'))
  await page.getByRole('textbox', { name: /^Exact JSON value/ }).fill('"Recoverable draft"')
  await page.getByRole('button', { name: 'Apply JSON edit', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Draft is not saved')
  expect(await downloadText(page, 'Download unsaved draft for recovery')).toBe(SOURCE.replace('"Synthetic inspector"', '"Recoverable draft"'))
  expect(await downloadText(page, 'Download original')).toBe(SOURCE)
  await page.evaluate(() => sessionStorage.removeItem('synthetic-reject-inspector-write'))
  await page.getByRole('button', { name: 'Retry save', exact: true }).click()
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await page.reload()
  await reopenFile(page)
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await selectPath(page, '$.Title')
  await expect(page.getByRole('textbox', { name: /^Exact JSON value/ })).toHaveValue('"Recoverable draft"')
})

test('reopens an edited document spanning storage chunks and preserves its exact original', async ({ page }) => {
  const payloadLength = 2 * 1024 * 1024 + 37
  const largeSource = SOURCE.replace('"FutureData": {', `"FutureData": {"payload": "${'x'.repeat(payloadLength)}", `)
  const expectedDraft = largeSource.replace('"Synthetic inspector"', '"Chunked draft"')
  const digest = (text: string) => createHash('sha256').update(text).digest('hex')
  await importMod(page, largeSource)
  await selectPath(page, '$.Title')
  await page.getByRole('textbox', { name: /^Exact JSON value/ }).fill('"Chunked draft"')
  await page.getByRole('button', { name: 'Apply JSON edit', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Select $.Title', exact: true })).toContainText('Chunked draft')
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await page.reload()
  await reopenFile(page)
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await selectPath(page, '$.Title')
  await expect(page.getByRole('textbox', { name: /^Exact JSON value/ })).toHaveValue('"Chunked draft"')
  await page.getByRole('button', { name: 'Review export', exact: true }).click()
  await expect(page.locator('.inspector-change')).toHaveCount(1)
  expect(digest(await downloadText(page, 'Download mod'))).toBe(digest(expectedDraft))
  expect(digest(await downloadText(page, 'Download original'))).toBe(digest(largeSource))
})

test('preserves an older format and calls out a marker change made through the whole document', async ({ page }) => {
  const olderSource = SOURCE.replace('"EditorVersion": 34', '"EditorVersion": 31')
  await importMod(page, olderSource)
  const format = page.locator('.inspector-format')
  await expect(format).toContainText('31')
  await expect(format).toContainText(/older/i)
  await selectPath(page, '$.Title')
  await page.getByRole('textbox', { name: /^Exact JSON value/ }).fill('"Edited older mod"')
  await page.getByRole('button', { name: 'Apply JSON edit', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Select $.Title', exact: true })).toContainText('Edited older mod')
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Review export', exact: true }).click()
  const olderDraft = olderSource.replace('"Synthetic inspector"', '"Edited older mod"')
  expect(await downloadText(page, 'Download mod')).toBe(olderDraft)
  await page.getByRole('button', { name: 'Close review', exact: true }).click()
  await page.getByRole('button', { name: 'Edit whole document JSON', exact: true }).click()
  const changedMarker = olderDraft.slice(1).replace('"EditorVersion": 31', '"EditorVersion": 34').trim()
  await page.getByRole('textbox', { name: /^Exact JSON value/ }).fill(changedMarker)
  await page.getByRole('button', { name: 'Apply JSON edit', exact: true }).click()
  await expect(format).toContainText('34')
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Review export', exact: true }).click()
  const review = page.getByRole('region', { name: 'Export review', exact: true })
  await expect(review).toContainText('EditorVersion changed')
  await expect(review).toContainText('31')
  await expect(review).toContainText('34')
  await expect(review).toContainText(/does not (?:convert|migrate)|no (?:conversions|migrations)/i)
  expect(await downloadText(page, 'Download original')).toBe(olderSource)
})

test('explains navigation entries and recursively opens a branch without editing saved editor state', async ({ page }) => {
  const treeSource = JSON.stringify({
    EditorVersion: 34,
    Tree: [{ ModelTypeID: 3, ModelID: 99000, SortOrder: 7, IsExpanded: false, Children: [
      { ModelTypeID: 7, ModelID: 91000, SortOrder: 2, IsExpanded: true, Children: [] },
    ] }],
    Folders: [{ ID: 99000, Name: 'Synthetic navigation folder' }],
    Passives: [{ ID: 91000, Name: 'Synthetic navigation passive', StatMods: [{ Tag: 477, Value1: 0, Value2: 0, Value3: 0 }] }],
    FutureData: { Nested: { Count: 1 } },
  }, null, 2)
  await importMod(page, treeSource)
  await page.getByRole('button', { name: 'Expand $.FutureData', exact: true }).click({ modifiers: ['Alt'] })
  await expect(page.getByRole('button', { name: 'Select $.FutureData.Nested.Count', exact: true })).toBeVisible()
  await selectPath(page, '$.Tree')
  await expect(page.locator('.inspector-context')).toContainText('Crystal Edit navigation')
  await page.getByRole('button', { name: 'Expand branch', exact: true }).click()
  await expect(page.getByRole('button', { name: /^Select \$\.Tree\[0\]$/ })).toContainText('Synthetic navigation folder')
  await expect(page.getByRole('button', { name: /^Select \$\.Tree\[0\]\.Children\[0\]$/ })).toContainText('Synthetic navigation passive')
  await expect(page.getByRole('button', { name: 'Select $.Tree[0].Children[0].ModelID', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Select $.FutureData.Nested.Count', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Collapse branch', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Expand $.Tree', exact: true })).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('button', { name: 'Select $.Tree[0].Children[0].ModelID', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Select $.FutureData.Nested.Count', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Expand $.Tree', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Expand $.Tree[0]', exact: true })).toHaveAttribute('aria-expanded', 'false')
  await page.getByRole('button', { name: 'Expand branch', exact: true }).click()
  await page.getByRole('button', { name: /^Select \$\.Tree\[0\]\.Children\[0\]$/ }).click()
  await expect(page.locator('.inspector-context')).toContainText('ModelPassive')
  await page.getByRole('button', { name: 'Go to referenced record', exact: true }).click()
  await expect(page.locator('.inspector-path')).toHaveText('$.Passives[0]')
  await page.getByRole('button', { name: 'Review export', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Export review', exact: true })).toContainText('No semantic changes')
  expect(await downloadText(page, 'Download mod')).toBe(treeSource)
  expect(await downloadText(page, 'Download original')).toBe(treeSource)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width)
})

test('resolves base world entities, searches locations, and retargets only the selected ID', async ({ page }) => {
  const data = {
    EditorVersion: 34,
    Title: 'Synthetic entity inspection',
    Entities: [{ ID: 4, EntityType: 0, BiomeID: 1, Coord: { X: 12, Y: 34, Z: 56 }, NpcData: { Key: 'Synthetic NPC override' } }],
    Tree: [{ ModelTypeID: 18, ModelID: 1 }, { ModelTypeID: 18, ModelID: 4 }, { ModelTypeID: 18, ModelID: 999999 }],
  }
  const source = JSON.stringify(data, null, 2)
  await importMod(page, source)
  await expect(page.locator('.mod-inspector')).not.toContainText('Base entity records are not bundled')
  await selectPath(page, '$.Tree[0].ModelID')
  await expect(page.locator('.inspector-context')).toContainText('Treasure: Tonic')
  await expect(page.locator('.inspector-context')).toContainText('Spawning Meadows')
  await expect(page.locator('.inspector-context')).toContainText('Coord (-12, 99, 4)')
  await selectPath(page, '$.Tree[1].ModelID')
  await expect(page.locator('.inspector-context')).toContainText('Synthetic NPC override')
  await page.getByRole('button', { name: 'Go to referenced record', exact: true }).click()
  await expect(page.locator('.inspector-path')).toHaveText('$.Entities[0]')
  await expect(page.locator('.inspector-context')).toContainText('Npc: Synthetic NPC override')
  await expect(page.locator('.inspector-context')).toContainText('Coord (12, 34, 56)')
  await selectPath(page, '$.Tree[2].ModelID')
  await expect(page.locator('.inspector-context')).toContainText('Unknown entity ID 999999')
  await selectPath(page, '$.Entities[0].ID')
  await expect(page.locator('.inspector-context')).toContainText('Z1_IntroNan')
  await page.getByRole('searchbox', { name: 'Search known values', exact: true }).fill('Spawning Meadows')
  const baseEntity = page.locator('.inspector-option').filter({ has: page.locator('code', { hasText: /^1$/ }) })
  await expect(baseEntity).toContainText('Treasure: Tonic')
  await baseEntity.click()
  await expect(page.getByRole('textbox', { name: /^Exact JSON value/ })).toHaveValue('1')
  await page.getByRole('button', { name: 'Apply JSON edit', exact: true }).click()
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Review export', exact: true }).click()
  expect(JSON.parse(await downloadText(page, 'Download mod'))).toEqual({ ...data, Entities: [{ ...data.Entities[0], ID: 1 }] })
  expect(await downloadText(page, 'Download original')).toBe(source)
})

test('recognizes external file versions and edits one copy without importing planner data', async ({ page }) => {
  const mod = { ID: 'synthetic-external-project', Title: 'Synthetic external mod', Version: '1.0', EditorVersion: 34, Passives: [{ ID: 91000, Name: 'Synthetic passive' }] }
  const firstSource = JSON.stringify(mod, null, 2)
  const secondSource = JSON.stringify({ ...mod, Version: '1.1', Notes: 'A later external file' }, null, 2)
  await page.goto(ROUTE)
  await expect(page.getByRole('heading', { name: 'Mods', exact: true })).toBeVisible()
  const plannerCounts = () => page.evaluate(async () => {
    const database = await new Promise<IDBDatabase>((resolve, reject) => {
      const request = indexedDB.open('crykit')
      request.onsuccess = () => resolve(request.result)
      request.onerror = () => reject(request.error)
    })
    try {
      const stores = ['catalogs', 'sources', 'imports', 'localDatas']
      const transaction = database.transaction(stores, 'readonly')
      return await Promise.all(stores.map(store => new Promise<number>((resolve, reject) => {
        const request = transaction.objectStore(store).count()
        request.onsuccess = () => resolve(request.result)
        request.onerror = () => reject(request.error)
      })))
    } finally { database.close() }
  })
  const before = await plannerCounts()
  const upload = page.getByLabel('Open mod JSON file', { exact: true })
  const files = page.getByRole('combobox', { name: 'Files opened in this tool', exact: true })
  const summary = page.getByRole('region', { name: 'Current file', exact: true })
  await upload.setInputFiles({ name: FILENAME, mimeType: 'application/json', buffer: Buffer.from(firstSource) })
  await expect(summary).toContainText('Version 1.0')
  await expect(summary).toContainText('Original file')
  await upload.setInputFiles({ name: FILENAME, mimeType: 'application/json', buffer: Buffer.from(secondSource) })
  await expect(summary).toContainText('Version 1.1')
  await page.reload()
  const firstOption = files.locator('option').filter({ hasText: 'Version 1.0' })
  const secondOption = files.locator('option').filter({ hasText: 'Version 1.1' })
  await expect(firstOption).toContainText('Synthetic external mod')
  await expect(secondOption).toContainText('Synthetic external mod')
  await files.selectOption((await firstOption.getAttribute('value'))!)
  await selectPath(page, '$.Title')
  await page.getByRole('textbox', { name: /^Exact JSON value/ }).fill('"Renamed working copy"')
  await page.getByRole('button', { name: 'Apply JSON edit', exact: true }).click()
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await expect(summary).toContainText('Renamed working copy')
  await expect(summary).toContainText('Edited copy')
  await expect(firstOption).toContainText('Renamed working copy')
  await expect(firstOption).toContainText('Edited copy')
  expect(await downloadText(page, 'Download original')).toBe(firstSource)
  await files.selectOption((await secondOption.getAttribute('value'))!)
  await expect(summary).toContainText('Synthetic external mod')
  await expect(summary).toContainText('Original file')
  expect(await downloadText(page, 'Download original')).toBe(secondSource)
  expect(await plannerCounts()).toEqual(before)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width)
})
