import { expect, test } from '@playwright/test'
import { MOBILE_TEST_TAG } from './test-tags'
import { expectOfflineReady } from './offline-helpers'
import { importSyntheticLibrary, syntheticReferencePath } from './mod-library-fixtures'
import { referencePath } from './reference-helpers'

test('an imported model sharing a native ID does not acquire unrelated artwork or source proof', async ({ page }) => {
  await importSyntheticLibrary(page)
  await page.goto(syntheticReferencePath(0, 'Equipment', 0, 'Synthetic Blade'))
  await expect(page.getByRole('heading', { name: 'Synthetic Blade', exact: true })).toBeVisible()
  await expect(page.locator('[data-artwork-source="game"]')).toHaveCount(0)
  await expect(page.locator('[data-artwork-source="mod"]')).toHaveCount(0)
  await page.getByRole('button', { name: 'Sources for Synthetic Blade', exact: true }).click()
  const sources = page.getByRole('dialog', { name: 'Sources for Synthetic Blade', exact: true })
  await expect(sources).toContainText('Equipment #0')
  await expect(sources).not.toContainText('Native source record')
  await page.keyboard.press('Escape')
  await page.goto(referencePath('base:equipment:0'))
  const native = page.getByRole('img', { name: 'Short Sword game artwork', exact: true })
  await expect(native).toBeVisible()
  await expect.poll(() => native.evaluate(element => (element as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
})

test('an imported class without verified artwork remains selectable and saved offline', { tag: MOBILE_TEST_TAG }, async ({ page, context }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await importSyntheticLibrary(page)
  await page.goto(syntheticReferencePath(1, 'Jobs', 26, 'Synthetic Class'))
  await expect(page.getByRole('heading', { name: 'Synthetic Class', exact: true })).toBeVisible()
  await expect(page.locator('[data-artwork-source="mod"]')).toHaveCount(0)
  await page.goto('/#/builds/library/new')
  const field = page.getByRole('combobox', { name: 'Class', exact: true })
  await field.fill('Synthetic Class')
  const option = page.getByRole('listbox', { name: 'Choose Class', exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: /^Synthetic Class$/ }) })
  await expect(option.locator('[data-artwork-source="game"]')).toHaveCount(0)
  await option.click()
  await page.getByRole('dialog', { name: 'Enable Synthetic Moonlight?', exact: true }).getByRole('button', { name: 'Enable and select Synthetic Class', exact: true }).click()
  await expect(field).toHaveValue('Synthetic Class')
  await page.getByLabel('Build title', { exact: true }).fill('Synthetic mod artwork build')
  await page.getByRole('button', { name: 'Save build', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Save new revision', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  await settings.getByRole('button', { name: 'Prepare for offline use', exact: true }).click()
  await expectOfflineReady(settings)
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true); await page.reload()
  await expect(page.getByRole('heading', { name: 'Synthetic mod artwork build', exact: true })).toBeVisible()
  await expect(field).toHaveValue('Synthetic Class')
  await expect(page.locator('.build-field__artwork [data-artwork-source="game"]')).toHaveCount(0)
  await page.goto(syntheticReferencePath(1, 'Jobs', 26, 'Synthetic Class'))
  await expect(page.getByRole('heading', { name: 'Synthetic Class', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})
