import { expect, test } from '@playwright/test'
import { referencePath, referenceUrlPattern } from './reference-helpers'
import { MOBILE_TEST_TAG } from './test-tags'

test('native effects lead the page while original claims remain available', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await page.goto(referencePath('base:item:132'))
  await expect(page.locator('.reference-detail .reference-description')).toContainText(/missing HP/i)
  await expect(page.locator('.reference-detail .reference-description')).not.toContainText('Recovery: 100% HP')
  const facts = page.getByRole('region', { name: 'Definition facts', exact: true })
  await expect(facts.locator('.definition-row').filter({ has: page.getByText('Effect', { exact: true }) })).toContainText(/missing HP/i)
  await expect(facts).not.toContainText('Sources differ')
  await page.getByRole('button', { name: 'Sources for Shoudu Stew', exact: true }).click()
  const originalClaims = page.getByText('Original field claims', { exact: true }).locator('..')
  await originalClaims.locator(':scope > summary').click()
  await expect(originalClaims.getByText('Single target. Recovery 100% missing HP.', { exact: true })).toBeVisible()
  await expect(originalClaims.getByText('Single target. Recovery: 100% HP', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('native effects and readable strategy descriptions are visible together', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await page.goto(referencePath('base:equipment:134'))
  await expect(page.getByRole('region', { name: 'Game details', exact: true })).toHaveCount(0)
  const description = page.locator('.reference-detail .reference-description')
  await expect(description.locator(':scope > p')).toContainText(/Resistance:\s*\+78/)
  await expect(description.locator(':scope > p')).toContainText(/Max\. MP:\s*\+20/)
  await expect(description.locator(':scope > p')).toContainText('Take 5% less magical damage.')
  const narrative = description.getByRole('region', { name: 'Description', exact: true })
  await expect(narrative.getByRole('heading', { name: 'Description', exact: true })).toBeVisible()
  await expect(narrative.getByText(/It can be useful to light armor wearers/)).toBeVisible()
  await expect(narrative).toContainText("It can be useful to light armor wearers who don't need Mind or Spirit, such as Chemists.")
  await expect(narrative).toContainText('before reaching the Chemist crystal')
  const facts = page.getByRole('region', { name: 'Definition facts', exact: true })
  const type = facts.locator('.definition-row').filter({ has: page.getByText('Equipment Type', { exact: true }) })
  await expect(type).toContainText('Light armor')
  await expect(type.locator('.sources-trigger')).toHaveCount(0)
  await expect(facts.locator('dt').filter({ hasText: /^Type$/ })).toHaveCount(0)
  const mp = facts.locator('.definition-row').filter({ has: page.locator('dt').filter({ hasText: /^Max MP$/ }) })
  await expect(mp.locator('dd')).toHaveText('20')
  await expect(mp.locator('.sources-trigger')).toHaveCount(0)
  await expect(facts.locator('dt').filter({ hasText: /^(Stat|Stat bonuses|Effect|Other effects)$/ })).toHaveCount(0)
  await narrative.getByRole('button', { name: 'Sources for Description', exact: true }).click()
  const descriptionSources = page.getByRole('dialog', { name: 'Sources for Description', exact: true })
  await expect(descriptionSources.locator('a[href*="/wiki/Dress?"]').first()).toBeVisible()
  await expect(descriptionSources).not.toContainText('Native game data')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Sources for Dress', exact: true }).click()
  const sources = page.getByRole('dialog', { name: 'Sources for Dress', exact: true })
  await expect(sources).not.toContainText('Original source description')
  await sources.getByText('Original description fields', { exact: true }).click()
  await expect(sources).not.toContainText('before reaching the Chemist crystal')
  await expect(sources.locator('a[href*="/wiki/Dress?"]').first()).toBeVisible()
  const originalFacts = sources.getByText('Original equipment fields', { exact: true }).locator('..')
  await originalFacts.locator(':scope > summary').click()
  await expect(originalFacts.getByText('Maximum MP +20', { exact: true })).toBeVisible()
  await expect(originalFacts.getByText('Reduce Magical Damage by 5%', { exact: true })).toBeVisible()
})

test('verified source alternatives navigate to native definitions without changing the original URL', async ({ page }) => {
  await page.goto(referencePath('base:recipe:ref-933'))
  await page.getByRole('button', { name: 'Sources for Fursuit', exact: true }).click()
  const counterpart = page.getByRole('button', { name: /View .* game definition/ })
  await expect(counterpart).toBeVisible()
  await counterpart.click()
  await expect(page).toHaveURL(referenceUrlPattern('base:recipe:36'))
  await page.getByRole('button', { name: 'Sources for Fursuit', exact: true }).click()
  await page.getByText('Related source entries', { exact: true }).click()
  await expect(page.getByRole('button', { name: 'Fursuit', exact: true })).toBeVisible()
})

test('a real acquisition disagreement remains visible alongside native routes', async ({ page }) => {
  await page.goto(referencePath('base:equipment:589'))
  await expect(page.getByRole('region', { name: 'How to obtain', exact: true })).toContainText('Steal')
  await page.getByRole('button', { name: 'Sources for Ember Scythe', exact: true }).click()
  await expect(page.getByText('Acquisition sources differ', { exact: true })).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Sources for Ember Scythe', exact: true })).toContainText('Red Guardian')
  await page.keyboard.press('Escape')
  await page.getByRole('combobox', { name: 'Game mode', exact: true }).selectOption('chaos')
  await expect(page.getByRole('region', { name: 'Definition facts', exact: true })).toContainText('Red Guardian')
  await page.getByRole('button', { name: 'Sources for Ember Scythe', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Sources for Ember Scythe', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Sources for Ember Scythe', exact: true }).getByText('Acquisition sources differ', { exact: true })).toHaveCount(0)
})

test('changing acquisition mode retains notes that have no reviewed replacement in that mode', async ({ page }) => {
  await page.goto(referencePath('base:item:132'))
  const facts = page.getByRole('region', { name: 'Definition facts', exact: true })
  await expect(facts).not.toContainText('Can be purchased from Shoudu Province.')
  await page.getByRole('combobox', { name: 'Game mode', exact: true }).selectOption('chaos')
  await expect(facts).toContainText('Can be purchased from Shoudu Province.')
  await expect(page.getByRole('region', { name: 'How to obtain', exact: true })).not.toContainText('Additional acquisition guidance')
})

test('external descriptions cite their own text without duplicating matching fact markers', async ({ page }) => {
  await page.goto(referencePath('base:item:168'))
  await expect(page.locator('.reference-description')).toContainText('Quintar')
  await expect(page.getByRole('button', { name: 'Sources for Description', exact: true })).toHaveCount(1)
  await expect(page.getByRole('region', { name: 'Definition facts', exact: true }).locator('dt').filter({ hasText: /^Description$/ })).toHaveCount(0)
  await page.goto(referencePath('base:item:ref-61'))
  const hero = page.locator('.reference-description')
  await expect(hero).toContainText('Chance for loot to drop is increased by 50%')
  await hero.getByRole('button', { name: 'Sources for Description', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Sources for Description', exact: true }).locator('a[href*="/wiki/Accessories/table?"]').first()).toBeVisible()
})
