import { openBuildPickerFilters } from './build-picker-helpers'
import { MOBILE_TEST_TAG } from './test-tags'
import { currentReferencePath, referencePath } from './reference-helpers'
import { expectOfflineReady } from './offline-helpers'
import { expect, test } from '@playwright/test'

const SLIME_PATH = referencePath('base:monster:2')
const NEW_TAB_REFERENCE_READY_TIMEOUT_MS = 20_000

test('enemy rewards use coins, technical details use integers, and source prices remain readable', async ({ page }) => {
  await page.goto(referencePath('base:monster:179'))
  await expect(page.locator('.enemy-rewards').getByRole('img', { name: '2 gold', exact: true })).toBeVisible()
  await expect(page.locator('.enemy-rewards')).not.toContainText('20000')
  await page.getByText('Technical details', { exact: false }).click()
  const money = page.getByRole('region', { name: 'Definition facts', exact: true }).locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^Money \(copper\)$/ }) })
  await expect(money.locator('dd')).toHaveText('20000')
  await expect(money.locator('.money-amount')).toHaveCount(0)
  await expect(page.getByText('Complete native source record', { exact: true })).toHaveCount(0)
  await page.goto(referencePath('base:item:1'))
  const cost = page.getByRole('region', { name: 'Definition facts', exact: true }).locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^Cost \(copper\)$/ }) })
  await expect(cost.getByRole('img', { name: '2 silver, 50 copper', exact: true })).toBeVisible()

})

test('same-name enemies remain distinct while mode variants are opt-in in global search', async ({ page }) => {
  await page.goto('/#/reference/search?q=woke%20qui')
  const search = page.getByRole('dialog', { name: 'Search CryKit', exact: true })
  const enemies = search.getByRole('link').filter({ has: page.locator('strong', { hasText: /^Woke Quintar(?: \((?:Chaos|Vanilla) mode\))?$/ }) })
  await expect(enemies).toHaveCount(2)
  const reserve = enemies.filter({ hasText: 'Level 54' })
  const overpass = enemies.filter({ hasText: 'Level 63' })
  await expect(reserve).toContainText('Quintar Reserve')
  await expect(reserve).toContainText('Record #179')
  await expect(overpass).toContainText('Overpass')
  await expect(overpass).toContainText('Record #318')
  await expect(reserve).toHaveAttribute('href', currentReferencePath('base:monster:179').slice(1))
  await expect(overpass).toHaveAttribute('href', currentReferencePath('base:monster:318').slice(1))
  await search.getByLabel('Include other sources and mode variants', { exact: true }).check()
  await expect(enemies).toHaveCount(6)
  await expect(enemies.filter({ hasText: 'Chaos mode' })).toHaveCount(2)
  await expect(enemies.filter({ hasText: 'Vanilla mode' })).toHaveCount(2)
  await search.getByLabel('Include other sources and mode variants', { exact: true }).uncheck()
  await expect(enemies).toHaveCount(2)
  await reserve.click()
  await expect(page.getByRole('heading', { name: 'Woke Quintar', exact: true })).toBeVisible()
  await expect(page.locator('.enemy-vitals')).toContainText('54')
})

test('enemy loot preserves modified clicks, opens a new tab, and navigates in app', async ({ page, context }) => {
  await page.goto(referencePath('base:monster:179'))
  const cookiePath = referencePath('base:item:205')
  const cookie = page.getByRole('region', { name: 'Steals', exact: true }).getByRole('link', { name: 'Quintar Cookie', exact: true })
  await expect(cookie).toHaveAttribute('href', cookiePath.slice(1))
  // Observe after React's delegated handler so a cancelled native click fails the test
  await cookie.evaluate(link => {
    const recordClick = (event: MouseEvent) => {
      if (!(event.target instanceof Node) || !link.contains(event.target)) return
      link.dataset.modifiedClick = `${event.ctrlKey || event.metaKey}:${event.defaultPrevented}`
      document.removeEventListener('click', recordClick)
    }
    document.addEventListener('click', recordClick)
  })
  const modifiedTabOpened = context.waitForEvent('page')
  await cookie.click({ modifiers: ['ControlOrMeta'] })
  const modifiedTab = await modifiedTabOpened
  await expect(cookie).toHaveAttribute('data-modified-click', 'true:false')
  await expect(page.getByRole('heading', { name: 'Woke Quintar', exact: true })).toBeVisible()
  await expect(modifiedTab).toHaveURL(new RegExp(`${cookiePath}$`), { timeout: NEW_TAB_REFERENCE_READY_TIMEOUT_MS })
  await modifiedTab.close()
  const opened = context.waitForEvent('page')
  await cookie.click({ button: 'middle' })
  const tab = await opened
  await expect(tab).toHaveURL(new RegExp(`${cookiePath}$`), { timeout: NEW_TAB_REFERENCE_READY_TIMEOUT_MS })
  // A new tab can finish navigation before its catalog detail renders
  await expect(tab.getByRole('heading', { name: 'Quintar Cookie', exact: true })).toBeVisible({ timeout: NEW_TAB_REFERENCE_READY_TIMEOUT_MS })
  await expect(page.getByRole('heading', { name: 'Woke Quintar', exact: true })).toBeVisible()
  await tab.close()
  await cookie.click()
  await expect(page.getByRole('heading', { name: 'Quintar Cookie', exact: true })).toBeVisible()
})

test('native enemy facts, separate steal rates, identity links, and offline scope are readable', { tag: MOBILE_TEST_TAG }, async ({ page, context }, testInfo) => {
  await page.goto(SLIME_PATH)
  await expect(page.getByRole('heading', { name: 'Slime', exact: true })).toBeVisible()
  const details = page.getByRole('region', { name: 'Game details', exact: true })
  await expect(page.locator('.reference-card__meta')).toContainText('Windows 1.6.9')
  const facts = page.getByRole('region', { name: 'Definition facts', exact: true })
  await expect(facts.locator('.sources-trigger')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Refine', exact: true })).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Planning fields', exact: true })).toHaveCount(0)
  await expect(page.locator('.enemy-vitals')).toContainText('50')
  await expect(page.locator('.enemy-vitals')).toContainText('40')
  expect(await page.locator('.enemy-vitals').evaluate(element => element.getBoundingClientRect().bottom < innerHeight - 66)).toBe(true)
  await expect(page.locator('.enemy-technical')).not.toHaveAttribute('open')
  await details.getByText('Technical details', { exact: false }).click()
  const sourceTrigger = page.getByRole('button', { name: 'Sources for Slime', exact: true })
  const sourceTrail = page.getByRole('dialog', { name: 'Sources for Slime', exact: true })
  await expect(sourceTrail).toHaveCount(0)
  await sourceTrigger.click()
  await sourceTrail.getByText('Related source entries', { exact: true }).click()
  await expect(sourceTrail.getByRole('button', { name: 'Slime', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(sourceTrail).toHaveCount(0)
  await expect(sourceTrigger).toBeFocused()
  await expect(details.getByText(/fingerprint|executable SHA-256/)).toHaveCount(0)
  await expect(details).not.toContainText('Native monster #2')
  const steals = details.getByRole('region', { name: 'Steals', exact: true })
  await expect(steals.getByRole('link', { name: 'Tonic', exact: true })).toBeVisible()
  await expect(steals.getByRole('columnheader', { name: 'Availability', exact: true })).toHaveCount(1)
  await expect(steals.getByRole('cell', { name: '75%', exact: true })).toBeVisible()
  await expect(steals.getByRole('columnheader', { name: 'Success', exact: true })).toHaveCount(1)
  await expect(steals.getByRole('cell', { name: '60%', exact: true })).toBeVisible()
  await details.getByText('Related definitions', { exact: true }).click()
  await expect(details.getByRole('link', { name: 'Tonic (item #18)', exact: true })).toHaveCount(2)
  await page.screenshot({ path: testInfo.outputPath('native-enemy-facts.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await details.getByRole('link', { name: 'Tonic (item #18)', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Tonic', exact: true })).toBeVisible()
  await expect(page.getByText('Complete native source record', { exact: true })).toHaveCount(0)
  await page.goto(SLIME_PATH)
  await page.getByRole('combobox', { name: 'Game mode', exact: true }).selectOption({ label: 'Vanilla' })
  await page.getByRole('combobox', { name: 'Difficulty', exact: true }).selectOption({ label: 'Easy' })
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  await settings.getByRole('button', { name: 'Prepare for offline use', exact: true }).click()
  await expectOfflineReady(settings)
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.reload()
  await expect(details.getByRole('region', { name: 'Steals', exact: true })).toContainText('75%')
  await expect(page.locator('.enemy-technical')).not.toHaveAttribute('open')
  await expect(page.getByRole('heading', { name: 'Slime', exact: true })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Game mode', exact: true })).toHaveValue('vanilla')
  await expect(page.getByRole('combobox', { name: 'Difficulty', exact: true })).toHaveValue('1')
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('40')
  await page.getByRole('combobox', { name: 'Game mode', exact: true }).selectOption({ label: 'Chaos' })
  await expect(page.getByRole('heading', { name: 'Slime (Chaos mode)', exact: true })).toBeVisible()
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('10')
  await page.reload()
  await expect(page.getByRole('combobox', { name: 'Game mode', exact: true })).toHaveValue('chaos')
  await expect(page.getByRole('combobox', { name: 'Difficulty', exact: true })).toHaveValue('1')
  await expect(page.locator('.enemy-metric--hp dd')).toHaveText('10')
})

test('enemy actions and issue reporting stay reachable without crowding the bestiary', async ({ page }) => {
  await page.goto(SLIME_PATH)
  const actions = page.getByRole('region', { name: 'Actions', exact: true })
  await expect(actions.getByRole('link', { name: 'Attack', exact: true })).toBeVisible()
  await expect(actions).toContainText('No additional conditions')
  await actions.getByRole('link', { name: 'Attack', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Attack', exact: true })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'Slime', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Actions', exact: true }).click()
  const menu = page.getByRole('dialog', { name: 'Reference actions', exact: true })
  await expect(menu).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(menu).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Actions', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Actions', exact: true }).click()
  await expect(menu.getByRole('link', { name: 'Report a data issue', exact: true })).toHaveAttribute('href', 'https://github.com/j-256/crykit/issues')
  await expect(menu.getByRole('button', { name: /edit|personal version/i })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(page.locator('.enemy-technical')).not.toHaveAttribute('open')
})

test('bestiary entries retain zero values and keep large boss rewards on one line', { tag: MOBILE_TEST_TAG }, async ({ page }, testInfo) => {
  await page.goto(referencePath('base:monster:0'))
  await expect(page.getByRole('heading', { name: 'Dummy', exact: true })).toBeVisible()
  await expect(page.locator('.enemy-vitals dd').filter({ hasText: /^0$/ })).toHaveCount(2)
  await expect(page.locator('.enemy-rewards dd').filter({ hasText: /^0$/ })).toHaveCount(3)
  await expect(page.getByRole('region', { name: 'Drops', exact: true })).toContainText('None listed in this record.')
  await expect(page.getByRole('region', { name: 'Steals', exact: true })).toContainText('None listed in this record.')
  await page.setViewportSize({ width: 320, height: 800 })
  await page.goto(referencePath('base:monster:201'))
  await expect(page.getByRole('heading', { name: 'Akamanto', exact: true })).toBeVisible()
  await expect(page.locator('.enemy-vitals')).toContainText('27000')
  await expect(page.locator('.enemy-rewards').getByRole('img', { name: '8 gold', exact: true })).toBeVisible()
  expect(await page.locator('.enemy-metric[data-numeric] dd').evaluateAll(elements => elements.every(element => element.scrollWidth <= element.clientWidth))).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('native-boss-narrow.png'), fullPage: true })
})

test('legacy build pickers prefer the native base and retain one reconciled Cure identity', async ({ page }) => {
  await page.goto('/#/builds/library')
  await page.getByRole('button', { name: 'Mira: sample Cleric', exact: true }).click()
  await page.getByRole('combobox', { name: 'Class', exact: true }).fill('Cleric')
  const classes = page.getByRole('listbox', { name: 'Choose Class', exact: true })
  const cleric = classes.getByRole('option').filter({ hasText: 'Windows 1.6.9' }).filter({ has: page.locator('strong', { hasText: /^Cleric$/ }) })
  await expect(cleric).toHaveCount(1)
  await expect(cleric).toContainText('Windows 1.6.9')
  await cleric.click()
  await page.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  await page.getByText('Ability and hit-chance preview', { exact: true }).click()
  await page.getByRole('combobox', { name: 'Preview ability', exact: true }).fill('Cure')
  const abilities = page.getByRole('listbox', { name: 'Choose Preview ability', exact: true })
  const cure = abilities.getByRole('option').filter({ hasText: 'Windows 1.6.9' }).filter({ has: page.locator('strong', { hasText: /^Cure(?: \(Vanilla mode\))?$/ }) })
  await expect(cure).toHaveCount(1)
  await expect(cure).toContainText('Windows 1.6.9')
  await openBuildPickerFilters(page)
  await abilities.getByText('Broader planning options', { exact: true }).click()
  await page.getByLabel('Include other sources and mode variants', { exact: true }).check()
  await expect(cure).toHaveCount(1)
  await cure.click()
  const costs = page.getByLabel('Effective ability costs', { exact: true })
  await expect(costs).toBeVisible()
  await expect(costs).toContainText('MP cost')
  await page.locator('summary').filter({ hasText: /^Formula reference$/ }).click()
  const ability = page.getByLabel('Ability estimate', { exact: true })
  await expect(ability.getByRole('heading', { name: 'Cure', exact: true })).toBeVisible()
  await expect(ability.locator('dt').filter({ hasText: /^Power coefficient$/ }).locator('..').locator('dd')).toHaveText(/^-\d[\d,]*$/)
})

test('new native loot icons, status cells, and distinct enemy sprites stay available offline', { tag: MOBILE_TEST_TAG }, async ({ page, context }) => {
  const expectImage = async (name: string) => {
    const image = page.getByRole('img', { name: `${name} game artwork`, exact: true })
    await expect(image).toBeVisible()
    await expect.poll(() => image.evaluate(element => (element as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
    expect(await image.evaluate(element => new URL((element as HTMLImageElement).src).origin === location.origin)).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    return image.getAttribute('src')
  }
  await page.goto(referencePath('base:monster:179'))
  const redSprite = await expectImage('Woke Quintar')
  expect(await page.getByRole('img', { name: 'Woke Quintar game artwork', exact: true }).evaluate(element => {
    const image = element as HTMLImageElement
    const bounds = image.getBoundingClientRect()
    return Math.abs(bounds.width / bounds.height - image.naturalWidth / image.naturalHeight)
  })).toBeLessThan(0.02)
  const eye = page.getByRole('region', { name: 'Drops', exact: true }).getByRole('link', { name: 'Woke Quintar Eye', exact: true })
  await eye.scrollIntoViewIfNeeded()
  await expect(eye.locator('[data-artwork-source="native"] img')).toHaveCount(1)
  await expect.poll(() => eye.locator('img').evaluate(element => (element as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  await eye.click()
  await expectImage('Woke Quintar Eye')
  await expect(page.getByText('Artwork source', { exact: true })).toHaveCount(0)
  await expect(page.getByText(/fingerprint|item\.dat record|Icon\/ItemC/)).toHaveCount(0)
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  const prepare = settings.getByRole('button', { name: 'Prepare for offline use', exact: true })
  if (await prepare.isVisible()) await prepare.click()
  await expectOfflineReady(settings)
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.reload()
  await expectImage('Woke Quintar Eye')
  await page.goto(referencePath('base:status:0'))
  await expectImage('Poison')
  await page.goto(referencePath('base:monster:318'))
  expect(await expectImage('Woke Quintar')).not.toBe(redSprite)
  await page.goto(referencePath('base:monster:179:mode:Chaos'))
  expect(await expectImage('Woke Quintar')).toBe(redSprite)
})
