import { expectOfflineReady } from './offline-helpers'
import { expect, test } from '@playwright/test'

const SLIME_PATH = '/#/reference/catalog/crystal-project-public-starter/revisions/native-v1/entities/native%3Abase%3Amonster%3A2'

test('enemy rewards and item costs share coin denominations while editing keeps copper values', async ({ page }) => {
  await page.goto(SLIME_PATH.replace('monster%3A2', 'monster%3A179'))
  await expect(page.locator('.enemy-rewards').getByRole('img', { name: '2 gold', exact: true })).toBeVisible()
  await expect(page.locator('.enemy-rewards')).not.toContainText('20000')
  await page.getByText('Technical details', { exact: false }).click()
  const money = page.getByRole('region', { name: 'Definition facts', exact: true }).locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^Money \(copper\)$/ }) })
  await expect(money.getByRole('img', { name: '2 gold', exact: true })).toBeVisible()
  await expect(page.getByText('Complete native source record', { exact: true })).toHaveCount(0)
  await page.goto(SLIME_PATH.replace('native%3Abase%3Amonster%3A2', 'base%3Aitem%3Aether'))
  const cost = page.getByRole('region', { name: 'Definition facts', exact: true }).locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^Cost \(copper\)$/ }) })
  await expect(cost.getByRole('img', { name: '2 silver, 50 copper', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Quick edit', exact: true }).click()
  await cost.getByRole('button', { name: 'Edit Cost (copper)', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'New Cost (copper)', exact: true })).toHaveText('250')
})

test('same-name enemies remain distinct while mode variants are opt-in in global search', async ({ page }) => {
  await page.goto('/#/reference/search?q=woke%20qui')
  const search = page.getByRole('dialog', { name: 'Search Crystal Companion', exact: true })
  const enemies = search.getByRole('link').filter({ has: page.locator('strong', { hasText: /^Woke Quintar$/ }) })
  await expect(enemies).toHaveCount(2)
  const reserve = enemies.filter({ hasText: 'Level 54' })
  const overpass = enemies.filter({ hasText: 'Level 63' })
  await expect(reserve).toContainText('Quintar Reserve')
  await expect(reserve).toContainText('Record #179')
  await expect(overpass).toContainText('Overpass')
  await expect(overpass).toContainText('Record #318')
  await expect(reserve).toHaveAttribute('href', /monster%3A179$/)
  await expect(overpass).toHaveAttribute('href', /monster%3A318$/)
  await search.getByLabel('Include other sources and mode variants', { exact: true }).check()
  await expect(enemies).toHaveCount(6)
  await expect(enemies.filter({ hasText: 'Chaos override' })).toHaveCount(2)
  await expect(enemies.filter({ hasText: 'Vanilla override' })).toHaveCount(2)
  await search.getByLabel('Include other sources and mode variants', { exact: true }).uncheck()
  await expect(enemies).toHaveCount(2)
  await reserve.click()
  await expect(page.getByRole('heading', { name: 'Woke Quintar', exact: true })).toBeVisible()
  await expect(page.locator('.enemy-vitals')).toContainText('54')
})

test('enemy loot supports modifier-click in a new tab and ordinary in-app navigation', async ({ page, context }) => {
  await page.goto(SLIME_PATH.replace('monster%3A2', 'monster%3A179'))
  const cookie = page.getByRole('region', { name: 'Steals', exact: true }).getByRole('link', { name: 'Quintar Cookie', exact: true })
  await expect(cookie).toHaveAttribute('href', /^#\/reference\/catalog\//)
  const opened = context.waitForEvent('page')
  await cookie.click({ modifiers: ['ControlOrMeta'] })
  const tab = await opened
  await expect(tab.getByRole('heading', { name: 'Quintar Cookie', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Woke Quintar', exact: true })).toBeVisible()
  await tab.close()
  await cookie.click()
  await expect(page.getByRole('heading', { name: 'Quintar Cookie', exact: true })).toBeVisible()
})

test('native enemy facts, separate steal rates, identity links, and offline scope are readable', async ({ page, context }, testInfo) => {
  await page.goto(SLIME_PATH)
  await expect(page.getByRole('heading', { name: 'Slime', exact: true })).toBeVisible()
  const details = page.getByRole('region', { name: 'Game details', exact: true })
  await expect(page.locator('.reference-card__meta')).toContainText('Windows 1.6.9')
  const facts = page.getByRole('region', { name: 'Definition facts', exact: true })
  await expect(facts.locator('summary').filter({ hasText: /^Sources$/ })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Refine', exact: true })).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Planning fields', exact: true })).toHaveCount(0)
  await expect(page.locator('.enemy-vitals')).toContainText('50')
  await expect(page.locator('.enemy-vitals')).toContainText('40')
  expect(await page.locator('.enemy-vitals').evaluate(element => element.getBoundingClientRect().bottom < innerHeight - 66)).toBe(true)
  await expect(page.locator('.enemy-technical')).not.toHaveAttribute('open')
  await details.getByText('Technical details', { exact: false }).click()
  await page.getByText('Source and version details', { exact: true }).click()
  await expect(page.getByRole('region', { name: 'Source trail', exact: true })).toContainText('Switch 1.6.6')
  await expect(details).not.toContainText('Native monster #2')
  const steals = details.getByRole('region', { name: 'Steals', exact: true })
  await expect(steals.getByRole('link', { name: 'Tonic', exact: true })).toBeVisible()
  await expect(steals.getByRole('columnheader', { name: 'Availability', exact: true })).toHaveCount(1)
  await expect(steals.getByRole('cell', { name: '75%', exact: true })).toBeVisible()
  await expect(steals.getByRole('columnheader', { name: 'Success', exact: true })).toHaveCount(1)
  await expect(steals.getByRole('cell', { name: '60%', exact: true })).toBeVisible()
  await details.getByText('Related definitions', { exact: true }).click()
  await expect(details.getByRole('link', { name: 'Tonic (item #18)', exact: true })).toHaveCount(2)
  await page.screenshot({ path: testInfo.outputPath('native-enemy-facts.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await details.getByRole('link', { name: 'Tonic (item #18)', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Tonic', exact: true })).toBeVisible()
  await expect(page.getByText('Complete native source record', { exact: true })).toHaveCount(0)
  await page.goto(SLIME_PATH)
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  await settings.getByRole('button', { name: 'Prepare for offline use', exact: true }).click()
  await expectOfflineReady(settings)
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.reload()
  await expect(details.getByRole('region', { name: 'Steals', exact: true })).toContainText('75%')
  await expect(page.locator('.enemy-technical')).not.toHaveAttribute('open')
  await expect(page.getByRole('heading', { name: 'Slime', exact: true })).toBeVisible()
})

test('enemy actions and editing stay reachable without crowding the bestiary', async ({ page }) => {
  await page.goto(SLIME_PATH)
  const actions = page.getByRole('region', { name: 'Actions', exact: true })
  await expect(actions.getByRole('link', { name: 'Attack', exact: true })).toBeVisible()
  await expect(actions).toContainText('No additional conditions')
  await actions.getByRole('link', { name: 'Attack', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Attack', exact: true })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'Slime', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Actions', exact: true }).click()
  const menu = page.getByRole('dialog', { name: 'Reference actions', exact: true })
  await expect(menu).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(menu).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Actions', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Actions', exact: true }).click()
  await menu.getByRole('button', { name: 'Quick edit', exact: true }).click()
  const facts = page.getByRole('region', { name: 'Definition facts', exact: true })
  const hp = facts.locator('.definition-row').filter({ has: page.locator('dt', { hasText: /^HP$/ }) })
  await hp.getByRole('button', { name: 'Edit HP', exact: true }).click()
  const form = page.getByRole('form', { name: 'Correct HP in place', exact: true })
  await form.getByRole('textbox', { name: 'New HP', exact: true }).fill('55')
  await form.getByRole('button', { name: 'Save', exact: true }).click()
  await page.getByRole('button', { name: 'Done editing', exact: true }).click()
  await expect(page.locator('.enemy-vitals')).toContainText('55')
  await page.reload()
  await expect(page.locator('.enemy-vitals')).toContainText('55')
  await expect(page.locator('.enemy-technical')).not.toHaveAttribute('open')
})

test('bestiary entries retain zero values and keep large boss rewards on one line', async ({ page }, testInfo) => {
  await page.goto(SLIME_PATH.replace('monster%3A2', 'monster%3A0'))
  await expect(page.getByRole('heading', { name: 'Dummy', exact: true })).toBeVisible()
  await expect(page.locator('.enemy-vitals dd').filter({ hasText: /^0$/ })).toHaveCount(2)
  await expect(page.locator('.enemy-rewards dd').filter({ hasText: /^0$/ })).toHaveCount(3)
  await expect(page.getByRole('region', { name: 'Drops', exact: true })).toContainText('None listed in this record.')
  await expect(page.getByRole('region', { name: 'Steals', exact: true })).toContainText('None listed in this record.')
  await page.setViewportSize({ width: 320, height: 800 })
  await page.goto(SLIME_PATH.replace('monster%3A2', 'monster%3A201'))
  await expect(page.getByRole('heading', { name: 'Akamanto', exact: true })).toBeVisible()
  await expect(page.locator('.enemy-vitals')).toContainText('27000')
  await expect(page.locator('.enemy-rewards').getByRole('img', { name: '8 gold', exact: true })).toBeVisible()
  expect(await page.locator('.enemy-metric[data-numeric] dd').evaluateAll(elements => elements.every(element => element.scrollWidth <= element.clientWidth))).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('native-boss-narrow.png'), fullPage: true })
})

test('ordinary planning choices prefer the native base and expose supplemental choices explicitly', async ({ page }) => {
  await page.goto('/#/builds/library/new')
  await page.getByRole('combobox', { name: 'Class', exact: true }).fill('Cleric')
  const classes = page.getByRole('listbox', { name: 'Choose Class', exact: true })
  const cleric = classes.getByRole('option').filter({ has: page.locator('strong', { hasText: /^Cleric$/ }) })
  await expect(cleric).toHaveCount(1)
  await expect(cleric).toContainText('Windows 1.6.9')
  await cleric.click()
  await page.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  await page.getByText('Stats & combat estimates', { exact: true }).click()
  await page.getByText('Ability and hit-chance preview', { exact: true }).click()
  await page.getByRole('combobox', { name: 'Preview ability', exact: true }).fill('Cure')
  const abilities = page.getByRole('listbox', { name: 'Choose Preview ability', exact: true })
  const cure = abilities.getByRole('option').filter({ has: page.locator('strong', { hasText: /^Cure$/ }) })
  await expect(cure).toHaveCount(1)
  await expect(cure).toContainText('Windows 1.6.9')
  await page.getByLabel('Include other sources and mode variants', { exact: true }).check()
  await expect(cure).toHaveCount(2)
})

test('new native loot icons, status cells, and distinct enemy sprites stay available offline', async ({ page, context }) => {
  const nativeDetail = (id: string) => `/#/reference/catalog/crystal-project-public-starter/revisions/native-v1/entities/${encodeURIComponent(id)}`
  const expectImage = async (name: string) => {
    const image = page.getByRole('img', { name: `${name} game artwork`, exact: true })
    await expect(image).toBeVisible()
    await expect.poll(() => image.evaluate(element => (element as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
    expect(await image.evaluate(element => new URL((element as HTMLImageElement).src).origin === location.origin)).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    return image.getAttribute('src')
  }
  await page.goto(nativeDetail('native:base:monster:179'))
  const redSprite = await expectImage('Woke Quintar')
  expect(await page.getByRole('img', { name: 'Woke Quintar game artwork', exact: true }).evaluate(element => {
    const image = element as HTMLImageElement
    const bounds = image.getBoundingClientRect()
    return Math.abs(bounds.width / bounds.height - image.naturalWidth / image.naturalHeight)
  })).toBeLessThan(0.02)
  const eye = page.getByRole('region', { name: 'Drops', exact: true }).getByRole('link', { name: 'Woke Quintar Eye', exact: true })
  await eye.scrollIntoViewIfNeeded()
  await expect(eye.locator('[data-artwork-source="native"] img')).toHaveCount(1)
  await expect.poll(() => eye.locator('img').evaluate(element => (element as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  await eye.click()
  await expectImage('Woke Quintar Eye')
  await page.getByText('Artwork source', { exact: true }).click()
  await expect(page.locator('.wiki-sprite-source')).toContainText('Windows 1.6.9 game files · base database')
  await expect(page.locator('.wiki-sprite-source')).toContainText('item.dat record 28 · Woke Quintar Eye')
  await expect(page.locator('.wiki-sprite-source')).toContainText('Icon/ItemC · crop 70,70 32x32')
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  const prepare = settings.getByRole('button', { name: 'Prepare for offline use', exact: true })
  if (await prepare.isVisible()) await prepare.click()
  await expectOfflineReady(settings)
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.reload()
  await expectImage('Woke Quintar Eye')
  await page.goto(nativeDetail('native:base:status:0'))
  await expectImage('Poison')
  await page.goto(nativeDetail('native:base:monster:318'))
  expect(await expectImage('Woke Quintar')).not.toBe(redSprite)
  await page.goto(nativeDetail('native:Chaos:monster:179'))
  expect(await expectImage('Woke Quintar')).toBe(redSprite)
})
