import { MOBILE_TEST_TAG } from './test-tags'
import { expect, test, type Locator, type Page } from '@playwright/test'
import { createBlankPlaythrough } from './local-data-helpers'

const BACKDROP_VIEWPORT = { width: 1280, height: 900 }

async function activatePoint(page: Page, touch: boolean, point: { x: number; y: number }) {
  if (touch) await page.touchscreen.tap(point.x, point.y)
  else await page.mouse.click(point.x, point.y)
}

async function clickOutside(page: Page, panel: Locator, touch: boolean) {
  const bounds = await panel.boundingBox()
  expect(bounds).not.toBeNull()
  expect(bounds!.x).toBeGreaterThan(0)
  await activatePoint(page, touch, { x: bounds!.x / 2, y: bounds!.y + bounds!.height / 2 })
}

test('backdrop dismissal ignores panel clicks and drags and restores focus without activating the page', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }) => {
  await page.setViewportSize(BACKDROP_VIEWPORT)
  await page.goto('/#/inventory')
  const reference = page.getByRole('button', { name: 'Reference', exact: true }).filter({ visible: true })
  const referenceBounds = await reference.boundingBox()
  expect(referenceBounds).not.toBeNull()
  const outside = { x: referenceBounds!.x + referenceBounds!.width / 2, y: referenceBounds!.y + referenceBounds!.height / 2 }
  const trigger = page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true })
  await trigger.click()
  const panel = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  const heading = panel.getByRole('heading', { name: 'Data & settings', exact: true })
  await heading.click()
  await expect(panel).toBeVisible()
  const headingBounds = await heading.boundingBox()
  expect(headingBounds).not.toBeNull()
  const inside = { x: headingBounds!.x + headingBounds!.width / 2, y: headingBounds!.y + headingBounds!.height / 2 }
  for (const [start, end] of [[inside, outside], [outside, inside]]) {
    await page.mouse.move(start.x, start.y)
    await page.mouse.down()
    await page.mouse.move(end.x, end.y)
    await page.mouse.up()
    await expect(panel).toBeVisible()
  }
  await activatePoint(page, isMobile, outside)
  await expect(panel).not.toBeVisible()
  await expect(page).toHaveURL(/#\/inventory$/)
  await expect(trigger).toBeFocused()
  await expect(page.getByRole('heading', { name: 'Inventory', exact: true })).toBeVisible()
})

test('definition search is ready for typing on opening, reopening, and direct links', async ({ page }) => {
  await page.goto('/#/inventory')
  await page.getByRole('button', { name: 'Add item', exact: true }).click()
  const observation = page.getByRole('dialog', { name: 'Add inventory item', exact: true })
  const trigger = observation.getByRole('button', { name: 'Choose Item definition', exact: true })
  const picker = page.getByRole('dialog', { name: 'Choose Item definition', exact: true })
  const search = picker.getByRole('searchbox', { name: 'Search available definitions', exact: true })
  await trigger.click()
  await expect(search).toBeFocused()
  await page.keyboard.type('Potion')
  await expect(search).toHaveValue('Potion')
  await page.keyboard.press('ArrowDown')
  await expect(picker.locator('[data-definition-result="true"]').first()).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(search).toBeFocused()
  await expect(search).toHaveValue('Potion')
  await page.reload()
  await expect(search).toBeFocused()
  await expect(search).toHaveValue('Potion')
})

test('backdrop dismissal closes only the top layer and respects unsaved definition guards', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }) => {
  await page.setViewportSize(BACKDROP_VIEWPORT)
  await page.goto('/#/inventory/new/pick/item-definition/definitions/new?q=Synthetic')
  const editor = page.getByRole('dialog', { name: 'Create personal definition', exact: true })
  const picker = page.getByRole('dialog', { name: 'Choose Item definition', exact: true })
  const observation = page.getByRole('dialog', { name: 'Add inventory item', exact: true })
  await expect(editor).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.activeElement?.closest('dialog')?.querySelector('h2')?.textContent)).toBe('Create personal definition')
  await editor.getByRole('textbox', { name: 'Definition name', exact: true }).fill('Retain this synthetic definition')
  await clickOutside(page, editor, isMobile)
  await expect(editor.getByText('Definition draft still open', { exact: true })).toBeVisible()
  await expect(editor.getByRole('textbox', { name: 'Definition name', exact: true })).toHaveValue('Retain this synthetic definition')
  await editor.getByRole('button', { name: 'Discard draft', exact: true }).click()
  await expect(editor).not.toBeVisible()
  await expect(picker).toBeVisible()
  await expect(picker.getByRole('searchbox', { name: 'Search available definitions', exact: true })).toHaveValue('Synthetic')
  await picker.getByRole('button', { name: 'Create "Synthetic"', exact: true }).click()
  await expect(editor).toBeVisible()
  await clickOutside(page, editor, isMobile)
  await expect(editor).not.toBeVisible()
  await expect(picker).toBeVisible()
  await expect(page).toHaveURL(/#\/inventory\/new\/pick\/item-definition\?q=Synthetic$/)
  await clickOutside(page, picker, isMobile)
  await expect(picker).not.toBeVisible()
  await expect(observation).toBeVisible()
  await expect(page).toHaveURL(/#\/inventory\/new$/)
})

test('definition dropdowns stay anchored, support keyboard selection, and leave the form usable', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }) => {
  await page.goto('/#/inventory/new')
  const form = page.getByRole('dialog', { name: 'Add inventory item', exact: true })
  const trigger = form.getByRole('button', { name: 'Choose Item definition', exact: true })
  const dropdown = page.getByRole('dialog', { name: 'Choose Item definition', exact: true })
  await trigger.click()
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await expect(dropdown).toHaveAttribute('aria-modal', 'false')
  await expect(page.locator('dialog:modal')).toHaveCount(1)
  const fieldBounds = (await trigger.boundingBox())!
  const popupBounds = (await dropdown.boundingBox())!
  const viewport = page.viewportSize()!
  expect(popupBounds.x).toBeGreaterThanOrEqual(0)
  expect(popupBounds.x + popupBounds.width).toBeLessThanOrEqual(viewport.width)
  expect(popupBounds.y).toBeGreaterThanOrEqual(0)
  expect(popupBounds.y + popupBounds.height).toBeLessThanOrEqual(viewport.height)
  expect(Math.min(Math.abs(popupBounds.y - fieldBounds.y - fieldBounds.height), Math.abs(fieldBounds.y - popupBounds.y - popupBounds.height))).toBeLessThan(10)
  expect(await form.evaluate((element) => getComputedStyle(element, '::backdrop').backdropFilter)).toBe('none')

  const search = dropdown.getByRole('searchbox', { name: 'Search available definitions', exact: true })
  await search.fill('Potion')
  await search.press('Enter')
  await expect(form).toBeVisible()
  await expect(dropdown).toBeVisible()
  await search.press('ArrowDown')
  await page.keyboard.press('ArrowDown')
  const selectedName = await dropdown.locator('[data-definition-result="true"]:focus strong').innerText()
  await page.keyboard.press('Enter')
  await expect(dropdown).not.toBeVisible()
  await expect(trigger).toContainText(selectedName)
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')

  await trigger.click()
  const heading = form.getByRole('heading', { name: 'Add inventory item', exact: true })
  if (isMobile) await heading.tap()
  else await heading.click()
  await expect(dropdown).not.toBeVisible()
  await expect(form).toBeVisible()
  await form.getByRole('combobox', { name: 'Do you own it?', exact: true }).selectOption('owned')
  await expect(form.getByRole('combobox', { name: 'Do you own it?', exact: true })).toHaveValue('owned')
})

test('dropdown scrolling and Tab preserve keyboard access and dialogs are centered', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await page.goto('/#/inventory/new')
  const form = page.getByRole('dialog', { name: 'Add inventory item', exact: true })
  const bounds = (await form.boundingBox())!
  const viewport = page.viewportSize()!
  expect(Math.abs(bounds.x + bounds.width / 2 - viewport.width / 2)).toBeLessThan(2)
  expect(Math.abs(bounds.y + bounds.height / 2 - viewport.height / 2)).toBeLessThan(2)
  expect(bounds.height).toBeLessThan(viewport.height)
  await form.getByRole('button', { name: 'Choose Item definition', exact: true }).click()
  const dropdown = page.getByRole('dialog', { name: 'Choose Item definition', exact: true })
  const search = dropdown.getByRole('searchbox', { name: 'Search available definitions', exact: true })
  await search.press('ArrowUp')
  await expect(dropdown.locator('[data-definition-result="true"]').last()).toBeFocused()
  await page.keyboard.press('Home')
  await expect(dropdown.locator('[data-definition-result="true"]').first()).toBeFocused()
  await search.focus()
  await search.press('Shift+Tab')
  await expect(form.getByRole('button', { name: 'Choose Item definition', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(dropdown).not.toBeVisible()
  await expect(form.getByRole('button', { name: 'Close dialog', exact: true })).toBeFocused()
})

test('class dropdowns switch fields directly and a lower field opens upward', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await page.goto('/#/inventory')
  await createBlankPlaythrough(page)
  await page.goto('/#/characters/new')
  const creation = page.getByRole('dialog', { name: 'Add character', exact: true })
  await creation.getByLabel('Character name').fill('Synthetic dropdown character')
  await creation.getByRole('button', { name: 'Add character', exact: true }).click()
  await page.getByRole('article', { name: 'Synthetic dropdown character', exact: true }).getByRole('link', { name: 'Capture snapshot', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Capture character snapshot', exact: true })
  const primary = form.getByRole('button', { name: 'Choose Primary class', exact: true })
  const secondary = form.getByRole('button', { name: 'Choose Secondary class', exact: true })
  await primary.click()
  const first = page.getByRole('dialog', { name: 'Choose Primary class', exact: true })
  await first.getByRole('searchbox').fill('Knight')
  await secondary.click()
  const second = page.getByRole('dialog', { name: 'Choose Secondary class', exact: true })
  await expect(first).not.toBeVisible()
  await expect(second.getByRole('searchbox')).toBeFocused()
  await expect(page).toHaveURL(/\/pick\/secondary-class$/)
  await page.keyboard.press('Escape')
  await expect(secondary).toBeFocused()
  await expect(form).toBeVisible()
  await primary.click()
  await expect(first.getByRole('searchbox')).toHaveValue('Knight')
  await page.keyboard.press('Escape')
  await form.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.goto('/#/inventory/new')
  const inventory = page.getByRole('dialog', { name: 'Add inventory item', exact: true })
  const trigger = inventory.getByRole('button', { name: 'Choose Item definition', exact: true })
  await trigger.evaluate((element) => { element.closest('.definition-picker-field')!.setAttribute('style', 'margin-top: 250px') })
  await trigger.click()
  const popup = page.getByRole('dialog', { name: 'Choose Item definition', exact: true })
  await popup.waitFor({ state: 'visible' })
  await inventory.locator('.sheet__body').evaluate((element) => { element.scrollTop = 0 })
  await expect.poll(async () => {
    const fieldBounds = (await trigger.boundingBox())!
    const popupBounds = (await popup.boundingBox())!
    return popupBounds.y + popupBounds.height < fieldBounds.y
  }).toBe(true)
  await expect(popup.getByRole('searchbox')).toBeFocused()
})
