import { expect, test } from '@playwright/test'

test('home opens the build library and separates tracking on desktop and touch', async ({ page, isMobile }, testInfo) => {
  if (isMobile) await page.setViewportSize({ width: 320, height: 740 })
  await page.goto('/')
  await expect(page).toHaveURL(/#\/builds\/library$/)
  await expect(page.getByRole('heading', { name: 'Builds', exact: true })).toBeVisible()
  const library = page.getByRole('region', { name: 'Build library', exact: true })
  const warriorButton = page.getByRole('button', { name: /Rowan: sample Warrior/ })
  const warrior = library.getByRole('article').filter({ has: warriorButton })
  await expect(warriorButton).toBeVisible()
  await expect(warrior.locator('.build-card__classes')).toContainText('Warrior')
  const equipment = warrior.locator('.build-card__summary-group').filter({ hasText: 'Equipment' })
  await expect(equipment).toContainText('Short Sword')
  await expect(equipment).toContainText('Buckler')
  await expect(equipment).toContainText('Breastplate')
  await expect(warrior.locator('.build-card__summary-group').filter({ hasText: 'Passives' })).toContainText('No passives selected')
  await expect(warrior.locator('.wiki-sprite img')).toHaveCount(4)
  await expect(page.getByRole('combobox', { name: 'Class', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Profile: Sample playthrough', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /^Scenario:/ })).toHaveCount(0)
  const menu = page.getByRole('navigation', { name: 'Primary navigation', exact: true }).filter({ visible: true })
  await expect(menu.getByRole('button')).toHaveText(['Builds', 'Characters', 'Reference', 'Inventory', 'Progress'])
  await expect(menu.getByRole('group', { name: 'Tracking', exact: true }).getByRole('button')).toHaveText(['Inventory', 'Progress'])
  await expect(menu.getByRole('button', { name: 'Builds', exact: true })).toHaveAttribute('aria-current', 'page')
  if (isMobile) {
    for (const button of await menu.getByRole('button').all()) {
      const bounds = (await button.boundingBox())!
      expect(bounds.height).toBeGreaterThanOrEqual(44)
      expect(bounds.width).toBeGreaterThanOrEqual(44)
    }
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('build-library-navigation.png'), fullPage: true })

  const reference = menu.getByRole('button', { name: 'Reference', exact: true })
  if (isMobile) await reference.tap()
  else await reference.press('Enter')
  await expect(page.getByRole('heading', { name: 'Reference', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /^Scenario:/ })).toHaveCount(0)
  const inventory = menu.getByRole('button', { name: 'Inventory', exact: true })
  if (isMobile) await inventory.tap()
  else await inventory.press('Enter')
  await expect(page.getByRole('heading', { name: 'Inventory', exact: true })).toBeVisible()
  await expect(inventory).toHaveAttribute('aria-current', 'page')
  await expect(page.getByRole('button', { name: 'Scenario: Sample starter team', exact: true })).toBeVisible()
  await page.goBack()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Reference', exact: true })).toBeVisible()
  await expect(reference).toHaveAttribute('aria-current', 'page')
})

test('direct settings return to Builds and saved build tracking requires an explicit choice', async ({ page, isMobile }) => {
  await page.goto('/#/settings/data')
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await expect(settings).toBeVisible()
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await expect(page).toHaveURL(/#\/builds\/library$/)
  await page.getByRole('region', { name: 'Build library', exact: true }).getByRole('button', { name: /Rowan: sample Warrior/ }).click()
  await expect(page.getByRole('combobox', { name: 'Class', exact: true })).toHaveValue('Warrior')
  await expect(page.getByRole('button', { name: 'Record as current', exact: true })).not.toBeVisible()
  const readiness = page.locator('.build-readiness')
  await expect(readiness).not.toHaveAttribute('open')
  if (isMobile) {
    await page.evaluate(() => scrollTo(0, 0))
    await expect(readiness).not.toBeInViewport()
  }
  await readiness.locator('summary').first().click()
  await expect(readiness.getByRole('heading', { name: 'Current readiness', exact: true })).toBeVisible()
  await readiness.getByRole('button', { name: 'Record as current', exact: true }).click()
  const recording = page.getByRole('dialog', { name: 'Record build as current', exact: true })
  await expect(recording.getByRole('button', { name: 'Record as current', exact: true })).toBeDisabled()
  await recording.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(recording).not.toBeVisible()
})
