import { saveAndApplyGameSetup, openCurrentGameSetup, selectedPlaythrough, chooseFourTeamMembers, createBlankPlaythrough, openGameSetupSection } from './local-data-helpers'
import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { strFromU8, unzipSync } from 'fflate'
import type { LocalData } from '../src/domain/types'

async function navigate(page: Page, destination: string) {
  const name = destination === 'Builds' ? /^(Builds|Builds & teams)$/ : new RegExp(`^${destination}$`)
  await page.getByRole('button', { name }).filter({ visible: true }).click()
}

async function openBuildLibrary(page: Page) {
  const library = page.locator('.build-library')
  if (await library.getAttribute('open') === null) await library.locator(':scope > summary').click()
}

async function openData(page: Page) {
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  return page.getByRole('dialog', { name: 'Data & settings', exact: true })
}

async function exportLocalData(page: Page): Promise<LocalData> {
  const panel = await openData(page)
  await panel.getByRole('button', { name: 'Import & backup', exact: true }).click()
  const event = page.waitForEvent('download')
  await panel.getByRole('button', { name: 'Export backup', exact: true }).click()
  const file = await (await event).path()
  if (!file) throw new Error('The backup download did not complete')
  const archive = unzipSync(await readFile(file))
  const payload = JSON.parse(strFromU8(archive['bundle.json']!)) as { localData: LocalData }
  await panel.getByRole('button', { name: 'Close dialog' }).click()
  return payload.localData
}

async function configureGameSetup(page: Page, _slotLabels = ['Main hand']) {
  const panel = await openData(page)
  await openCurrentGameSetup(panel)
  await panel.getByLabel('Game Setup label').fill('Synthetic configuration')
  await panel.getByRole('combobox', { name: 'Difficulty', exact: true }).selectOption('0')
  await saveAndApplyGameSetup(panel)
  await expect(page.getByText('Saved locally', { exact: true })).toBeAttached()
  await panel.getByRole('button', { name: 'Close dialog' }).click()
}

async function addCharacter(page: Page, name: string) {
  await navigate(page, 'Characters')
  await page.getByRole('button', { name: 'Add character', exact: true }).first().click()
  const form = page.getByRole('dialog', { name: 'Add character', exact: true })
  await form.getByLabel('Character name').fill(name)
  await form.getByRole('button', { name: 'Add character', exact: true }).click()
  await expect(form).not.toBeVisible()
  await page.getByRole('article', { name, exact: true }).getByRole('link', { name, exact: true }).click()
}

async function addStock(page: Page) {
  await navigate(page, 'Inventory')
  await page.getByRole('button', { name: 'Add item', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Add inventory item' })
  await form.getByRole('button', { name: 'Enter an unlisted item', exact: true }).click()
  await form.getByLabel('Item name').fill('Synthetic shared staff')
  await form.getByLabel('Current possession').selectOption('owned')
  await form.getByLabel('Quantity certainty').selectOption('exact')
  await form.getByLabel('Current count').fill('1')
  await form.getByRole('button', { name: 'Add item', exact: true }).click()
  await expect(form).not.toBeVisible()
}

test.beforeEach(async ({ page }) => {
  await page.goto('/#/inventory')
  await expect(page.getByRole('heading', { name: 'Inventory', exact: true })).toBeVisible()
  await createBlankPlaythrough(page)
})

test('character, party progress, and historical events remain independent observations', async ({ page }) => {
  await configureGameSetup(page)
  await addCharacter(page, 'Synthetic Rowan')
  await page.getByRole('button', { name: 'Capture snapshot', exact: true }).click()
  const snapshot = page.getByRole('dialog', { name: 'Capture character snapshot' })
  await snapshot.getByLabel('Level certainty', { exact: true }).selectOption('known')
  await snapshot.getByLabel('Level', { exact: true }).fill('20')
  await expect(snapshot.getByLabel('Shared PP capacity', { exact: true })).toHaveCount(0)
  await snapshot.getByRole('button', { name: 'Add stat', exact: true }).click()
  await snapshot.getByLabel('Stat name').fill('Max HP')
  await snapshot.getByLabel('Displayed value certainty', { exact: true }).selectOption('known')
  await snapshot.getByLabel('Displayed value', { exact: true }).fill('321')
  await snapshot.getByLabel('Observed on', { exact: true }).fill('2024-06-15')
  await snapshot.getByRole('button', { name: 'Save snapshot', exact: true }).click()
  await expect(snapshot).not.toBeVisible()

  await expect(page.getByRole('button', { name: 'Skills', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await page.getByRole('combobox', { name: 'Skill type', exact: true }).selectOption('monsterMagic')
  await page.getByRole('button', { name: 'Add spell', exact: true }).click()
  const learning = page.getByRole('dialog', { name: 'Record Monster Magic' })
  await learning.getByRole('button', { name: 'Choose Monster Magic', exact: true }).click()
  const magicPicker = page.getByRole('dialog', { name: 'Choose Monster Magic', exact: true })
  await magicPicker.getByRole('searchbox', { name: 'Search available definitions', exact: true }).fill('Synthetic rain spell')
  await magicPicker.getByRole('button', { name: 'Create "Synthetic rain spell"', exact: true }).click()
  const definition = page.getByRole('dialog', { name: 'Create personal definition', exact: true })
  await expect(definition.getByRole('textbox', { name: 'Definition name', exact: true })).toHaveValue('Synthetic rain spell')
  await definition.getByRole('button', { name: 'Create definition', exact: true }).click()
  await expect(definition).not.toBeVisible()
  await expect(magicPicker).not.toBeVisible()
  await learning.getByRole('combobox', { name: 'Learned', exact: true }).selectOption('true')
  await learning.getByRole('button', { name: 'Save learning', exact: true }).click()
  await expect(learning).not.toBeVisible()
  await page.getByRole('button', { name: 'Edit Synthetic rain spell', exact: true }).click()
  await expect(learning.getByRole('button', { name: 'Choose Monster Magic', exact: true })).toBeDisabled()
  await expect(learning.getByRole('textbox', { name: /New personal .* name/ })).toHaveCount(0)
  await learning.getByRole('button', { name: 'Save learning', exact: true }).click()
  await expect(learning).not.toBeVisible()

  await navigate(page, 'Progress')
  await page.getByRole('button', { name: 'Add other class', exact: true }).click()
  const progress = page.getByRole('dialog', { name: 'Add other class progress' })
  await progress.getByLabel('Class display name').fill('Synthetic pathfinder')
  await progress.getByLabel('Mastery state').selectOption('unlocked')
  await progress.getByLabel('Master location certainty').selectOption('known')
  await progress.getByLabel('Master location', { exact: true }).fill('Synthetic northern camp')
  await progress.getByRole('button', { name: 'Save progress', exact: true }).click()
  await expect(progress).not.toBeVisible()
  const before = await exportLocalData(page)
  await page.locator('.progress-other__row').getByRole('button', { name: 'Details', exact: true }).click()
  const edit = page.getByRole('dialog', { name: 'Edit progress record' })
  await edit.getByLabel('Mastery state').selectOption('sealAcquired')
  await edit.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(edit).not.toBeVisible()
  await expect(page.getByText('Synthetic northern camp', { exact: true })).not.toBeVisible()

  await navigate(page, 'Inventory')
  await page.getByRole('button', { name: 'Record event', exact: true }).first().click()
  const event = page.getByRole('dialog', { name: 'Record acquisition or loss' })
  await event.getByLabel('Item display name').fill('Synthetic past keepsake')
  await event.getByRole('button', { name: 'Save event', exact: true }).click()
  await expect(event).not.toBeVisible()
  const after = await exportLocalData(page)
  expect(Object.keys(selectedPlaythrough(after).progress)).toEqual(Object.keys(selectedPlaythrough(before).progress))
  const milestone = Object.values(selectedPlaythrough(after).progress)[0]!
  expect(milestone.masterLocation).toEqual({ state: 'known', value: 'Synthetic northern camp' })
  expect(milestone.unlocked).toEqual({ state: 'known', value: true })
  expect(milestone.partyMastery).toEqual({ state: 'known', value: true })
  expect(milestone.collection).toEqual({ state: 'known', value: true })
  expect(selectedPlaythrough(after).inventory).toEqual({})
  expect(Object.values(selectedPlaythrough(after).inventoryEvents)[0]).toMatchObject({ kind: 'acquired', quantity: { state: 'unknown' } })
  expect(Object.values(selectedPlaythrough(after).inventoryEvents)[0]).not.toHaveProperty('observedAt')
  const character = Object.values(selectedPlaythrough(after).characters)[0]!
  const observed = character.snapshots[character.currentSnapshotId!]!
  expect(observed).toMatchObject({ level: { state: 'known', value: 20 }, observedAt: '2024-06-15' })
  expect(observed).not.toHaveProperty('ppCapacity')
  expect(observed.displayedStats['Max HP']?.value).toEqual({ state: 'known', value: 321 })
  expect(character.classProgress).toEqual({})
  expect(Object.values(character.learnedNodes)[0]).toMatchObject({ kind: 'monsterMagic', learned: { state: 'known', value: true }, actualPaidLp: { state: 'unknown' } })
})

test('immutable alternatives contend only when selected together in a scenario', async ({ page }) => {
  await configureGameSetup(page)
  await addStock(page)
  await addCharacter(page, 'Synthetic Rowan')
  await addCharacter(page, 'Synthetic Vale')
  await addCharacter(page, 'Synthetic Ivo')
  await addCharacter(page, 'Synthetic Nia')
  await navigate(page, 'Builds')
  await page.getByRole('button', { name: 'New Build', exact: true }).click()
  await page.getByRole('combobox', { name: 'Copy Game Setup', exact: true }).selectOption('playthrough')
  const build = page.locator('.build-sheet')
  await build.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  await build.getByText('Build details & notes', { exact: true }).click()
  await build.getByLabel('Build title').fill('Shared staff template')
  await build.getByRole('button', { name: 'Loadout', exact: true }).click()
  const openEditor = async () => page.locator('.build-sheet')
  let editor = await openEditor()
  await editor.getByRole('combobox', { name: 'Main hand', exact: true }).click()
  const picker = page.getByRole('listbox', { name: 'Choose Main hand' })
  await page.getByRole('combobox', { name: 'Main hand', exact: true }).fill('Synthetic shared staff')
  await picker.getByRole('option', { name: /^Synthetic shared staff / }).click()
  await editor.getByRole('button', { name: /^Save (build|new revision)$/ }).click()
  await expect(page.getByText('Saved locally', { exact: true })).toBeAttached()
  const first = await exportLocalData(page)
  const sharedStaffBuild = Object.values(first.builds).find((candidate) => candidate.title === 'Shared staff template')!
  const firstRevision = first.buildRevisions[sharedStaffBuild.latestRevisionId!]!

  editor = await openEditor()
  await editor.getByRole('combobox', { name: 'Main hand', exact: true }).click()
  await page.getByRole('listbox', { name: 'Choose Main hand' }).getByRole('option', { name: /Leave empty/ }).click()
  await editor.getByRole('button', { name: /^Save (build|new revision)$/ }).click()
  await expect(page.getByText('Saved locally', { exact: true })).toBeAttached()
  await page.goto('/#/builds/teams')
  await page.getByRole('button', { name: 'New party plan', exact: true }).click()
  const team = page.getByRole('dialog', { name: 'Create party plan' })
  await team.getByLabel('Party plan name').fill('Synthetic simultaneous team')
  await chooseFourTeamMembers(team)
  await team.getByRole('button', { name: 'Create party plan', exact: true }).click()
  await expect(team).not.toBeVisible()
  await page.getByRole('combobox', { name: 'Synthetic Rowan', exact: true }).selectOption(firstRevision.id)
  await expect(page.getByText('Saved locally', { exact: true })).toBeAttached()
  await page.getByRole('combobox', { name: 'Synthetic Vale', exact: true }).selectOption(firstRevision.id)
  await expect(page.getByText('Confirmed stock cannot cover simultaneous assignments', { exact: false }).first()).toBeVisible()
  const simultaneous = await exportLocalData(page)
  expect(simultaneous.buildRevisions[firstRevision.id]).toEqual(firstRevision)
  expect(Object.values(selectedPlaythrough(simultaneous).inventory)[0]?.quantity).toEqual({ kind: 'exact', value: 1 })
  expect(Object.values(selectedPlaythrough(simultaneous).characters).every((character) => !character.currentSnapshotId)).toBe(true)
  await page.getByRole('combobox', { name: 'Synthetic Vale', exact: true }).selectOption('')
  await expect(page.getByText('Saved locally', { exact: true })).toBeAttached()
  await expect(page.getByText('Confirmed stock cannot cover simultaneous assignments', { exact: false })).toHaveCount(0)
  await page.getByRole('button', { name: 'Compare revisions', exact: true }).click()
  const secondRevision = Object.values(simultaneous.buildRevisions).find((revision) => revision.buildId === sharedStaffBuild.id && revision.id !== firstRevision.id)!
  await page.getByLabel('Revision A').selectOption(firstRevision.id)
  await page.getByLabel('Revision B').selectOption(secondRevision.id)
  await page.getByText('Evidence and differences', { exact: true }).click()
  await expect(page.locator('.comparison-row').getByText(/Synthetic shared staff/)).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('build drafts resist navigation and recording current preserves level and the existing party plan', async ({ page, isMobile }) => {
  await configureGameSetup(page)
  await addCharacter(page, 'Synthetic Rowan')
  await addCharacter(page, 'Synthetic Vale')
  await addCharacter(page, 'Synthetic Ivo')
  await addCharacter(page, 'Synthetic Nia')
  await page.getByRole('combobox', { name: 'Character', exact: true }).selectOption({ label: 'Synthetic Rowan' })
  await page.getByRole('button', { name: 'Capture snapshot', exact: true }).click()
  const snapshot = page.getByRole('dialog', { name: 'Capture character snapshot' })
  await snapshot.getByLabel('Level certainty', { exact: true }).selectOption('known')
  await snapshot.getByLabel('Level', { exact: true }).fill('20')
  await expect(snapshot.getByLabel('Shared PP capacity', { exact: true })).toHaveCount(0)
  await snapshot.getByRole('button', { name: 'Save snapshot', exact: true }).click()
  await expect(snapshot).not.toBeVisible()
  await navigate(page, 'Builds')
  await page.goto('/#/builds/teams')
  await page.getByRole('button', { name: 'New party plan', exact: true }).click()
  const currentTeam = page.getByRole('dialog', { name: 'Create party plan', exact: true })
  await currentTeam.getByLabel('Party plan name').fill('Synthetic current team')
  await chooseFourTeamMembers(currentTeam)
  await currentTeam.getByRole('button', { name: 'Create party plan', exact: true }).click()
  await expect(currentTeam).not.toBeVisible()
  await page.getByRole('button', { name: 'Build library', exact: true }).click()
  await page.getByRole('button', { name: 'New Build', exact: true }).click()
  await page.getByRole('combobox', { name: 'Copy Game Setup', exact: true }).selectOption('playthrough')
  const build = page.locator('.build-sheet')
  await expect(page.getByRole('status', { name: 'Build PP summary' })).toContainText('0 / 10 PP')
  await build.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  await build.getByText('Build details & notes', { exact: true }).click()
  await build.getByLabel('Build title').fill('Observed Rowan build')
  await expect(page.getByLabel('PP reference character')).toHaveCount(0)
  const editor = page.locator('.build-sheet')
  await editor.getByLabel('Rotation or use notes').fill('Retain this unsaved draft')
  await page.evaluate(() => { window.location.hash = '/inventory' })
  await expect(page).toHaveURL(/#\/builds\/library\/new$/)
  await expect(editor.getByLabel('Rotation or use notes')).toHaveValue('Retain this unsaved draft')
  if (!isMobile) {
    const settings = await openData(page)
    await expect(settings).not.toBeVisible()
    await expect(page.getByText('Unsaved edits are still open', { exact: true })).toBeVisible()
    await expect(page).toHaveURL(/#\/builds\/library\/new$/)
    await expect(editor.getByLabel('Rotation or use notes')).toHaveValue('Retain this unsaved draft')
  }
  await editor.getByRole('button', { name: /^Save (build|new revision)$/ }).click()
  await expect(page.getByText('Saved locally', { exact: true })).toBeAttached()
  await page.locator('.build-readiness > summary').click()
  await page.getByRole('button', { name: 'Compare / record on a character', exact: true }).click()
  const recording = page.locator('dialog').filter({ has: page.getByRole('heading', { name: 'Compare and record Build', exact: true }) })
  await recording.getByRole('combobox', { name: /^Character/ }).selectOption({ label: 'Synthetic Rowan' })
  await expect(recording.getByRole('button', { name: 'Record as current', exact: true })).toBeDisabled()
  await recording.getByRole('checkbox', { name: /I made these changes in game/ }).check()
  await recording.getByRole('button', { name: 'Record as current', exact: true }).click()
  await expect(recording).not.toBeVisible()
  const localData = await exportLocalData(page)
  const character = Object.values(selectedPlaythrough(localData).characters)[0]!
  const observed = character.snapshots[character.currentSnapshotId!]!
  expect(observed.level).toEqual({ state: 'known', value: 20 })
  expect(observed).not.toHaveProperty('ppCapacity')
  expect(selectedPlaythrough(localData).inventory).toEqual({})
  expect(character.learnedNodes).toEqual({})
  const partyPlans = Object.values(selectedPlaythrough(localData).scenarios)
  expect(partyPlans).toHaveLength(1)
  expect(partyPlans[0]?.label).toBe('Synthetic current team')
  expect(partyPlans[0]?.kind).toBe('draft')
  expect(partyPlans[0]?.assignments).toEqual({})
})

test('named shared-copy checkpoints clone independently and picker history preserves its query', async ({ page }, testInfo) => {
  await configureGameSetup(page, ['Main hand', 'Off hand'])
  await addStock(page)
  await addCharacter(page, 'Synthetic Rowan')
  await addCharacter(page, 'Synthetic Vale')
  await addCharacter(page, 'Synthetic Ivo')
  await addCharacter(page, 'Synthetic Nia')
  await navigate(page, 'Builds')
  await page.getByRole('button', { name: 'New Build', exact: true }).click()
  await page.getByRole('combobox', { name: 'Copy Game Setup', exact: true }).selectOption('playthrough')
  const creation = page.locator('.build-sheet')
  await creation.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  await creation.getByText('Build details & notes', { exact: true }).click()
  await creation.getByLabel('Build title').fill('Two-slot template')
  await creation.getByRole('button', { name: 'Loadout', exact: true }).click()
  const editor = page.locator('.build-sheet')
  await editor.getByRole('combobox', { name: 'Main hand', exact: true }).click()
  const picker = page.getByRole('listbox', { name: 'Choose Main hand', exact: true })
  await page.getByRole('combobox', { name: 'Main hand', exact: true }).fill('shared staff')
  await page.goBack()
  await expect(picker).not.toBeVisible()
  await expect(editor.getByRole('combobox', { name: 'Main hand', exact: true })).toBeVisible()
  await editor.getByRole('combobox', { name: 'Main hand', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Main hand', exact: true })).toHaveValue('shared staff')
  await picker.getByRole('option', { name: /^Synthetic shared staff / }).click()
  await editor.getByRole('combobox', { name: 'Off hand', exact: true }).click()
  const offHandPicker = page.getByRole('listbox', { name: 'Choose Off hand', exact: true })
  await page.getByRole('combobox', { name: 'Off hand', exact: true }).fill('Synthetic shared staff')
  await offHandPicker.getByRole('option', { name: /^Synthetic shared staff / }).click()
  const grouping = editor.getByRole('combobox', { name: 'Off hand: Same copy as', exact: true })
  await expect(grouping).toHaveValue('')
  await grouping.selectOption({ label: 'Main hand' })
  await editor.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  await editor.getByLabel('Checkpoint name').fill('One physical staff')
  await page.screenshot({ path: testInfo.outputPath('build-editor.png'), fullPage: true })
  await editor.getByRole('button', { name: /^Save (build|new revision)$/ }).click()
  await expect(page.getByText('Saved locally', { exact: true })).toBeVisible()
  const before = await exportLocalData(page)
  const originalBuild = Object.values(before.builds).find((build) => build.title === 'Two-slot template')!
  const originalRevision = before.buildRevisions[originalBuild.latestRevisionId!]!
  const equipment = Object.values(originalRevision.content.equipment).filter((value) => value !== null)
  expect(equipment).toHaveLength(2)
  expect(equipment[0]?.allocationId).toBeTruthy()
  expect(equipment[0]?.allocationId).toBe(equipment[1]?.allocationId)
  expect(originalRevision.note).toBe('One physical staff')

  await page.getByRole('button', { name: 'Clone Build', exact: true }).click()
  await openBuildLibrary(page)
  const library = page.locator('.build-library')
  const copyButton = library.getByRole('button', { name: 'Two-slot template (copy)', exact: true })
  const copyCard = copyButton.locator('xpath=ancestor::article[1]')
  await expect(copyCard).toHaveAttribute('aria-current', 'true')
  const after = await exportLocalData(page)
  const copy = Object.values(after.builds).find((build) => build.id !== originalBuild.id && build.title === 'Two-slot template (copy)')!
  const copiedRevision = after.buildRevisions[copy.latestRevisionId!]!
  expect(copy.state).toBe('draft')
  expect(copiedRevision.id).not.toBe(originalRevision.id)
  expect(copiedRevision.revision).toBe(1)
  expect(copiedRevision.content).toEqual(originalRevision.content)
  expect(after.buildRevisions[originalRevision.id]).toEqual(originalRevision)
  expect(selectedPlaythrough(after).inventory).toEqual(selectedPlaythrough(before).inventory)
  expect(selectedPlaythrough(after).characters).toEqual(selectedPlaythrough(before).characters)
  expect(selectedPlaythrough(after).scenarios).toEqual(selectedPlaythrough(before).scenarios)

  await page.goto('/#/builds/teams')
  await page.getByRole('button', { name: 'New party plan', exact: true }).click()
  const team = page.getByRole('dialog', { name: 'Create party plan', exact: true })
  await team.getByLabel('Party plan name').fill('Shared physical copy')
  await chooseFourTeamMembers(team)
  await team.getByRole('button', { name: 'Create party plan', exact: true }).click()
  await expect(team).not.toBeVisible()
  const assignment = page.getByRole('combobox', { name: 'Synthetic Rowan', exact: true })
  await expect(assignment.locator(`option[value="${copiedRevision.id}"]`)).toContainText('One physical staff')
  await assignment.selectOption(copiedRevision.id)
  await expect(page.getByText('Saved locally', { exact: true })).toBeVisible()
  await expect(page.getByText('Confirmed stock cannot cover simultaneous assignments', { exact: false })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('team-scenario.png'), fullPage: true })
  await page.getByRole('button', { name: 'Compare revisions', exact: true }).click()
  await expect(page.getByLabel('Revision A').locator(`option[value="${originalRevision.id}"]`)).toContainText('One physical staff')
  await page.getByLabel('Revision A').selectOption(originalRevision.id)
  await page.getByLabel('Revision B').selectOption(copiedRevision.id)
  await page.getByText('Evidence and differences', { exact: true }).click()
  await expect(page.locator('.comparison-row').getByText('1 confirmed · 0 uncertain · 0 missing', { exact: true })).toHaveCount(2)
  await navigate(page, 'Inventory')
  await page.getByRole('button', { name: 'Edit Synthetic shared staff', exact: true }).click()
  const stock = page.getByRole('dialog', { name: 'Edit inventory observation', exact: true })
  await stock.getByLabel('Quantity certainty').selectOption('atLeast')
  await stock.getByLabel('Known minimum').fill('1')
  await stock.getByRole('button', { name: 'Save observation', exact: true }).click()
  await expect(stock).not.toBeVisible()
  await navigate(page, 'Builds')
  await expect(page.getByRole('region', { name: 'Build library', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Two-slot template', exact: true }).click()
  await editor.getByRole('combobox', { name: 'Off hand: Same copy as', exact: true }).selectOption('')
  await editor.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  await editor.getByText('Build details & notes', { exact: true }).click()
  await editor.getByLabel('Checkpoint name').fill('Separate physical copies')
  await editor.getByRole('button', { name: /^Save (build|new revision)$/ }).click()
  await expect(page.getByText('Saved locally', { exact: true })).toBeVisible()
  const minimumStock = await exportLocalData(page)
  expect(minimumStock.buildRevisions[originalRevision.id]).toEqual(originalRevision)
  await page.getByRole('button', { name: 'Compare revisions', exact: true }).click()
  await page.getByLabel('Revision A').selectOption(originalRevision.id)
  await page.getByLabel('Revision B').selectOption(minimumStock.builds[originalBuild.id]!.latestRevisionId!)
  await page.getByText('Evidence and differences', { exact: true }).click()
  await expect(page.locator('.comparison-row').getByText('1 confirmed · 1 uncertain · 0 missing', { exact: true })).toHaveCount(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('snapshot edits reject duplicate stats and distinguish empty from unrecorded slots', async ({ page }) => {
  const settings = await openData(page)
  await openCurrentGameSetup(settings)
  await settings.getByLabel('Game Setup label').fill('Synthetic validation configuration')
  await settings.getByRole('combobox', { name: 'Difficulty', exact: true }).selectOption('0')
  await saveAndApplyGameSetup(settings)
  await expect(page.getByText('Saved locally', { exact: true })).toBeAttached()
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await addCharacter(page, 'Synthetic Ash')
  await page.getByRole('button', { name: 'Capture snapshot', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Capture character snapshot', exact: true })
  await form.getByRole('button', { name: 'Choose Main hand', exact: true }).click()
  await page.getByRole('dialog', { name: 'Choose Main hand', exact: true }).getByRole('button', { name: /^Empty/ }).click()
  for (const name of ['Max HP', ' Max HP ']) {
    await form.getByRole('button', { name: 'Add stat', exact: true }).click()
    await form.getByRole('textbox', { name: 'Stat name', exact: true }).last().fill(name)
  }
  await form.getByRole('button', { name: 'Save snapshot', exact: true }).click()
  await expect(form.getByRole('alert')).toContainText('Displayed stat names must be unique after trimming whitespace')
  await expect(form).toBeVisible()
  await form.getByRole('button', { name: 'Remove stat', exact: true }).last().click()
  await form.getByRole('button', { name: 'Save snapshot', exact: true }).click()
  await expect(form).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Choose Main hand', exact: true })).toContainText('Empty')
  const empty = await exportLocalData(page)
  const character = Object.values(selectedPlaythrough(empty).characters)[0]!
  const emptySnapshot = character.snapshots[character.currentSnapshotId!]!
  const slotId = empty.gameSetups[empty.planningGameSetupRevisionId!]!.slots[0]!.id
  expect(emptySnapshot.equipment[slotId]).toBeNull()
  await page.getByRole('button', { name: 'Capture snapshot', exact: true }).click()
  await form.getByRole('button', { name: 'Choose Main hand', exact: true }).click()
  await page.getByRole('dialog', { name: 'Choose Main hand', exact: true }).getByRole('button', { name: /^Unknown/ }).click()
  await form.getByRole('button', { name: 'Save snapshot', exact: true }).click()
  await expect(form).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Choose Main hand', exact: true })).toContainText('Unknown')
  const unrecorded = await exportLocalData(page)
  const updated = selectedPlaythrough(unrecorded).characters[character.id]!
  expect(updated.snapshots[updated.currentSnapshotId!]!.equipment).not.toHaveProperty(slotId)
  expect(updated.snapshots[emptySnapshot.id]!.equipment[slotId]).toBeNull()
})
