import { addBundledModToReference, waitForPlannerReady } from './local-data-helpers'
import { referencePath } from './reference-helpers'
import { MOBILE_TEST_TAG } from './test-tags'
import { expectOfflineReady } from './offline-helpers'
import { expect, test, type Page } from '@playwright/test'
import { EQUIPMENT_CATEGORIES } from '../src/ui/reference-categories'

async function showFilters(page: Page, isMobile: boolean) {
  if (isMobile) await page.getByRole('button', { name: /^Filters/ }).click()
}

test('equipment categories combine base and mod records using stable keys', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }) => {
  await addBundledModToReference(page, 'Equipment Expansion')
  await page.goto('/#/reference?v=1&kind=item')
  await expect(page.getByRole('heading', { name: 'Reference', exact: true })).toBeVisible()
  await showFilters(page, isMobile)
  const categories = page.getByRole('group', { name: 'Reference category filters', exact: true })
  const search = page.getByRole('searchbox', { name: 'Search reference categories', exact: true })
  await search.fill('Staff')
  await expect(categories.getByRole('button', { name: /^Staves \(\d+\)$/ })).toHaveCount(1)
  await search.fill('axe')
  const axes = categories.getByRole('button', { name: /^Axes \(\d+\)$/ })
  await expect(axes).toHaveCount(1)
  await expect(categories.getByRole('button', { name: /^Axe \(\d+\)$/ })).toHaveCount(0)
  await axes.click()
  const active = page.getByRole('group', { name: 'Active reference filters', exact: true })
  await expect(active.getByRole('button', { name: 'Remove Axes filter', exact: true })).toBeVisible()
  const card = (name: string) => page.locator('.reference-card').filter({ has: page.getByRole('heading', { name, exact: true }) })
  await expect(card('Hand Axe')).toBeVisible()
  await expect(card('Backbreaker')).toBeVisible()
  await expect(card('Short Sword')).toHaveCount(0)
  expect(new URLSearchParams(new URL(page.url()).hash.split('?')[1]).get('category')).toBe(EQUIPMENT_CATEGORIES.Axe.key)
  await page.reload()
  await expect(active.getByRole('button', { name: 'Remove Axes filter', exact: true })).toBeVisible()
  await showFilters(page, isMobile)
  await page.getByRole('button', { name: 'Source mod', exact: true }).click()
  const mods = page.getByRole('group', { name: 'Reference mods filters', exact: true })
  await mods.getByRole('button', { name: /^Base game \(\d+\)$/ }).click()
  await expect(card('Hand Axe')).toBeVisible()
  await expect(card('Backbreaker')).toHaveCount(0)
  await active.getByRole('button', { name: 'Remove Source mod: Base game filter', exact: true }).click()
  await mods.getByRole('button', { name: /^Equipment Expansion \(\d+\)$/ }).click()
  await expect(card('Backbreaker')).toBeVisible()
  await expect(card('Hand Axe')).toHaveCount(0)
})

test('category families remain searchable, preserve alternatives, and expose hidden selections', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }) => {
  await page.goto('/#/reference?v=1')
  await waitForPlannerReady(page)
  await expect(page.getByRole('heading', { name: 'Reference', exact: true })).toBeVisible()
  await showFilters(page, isMobile)
  await page.getByRole('button', { name: 'Definition type', exact: true }).click()
  const types = page.getByRole('group', { name: 'Reference definition type filters', exact: true })
  await expect(types.getByRole('heading', { name: 'Equipment & items', exact: true })).toBeVisible()
  await expect(types.getByRole('heading', { name: 'Classes & skills', exact: true })).toBeVisible()
  await types.getByRole('button', { name: /^Items \d+$/ }).click()

  const categories = page.getByRole('group', { name: 'Reference category filters', exact: true })
  const weapons = categories.getByRole('button', { name: /^Weapons / })
  await weapons.focus()
  await page.keyboard.press('Enter')
  await expect(weapons).toHaveAttribute('aria-expanded', 'true')
  await categories.getByRole('button', { name: /^Swords \(\d+\)$/ }).click()
  const active = page.getByRole('group', { name: 'Active reference filters', exact: true })
  await expect(active.getByRole('button', { name: 'Remove Swords filter', exact: true })).toBeVisible()
  const search = page.getByRole('searchbox', { name: 'Search reference categories', exact: true })
  await search.fill('Daggers')
  await categories.getByRole('button', { name: /^Daggers \(\d+\)$/ }).click()
  await expect(active.getByRole('button', { name: 'Remove Daggers filter', exact: true })).toBeVisible()
  await expect(page.locator('.reference-card').filter({ has: page.getByRole('heading', { name: 'Artisan Sword', exact: true }) })).toBeVisible()
  await expect(page.locator('.reference-card').filter({ has: page.getByRole('heading', { name: 'Ambush Knife', exact: true }) })).toBeVisible()
  await expect(page.locator('.reference-card').filter({ has: page.getByRole('heading', { name: 'Ancient Axe', exact: true }) })).toHaveCount(0)
  await search.fill('unmatched synthetic category')
  await expect(page.getByText('No categories match this search.', { exact: true })).toBeVisible()
  await expect(active.getByRole('button', { name: 'Remove Swords filter', exact: true })).toBeVisible()
  if (isMobile) {
    await page.getByRole('button', { name: /^Hide filters/ }).click()
    await expect(page.getByRole('button', { name: /^Filters/ })).toContainText('3 active')
  }
  await active.getByRole('button', { name: 'Remove Swords filter', exact: true }).click()
  await expect(active.getByRole('button', { name: 'Remove Swords filter', exact: true })).toHaveCount(0)
  await page.goBack()
  await expect(active.getByRole('button', { name: 'Remove Swords filter', exact: true })).toBeVisible()
  await page.reload()
  await expect(active.getByRole('button', { name: 'Remove Daggers filter', exact: true })).toBeVisible()
  await active.getByRole('button', { name: 'Clear all filters', exact: true }).click()
  await expect(active).toHaveCount(0)
  await expect(page).not.toHaveURL(/category=|kind=/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('supplemental reference audiences stay hidden by default and remain directly reachable', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }) => {
  await page.goto('/#/reference?v=1&q=AbilityItemConsumptionDown')
  await waitForPlannerReady(page)
  await expect(page.locator('.reference-card').filter({ has: page.getByRole('heading', { name: 'AbilityItemConsumptionDown', exact: true }) })).toHaveCount(0)
  const hidden = page.getByRole('status').filter({ hasText: 'additional match is hidden' })
  await expect(hidden).toBeVisible()
  await hidden.getByRole('button', { name: 'Show Technical mechanics', exact: true }).click()
  const technical = page.locator('.reference-card').filter({ has: page.getByRole('heading', { name: 'AbilityItemConsumptionDown', exact: true }) })
  await expect(technical).toBeVisible()
  await expect(page).toHaveURL(/audience=technical/)

  await showFilters(page, isMobile)
  await page.getByRole('button', { name: 'Additional reference', exact: true }).click()
  const audiences = page.getByRole('group', { name: 'Additional reference filters', exact: true })
  await expect(audiences.getByRole('button', { name: /^Technical mechanics \d+$/ })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('group', { name: 'Active reference filters', exact: true }).getByRole('button', { name: 'Remove Include Technical mechanics filter', exact: true }).click()
  await expect(technical).toHaveCount(0)
  await expect(page).not.toHaveURL(/audience=technical/)

  await page.goto(referencePath('base:mechanic:stat:ref-445') + '?v=1')
  await expect(page.getByRole('heading', { name: 'AbilityItemConsumptionDown', exact: true })).toBeVisible()
  await expect(page).not.toHaveURL(/audience=technical/)

  await page.goto('/#/reference?v=1&q=Growth+estimates+and+damage+formula+research')
  await expect(page.locator('.reference-card').filter({ has: page.getByRole('heading', { name: 'Growth estimates and damage formula research', exact: true }) })).toBeVisible()
  await page.goto('/#/reference?v=1&q=Bgtest')
  await expect(page.getByText('No matches', { exact: true })).toBeVisible()
  await expect(page.getByText(/additional match/)).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('class facets combine with definition types and survive details and offline reloads', { tag: MOBILE_TEST_TAG }, async ({ page, context, isMobile }) => {
  await page.goto('/#/reference?v=1&kind=ability')
  await showFilters(page, isMobile)
  await page.getByRole('button', { name: 'Class', exact: true }).click()
  const classes = page.getByRole('group', { name: 'Reference classes filters', exact: true })
  const search = page.getByRole('searchbox', { name: 'Search reference classes', exact: true })
  await search.fill('Warrior')
  await classes.getByRole('button', { name: /^Warrior \(\d+\)$/ }).click()
  const taunt = page.locator('.reference-card').filter({ has: page.getByRole('heading', { name: 'Taunt', exact: true }) })
  await expect(taunt).toBeVisible()
  await expect(page.locator('.reference-card').filter({ has: page.getByRole('heading', { name: 'Fire', exact: true }) })).toHaveCount(0)
  await search.fill('Rogue')
  await classes.getByRole('button', { name: /^Rogue \(\d+\)$/ }).click()
  const backstab = page.locator('.reference-card').filter({ has: page.getByRole('heading', { name: 'Backstab', exact: true }) })
  await expect(backstab).toBeVisible()
  await taunt.click()
  await page.getByRole('button', { name: 'Back to results', exact: true }).click()
  await expect(backstab).toBeVisible()
  const active = page.getByRole('group', { name: 'Active reference filters', exact: true })
  await active.getByRole('button', { name: 'Remove Class: Warrior filter', exact: true }).click()
  await expect(taunt).toHaveCount(0)
  await expect(backstab).toBeVisible()

  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  await settings.getByRole('button', { name: 'Prepare for offline use', exact: true }).click()
  await expectOfflineReady(settings)
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.reload()
  await expect(backstab).toBeVisible()
  await expect(active.getByRole('button', { name: 'Remove Class: Rogue filter', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('active filters remain removable when their values are absent from the library', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }) => {
  await page.goto('/#/reference?v=1&kind=item&category=Synthetic&class=Synthetic&slot=Synthetic&element=Synthetic&mod=Synthetic&source=Synthetic&ppMin=1&ppMax=4&q=Synthetic&weapon=Dagger&uncertainSkills=1')
  await waitForPlannerReady(page)
  const active = page.getByRole('group', { name: 'Active reference filters', exact: true })
  await expect(active.getByRole('button', { name: 'Remove Equipment slot: Synthetic filter', exact: true })).toBeVisible()
  if (isMobile) await expect(page.getByRole('button', { name: /^Filters/ })).toContainText('12 active')
  await active.getByRole('button', { name: 'Clear all filters', exact: true }).click()
  await expect(active).toHaveCount(0)
  await expect(page).toHaveURL(/#\/reference\?v=1$/)
  await expect(page.locator('.reference-card').first()).toBeVisible()
})

test('source mod facets include established catalog associations and agree with result badges', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }) => {
  await addBundledModToReference(page, 'Equipment Expansion')
  await page.goto('/#/reference?v=1&kind=item')
  await showFilters(page, isMobile)
  await page.getByRole('button', { name: 'Source mod', exact: true }).click()
  await page.getByRole('searchbox', { name: 'Search reference mods', exact: true }).fill('Equipment Expansion')
  await page.getByRole('group', { name: 'Reference mods filters', exact: true }).getByRole('button', { name: /^Equipment Expansion \(\d+\)$/ }).click()
  const result = page.locator('.reference-card').filter({ has: page.getByRole('heading', { name: 'Backbreaker', exact: true }) })
  await expect(result).toBeVisible()
  await expect(result.getByText('Mod: Equipment Expansion', { exact: true })).toBeVisible()
  await expect(result).toContainText('Enabled status not recorded')
  await expect(result).not.toContainText('Possible match')
  await expect(page).toHaveURL(/mod=Equipment\+Expansion/)
})
