import { createBlankPlaythrough } from './profile-helpers'
import { expect, test, type Locator, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { strFromU8, unzipSync } from 'fflate'
import type { CatalogSnapshot, Profile } from '../src/domain/types'

async function openData(page: Page) {
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  return page.getByRole('dialog', { name: 'Data & settings', exact: true })
}

async function exportProfile(page: Page) {
  const panel = await openData(page)
  await panel.getByRole('button', { name: 'Import & backup', exact: true }).click()
  const downloaded = page.waitForEvent('download')
  await panel.getByRole('button', { name: 'Export backup', exact: true }).click()
  const path = await (await downloaded).path()
  if (!path) throw new Error('Expected a completed backup download')
  const bytes = await readFile(path)
  const entries = unzipSync(bytes)
  const bundle = JSON.parse(strFromU8(entries['bundle.json']!)) as { profile: Profile; catalogs: readonly CatalogSnapshot[] }
  await panel.getByRole('button', { name: 'Close dialog', exact: true }).click()
  return { ...bundle, bytes }
}

async function search(page: Page, query: string, shortcut = 'Control+k') {
  await page.keyboard.press(shortcut)
  const palette = page.getByRole('dialog', { name: 'Search Crystal Companion', exact: true })
  await expect(palette).toBeVisible()
  await expect(palette.getByRole('searchbox', { name: 'Search Crystal Companion', exact: true })).toBeFocused()
  await palette.getByRole('searchbox', { name: 'Search Crystal Companion', exact: true }).fill(query)
  return palette
}

async function chooseDefinition(page: Page, form: Locator, label: string, query: string, name: string) {
  await form.getByRole('button', { name: `Choose ${label}`, exact: true }).click()
  const picker = page.getByRole('dialog', { name: `Choose ${label}`, exact: true })
  await picker.getByRole('searchbox', { name: 'Search available definitions', exact: true }).fill(query)
  await picker.locator('[data-definition-result="true"]').filter({ has: page.locator('strong', { hasText: new RegExp(`^${name}$`) }) }).first().click()
  await expect(picker).not.toBeVisible()
}

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Inventory', exact: true })).toBeVisible()
  await createBlankPlaythrough(page)
})

test('universal search focuses the input on shortcuts, reopening, and the search button', async ({ page, isMobile }) => {
  const trigger = page.getByRole('button', { name: isMobile ? 'Search planner' : /^Search/ }).filter({ visible: true })
  const palette = page.getByRole('dialog', { name: 'Search Crystal Companion', exact: true })
  const input = palette.getByRole('searchbox', { name: 'Search Crystal Companion', exact: true })
  await trigger.focus()
  for (const shortcut of ['Meta+k', 'Control+k']) {
    await page.keyboard.press(shortcut)
    await expect(input).toBeFocused()
    await page.keyboard.type('Taunt')
    await expect(input).toHaveValue('Taunt')
    await page.keyboard.press('Escape')
    await expect(palette).not.toBeVisible()
    await expect(trigger).toBeFocused()
  }
  await trigger.click()
  await expect(input).toBeFocused()
  await page.keyboard.type('Potion')
  await expect(input).toHaveValue('Potion')
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
})

test('starter picklists and universal search work without importing or inventing personal state', async ({ page, isMobile }) => {
  const externalRequests: string[] = []
  page.on('request', (request) => {
    if (!request.url().startsWith('http://127.0.0.1:4173/')) externalRequests.push(request.url())
  })
  const blank = await exportProfile(page)
  expect(blank.profile.inventory).toEqual({})
  expect(blank.profile.characters).toEqual({})
  expect(blank.profile.progress).toEqual({})
  expect(blank.profile.personalDefinitions).toEqual({})

  await page.getByRole('button', { name: 'Add item', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Add inventory item', exact: true })
  await expect(form.getByRole('button', { name: 'Choose Item definition', exact: true })).toBeFocused()
  await expect(form.getByRole('textbox', { name: 'Item name', exact: true })).not.toBeVisible()
  await expect(form.getByRole('button', { name: 'Add item', exact: true })).toBeDisabled()
  await chooseDefinition(page, form, 'Item definition', 'Potion', 'Potion')
  await expect(form.getByRole('button', { name: 'Choose Item definition', exact: true })).toContainText('Potion')
  await expect(form.getByRole('textbox', { name: 'Item name', exact: true })).not.toBeVisible()
  await form.getByLabel('Current possession').selectOption('owned')
  await form.getByLabel('Quantity certainty').selectOption('exact')
  await form.getByLabel('Current count').fill('3')
  await form.getByRole('button', { name: 'Add item', exact: true }).click()
  await expect(form).not.toBeVisible()

  const palette = await search(page, 'Taunt', 'Meta+k')
  await palette.getByRole('searchbox', { name: 'Search Crystal Companion', exact: true }).press('ArrowDown')
  await expect(palette.locator('[data-universal-result="true"]').first()).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(palette).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'Taunt', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Back to results', exact: true }).click()

  const trigger = page.getByRole('button', { name: isMobile ? 'Search planner' : /^Search/ }).filter({ visible: true })
  await trigger.click()
  await expect(palette).toBeVisible()
  await palette.getByRole('searchbox', { name: 'Search Crystal Companion', exact: true }).fill('A nonempty query')
  await palette.getByRole('searchbox', { name: 'Search Crystal Companion', exact: true }).press('Escape')
  await expect(palette).not.toBeVisible()
  await expect(trigger).toBeFocused()

  await search(page, 'Potion Inventory')
  await palette.locator('[data-universal-result="true"]').click()
  await expect(page.getByRole('heading', { name: 'Inventory', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Edit inventory observation', exact: true })).toBeVisible()
  await page.getByRole('dialog', { name: 'Edit inventory observation', exact: true }).getByRole('button', { name: 'Cancel', exact: true }).click()
  await search(page, 'Potion Inventory')
  await palette.locator('[data-universal-result="true"]').click()
  await expect(page.getByRole('dialog', { name: 'Edit inventory observation', exact: true })).toBeVisible()
  await page.getByRole('dialog', { name: 'Edit inventory observation', exact: true }).getByRole('button', { name: 'Cancel', exact: true }).click()
  const saved = await exportProfile(page)
  expect(Object.values(saved.profile.inventory)).toHaveLength(1)
  expect(Object.values(saved.profile.inventory)[0]?.observedName).toBe('Potion')
  expect(Object.values(saved.profile.inventory)[0]?.quantity).toEqual({ kind: 'exact', value: 3 })
  expect(saved.catalogs.some((catalog) => catalog.id === 'crystal-project-public-starter')).toBe(true)
  expect(saved.profile.characters).toEqual({})
  expect(saved.profile.progress).toEqual({})
  expect(externalRequests).toEqual([])
})

test('inventory display names remain optional and preserve the selected item across edits', async ({ page }) => {
  await page.goto('/#/inventory/new')
  const form = page.getByRole('dialog', { name: 'Add inventory item', exact: true })
  await expect(form.getByRole('button', { name: 'Choose Item definition', exact: true })).toBeFocused()
  await chooseDefinition(page, form, 'Item definition', 'Potion', 'Potion')
  await form.getByRole('button', { name: 'Customize display name', exact: true }).click()
  const displayName = form.getByRole('textbox', { name: 'Display name', exact: true })
  await expect(displayName).toBeFocused()
  await displayName.fill('Synthetic travel potion')
  await chooseDefinition(page, form, 'Item definition', 'Potion', 'Potion')
  await expect(displayName).toHaveValue('Synthetic travel potion')
  await form.getByRole('button', { name: 'Add item', exact: true }).click()
  await expect(form).not.toBeVisible()
  const created = await exportProfile(page)
  const position = Object.values(created.profile.inventory)[0]!
  expect(position.observedName).toBe('Synthetic travel potion')
  expect(position.ref.kind).toBe('catalog')
  expect(created.profile.personalDefinitions).toEqual({})

  await page.reload()
  await page.getByRole('button', { name: 'Edit Synthetic travel potion', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Edit inventory observation', exact: true })
  await expect(editor.getByRole('button', { name: 'Choose Item definition', exact: true })).toBeFocused()
  await expect(editor.getByRole('textbox', { name: 'Display name', exact: true })).toHaveValue('Synthetic travel potion')
  await editor.getByRole('textbox', { name: 'Display name', exact: true }).fill('')
  await editor.getByRole('button', { name: 'Save observation', exact: true }).click()
  await expect(editor).not.toBeVisible()
  const restoredName = await exportProfile(page)
  expect(restoredName.profile.inventory[position.id]).toMatchObject({ id: position.id, ref: position.ref, observedName: 'Potion', possession: position.possession, quantity: position.quantity })

  await page.getByRole('button', { name: 'Edit Potion', exact: true }).click()
  await expect(editor.getByRole('textbox', { name: 'Display name', exact: true })).not.toBeVisible()
  await editor.getByRole('button', { name: 'Customize display name', exact: true }).click()
  await editor.getByRole('textbox', { name: 'Display name', exact: true }).fill('Synthetic temporary name')
  await editor.getByRole('button', { name: 'Use item name', exact: true }).click()
  await expect(editor.getByRole('textbox', { name: 'Display name', exact: true })).not.toBeVisible()
  await expect(editor.getByRole('button', { name: 'Customize display name', exact: true })).toBeFocused()
  await editor.getByRole('button', { name: 'Customize display name', exact: true }).click()
  await expect(editor.getByRole('textbox', { name: 'Display name', exact: true })).toHaveValue('Potion')
  await editor.getByRole('textbox', { name: 'Display name', exact: true }).fill('Synthetic previous item name')
  await chooseDefinition(page, editor, 'Item definition', 'Ether', 'Ether')
  await expect(editor.getByRole('textbox', { name: 'Display name', exact: true })).not.toBeVisible()
  await editor.getByRole('button', { name: 'Save observation', exact: true }).click()
  await expect(editor).not.toBeVisible()
  const changedItem = await exportProfile(page)
  expect(Object.values(changedItem.profile.inventory)).toHaveLength(1)
  expect(changedItem.profile.inventory[position.id]?.observedName).toBe('Ether')
  expect(changedItem.profile.inventory[position.id]?.ref).not.toEqual(position.ref)
  expect(changedItem.profile.personalDefinitions).toEqual({})
  expect(changedItem.catalogs).toEqual(created.catalogs)
})

test('nested definition creation preserves the observation and universal search cannot discard it', async ({ page }) => {
  await page.getByRole('button', { name: 'Add item', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Add inventory item', exact: true })
  await form.getByRole('button', { name: 'Enter an unlisted item', exact: true }).click()
  await expect(form.getByRole('textbox', { name: 'Item name', exact: true })).toBeFocused()
  await form.getByRole('textbox', { name: 'Item name', exact: true }).fill('Unfinished observation')
  const palette = await search(page, 'Warrior')
  await palette.locator('[data-universal-result="true"]').first().click()
  await expect(palette.getByText('Navigation blocked', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(form).toBeVisible()
  await expect(form.getByRole('textbox', { name: 'Item name', exact: true })).toHaveValue('Unfinished observation')

  await form.getByRole('button', { name: 'Choose Item definition', exact: true }).click()
  const picker = page.getByRole('dialog', { name: 'Choose Item definition', exact: true })
  await picker.getByRole('searchbox', { name: 'Search available definitions', exact: true }).fill('Synthetic glass lantern')
  await picker.getByRole('searchbox', { name: 'Search available definitions', exact: true }).press('Escape')
  await expect(picker).not.toBeVisible()
  await expect(form).toBeVisible()
  await expect(form.getByRole('textbox', { name: 'Item name', exact: true })).toHaveValue('Unfinished observation')
  await form.getByRole('button', { name: 'Choose Item definition', exact: true }).click()
  await expect(picker.getByRole('searchbox', { name: 'Search available definitions', exact: true })).toHaveValue('Synthetic glass lantern')
  await picker.getByRole('button', { name: 'Create "Synthetic glass lantern"', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Create personal definition', exact: true })
  await expect(editor.getByRole('textbox', { name: 'Definition name', exact: true })).toHaveValue('Synthetic glass lantern')
  await editor.getByLabel('Aliases').fill('Synthetic beacon')
  await editor.getByRole('button', { name: 'Create definition', exact: true }).click()
  await expect(editor).not.toBeVisible()
  await expect(picker).not.toBeVisible()
  await expect(form).toBeVisible()
  await expect(form.getByRole('button', { name: 'Choose Item definition', exact: true })).toContainText('Synthetic glass lantern')
  await expect(form.getByRole('textbox', { name: 'Item name', exact: true })).not.toBeVisible()
  await form.getByRole('button', { name: 'Cancel', exact: true }).click()

  const backup = await exportProfile(page)
  expect(backup.profile.inventory).toEqual({})
  expect(Object.values(backup.profile.personalDefinitions).map((definition) => definition.name)).toEqual(['Synthetic glass lantern'])
  await search(page, 'Synthetic beacon')
  await expect(palette.locator('[data-universal-result="true"]')).toHaveCount(1)
  await palette.locator('[data-universal-result="true"]').click()
  await expect(page.getByRole('heading', { name: 'Synthetic glass lantern', exact: true })).toBeVisible()
})

test('item overrides preserve stock and checkpoints and can be collected into an inactive ruleset revision', async ({ page }) => {
  const settings = await openData(page)
  await settings.getByRole('button', { name: 'Ruleset', exact: true }).click()
  await settings.getByLabel('Ruleset label').fill('Synthetic base rules')
  await settings.getByRole('button', { name: 'Add slot', exact: true }).click()
  await settings.getByLabel('Slot 1', { exact: true }).fill('Main hand')
  await settings.getByRole('button', { name: 'Create ruleset', exact: true }).click()
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()

  await page.getByRole('button', { name: 'Add item', exact: true }).click()
  const stock = page.getByRole('dialog', { name: 'Add inventory item', exact: true })
  await chooseDefinition(page, stock, 'Item definition', 'Iron Sword', 'Iron Sword')
  await stock.getByLabel('Current possession').selectOption('owned')
  await stock.getByLabel('Quantity certainty').selectOption('exact')
  await stock.getByLabel('Current count').fill('2')
  await stock.getByRole('button', { name: 'Add item', exact: true }).click()
  await expect(stock).not.toBeVisible()

  await page.getByRole('button', { name: /^(Builds|Builds & teams)$/ }).filter({ visible: true }).click()
  await page.getByRole('button', { name: 'New build', exact: true }).click()
  const creation = page.locator('.build-sheet')
  await creation.getByText('Build details & notes', { exact: true }).click()
  await creation.getByLabel('Build title').fill('Synthetic catalog checkpoint')
  const buildEditor = page.locator('.build-sheet')
  await buildEditor.getByRole('combobox', { name: 'Main hand', exact: true }).click()
  const itemPicker = page.getByRole('listbox', { name: 'Choose Main hand', exact: true })
  await page.getByRole('combobox', { name: 'Main hand', exact: true }).fill('Iron Sword')
  await itemPicker.getByRole('option').filter({ has: page.locator('strong', { hasText: /^Iron Sword$/ }) }).click()
  await buildEditor.getByLabel('Checkpoint name').fill('Before personal correction')
  const palette = await search(page, 'Taunt')
  await palette.locator('[data-universal-result="true"]').first().click()
  await expect(palette.getByText('Navigation blocked', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(buildEditor.getByLabel('Checkpoint name')).toHaveValue('Before personal correction')
  await buildEditor.getByRole('button', { name: /^Save (build|new revision)$/ }).click()
  await expect(page.getByText('Saved locally', { exact: true })).toBeAttached()
  const before = await exportProfile(page)
  expect(Object.values(before.profile.buildRevisions)).toHaveLength(1)

  await search(page, 'Iron Sword item')
  await palette.locator('[data-universal-result="true"]').filter({ has: page.locator('strong', { hasText: /^Iron Sword$/ }) }).click()
  await page.getByRole('button', { name: 'Edit as personal override', exact: true }).click()
  const definition = page.getByRole('dialog', { name: 'Edit Iron Sword', exact: true })
  await expect(definition.getByRole('textbox', { name: 'Definition name', exact: true })).toHaveValue('Iron Sword')
  await definition.getByRole('textbox', { name: 'Definition name', exact: true }).fill('Synthetic tempered sword')
  await definition.getByLabel('Aliases').fill('Iron Sword\nSynthetic blade')
  await definition.getByRole('textbox', { name: 'Description', exact: true }).fill('Synthetic description for an override preservation check')
  await definition.getByLabel('Category knowledge').selectOption('known')
  await definition.getByRole('textbox', { name: 'Category', exact: true }).fill('Synthetic weapons')
  await definition.getByRole('button', { name: 'Save new override', exact: true }).click()
  await expect(definition).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'Synthetic tempered sword', exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Collect into ruleset revision', exact: true }).click()
  const collection = page.getByRole('dialog', { name: 'Collect into ruleset revision', exact: true })
  await collection.getByLabel('Source ruleset revision').selectOption(before.profile.activeRulesetRevisionId!)
  await collection.getByLabel('New revision label').fill('Synthetic reviewed definitions')
  await collection.getByRole('button', { name: 'Create ruleset revision', exact: true }).click()
  await expect(collection).not.toBeVisible()
  const after = await exportProfile(page)
  expect(after.profile.inventory).toEqual(before.profile.inventory)
  expect(after.profile.buildRevisions).toEqual(before.profile.buildRevisions)
  expect(after.profile.activeRulesetRevisionId).toBe(before.profile.activeRulesetRevisionId)
  const override = Object.values(after.profile.personalDefinitions).find((entry) => entry.name === 'Synthetic tempered sword')!
  expect(override.baseRef).toEqual(Object.values(before.profile.inventory)[0]!.ref)
  const collected = Object.values(after.profile.rulesets).find((entry) => entry.label === 'Synthetic reviewed definitions')!
  expect(collected.definitionOverrides).toEqual([{ kind: 'personal', definitionId: override.id }])

  await page.getByRole('button', { name: 'Inventory', exact: true }).filter({ visible: true }).click()
  await page.getByRole('button', { name: 'Edit Iron Sword', exact: true }).click()
  const observation = page.getByRole('dialog', { name: 'Edit inventory observation', exact: true })
  await chooseDefinition(page, observation, 'Item definition', 'Synthetic blade', 'Synthetic tempered sword')
  await observation.getByRole('button', { name: 'Save observation', exact: true }).click()
  await expect(observation).not.toBeVisible()
  await page.getByRole('searchbox', { name: 'Search inventory', exact: true }).fill('Synthetic blade')
  await page.getByRole('group', { name: 'Inventory category filters', exact: true }).getByRole('button', { name: 'Synthetic weapons (1)', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Edit Synthetic tempered sword', exact: true })).toBeVisible()
  const linked = await exportProfile(page)
  expect(Object.values(linked.profile.inventory)).toHaveLength(1)
  expect(Object.values(linked.profile.inventory)[0]?.quantity).toEqual({ kind: 'exact', value: 2 })
  expect(Object.values(linked.profile.inventory)[0]?.ref).toEqual({ kind: 'personal', definitionId: override.id })
  expect(linked.profile.buildRevisions).toEqual(before.profile.buildRevisions)

  const restore = await openData(page)
  await restore.locator('input[type="file"]').setInputFiles({ name: 'synthetic-overrides.zip', mimeType: 'application/zip', buffer: linked.bytes })
  await restore.getByRole('button', { name: 'Create profile', exact: true }).click()
  await expect(restore).not.toBeVisible()
  const restored = await exportProfile(page)
  expect(restored.profile.personalDefinitions).toEqual(linked.profile.personalDefinitions)
  expect(restored.profile.inventory).toEqual(linked.profile.inventory)
  expect(restored.profile.rulesets).toEqual(linked.profile.rulesets)
  expect(restored.profile.buildRevisions).toEqual(linked.profile.buildRevisions)
})
