import { openSavedCatalogVersion, readPlannerData } from './definition-fixtures'
import { currentReferencePath, referenceUrlPattern } from './reference-helpers'
import { MOBILE_TEST_TAG } from './test-tags'
import { BUNDLED_CATALOGS } from '../src/catalog/bundled'
import { resolveBundledCatalogPins } from '../src/interchange/native'
import { saveAndApplyGameSetup, openCurrentGameSetup, selectedPlaythrough, createBlankPlaythrough, openGameSetupSection, replacePlannerData } from './local-data-helpers'
import { expect, test, type Locator, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { strFromU8, unzipSync } from 'fflate'
import type { CatalogSnapshot, LocalData } from '../src/domain/types'
import { createSaveEditorFixture } from '../src/domain/save-editor.fixture'
import { encodeCrystalSave } from '../src/interchange/crystal-save'

async function openData(page: Page) {
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  return page.getByRole('dialog', { name: 'Data & settings', exact: true })
}

async function exportLocalData(page: Page) {
  const panel = await openData(page)
  await panel.getByRole('button', { name: 'Import & backup', exact: true }).click()
  const downloaded = page.waitForEvent('download')
  await panel.getByRole('button', { name: 'Export backup', exact: true }).click()
  const path = await (await downloaded).path()
  if (!path) throw new Error('Expected a completed backup download')
  const bytes = await readFile(path)
  const entries = unzipSync(bytes)
  const bundle = JSON.parse(strFromU8(entries['bundle.json']!)) as { localData: LocalData; catalogs: readonly CatalogSnapshot[]; bundledCatalogs?: readonly Pick<CatalogSnapshot, 'id' | 'revisionId' | 'checksum'>[] }
  await panel.getByRole('button', { name: 'Close dialog', exact: true }).click()
  expect(JSON.parse(strFromU8(entries['manifest.json']!)).formatVersion).toBe('2.1.0')
  return { ...bundle, catalogs: [...bundle.catalogs, ...resolveBundledCatalogPins(bundle.bundledCatalogs ?? [], BUNDLED_CATALOGS)], bytes }
}

async function search(page: Page, query: string, shortcut = 'Control+k') {
  await page.keyboard.press(shortcut)
  const palette = page.getByRole('dialog', { name: 'Search CryKit', exact: true })
  await expect(palette).toBeVisible()
  await expect(palette.getByRole('searchbox', { name: 'Search CryKit', exact: true })).toBeFocused()
  await palette.getByRole('searchbox', { name: 'Search CryKit', exact: true }).fill(query)
  return palette
}

async function chooseDefinition(page: Page, form: Locator, label: string, query: string, name: string) {
  await form.getByRole('button', { name: `Choose ${label}`, exact: true }).click()
  const picker = page.getByRole('dialog', { name: `Choose ${label}`, exact: true })
  await picker.getByRole('searchbox', { name: 'Search available definitions', exact: true }).fill(query)
  await picker.locator('[data-definition-result="true"]').filter({ has: page.locator('strong', { hasText: new RegExp(`^${name}$`) }) }).first().click()
  await expect(picker).not.toBeVisible()
}

test.beforeEach(async ({ page }) => {
  await page.goto('/#/inventory')
  await expect(page.getByRole('heading', { name: 'Inventory', exact: true })).toBeVisible()
  await createBlankPlaythrough(page)
})

test('universal search focuses the input on shortcuts, reopening, and the search button', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }) => {
  const trigger = page.getByRole('button', { name: isMobile ? 'Search planner' : /^Search/ }).filter({ visible: true })
  const palette = page.getByRole('dialog', { name: 'Search CryKit', exact: true })
  const input = palette.getByRole('searchbox', { name: 'Search CryKit', exact: true })
  await trigger.focus()
  for (const shortcut of ['Meta+k', 'Control+k']) {
    await page.keyboard.press(shortcut)
    await expect(input).toBeFocused()
    await page.keyboard.type('Taunt')
    await expect(input).toHaveValue('Taunt')
    await page.keyboard.press('Escape')
    await expect(palette).not.toBeVisible()
    await expect(trigger).toBeFocused()
  }
  await trigger.click()
  await expect(input).toBeFocused()
  await page.keyboard.type('Potion')
  await expect(input).toHaveValue('Potion')
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
})

test('search distinguishes duplicate native records and replaces the mobile navigation menu', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }) => {
  const before = await readPlannerData(page)
  const menu = page.getByRole('dialog', { name: 'Navigate CryKit', exact: true })
  if (isMobile) {
    await page.getByRole('button', { name: 'More destinations', exact: true }).click()
    await expect(menu).toBeVisible()
  }
  const palette = await search(page, 'Potion')
  await expect(menu).toHaveCount(0)
  const first = palette.getByRole('link', { name: /^Potion Ability · Game data · .+ · Record #10$/ })
  const second = palette.getByRole('link', { name: /^Potion Ability · Game data · .+ · Record #236$/ })
  await expect(first).toBeVisible()
  await expect(second).toBeVisible()
  await expect(first).toContainText('base database')
  await expect(second).toContainText('base database')
  await expect(first).toHaveAttribute('href', currentReferencePath('base:ability:10').slice(1))
  await expect(second).toHaveAttribute('href', currentReferencePath('base:ability:236').slice(1))
  await expect(palette.getByRole('link', { name: 'Potion Item · Game data', exact: true })).toBeVisible()
  await second.click()
  await expect(palette).not.toBeVisible()
  await expect(page.getByText('Navigation blocked', { exact: true })).toHaveCount(0)
  await expect(page).toHaveURL(referenceUrlPattern('base:ability:236'))
  await expect(page.getByRole('heading', { name: 'Potion', exact: true })).toBeVisible()
  expect(await readPlannerData(page)).toEqual(before)
})

test('starter picklists and universal search work without importing or inventing personal state', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile, baseURL }) => {
  const externalRequests: string[] = []
  const appOrigin = new URL(baseURL!).origin
  page.on('request', (request) => {
    if (new URL(request.url()).origin !== appOrigin) externalRequests.push(request.url())
  })
  const blank = await exportLocalData(page)
  expect(selectedPlaythrough(blank.localData).inventory).toEqual({})
  expect(selectedPlaythrough(blank.localData).characters).toEqual({})
  expect(selectedPlaythrough(blank.localData).progress).toEqual({})
  expect(blank.localData.personalDefinitions).toEqual({})

  await page.getByRole('button', { name: 'Add item', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Add inventory item', exact: true })
  await expect(form.getByRole('button', { name: 'Choose Item definition', exact: true })).toBeFocused()
  await expect(form.getByRole('textbox', { name: 'Item name', exact: true })).not.toBeVisible()
  await expect(form.getByRole('button', { name: 'Add item', exact: true })).toBeDisabled()
  await chooseDefinition(page, form, 'Item definition', 'Potion', 'Potion')
  await expect(form.getByRole('button', { name: 'Choose Item definition', exact: true })).toContainText('Potion')
  await expect(form.getByRole('textbox', { name: 'Item name', exact: true })).not.toBeVisible()
  await form.getByLabel('Do you own it?').selectOption('owned')
  await form.getByLabel('How many?').selectOption('exact')
  await form.getByLabel('Current count').fill('3')
  await form.getByRole('button', { name: 'Add item', exact: true }).click()
  await expect(form).not.toBeVisible()

  const palette = await search(page, 'Taunt', 'Meta+k')
  await palette.getByRole('searchbox', { name: 'Search CryKit', exact: true }).press('ArrowDown')
  await expect(palette.locator('[data-universal-result="true"]').first()).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(palette).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'Taunt', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Back to results', exact: true }).click()

  const trigger = page.getByRole('button', { name: isMobile ? 'Search planner' : /^Search/ }).filter({ visible: true })
  await trigger.click()
  await expect(palette).toBeVisible()
  await palette.getByRole('searchbox', { name: 'Search CryKit', exact: true }).fill('A nonempty query')
  await palette.getByRole('searchbox', { name: 'Search CryKit', exact: true }).press('Escape')
  await expect(palette).not.toBeVisible()
  await expect(trigger).toBeFocused()

  await search(page, 'Potion Inventory')
  await palette.locator('[data-universal-result="true"]').click()
  await expect(page.getByRole('heading', { name: 'Inventory', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Edit inventory observation', exact: true })).toBeVisible()
  await page.getByRole('dialog', { name: 'Edit inventory observation', exact: true }).getByRole('button', { name: 'Cancel', exact: true }).click()
  await search(page, 'Potion Inventory')
  await palette.locator('[data-universal-result="true"]').click()
  await expect(page.getByRole('dialog', { name: 'Edit inventory observation', exact: true })).toBeVisible()
  await page.getByRole('dialog', { name: 'Edit inventory observation', exact: true }).getByRole('button', { name: 'Cancel', exact: true }).click()
  const saved = await exportLocalData(page)
  expect(Object.values(selectedPlaythrough(saved.localData).inventory)).toHaveLength(1)
  expect(Object.values(selectedPlaythrough(saved.localData).inventory)[0]?.observedName).toBe('Potion')
  expect(Object.values(selectedPlaythrough(saved.localData).inventory)[0]?.quantity).toEqual({ kind: 'exact', value: 3 })
  expect(saved.catalogs.some((catalog) => catalog.id === 'crystal-project-public-starter')).toBe(true)
  expect(selectedPlaythrough(saved.localData).characters).toEqual({})
  expect(selectedPlaythrough(saved.localData).progress).toEqual({})
  expect(externalRequests).toEqual([])
})

test('inventory display names remain optional and preserve the selected item across edits', async ({ page }) => {
  await page.goto('/#/inventory/new')
  const form = page.getByRole('dialog', { name: 'Add inventory item', exact: true })
  await expect(form.getByRole('button', { name: 'Choose Item definition', exact: true })).toBeFocused()
  await chooseDefinition(page, form, 'Item definition', 'Potion', 'Potion')
  await form.getByRole('button', { name: 'Customize display name', exact: true }).click()
  const displayName = form.getByRole('textbox', { name: 'Display name', exact: true })
  await expect(displayName).toBeFocused()
  await displayName.fill('Synthetic travel potion')
  await chooseDefinition(page, form, 'Item definition', 'Potion', 'Potion')
  await expect(displayName).toHaveValue('Synthetic travel potion')
  await form.getByRole('button', { name: 'Add item', exact: true }).click()
  await expect(form).not.toBeVisible()
  const created = await exportLocalData(page)
  const position = Object.values(selectedPlaythrough(created.localData).inventory)[0]!
  expect(position.observedName).toBe('Synthetic travel potion')
  expect(position.ref.kind).toBe('catalog')
  expect(created.localData.personalDefinitions).toEqual({})

  await page.reload()
  await page.getByRole('button', { name: 'Edit Synthetic travel potion', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Edit inventory observation', exact: true })
  await expect(editor.getByRole('button', { name: 'Choose Item definition', exact: true })).toBeFocused()
  await expect(editor.getByRole('textbox', { name: 'Display name', exact: true })).toHaveValue('Synthetic travel potion')
  await editor.getByRole('textbox', { name: 'Display name', exact: true }).fill('')
  await editor.getByRole('button', { name: 'Save observation', exact: true }).click()
  await expect(editor).not.toBeVisible()
  const restoredName = await exportLocalData(page)
  expect(selectedPlaythrough(restoredName.localData).inventory[position.id]).toMatchObject({ id: position.id, ref: position.ref, observedName: 'Potion', possession: position.possession, quantity: position.quantity })

  await page.getByRole('button', { name: 'Edit Potion', exact: true }).click()
  await expect(editor.getByRole('textbox', { name: 'Display name', exact: true })).not.toBeVisible()
  await editor.getByRole('button', { name: 'Customize display name', exact: true }).click()
  await editor.getByRole('textbox', { name: 'Display name', exact: true }).fill('Synthetic temporary name')
  await editor.getByRole('button', { name: 'Use item name', exact: true }).click()
  await expect(editor.getByRole('textbox', { name: 'Display name', exact: true })).not.toBeVisible()
  await expect(editor.getByRole('button', { name: 'Customize display name', exact: true })).toBeFocused()
  await editor.getByRole('button', { name: 'Customize display name', exact: true }).click()
  await expect(editor.getByRole('textbox', { name: 'Display name', exact: true })).toHaveValue('Potion')
  await editor.getByRole('textbox', { name: 'Display name', exact: true }).fill('Synthetic previous item name')
  await chooseDefinition(page, editor, 'Item definition', 'Ether', 'Ether')
  await expect(editor.getByRole('textbox', { name: 'Display name', exact: true })).not.toBeVisible()
  await editor.getByRole('button', { name: 'Save observation', exact: true }).click()
  await expect(editor).not.toBeVisible()
  const changedItem = await exportLocalData(page)
  expect(Object.values(selectedPlaythrough(changedItem.localData).inventory)).toHaveLength(1)
  expect(selectedPlaythrough(changedItem.localData).inventory[position.id]?.observedName).toBe('Ether')
  expect(selectedPlaythrough(changedItem.localData).inventory[position.id]?.ref).not.toEqual(position.ref)
  expect(changedItem.localData.personalDefinitions).toEqual({})
  expect(changedItem.catalogs).toEqual(created.catalogs)
})

test('nested definition creation preserves the observation and universal search cannot discard it', async ({ page }) => {
  await page.getByRole('button', { name: 'Add item', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Add inventory item', exact: true })
  await form.getByRole('button', { name: 'Enter an unlisted item', exact: true }).click()
  await expect(form.getByRole('textbox', { name: 'Item name', exact: true })).toBeFocused()
  await form.getByRole('textbox', { name: 'Item name', exact: true }).fill('Unfinished observation')
  const palette = await search(page, 'Warrior')
  await palette.locator('[data-universal-result="true"]').first().click()
  await expect(palette.getByText('Navigation blocked', { exact: true })).toBeVisible()
  await expect(palette.getByRole('region', { name: 'Resolve search navigation', exact: true })).toBeFocused()
  await expect(palette.getByRole('searchbox', { name: 'Search CryKit', exact: true })).toHaveValue('Warrior')
  await page.keyboard.press('Escape')
  await expect(form).toBeVisible()
  await expect(form.getByRole('textbox', { name: 'Item name', exact: true })).toHaveValue('Unfinished observation')
  await expect(form.getByRole('textbox', { name: 'Item name', exact: true })).toBeFocused()

  await form.getByRole('button', { name: 'Choose Item definition', exact: true }).click()
  const picker = page.getByRole('dialog', { name: 'Choose Item definition', exact: true })
  await picker.getByRole('searchbox', { name: 'Search available definitions', exact: true }).fill('Synthetic glass lantern')
  await picker.getByRole('searchbox', { name: 'Search available definitions', exact: true }).press('Escape')
  await expect(picker).not.toBeVisible()
  await expect(form).toBeVisible()
  await expect(form.getByRole('textbox', { name: 'Item name', exact: true })).toHaveValue('Unfinished observation')
  await form.getByRole('button', { name: 'Choose Item definition', exact: true }).click()
  await expect(picker.getByRole('searchbox', { name: 'Search available definitions', exact: true })).toHaveValue('Synthetic glass lantern')
  await picker.getByRole('button', { name: 'Create "Synthetic glass lantern"', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Create personal definition', exact: true })
  await expect(editor.getByRole('textbox', { name: 'Definition name', exact: true })).toHaveValue('Synthetic glass lantern')
  await editor.getByLabel('Aliases').fill('Synthetic beacon')
  await editor.getByRole('button', { name: 'Create definition', exact: true }).click()
  await expect(editor).not.toBeVisible()
  await expect(picker).not.toBeVisible()
  await expect(form).toBeVisible()
  await expect(form.getByRole('button', { name: 'Choose Item definition', exact: true })).toContainText('Synthetic glass lantern')
  await expect(form.getByRole('textbox', { name: 'Item name', exact: true })).not.toBeVisible()
  await form.getByRole('button', { name: 'Cancel', exact: true }).click()

  const backup = await exportLocalData(page)
  expect(selectedPlaythrough(backup.localData).inventory).toEqual({})
  expect(Object.values(backup.localData.personalDefinitions).map((definition) => definition.name)).toEqual(['Synthetic glass lantern'])
  await search(page, 'Synthetic beacon')
  await expect(palette.locator('[data-universal-result="true"]')).toHaveCount(1)
  await palette.locator('[data-universal-result="true"]').click()
  await expect(page.getByRole('heading', { name: 'Synthetic glass lantern', exact: true })).toBeVisible()
})

test('blocked deep search results reveal local recovery repeatedly and return to the retained editor', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await page.getByRole('button', { name: 'Save Editor', exact: true }).filter({ visible: true }).click()
  await page.getByLabel('Open Crystal Project save', { exact: true }).setInputFiles({ name: 'synthetic-search-recovery.sav', mimeType: 'application/octet-stream', buffer: Buffer.from(encodeCrystalSave(createSaveEditorFixture())) })
  const copper = page.getByLabel('Copper', { exact: true })
  await copper.fill('789')
  const editorUrl = page.url()
  const palette = await search(page, 'Item')
  const searchUrl = page.url()
  const results = palette.locator('[data-universal-result="true"]')
  const body = palette.locator('.sheet__body')
  const notice = palette.getByRole('region', { name: 'Resolve search navigation', exact: true })
  await expect(results.last()).toBeAttached()
  for (let attempt = 0; attempt < 2; attempt += 1) {
    await results.last().scrollIntoViewIfNeeded()
    expect(await body.evaluate(element => element.scrollTop)).toBeGreaterThan(0)
    await results.last().click()
    await expect(notice).toBeFocused()
    await expect(notice.getByText('Navigation blocked', { exact: true })).toBeVisible()
    await expect(notice.getByRole('button', { name: 'Return to editor', exact: true })).toBeVisible()
    await expect(palette.getByRole('searchbox', { name: 'Search CryKit', exact: true })).toHaveValue('Item')
    await expect(page).toHaveURL(searchUrl)
    expect(await palette.evaluate(element => element.contains(document.activeElement))).toBe(true)
    const noticeBounds = await notice.boundingBox()
    const bodyBounds = await body.boundingBox()
    expect(noticeBounds).not.toBeNull()
    expect(bodyBounds).not.toBeNull()
    expect(noticeBounds!.y).toBeGreaterThanOrEqual(bodyBounds!.y)
    expect(noticeBounds!.y + noticeBounds!.height).toBeLessThanOrEqual(bodyBounds!.y + bodyBounds!.height)
  }
  await notice.getByRole('button', { name: 'Return to editor', exact: true }).click()
  await expect(palette).not.toBeVisible()
  await expect(page).toHaveURL(editorUrl)
  await expect(page.getByRole('heading', { name: 'Save Editor', exact: true })).toBeVisible()
  await expect(copper).toHaveValue('789')
  const warning = page.getByRole('region', { name: 'Resolve unsaved edits', exact: true })
  await expect(warning).toBeFocused()
  await expect(warning.getByRole('button', { name: 'Export and continue', exact: true })).toBeVisible()
})

test('saved catalog versions preserve stock and checkpoints and can be collected into an inactive Game Setup revision', async ({ page }) => {
  const settings = await openData(page)
  await openCurrentGameSetup(settings)
  await settings.getByLabel('Game Setup label').fill('Synthetic base rules')
  await settings.getByRole('combobox', { name: 'Difficulty', exact: true }).selectOption('0')
  await saveAndApplyGameSetup(settings)
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()

  await page.getByRole('button', { name: 'Add item', exact: true }).click()
  const stock = page.getByRole('dialog', { name: 'Add inventory item', exact: true })
  await chooseDefinition(page, stock, 'Item definition', 'Iron Sword', 'Iron Sword')
  await stock.getByLabel('Do you own it?').selectOption('owned')
  await stock.getByLabel('How many?').selectOption('exact')
  await stock.getByLabel('Current count').fill('2')
  await stock.getByRole('button', { name: 'Add item', exact: true }).click()
  await expect(stock).not.toBeVisible()

  await page.getByRole('button', { name: /^(Builds|Builds & teams)$/ }).filter({ visible: true }).click()
  await page.getByRole('button', { name: 'New Build', exact: true }).click()
  const creation = page.locator('.build-sheet')
  await creation.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  await creation.getByText('Build details & notes', { exact: true }).click()
  await page.locator('.context-bar').getByRole('textbox', { name: 'Build title', exact: true }).fill('Synthetic catalog checkpoint')
  const buildEditor = page.locator('.build-sheet')
  await buildEditor.getByRole('button', { name: 'Loadout', exact: true }).click()
  await buildEditor.getByRole('combobox', { name: 'Main hand', exact: true }).click()
  const itemPicker = page.getByRole('listbox', { name: 'Choose Main hand', exact: true })
  await page.getByRole('combobox', { name: 'Main hand', exact: true }).fill('Iron Sword')
  await itemPicker.getByRole('option').filter({ hasText: 'Windows 1.6.9' }).filter({ has: page.locator('strong', { hasText: /^Iron Sword$/ }) }).click()
  await buildEditor.getByRole('button', { name: 'Checks & notes', exact: true }).click()
  await buildEditor.getByLabel('Checkpoint name').fill('Original catalog checkpoint')
  const palette = await search(page, 'Taunt')
  await palette.locator('[data-universal-result="true"]').first().click()
  await expect(palette).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'Taunt', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Return to build draft', exact: true }).click()
  await expect(buildEditor.getByLabel('Checkpoint name')).toHaveValue('Original catalog checkpoint')
  await page.locator('.context-bar').getByRole('button', { name: /^Save (build|new revision)$/ }).click()
  await expect(page.getByText('Saved locally', { exact: true })).toBeAttached()
  const before = await exportLocalData(page)
  const checkpointBuild = Object.values(before.localData.builds).find((build) => build.title === 'Synthetic catalog checkpoint')!
  expect(Object.values(before.localData.buildRevisions).filter((revision) => revision.buildId === checkpointBuild.id)).toHaveLength(1)

  await search(page, 'Iron Sword item')
  await palette.locator('[data-universal-result="true"]').filter({ has: page.locator('strong', { hasText: /^Iron Sword$/ }) }).click()
  await expect(page.getByRole('button', { name: 'Create personal version', exact: true })).toHaveCount(0)
  await openSavedCatalogVersion(page, 'base:equipment:11', 'Synthetic tempered sword', { aliases: ['Iron Sword', 'Synthetic blade'], fields: { Category: { state: 'known', value: 'Synthetic weapons' } } })

  await page.getByRole('button', { name: 'Collect into Game Setup revision', exact: true }).click()
  const collection = page.getByRole('dialog', { name: 'Collect into Game Setup revision', exact: true })
  await collection.getByLabel('Source Game Setup revision').selectOption(before.localData.planningGameSetupRevisionId!)
  await collection.getByLabel('New revision label').fill('Synthetic reviewed definitions')
  await collection.getByRole('button', { name: 'Create Game Setup revision', exact: true }).click()
  await expect(collection).not.toBeVisible()
  const after = await exportLocalData(page)
  expect(selectedPlaythrough(after.localData).inventory).toEqual(selectedPlaythrough(before.localData).inventory)
  expect(after.localData.buildRevisions).toEqual(before.localData.buildRevisions)
  expect(after.localData.planningGameSetupRevisionId).toBe(before.localData.planningGameSetupRevisionId)
  const override = Object.values(after.localData.personalDefinitions).find((entry) => entry.name === 'Synthetic tempered sword')!
  expect(override.baseRef).toEqual(Object.values(selectedPlaythrough(before.localData).inventory)[0]!.ref)
  const collected = Object.values(after.localData.gameSetups).find((entry) => entry.label === 'Synthetic reviewed definitions')!
  expect(collected.definitionOverrides).toEqual([{ kind: 'personal', definitionId: override.id }])

  await page.getByRole('button', { name: 'Inventory', exact: true }).filter({ visible: true }).click()
  await page.getByRole('button', { name: 'Edit Iron Sword', exact: true }).click()
  const observation = page.getByRole('dialog', { name: 'Edit inventory observation', exact: true })
  await chooseDefinition(page, observation, 'Item definition', 'Synthetic blade', 'Synthetic tempered sword')
  await observation.getByRole('button', { name: 'Save observation', exact: true }).click()
  await expect(observation).not.toBeVisible()
  await page.getByRole('searchbox', { name: 'Search inventory', exact: true }).fill('Synthetic blade')
  await page.getByRole('button', { name: 'Linked category: All categories', exact: true }).click()
  await page.getByRole('group', { name: 'Inventory category filters', exact: true }).getByRole('button', { name: 'Synthetic weapons (1)', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Edit Synthetic tempered sword', exact: true })).toBeVisible()
  const linked = await exportLocalData(page)
  expect(Object.values(selectedPlaythrough(linked.localData).inventory)).toHaveLength(1)
  expect(Object.values(selectedPlaythrough(linked.localData).inventory)[0]?.quantity).toEqual({ kind: 'exact', value: 2 })
  expect(Object.values(selectedPlaythrough(linked.localData).inventory)[0]?.ref).toEqual({ kind: 'personal', definitionId: override.id })
  expect(linked.localData.buildRevisions).toEqual(before.localData.buildRevisions)

  const restore = await openData(page)
  await restore.locator('input[type="file"]').setInputFiles({ name: 'synthetic-overrides.zip', mimeType: 'application/zip', buffer: linked.bytes })
  await replacePlannerData(restore)
  await expect(restore).not.toBeVisible()
  const restored = await exportLocalData(page)
  expect(restored.localData.personalDefinitions).toEqual(linked.localData.personalDefinitions)
  expect(selectedPlaythrough(restored.localData).inventory).toEqual(selectedPlaythrough(linked.localData).inventory)
  expect(restored.localData.gameSetups).toEqual(linked.localData.gameSetups)
  expect(restored.localData.buildRevisions).toEqual(linked.localData.buildRevisions)
})
