import { createBlankPlaythrough, openSwitchModPacks } from './local-data-helpers'
import { expect, test, type Page } from '@playwright/test'

const card = (page: Page, name: string) => page.locator('.reference-card').filter({ has: page.getByRole('heading', { name, exact: true }) })

async function expectWeapon(page: Page, isMobile: boolean, weapon: string) {
  if (isMobile) {
    const toggle = page.getByRole('button', { name: /^(Filters|Hide filters)/ })
    await expect(toggle).toBeVisible()
    if (await toggle.getAttribute('aria-expanded') === 'false') await toggle.click()
  }
  await expect(page.getByRole('combobox', { name: 'Weapon skills usable with', exact: true })).toHaveValue(weapon)
}

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await createBlankPlaythrough(page)
})

test('dagger lookup is keyboard accessible and retains filters through details, history, and offline reloads', async ({ page, context, isMobile }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Builds', exact: true })).toBeVisible()
  await page.keyboard.press('Meta+k')
  const palette = page.getByRole('dialog', { name: 'Search Crystal Companion', exact: true })
  await expect(palette.getByRole('searchbox')).toBeFocused()
  await page.keyboard.type('dagger')
  const result = palette.locator('[data-universal-result="true"]').first()
  await expect(result).toContainText('Skills usable with Dagger')
  await page.keyboard.press('ArrowDown')
  await expect(result).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(palette).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'Skills usable with Dagger', exact: true })).toBeVisible()
  const selector = page.getByRole('combobox', { name: 'Weapon skills usable with', exact: true })
  await expectWeapon(page, isMobile, 'Dagger')
  await expect(card(page, 'Backstab')).toContainText('Rogue')
  await expect(card(page, 'Backstab')).toContainText('Dagger / Rapier')
  await expect(card(page, 'Backstab')).toContainText('10 AP')
  await expect(card(page, 'Fire Seal')).toBeVisible()
  await expect(card(page, 'Power Break')).toContainText('Any weapon')
  for (const name of ['Fire', 'Taunt', 'Beat Down', 'Equip Dagger']) await expect(card(page, name)).toHaveCount(0)
  await expect(page.getByText('Possible match', { exact: true })).toHaveCount(0)
  const uncertain = page.getByRole('checkbox', { name: /Include skills with unknown/ })
  await uncertain.check()
  await expect(page).toHaveURL(/uncertainSkills=1/)
  await uncertain.uncheck()
  await card(page, 'Backstab').click()
  await expect(page.getByRole('heading', { name: 'Backstab', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Back to results', exact: true }).click()
  await expectWeapon(page, isMobile, 'Dagger')
  await selector.selectOption('Bow')
  await expect(page.getByRole('heading', { name: 'Skills usable with Bow', exact: true })).toBeVisible()
  await expect(card(page, 'Backstab')).toHaveCount(0)
  await page.goBack()
  await expectWeapon(page, isMobile, 'Dagger')
  await page.reload()
  await expectWeapon(page, isMobile, 'Dagger')
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  await settings.getByRole('button', { name: 'Prepare for offline use', exact: true }).click()
  await expect(settings.getByText('Offline ready', { exact: true })).toBeVisible({ timeout: 15_000 })
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await expectWeapon(page, isMobile, 'Dagger')
  await context.setOffline(true)
  await page.reload()
  await expect(card(page, 'Backstab')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('the weapon list respects the active unrestricted-skills mod setting', async ({ page }) => {
  await page.goto('/#/reference?v=1&weapon=Dagger')
  await expect(card(page, 'Backstab')).toBeVisible()
  await expect(card(page, 'Beat Down')).toHaveCount(0)
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Game Setup', exact: true }).click()
  await openSwitchModPacks(settings)
  await settings.getByRole('textbox', { name: 'Game Setup label', exact: true }).fill('Weapon filter check')
  await settings.getByRole('combobox', { name: 'Unrestricted Weapon Skills', exact: true }).selectOption('enabled')
  await settings.getByRole('button', { name: /^(Create Game Setup|Save new Game Setup revision)$/ }).click()
  await expect(page.getByText('Saved locally', { exact: true })).toBeAttached()
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await expect(card(page, 'Beat Down')).toBeVisible()
  await expect(card(page, 'Beat Down')).toContainText('Unarmed / Staff')
  await expect(card(page, 'Fire')).toHaveCount(0)
  await page.reload()
  await expect(card(page, 'Beat Down')).toBeVisible()
})
