import { expect, test, type Page } from '@playwright/test'
import { MOBILE_TEST_TAG } from './test-tags'
import { expectOfflineReady } from './offline-helpers'
import type { LocalData } from '../src/domain/types'

async function storedData(page: Page): Promise<LocalData> {
  return page.evaluate(() => new Promise((resolve, reject) => {
    const request = indexedDB.open('crykit')
    request.onerror = () => reject(request.error)
    request.onsuccess = () => {
      const database = request.result
      const read = database.transaction('localDatas', 'readonly').objectStore('localDatas').getAll()
      read.onerror = () => { database.close(); reject(read.error) }
      read.onsuccess = () => { database.close(); resolve(read.result[0].localData) }
    }
  }))
}

async function expectTerrain(page: Page) {
  await expect(page.getByRole('heading', { name: 'World Map', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Sources for World Map', exact: true })).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Interactive world map', exact: true })).toBeVisible()
  await expect.poll(() => page.locator('.world-map-terrain img').evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBe(true)
}

test('world map navigation supports clustered zoom, keyboard exploration, and underground layers', { tag: MOBILE_TEST_TAG }, async ({ page, isMobile }, testInfo) => {
  await page.goto('/')
  const navigation = page.getByRole('button', { name: 'World Map', exact: true }).filter({ visible: true })
  await navigation.click()
  await expectTerrain(page)
  await expect(navigation).toHaveAttribute('aria-current', 'page')
  const viewport = page.getByRole('region', { name: 'Interactive world map', exact: true })
  const scale = viewport.locator('.world-map-scale strong')
  await expect(scale).toHaveText('1.0×')
  const clusters = viewport.getByRole('button', { name: /locations near .+\. Zoom in$/ })
  expect(await clusters.count()).toBeGreaterThan(0)
  await clusters.first().click()
  await expect(scale).toHaveText('2.0×')
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
  await expect(scale).toHaveText('3.2×')
  await page.getByRole('button', { name: 'Zoom out', exact: true }).click()
  await expect(scale).toHaveText('2.0×')
  if (!isMobile) {
    await viewport.focus()
    await page.keyboard.press('+')
    await expect(scale).toHaveText('3.2×')
    await page.keyboard.press('ArrowRight')
    await page.keyboard.press('Home')
  } else await page.getByRole('button', { name: 'Fit map', exact: true }).tap()
  await expect(scale).toHaveText('1.0×')
  const overworldImage = await page.locator('.world-map-terrain img').getAttribute('src')
  await page.getByLabel('Map layer', { exact: true }).selectOption('1')
  await expectTerrain(page)
  await expect(page.locator('.world-map-terrain img')).not.toHaveAttribute('src', overworldImage!)
  await page.reload()
  await expectTerrain(page)
  await expect(page.getByLabel('Map layer', { exact: true })).toHaveValue('1')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('world-map-caves.png'), fullPage: true })
})

test('overlapping chest choices stay reachable and map controls resist native scrolling', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  const MAX_NEARBY_CLUSTER_ATTEMPTS = 6
  await page.goto('/#/map?mods=none')
  await expectTerrain(page)
  await page.getByRole('searchbox', { name: 'Search map', exact: true }).fill('Knockout Stick Sara Sara Bazaar')
  await page.getByRole('button', { name: 'Show Knockout Stick on map', exact: true }).click()
  const viewport = page.getByRole('region', { name: 'Interactive world map', exact: true })
  const zoomIn = viewport.getByRole('button', { name: 'Zoom in', exact: true })
  while (await zoomIn.isEnabled()) await zoomIn.click()
  await expect(viewport.locator('.world-map-scale strong')).toHaveText('32.0×')
  await page.getByRole('button', { name: 'Close location details', exact: true }).click()
  await viewport.scrollIntoViewIfNeeded()
  const controls = viewport.locator('.world-map-zoom')
  const controlsBefore = await controls.boundingBox()
  await viewport.evaluate(element => {
    element.scrollTo({ left: 212, top: 96 })
    element.scrollLeft = 212
    element.scrollTop = 96
  })
  await expect.poll(() => viewport.evaluate(element => ({ left: element.scrollLeft, top: element.scrollTop }))).toEqual({ left: 0, top: 0 })
  const controlsAfter = await controls.boundingBox()
  expect(controlsAfter!.x).toBeCloseTo(controlsBefore!.x, 1)
  expect(controlsAfter!.y).toBeCloseTo(controlsBefore!.y, 1)
  const clusters = viewport.getByRole('button', { name: /locations near .+\. Choose a location$/ })
  const chooser = viewport.getByRole('region', { name: 'Nearby map locations', exact: true })
  const knockoutChoice = chooser.getByRole('button', { name: /^Knockout Stick Vanilla/ })
  const attempts = Math.min(await clusters.count(), MAX_NEARBY_CLUSTER_ATTEMPTS)
  for (let index = 0; index < attempts; index += 1) {
    await clusters.nth(index).click()
    await expect(chooser).toBeVisible()
    if (await knockoutChoice.count()) break
    await chooser.getByRole('button', { name: 'Close nearby locations', exact: true }).click()
  }
  await expect(knockoutChoice).toBeVisible()
  await expect(knockoutChoice).toContainText('Height 101')
  await expect(chooser.getByRole('button', { name: /^Potion Vanilla/ })).toContainText('Height 106')
  const mapBounds = (await viewport.boundingBox())!
  for (const target of [chooser, controls, knockoutChoice, chooser.getByRole('button', { name: 'Close nearby locations', exact: true })]) {
    const bounds = (await target.boundingBox())!
    expect(bounds.x).toBeGreaterThanOrEqual(mapBounds.x)
    expect(bounds.y).toBeGreaterThanOrEqual(mapBounds.y)
    expect(bounds.x + bounds.width).toBeLessThanOrEqual(mapBounds.x + mapBounds.width)
    expect(bounds.y + bounds.height).toBeLessThanOrEqual(mapBounds.y + mapBounds.height)
  }
  await knockoutChoice.click()
  await expect(chooser).toHaveCount(0)
  const details = page.getByRole('region', { name: 'Map location details', exact: true })
  await expect(details.getByRole('heading', { name: 'Knockout Stick', exact: true })).toBeVisible()
  await expect(details).toContainText('Height 101')
  await expect(details.getByRole('link', { name: 'Knockout Stick', exact: true })).toBeVisible()
})

test('a build draft survives a map research detour without allowing an unrelated navigation', async ({ page }) => {
  await page.goto('/#/builds/library/new')
  const equipment = page.getByRole('combobox', { name: 'Main hand', exact: true })
  await equipment.fill('Iron Sword')
  await page.getByRole('listbox', { name: 'Choose Main hand', exact: true }).getByRole('option').filter({ has: page.locator('strong', { hasText: /^Iron Sword$/ }) }).click()
  await expect(equipment).toHaveValue('Iron Sword')
  await page.getByRole('button', { name: 'World Map', exact: true }).filter({ visible: true }).click()
  await expectTerrain(page)
  await expect(page.getByText('Your build draft is kept in this tab', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Return to build draft', exact: true }).click()
  await expect(equipment).toHaveValue('Iron Sword')
  await page.getByRole('button', { name: 'Inventory', exact: true }).filter({ visible: true }).click()
  await expect(page.getByText('Unsaved edits are still open', { exact: true })).toBeVisible()
  await expect(equipment).toHaveValue('Iron Sword')
})

test('native shops, underground bosses, and named regions reveal their exact locations', async ({ page }) => {
  await page.goto('/#/map')
  await expectTerrain(page)
  const before = await storedData(page)
  const search = page.getByRole('searchbox', { name: 'Search map', exact: true })
  await search.fill('Weapon Merchant Delende')
  await page.getByRole('button', { name: 'Show Weapon Merchant on map', exact: true }).first().click()
  const details = page.getByRole('region', { name: 'Map location details', exact: true })
  await expect(details.getByRole('heading', { name: 'Weapon Merchant', exact: true })).toBeVisible()
  await expect(details.getByRole('button', { name: 'Sources for Weapon Merchant location', exact: true })).toHaveCount(0)
  await expect(details).toContainText('Delende')
  await expect(details).toContainText('Shop stock')
  expect(await details.getByRole('link').count()).toBeGreaterThan(0)
  await search.fill('Canal Beast')
  await page.getByRole('button', { name: 'Show Canal Beast on map', exact: true }).click()
  await expect(details.getByRole('heading', { name: 'Canal Beast', exact: true })).toBeVisible()
  await expect(details.locator('.eyebrow')).toHaveText('Bosses')
  await expect(page.getByLabel('Map layer', { exact: true })).toHaveValue('1')
  await expect(page.getByRole('button', { name: 'Selected location: Canal Beast', exact: true })).toBeVisible()
  await expect(details.getByRole('link', { name: 'Canal Beast', exact: true })).toBeVisible()
  await search.fill('Spawning Meadows')
  await page.getByRole('button', { name: 'Show Spawning Meadows on map', exact: true }).click()
  await expect(details.getByRole('heading', { name: 'Spawning Meadows', exact: true })).toBeVisible()
  await expect(details.locator('.eyebrow')).toHaveText('Region')
  await expect(page.getByLabel('Map layer', { exact: true })).toHaveValue('0')
  expect(await storedData(page)).toEqual(before)
})

test('a temporary map source download failure can be retried without replacing local records', async ({ page }) => {
  let failures = 0
  await page.route(/\/assets\/world-map-[^/]+\.(?:js|json)$/, async route => {
    if (failures === 0) {
      failures += 1
      await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Temporarily unavailable' }) })
    } else await route.continue()
  })
  await page.goto('/#/map')
  await expect(page.getByText('Map unavailable', { exact: true })).toBeVisible()
  const before = await storedData(page)
  await page.getByRole('button', { name: 'Retry world map', exact: true }).click()
  await expectTerrain(page)
  expect(failures).toBe(1)
  expect(await storedData(page)).toEqual(before)
})

test('Silver Ore mining points have resource filters and item references independent of NPCs', { tag: MOBILE_TEST_TAG }, async ({ page }) => {
  await page.goto('/#/map')
  await expectTerrain(page)
  const before = await storedData(page)
  await page.getByRole('searchbox', { name: 'Search map', exact: true }).fill('Silver Ore Rolling Quintar Fields')
  const result = page.getByRole('button', { name: 'Show Silver Ore node on map', exact: true })
  await result.click()
  const details = page.getByRole('region', { name: 'Map location details', exact: true })
  await expect(details.getByRole('heading', { name: 'Silver Ore node', exact: true })).toBeVisible()
  await expect(details.locator('.eyebrow')).toHaveText('Resources')
  await expect(details).toContainText('Mining point')
  await expect(details).toContainText('Rolling Quintar Fields')
  await expect(details.getByRole('link', { name: 'Silver Ore', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Selected location: Silver Ore node', exact: true })).toHaveClass(/world-map-marker--resource/)
  await page.getByRole('button', { name: 'NPCs', exact: true }).click()
  await expect(result).toBeVisible()
  await expect(details.locator('.eyebrow')).toHaveText('Resources')
  await page.getByRole('button', { name: 'Close location details', exact: true }).click()
  await page.getByRole('button', { name: 'Resources', exact: true }).click()
  await expect(result).toHaveCount(0)
  await expect(page.locator('.world-map-marker--resource')).toHaveCount(0)
  await page.getByRole('button', { name: 'Resources', exact: true }).click()
  await result.click()
  await expect(details.getByRole('heading', { name: 'Silver Ore node', exact: true })).toBeVisible()
  expect(await storedData(page)).toEqual(before)
})

test('Equipment Expansion locations retain source badges, filters, reference links, and offline layers', { tag: MOBILE_TEST_TAG }, async ({ page, context, baseURL }, testInfo) => {
  const externalRequests: string[] = []
  page.on('request', request => { if (!request.url().startsWith(`${baseURL}/`)) externalRequests.push(request.url()) })
  await page.goto('/#/map')
  await expectTerrain(page)
  const before = await storedData(page)
  const search = page.getByRole('searchbox', { name: 'Search map', exact: true })
  await search.fill('Backbreaker')
  const result = page.getByRole('button', { name: 'Show Backbreaker on map', exact: true })
  await expect(result).toBeVisible()
  await result.click()
  const details = page.getByRole('region', { name: 'Map location details', exact: true })
  await expect(details.getByRole('heading', { name: 'Backbreaker', exact: true })).toBeVisible()
  await expect(details.locator('.world-map-source-badge--mod')).toContainText('Equipment Expansion')
  await details.getByRole('button', { name: 'Sources for Backbreaker location', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Sources for Backbreaker location', exact: true })).toContainText('Equipment Expansion')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Selected location: Backbreaker', exact: true })).toHaveClass(/world-map-marker--mod/)
  const locationUrl = page.url()
  await page.getByRole('button', { name: 'Close location details', exact: true }).click()
  const sources = page.locator('.world-map-source-filters')
  await sources.getByRole('checkbox', { name: 'Equipment Expansion', exact: true }).uncheck()
  await expect(result).toHaveCount(0)
  await sources.getByRole('checkbox', { name: 'Equipment Expansion', exact: true }).check()
  await expect(result).toBeVisible()
  await page.getByRole('button', { name: 'Chests', exact: true }).click()
  await expect(result).toHaveCount(0)
  await page.getByRole('button', { name: 'Chests', exact: true }).click()
  await result.click()
  await details.getByRole('link', { name: 'Backbreaker', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Backbreaker', exact: true })).toBeVisible()
  await page.goto(locationUrl)
  await expectTerrain(page)
  await expect(details).toContainText('Equipment Expansion')
  expect(await storedData(page)).toEqual(before)
  await page.getByRole('button', { name: /^(Data & settings|Open data and settings)$/ }).filter({ visible: true }).click()
  const settings = page.getByRole('dialog', { name: 'Data & settings', exact: true })
  await settings.getByRole('button', { name: 'Offline & storage', exact: true }).click()
  const prepare = settings.getByRole('button', { name: 'Prepare for offline use', exact: true })
  if (await prepare.isVisible()) await prepare.click()
  await expectOfflineReady(settings)
  await settings.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await context.setOffline(true)
  await page.reload()
  await expectTerrain(page)
  await expect(details.getByRole('heading', { name: 'Backbreaker', exact: true })).toBeVisible()
  await page.getByLabel('Map layer', { exact: true }).selectOption('9')
  await expectTerrain(page)
  await expect(page.getByLabel('Map layer', { exact: true })).toHaveValue('9')
  await page.screenshot({ path: testInfo.outputPath('world-map-offline-dungeon.png'), fullPage: true })
  expect(externalRequests).toEqual([])
})

test('an arbitrary placement-only mod previews native loot without changing saved Game Setups', async ({ page }) => {
  const source = JSON.stringify({ ID: 'synthetic-map-placements', Title: 'Synthetic placements', Version: '1', EditorVersion: 34, Entities: [{ ID: 900001, EntityType: 5, BiomeID: 1, Coord: { X: -12, Y: 99, Z: 4 }, TreasureData: { LootType: 1, LootValue: 18, Style: 1 } }] })
  await page.goto('/#/mods/editor')
  await page.getByLabel('Open mod JSON file', { exact: true }).setInputFiles({ name: 'synthetic-placements.json', mimeType: 'application/json', buffer: Buffer.from(source) })
  await expect(page.getByText('Saved in this browser', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save to CryKit', exact: true }).click()
  await expect(page.getByText('Mod revision saved to CryKit', { exact: true })).toBeVisible()
  const before = await storedData(page)
  await page.getByRole('button', { name: 'World Map', exact: true }).filter({ visible: true }).click()
  await expectTerrain(page)
  const savedSetup = before.planningGameSetupRevisionId!
  await page.getByLabel('Game Setup', { exact: true }).selectOption(savedSetup)
  await expect(page.getByLabel('Game Setup', { exact: true })).toHaveValue(savedSetup)
  await expect(page.locator('.world-map-mods [role="status"]')).toHaveCount(0)
  await expect(page.locator('.world-map-source-filters')).not.toContainText('Equipment Expansion')
  await page.locator('.world-map-mods > summary').click()
  await page.getByRole('button', { name: 'Preview vanilla only', exact: true }).click()
  const choice = page.locator('.world-map-mod-choices').getByRole('checkbox', { name: /^Synthetic placements/ })
  await choice.check()
  await page.getByRole('searchbox', { name: 'Search map', exact: true }).fill('Synthetic placements')
  await page.getByRole('button', { name: 'Show Tonic on map', exact: true }).click()
  const details = page.getByRole('region', { name: 'Map location details', exact: true })
  await expect(details.getByRole('heading', { name: 'Tonic', exact: true })).toBeVisible()
  await expect(details.locator('.world-map-source-badge--mod')).toContainText('Synthetic placements')
  await expect(details).toContainText('Spawning Meadows')
  await expect(details.getByRole('link', { name: 'Tonic', exact: true })).toBeVisible()
  await page.reload()
  await expectTerrain(page)
  await expect(details).toContainText('Synthetic placements')
  expect(await storedData(page)).toEqual(before)
  await page.locator('.world-map-mods > summary').click()
  await page.getByRole('button', { name: 'Preview vanilla only', exact: true }).click()
  await expect(page.locator('.world-map-mods [role="status"]')).toHaveCount(0)
  await expect(page.locator('.world-map-source-filters')).not.toContainText('Synthetic placements')
  await expect(page.locator('.world-map-source-filters')).not.toContainText('Equipment Expansion')
  await page.reload()
  await expectTerrain(page)
  await expect(page.locator('.world-map-mods [role="status"]')).toHaveCount(0)
  await expect(page.locator('.world-map-source-filters')).not.toContainText('Synthetic placements')
  await expect(page.locator('.world-map-source-filters')).not.toContainText('Equipment Expansion')
  expect(await storedData(page)).toEqual(before)
})
